# Reading output from part 2

In [1]:
import pandas as pd
from pathlib import Path

json_path = Path('/kaggle/input/notebooks/sebastianvpal/improving-baseline-model-part2/hp_search_results_part2.jsonl')
json_results = pd.read_json(json_path,lines = True)
# Sorting the results: from best to worst
json_results = json_results.sort_values("best_score", ascending = False)

In [2]:
json_results.head(10)

,trial_id,elapsed_s,fold,n_epochs,max_iters,seed,data_parallel,batch_size,method,lr,det_loss_weight,det_neg_weight,det_threshold,best_score,final_edge_loss,final_det_loss,final_test_acc,final_test_recall,best_test_acc,best_test_recall
3,tier1_003,1006.2,0,4,200,0,False,2,hp_search_tier1,0.00005,4,0.010,0.80,0.925941,0.000640,0.006326,0.998590,0.887633,0.998633,0.927208
0,tier1_000,1022.8,0,4,200,0,False,2,hp_search_tier1,0.00001,4,0.030,0.80,0.917582,0.000659,0.016699,0.998729,0.898940,0.998753,0.918728
1,tier1_001,1010.8,0,4,200,0,False,2,hp_search_tier1,0.00003,4,0.010,0.80,0.916434,0.000581,0.006555,0.998894,0.894700,0.999040,0.917314
7,tier1_007,1006.8,0,4,200,0,False,2,hp_search_tier1,0.00003,3,0.030,0.99,0.911712,0.000651,0.014730,0.998508,0.913074,0.998508,0.913074
2,tier1_002,1007.4,0,4,200,0,False,2,hp_search_tier1,0.00001,4,0.030,0.99,0.909153,0.000733,0.017092,0.998798,0.910247,0.998798,0.910247
5,tier1_005,1009.2,0,4,200,0,False,2,hp_search_tier1,0.00005,4,0.010,0.92,0.906162,0.000664,0.006762,0.998613,0.907420,0.998613,0.907420
6,tier1_006,1014.6,0,4,200,0,False,2,hp_search_tier1,0.00003,2,0.003,0.99,0.905376,0.000511,0.002632,0.999126,0.841696,0.999303,0.906007
8,tier1_008,1021.0,0,4,200,0,False,2,hp_search_tier1,0.00003,3,0.003,0.92,0.901002,0.000509,0.003354,0.999021,0.895406,0.999152,0.901767
11,tier1_011,1021.9,0,4,200,0,False,2,hp_search_tier1,0.00001,3,0.003,0.99,0.900369,0.000502,0.002734,0.999233,0.901060,0.999233,0.901060
9,tier1_009,1013.6,0,4,200,0,False,2,hp_search_tier1,0.00005,2,0.030,0.80,0.899984,0.000688,0.014352,0.998715,0.857951,0.998806,0.901060

In [3]:
# sanity-check marginal effect of each param independently
to_chek = ["lr", "det_loss_weight", "det_neg_weight", "det_threshold"]
for param in [*to_chek]:
    print(json_results.groupby(param)["best_score"].agg(["mean", "std", "count"]).sort_values("mean", ascending = False),"\n","--"*20)

             mean       std  count
lr
0.00005  0.910696  0.013560      3
0.00003  0.908631  0.006811      4
0.00001  0.901675  0.012126      5
 ----------------------------------------
                     mean       std  count
det_loss_weight
4                0.915054  0.007758      5
3                0.901955  0.007088      4
2                0.897297  0.009706      3
 ----------------------------------------
                    mean       std  count
det_neg_weight
0.010           0.916179  0.009892      3
0.030           0.909608  0.007322      4
0.003           0.897603  0.007253      5
 ----------------------------------------
                   mean       std  count
det_threshold
0.80           0.910936  0.013056      5
0.99           0.906652  0.004932      4
0.92           0.897898  0.010177      3
 ----------------------------------------

In [4]:
json_results.groupby("det_threshold")[["best_score", "best_test_acc", "best_test_recall"]].agg(["mean", "std"])

              best_score           best_test_acc           best_test_recall  \
                    mean       std          mean       std             mean
det_threshold
0.80            0.910936  0.013056      0.998897  0.000248         0.911943
0.92            0.897898  0.010177      0.998841  0.000279         0.898940
0.99            0.906652  0.004932      0.998961  0.000376         0.907597


                    std
det_threshold
0.80           0.013227
0.92           0.010192
0.99           0.005237

**Observations:**

- The `learning_rate`optimal value was reached with 5e-5. However, other value candidates as 3e-5 and 1e-5 reched good values as well. An idea is to implement a `callback`using this information. Stating at a large value such as 1e-4 and decreasing util 1e-5.
- The optimal value for `det_loss_weight`is around 4 ( with 4 and 3 the best score reached similar values)
- In the previous notebook (part2) the best value for `det_neg_weight` was 0.003 with 0.9081 followed by 0.030 with 0.9070. In this ocassion the best score was obtained with 0.01 (0.9161 best score) and followd by 0.03 (0.9096) this migh indicate that the best value  for this metric is in the order of 1e-2 to 3e-2 and not 3e-3.
- As in part2 of this search, the optimal value for `det_threshold` was obtained with 0.80, moving to a larger value such as 0.92 didn't give any benefit or improvement in the metric.

---

**Observation 2:**

The values from `final_test_acc`, `final_test_recall`, `best_test_acc`, `best_test_recall` from this notebook and part2 shown that the model is struggling to accuratly identify nodes (cells) while with the identified edges (links between cells) are correctly predicted. This is supported by looking at `best_test_acc`, `best_test_recall`, for example, `best_test_acc` is related to edge detection and it achieves a value of ~ 0.99 while `best_test_recall` (associated to node detection) gets ~ 0.91, meaning that 9% (in average, for this short test) of the nodes are wrong. This is important as **we can isolate where the model is performing worst and plan strategies to improve this aspect.**

---
**caveat:**

Statistica significance. Every analyzed group has 3-5 samples with std values ranging from 0.005 to 0.014 with  group means in the same order of magnitude, making weaker the conclusion drawn from difference in the means between groups, i.e. many of these group differences are within about one standard error of each other. Nevertheless, it does not mean that these results are meaningless but it is important to take into account when defining values for a larger training. 

---
**Conclusion from Set 1 analysis**

From these two searches it is possible to conclude that: the best value for `learning rate`lies between 9e-4 and 3e-5, for this reason a `Callback` will be implemented. Optimal values for `det_loss_weight`, `det_neg_weight` and `det_threshold` are **4, 1e-2, and 0.80, respectively**.

# Sweep on set 2.

Now we are going to move one and perform the search for the optimal values for the set of variables we have defined as "set 2" (check first part of these notebook series). The fist steps of the notebook are the same as for the previous ones, i.e. configuration, setting environment, code modifications, the only change is in the variables sweep

## Defining input data

In [5]:
from pathlib import Path
import os
DATA_PATH = Path('/kaggle/input/competitions/biohub-cell-tracking-during-development')
TRAINING_PATH =  DATA_PATH/'train'
TEST_PATH = DATA_PATH/'test'


#------------ Listing folders in train -----------
print("Input contents:", os.listdir(TRAINING_PATH)[:5],"\n")
print(" First 5 elements in train folder, it contains '.geff' folders (annotated graphs) and '.zarr' folder (videos)")

Input contents: ['6bba_2540cd90.geff', '44b6_0b24845f.geff', '44b6_996155de.geff', '44b6_0c582fdc.geff', '6bba_cf35214c.zarr']

 First 5 elements in train folder, it contains '.geff' folders (annotated graphs) and '.zarr' folder (videos)

## Modifications to baseline model

In [6]:
import shutil, sys
from pathlib import Path
# --------- Making a copy of the folder to my own working space --------------
# ---------             such that I can edit it     --------------------------

ARTIFACTS_SRC  = Path("/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts")
ARTIFACTS_WORK = Path("/kaggle/working/cellmot-baseline-artifacts")

if not ARTIFACTS_WORK.exists():
    shutil.copytree(ARTIFACTS_SRC, ARTIFACTS_WORK)

# put the writable copy ahead of anything else on the path
sys.path.insert(0, str(ARTIFACTS_WORK))
sys.path.insert(0, str(ARTIFACTS_WORK / "repo/scripts"))   # adjust to wherever train_unet_transformer.py actually sits
sys.path.insert(0, str(ARTIFACTS_WORK / "repo/src"))

In [7]:
needed_dirs = {
    matches[0].parent for name in
    ("train_unet_transformer.py", "tracking_cellmot", "augmentations.py", "dataspec.py")
    if (matches := list(ARTIFACTS_WORK.rglob(name)))
}
needed_dirs

{PosixPath('/kaggle/working/cellmot-baseline-artifacts/repo/scripts'),
 PosixPath('/kaggle/working/cellmot-baseline-artifacts/repo/src')}

In [8]:
import glob
import os
import subprocess
import sys
import shutil

# 1. Find all wheels, but filter OUT numpy wheels to avoid breaking C-extensions
wheels = [
    f for f in glob.glob(f"{ARTIFACTS_SRC}/wheels/*.whl")
    if "numpy" not in os.path.basename(f).lower()
]

# 2. Install only the required non-NumPy wheels without upgrading dependencies
subprocess.run(
    [
        "pip", "install", 
        "--no-index", 
        "--find-links", f"{ARTIFACTS_SRC}/wheels",
        "--no-deps",
        *wheels
    ],
    check=True)

Looking in links: /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/imagecodecs-2026.6.26-cp312-abi3-manylinux_2_28_x86_64.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/shellingham-1.5.4-py2.py3-none-any.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/numcodecs-0.15.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/bidict-0.23.1-py3-none-any.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/requests-2.34.2-py3-none-any.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/lazy_loader-0.5-py3-none-any.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/typing_extensions-4.15.0-py3-none-any.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/dask-2026.6.0-py3-none-any.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/charset_normalizer-3.4.7-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/cloudpickle-3.1.2-py3-none-any.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/toolz-1.1.0-py3-none-any.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/pydantic_core-2.46.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/idna-3.18-py3-none-any.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/imageio-2.37.3-py3-none-any.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/scipy-1.18.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/psygnal-0.15.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/ndindex-1.10.1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/tqdm-4.68.3-py3-none-any.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/markdown_it_py-4.2.0-py3-none-any.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/click-8.4.2-py3-none-any.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/blosc2-4.7.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/zarr-3.2.1-py3-none-any.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/pillow-12.2.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/certifi-2026.6.17-py3-none-any.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/msgpack-1.2.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/partd-1.4.2-py3-none-any.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/rustworkx-0.18.0-cp310-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/ilpy-0.6.0-py3-none-any.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/urllib3-2.7.0-py3-none-any.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/typing_inspection-0.4.2-py3-none-any.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/networkx-3.6.1-py3-none-any.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/annotated_types-0.7.0-py3-none-any.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/annotated_doc-0.0.4-py3-none-any.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/scikit_image-0.26.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/donfig-0.8.1.post1-py3-none-any.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/wrapt-2.2.2-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/tracksdata-0.1.0rc6.dev3+g980c2d30a-py3-none-any.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/threadpoolctl-3.6.0-py3-none-any.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/pydantic-2.13.4-py3-none-any.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/numexpr-2.14.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/tifffile-2026.6.1-py3-none-any.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/typer-0.26.8-py3-none-any.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/sqlalchemy-2.0.51-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/deprecated-1.3.1-py2.py3-none-any.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/fsspec-2026.6.0-py3-none-any.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/google_crc32c-1.8.0-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/llvmlite-0.47.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/polars-1.42.0-py3-none-any.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/pyyaml-6.0.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/geff-1.2.0.1.1-py3-none-any.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/mdurl-0.1.2-py3-none-any.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/numba-0.65.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/packaging-26.2-py3-none-any.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/pygments-2.20.0-py3-none-any.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/polars_runtime_32-1.42.0-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/pyscipopt-6.2.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/locket-1.0.0-py2.py3-none-any.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/rich-15.0.0-py3-none-any.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/greenlet-3.5.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/pyarrow-24.0.0-cp312-cp312-manylinux_2_28_x86_64.whl
Processing /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/geff_spec-1.1.1-py3-none-any.whl
shellingham is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.
lazy-loader is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.
typing-extensions is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.
charset-normalizer is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.
cloudpickle is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.
imageio is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.
psygnal is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.
ndindex is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.
partd is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.
typing-inspection is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.
networkx is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.
annotated-types is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.
annotated-doc is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.
threadpoolctl is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.
numexpr is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.
deprecated is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.
google-crc32c is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.
pyyaml is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.
mdurl is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.
pygments is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.
locket is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.
pyarrow is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.
Installing collected packages: zarr, wrapt, urllib3, typer, tracksdata, tqdm, toolz, tifffile, sqlalchemy, scipy, scikit-image, rustworkx, rich, requests, pyscipopt, pydantic-core, pydantic, polars-runtime-32, polars, pillow, packaging, numcodecs, numba, msgpack, markdown-it-py, llvmlite, imagecodecs, ilpy, idna, greenlet, geff-spec, geff, fsspec, donfig, dask, click, certifi, blosc2, bidict
  Attempting uninstall: wrapt
    Found existing installation: wrapt 2.1.2
    Uninstalling wrapt-2.1.2:
      Successfully uninstalled wrapt-2.1.2
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.5.0
    Uninstalling urllib3-2.5.0:
      Successfully uninstalled urllib3-2.5.0
  Attempting uninstall: typer
    Found existing installation: typer 0.24.2
    Uninstalling typer-0.24.2:
      Successfully uninstalled typer-0.24.2
  Attempting uninstall: tqdm
    Found existing installation: tqdm 4.67.3
    Uninstalling tqdm-4.67.3:
      Successfully uninstalled tqdm-4.67.3
  Attempting uninstall: toolz
    Found existing installation: toolz 0.12.1
    Uninstalling toolz-0.12.1:
      Successfully uninstalled toolz-0.12.1
  Attempting uninstall: tifffile
    Found existing installation: tifffile 2026.4.11
    Uninstalling tifffile-2026.4.11:
      Successfully uninstalled tifffile-2026.4.11
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 2.0.49
    Uninstalling SQLAlchemy-2.0.49:
      Successfully uninstalled SQLAlchemy-2.0.49
  Attempting uninstall: scipy
    Found existing installation: scipy 1.16.3
    Uninstalling scipy-1.16.3:
      Successfully uninstalled scipy-1.16.3
  Attempting uninstall: scikit-image
    Found existing installation: scikit-image 0.25.2
    Uninstalling scikit-image-0.25.2:
      Successfully uninstalled scikit-image-0.25.2
  Attempting uninstall: rich
    Found existing installation: rich 13.9.4
    Uninstalling rich-13.9.4:
      Successfully uninstalled rich-13.9.4
  Attempting uninstall: requests
    Found existing installation: requests 2.32.4
    Uninstalling requests-2.32.4:
      Successfully uninstalled requests-2.32.4
  Attempting uninstall: pydantic-core
    Found existing installation: pydantic_core 2.41.4
    Uninstalling pydantic_core-2.41.4:
      Successfully uninstalled pydantic_core-2.41.4
  Attempting uninstall: pydantic
    Found existing installation: pydantic 2.12.3
    Uninstalling pydantic-2.12.3:
      Successfully uninstalled pydantic-2.12.3
  Attempting uninstall: polars-runtime-32
    Found existing installation: polars-runtime-32 1.35.2
    Uninstalling polars-runtime-32-1.35.2:
      Successfully uninstalled polars-runtime-32-1.35.2
  Attempting uninstall: polars
    Found existing installation: polars 1.35.2
    Uninstalling polars-1.35.2:
      Successfully uninstalled polars-1.35.2
  Attempting uninstall: pillow
    Found existing installation: pillow 11.3.0
    Uninstalling pillow-11.3.0:
      Successfully uninstalled pillow-11.3.0
  Attempting uninstall: packaging
    Found existing installation: packaging 26.1
    Uninstalling packaging-26.1:
      Successfully uninstalled packaging-26.1
  Attempting uninstall: numba
    Found existing installation: numba 0.60.0
    Uninstalling numba-0.60.0:
      Successfully uninstalled numba-0.60.0
  Attempting uninstall: msgpack
    Found existing installation: msgpack 1.1.2
    Uninstalling msgpack-1.1.2:
      Successfully uninstalled msgpack-1.1.2
  Attempting uninstall: markdown-it-py
    Found existing installation: markdown-it-py 4.0.0
    Uninstalling markdown-it-py-4.0.0:
      Successfully uninstalled markdown-it-py-4.0.0
  Attempting uninstall: llvmlite
    Found existing installation: llvmlite 0.43.0
    Uninstalling llvmlite-0.43.0:
      Successfully uninstalled llvmlite-0.43.0
  Attempting uninstall: idna
    Found existing installation: idna 3.13
    Uninstalling idna-3.13:
      Successfully uninstalled idna-3.13
  Attempting uninstall: greenlet
    Found existing installation: greenlet 3.4.0
    Uninstalling greenlet-3.4.0:
      Successfully uninstalled greenlet-3.4.0
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2025.3.0
    Uninstalling fsspec-2025.3.0:
      Successfully uninstalled fsspec-2025.3.0
  Attempting uninstall: dask
    Found existing installation: dask 2026.1.1
    Uninstalling dask-2026.1.1:
      Successfully uninstalled dask-2026.1.1
  Attempting uninstall: click
    Found existing installation: click 8.3.3
    Uninstalling click-8.3.3:
      Successfully uninstalled click-8.3.3
  Attempting uninstall: certifi
    Found existing installation: certifi 2026.4.22
    Uninstalling certifi-2026.4.22:
      Successfully uninstalled certifi-2026.4.22
  Attempting uninstall: blosc2
    Found existing installation: blosc2 4.1.2
    Uninstalling blosc2-4.1.2:
      Successfully uninstalled blosc2-4.1.2
Successfully installed bidict-0.23.1 blosc2-4.7.0 certifi-2026.6.17 click-8.4.2 dask-2026.6.0 donfig-0.8.1.post1 fsspec-2026.6.0 geff-1.2.0.1.1 geff-spec-1.1.1 greenlet-3.5.3 idna-3.18 ilpy-0.6.0 imagecodecs-2026.6.26 llvmlite-0.47.0 markdown-it-py-4.2.0 msgpack-1.2.1 numba-0.65.1 numcodecs-0.15.1 packaging-26.2 pillow-12.2.0 polars-1.42.0 polars-runtime-32-1.42.0 pydantic-2.13.4 pydantic-core-2.46.4 pyscipopt-6.2.1 requests-2.34.2 rich-15.0.0 rustworkx-0.18.0 scikit-image-0.26.0 scipy-1.18.0 sqlalchemy-2.0.51 tifffile-2026.6.1 toolz-1.1.0 tqdm-4.68.3 tracksdata-0.1.0rc6.dev3+g980c2d30a typer-0.26.8 urllib3-2.7.0 wrapt-2.2.2 zarr-3.2.1

CompletedProcess(args=['pip', 'install', '--no-index', '--find-links', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels', '--no-deps', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/imagecodecs-2026.6.26-cp312-abi3-manylinux_2_28_x86_64.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/shellingham-1.5.4-py2.py3-none-any.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/numcodecs-0.15.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/bidict-0.23.1-py3-none-any.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/requests-2.34.2-py3-none-any.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/lazy_loader-0.5-py3-none-any.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/typing_extensions-4.15.0-py3-none-any.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/dask-2026.6.0-py3-none-any.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/charset_normalizer-3.4.7-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/cloudpickle-3.1.2-py3-none-any.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/toolz-1.1.0-py3-none-any.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/pydantic_core-2.46.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/idna-3.18-py3-none-any.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/imageio-2.37.3-py3-none-any.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/scipy-1.18.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/psygnal-0.15.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/ndindex-1.10.1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/tqdm-4.68.3-py3-none-any.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/markdown_it_py-4.2.0-py3-none-any.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/click-8.4.2-py3-none-any.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/blosc2-4.7.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/zarr-3.2.1-py3-none-any.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/pillow-12.2.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/certifi-2026.6.17-py3-none-any.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/msgpack-1.2.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/partd-1.4.2-py3-none-any.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/rustworkx-0.18.0-cp310-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/ilpy-0.6.0-py3-none-any.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/urllib3-2.7.0-py3-none-any.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/typing_inspection-0.4.2-py3-none-any.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/networkx-3.6.1-py3-none-any.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/annotated_types-0.7.0-py3-none-any.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/annotated_doc-0.0.4-py3-none-any.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/scikit_image-0.26.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/donfig-0.8.1.post1-py3-none-any.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/wrapt-2.2.2-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/tracksdata-0.1.0rc6.dev3+g980c2d30a-py3-none-any.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/threadpoolctl-3.6.0-py3-none-any.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/pydantic-2.13.4-py3-none-any.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/numexpr-2.14.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/tifffile-2026.6.1-py3-none-any.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/typer-0.26.8-py3-none-any.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/sqlalchemy-2.0.51-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/deprecated-1.3.1-py2.py3-none-any.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/fsspec-2026.6.0-py3-none-any.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/google_crc32c-1.8.0-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/llvmlite-0.47.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/polars-1.42.0-py3-none-any.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/pyyaml-6.0.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/geff-1.2.0.1.1-py3-none-any.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/mdurl-0.1.2-py3-none-any.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/numba-0.65.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/packaging-26.2-py3-none-any.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/pygments-2.20.0-py3-none-any.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/polars_runtime_32-1.42.0-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/pyscipopt-6.2.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/locket-1.0.0-py2.py3-none-any.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/rich-15.0.0-py3-none-any.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/greenlet-3.5.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/pyarrow-24.0.0-cp312-cp312-manylinux_2_28_x86_64.whl', '/kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/wheels/geff_spec-1.1.1-py3-none-any.whl'], returncode=0)

**Creating splits_filefile for the training and test datasets**

In [9]:
import json
import random
from pathlib import Path

if not TRAINING_PATH.is_dir():
    raise FileNotFoundError(f"TRAINING_PATH does not exist or is not a directory: {TRAINING_PATH}")

# stems with matching .geff annotation, same convention as the rest of the pipeline
train_pool_stems = sorted(
    p.stem for p in TRAINING_PATH.iterdir()
    if p.is_dir() and p.suffix == ".zarr"
    and (TRAINING_PATH / f"{p.stem}.geff").exists()
)
print(f"{len(train_pool_stems)} videos available in training pool")


MAX_SAMPLES = 10 # define how many datasets will be considered MAX_SAMPLES <= len(train_pool_stems)
VAL_FRACTION = 0.15  # 15% of the total considered data 
n_val = max(1, round(MAX_SAMPLES * VAL_FRACTION))

rng = random.Random(0)          # fixed seed — same split reused across every hp-search trial
shuffled = train_pool_stems.copy()
rng.shuffle(shuffled)
subset = shuffled[:MAX_SAMPLES]

val_stems = sorted(subset[:n_val])
train_stems = sorted(subset[n_val:])

print(f"{len(train_stems)} train / {len(val_stems)} val")
assert set(train_stems).isdisjoint(val_stems)  # sanity check — no leakage between the two

splits = [{"split": 0, "train": train_stems, "test": val_stems}]
# if split = "all" the "train()" function performs 5 folds during training
with open(f"{ARTIFACTS_WORK}/kaggle_train_val_splits.json", "w") as f:
    json.dump(splits, f, indent=2)

199 videos available in training pool
8 train / 2 val

In [10]:
#---------- Reading back the json file just created ------------
with open(f"{ARTIFACTS_WORK}/kaggle_train_val_splits.json", "r") as f:
    json_file = json.load(f)

json_file

[{'split': 0,
  'train': ['44b6_1574802b',
   '44b6_d5e7d891',
   '6bba_2312ac41',
   '6bba_5c824876',
   '6bba_7af54fde',
   '6bba_7b5d3b2c',
   '6bba_afb141ff',
   '6bba_d1acb6ff'],
  'test': ['44b6_d754aa59', '6bba_268e1230']}]

Applying modifications to the baseline code


Working now on the folder located in my work folder

In [11]:
REPO_DIR = ARTIFACTS_WORK / "repo"
target = REPO_DIR / "scripts" / "train_unet_transformer.py"  # path to the training script
src = target.read_text()

# 1. thread det_threshold through train_epoch
src = src.replace(
    "def train_epoch(\n    model: UNetNodeTransformer,\n    loader: DataLoader,\n    optimizer: torch.optim.Optimizer,\n    device: torch.device,\n    det_loss_weight: float = 0.1,\n    det_neg_weight: float = 0.1,\n    max_iters: int | None = None,\n    pool_kernel_um: float = 5.0,\n) -> tuple[float, float]:",
    "def train_epoch(\n    model: UNetNodeTransformer,\n    loader: DataLoader,\n    optimizer: torch.optim.Optimizer,\n    device: torch.device,\n    det_loss_weight: float = 0.1,\n    det_neg_weight: float = 0.1,\n    max_iters: int | None = None,\n    pool_kernel_um: float = 5.0,\n    det_threshold: float = 0.3,\n) -> tuple[float, float]:"
)
src = src.replace(
    "                voxel_size=voxel_size,\n                pool_kernel_um=pool_kernel_um,\n                frame_index=i, window_size=W,\n            )\n            unet_feat = model._index_features(\n                unet_out[:, i], det_c, det_m,\n            )\n            frame_det.append((det_c, det_p, det_m, matches, unet_feat))\n\n        # --- 4. Per-pair edge prediction",
    "                voxel_size=voxel_size,\n                pool_kernel_um=pool_kernel_um,\n                det_threshold=det_threshold,\n                frame_index=i, window_size=W,\n            )\n            unet_feat = model._index_features(\n                unet_out[:, i], det_c, det_m,\n            )\n            frame_det.append((det_c, det_p, det_m, matches, unet_feat))\n\n        # --- 4. Per-pair edge prediction"
)

# 2. train() returns metrics instead of just the model
src = src.replace(
    "    print(f\"\\nBest score (acc*recall): {best_score:.4f}, saved to {save_path}\")\n    if save_path.exists():",
    "    print(f\"\\nBest score (acc*recall): {best_score:.4f}, saved to {save_path}\")\n    metrics = {\"best_score\": best_score, \"final_edge_loss\": edge_loss,\n               \"final_det_loss\": det_loss, \"final_test_acc\": test_acc,\n               \"final_test_recall\": test_recall}\n    if save_path.exists():"
)
src = src.replace(
    "        model.load_state_dict(state)\n    return model",
    "        model.load_state_dict(state)\n    return model, metrics"
)

target.write_text(src)

49486

In [12]:
REPO_DIR = ARTIFACTS_WORK / "repo"

target = REPO_DIR / "scripts" / "train_unet_transformer.py"  # same path as before
src = target.read_text()

# 1. add full_checkpoint to train()'s signature
src = src.replace(
    "    pool_kernel_um: float = 5.0,\n    data_parallel: bool = True,\n) -> UNetNodeTransformer:",
    "    pool_kernel_um: float = 5.0,\n    data_parallel: bool = True,\n    full_checkpoint: Path | None = None,\n    det_threshold: float = 0.3,\n) -> UNetNodeTransformer:"
)

# 2. load it right after model construction, BEFORE any DataParallel wrapping
#    (checkpoint keys are unwrapped "unet.*", wrapping would change them to "unet.module.*")
src = src.replace(
    "    model = UNetNodeTransformer(\n        unet=unet,\n        unet_out_channels=unet_out_channels,\n        pos_feat_dim=pos_feat_dim,\n    ).to(device)\n",
    "    model = UNetNodeTransformer(\n        unet=unet,\n        unet_out_channels=unet_out_channels,\n        pos_feat_dim=pos_feat_dim,\n    ).to(device)\n\n"
    "    if full_checkpoint is not None:\n"
    "        ckpt_state = torch.load(full_checkpoint, map_location=device, weights_only=True)\n"
    "        missing, unexpected = model.load_state_dict(ckpt_state, strict=False)\n"
    "        print(f\"  Full checkpoint loaded from {full_checkpoint}: \"\n"
    "              f\"{len(missing)} missing, {len(unexpected)} unexpected\", flush=True)\n"
    "        if missing or unexpected:\n"
    "            print(f\"    missing (sample): {missing[:5]}\", flush=True)\n"
    "            print(f\"    unexpected (sample): {unexpected[:5]}\", flush=True)\n"
)

# 2. pass it into the train_epoch(...) call inside the epoch loop
src = src.replace(
    "        edge_loss, det_loss = train_epoch(\n"
    "            model, train_loader, optimizer, device, det_loss_weight, det_neg_weight,\n"
    "            max_iters=max_iters, pool_kernel_um=pool_kernel_um,\n"
    "        )",
    "        edge_loss, det_loss = train_epoch(\n"
    "            model, train_loader, optimizer, device, det_loss_weight, det_neg_weight,\n"
    "            max_iters=max_iters, pool_kernel_um=pool_kernel_um, det_threshold=det_threshold,\n"
    "        )"
)

# 3. pass it into the evaluate(...) call inside the epoch loop
src = src.replace(
    "        test_loss, test_acc, test_recall = evaluate(model, test_loader, device, pool_kernel_um=pool_kernel_um)",
    "        test_loss, test_acc, test_recall = evaluate(model, test_loader, device, pool_kernel_um=pool_kernel_um, det_threshold=det_threshold)"
)


target.write_text(src)

# sanity checks — confirm both edits actually matched before trusting them
assert "full_checkpoint: Path | None = None," in src
assert "Full checkpoint loaded from" in src
assert "det_threshold: float = 0.3,\n) -> UNetNodeTransformer:" in src
assert "pool_kernel_um=pool_kernel_um, det_threshold=det_threshold,\n        )" in src
assert "evaluate(model, test_loader, device, pool_kernel_um=pool_kernel_um, det_threshold=det_threshold)" in src

In [13]:
# 1. add det_threshold to evaluate()'s signature
src = src.replace(
    "def evaluate(\n"
    "    model: UNetNodeTransformer,\n"
    "    loader: DataLoader,\n"
    "    device: torch.device,\n"
    "    pool_kernel_um: float = 5.0,\n"
    ") -> tuple[float, float, float]:",
    "def evaluate(\n"
    "    model: UNetNodeTransformer,\n"
    "    loader: DataLoader,\n"
    "    device: torch.device,\n"
    "    pool_kernel_um: float = 5.0,\n"
    "    det_threshold: float = 0.3,\n"
    ") -> tuple[float, float, float]:"
)

# 2. pass it into detect_and_match(...) inside evaluate()'s loop
src = src.replace(
    "            det_c, det_p, det_m, matches = detect_and_match(\n"
    "                det_logits[i], coords[:, i], masks[:, i],\n"
    "                image_shape,\n"
    "                voxel_size=voxel_size,\n"
    "                pool_kernel_um=pool_kernel_um,\n"
    "                frame_index=i, window_size=W,\n"
    "            )\n"
    "            unet_feat = model._index_features(\n"
    "                unet_out[:, i], det_c, det_m,\n"
    "            )\n"
    "            frame_det.append((det_c, det_p, det_m, matches, unet_feat))\n"
    "\n"
    "            # Node recall:",
    "            det_c, det_p, det_m, matches = detect_and_match(\n"
    "                det_logits[i], coords[:, i], masks[:, i],\n"
    "                image_shape,\n"
    "                voxel_size=voxel_size,\n"
    "                pool_kernel_um=pool_kernel_um,\n"
    "                det_threshold=det_threshold,\n"
    "                frame_index=i, window_size=W,\n"
    "            )\n"
    "            unet_feat = model._index_features(\n"
    "                unet_out[:, i], det_c, det_m,\n"
    "            )\n"
    "            frame_det.append((det_c, det_p, det_m, matches, unet_feat))\n"
    "\n"
    "            # Node recall:"
)

target.write_text(src)
assert "det_threshold: float = 0.3,\n) -> tuple[float, float, float]:" in src

In [14]:
lines = target.read_text().splitlines(keepends=True)

# line 1201 in your grep output is 1-indexed; list index is 1200
assert "Best score (acc" in lines[1200], f"unexpected content at index 1200: {lines[1200]!r}"

# metrics_block = (
#     '    metrics = {"best_score": best_score, "final_edge_loss": edge_loss,\n'
#     '               "final_det_loss": det_loss, "final_test_acc": test_acc,\n'
#     '               "final_test_recall": test_recall}\n'
# )

metrics_block = (
    '    metrics = {"best_score": best_score, "final_edge_loss": edge_loss,\n'
    '               "final_det_loss": det_loss, "final_test_acc": test_acc,\n'
    '               "final_test_recall": test_recall,\n'
    '               "best_test_acc": best_test_acc, "best_test_recall": best_test_recall}\n'
)


lines.insert(1201, metrics_block)  # insert right after the print line
target.write_text("".join(lines))
print("inserted")

inserted

In [15]:
REPO_DIR = ARTIFACTS_WORK / "repo"

target = REPO_DIR / "scripts" / "train_unet_transformer.py"  # same path as before
src = target.read_text()

old = (
    "        if is_best:\n"
    "            best_score = score\n"
)
new = (
    "        if is_best:\n"
    "            best_score = score\n"
    "            best_test_acc, best_test_recall = test_acc, test_recall\n"
)

#to check my text is well constructed with respect to the .py file
assert src.count(old) == 1, f"expected exactly 1 match, found {src.count(old)}"

src = src.replace(old, new)
target.write_text(src)

# verify against the file, not just the in-memory string
current = target.read_text()
assert "best_test_acc, best_test_recall = test_acc, test_recall" in current
print("confirmed on disk")

confirmed on disk

In [16]:
import inspect
from train_unet_transformer import train
print(inspect.getsource(train).count("best_test_acc"))  # should be >= 2 (assignment + dict entry)

3

/usr/local/lib/python3.12/dist-packages/dask/array/image.py:7: FutureWarning: `find_available_plugins` is deprecated since version 0.25 and will be removed in version 0.27. The plugin infrastructure of `skimage.io` is deprecated. Instead, use `imageio` or other I/O packages directly.
  from skimage.io import imread as sk_imread
/usr/lib/python3.12/importlib/__init__.py:90: FutureWarning: `reset_plugins` is deprecated since version 0.25 and will be removed in version 0.27. The plugin infrastructure of `skimage.io` is deprecated. Instead, use `imageio` or other I/O packages directly.
  return _bootstrap._gcd_import(name[level:], package, level)

## Run configuration

In [17]:
METHOD = "unet_transformer"

# --------------- Reading weights from the baseline model ---------------------------------------
# in the test set, the baseline model scored 0.8, let's see if we can improve this
# Model checkpoint (relative to the repo, or an absolute path to your own).
WEIGHTS = f"weights/{METHOD}/split_0/edge_predictor_best.pth"

## Sweep of set 2

#### Computing average spacing between cells from input datasets

In [18]:
import numpy as np
import polars as pl
from tracking_cellmot.io import open_dataset
from scipy.spatial import cKDTree

# pick a couple of representative training videos
# sample_stems = train_stems[:3]
sample_stems  = train_pool_stems # use this option if you want to use the whole training set

all_nn_dists = []
all_voxel_sizes = []

for stem in sample_stems: #moving trhough each movie (folder)
    ds = open_dataset(TRAINING_PATH / stem, normalize=False, require_tracks=True,
                       load_image=False, downsample=(1, 1, 1))  # no downsample — real physical units
    tracks = ds.tracks #gets the tracks
    voxel_size = ds.scale  # physical size per voxel, (Z, Y, X) as commented in competition documentation
    all_voxel_sizes.append(voxel_size)

    attrs = tracks.node_attrs(attr_keys=["t", "z", "y", "x"]) #this is a polars dataframe
    for t in attrs["t"].unique().to_list(): #unique temporal steps
        frame = attrs.filter(pl.col("t") == t) #taking only the frame t (Z,Y,X are obtained)
        coords = frame.select(["z", "y", "x"]).to_numpy() * np.array(voxel_size)  # -> getting coordinate and then physical microns
        if len(coords) < 2: #not a 3d space
            continue
        # nearest-neighbor distance for each node in this frame
        
        tree = cKDTree(coords)
        dists, _ = tree.query(coords, k=2)  # k=2: closest point to itself (0) + true nearest neighbor
        all_nn_dists.extend(dists[:, 1]) #to concantenate the array

all_nn_dists = np.array(all_nn_dists)
p10 = np.percentile(all_nn_dists,10)
median = np.median(all_nn_dists)
p90 = np.percentile(all_nn_dists,90)
print(f"voxel_size (Z,Y,X) per video: {all_voxel_sizes}")
print(f"nearest-neighbor distance (microns): "
      f"p10={p10:.2f}  "
      f"median={median:.2f}  "
      f"p90={p90:.2f}")

voxel_size (Z,Y,X) per video: [(1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625), (1.625, 0.40625, 0.40625)]
nearest-neighbor distance (microns): p10=13.96  median=24.99  p90=43.32

### Performing sweep

In [19]:
import itertools
import json
import time
from pathlib import Path
import gc
import torch
import random

from train_unet_transformer import train

RESULTS_PATH = Path("hp_search_results_part3.jsonl")
random.seed(0)
n_random_trials = 12  #approx 4 hours with 12 trials



def log_result(record: dict) -> None:
    with open(RESULTS_PATH, "a") as f:
        f.write(json.dumps(record) + "\n")

def run_trial(trial_id: str, **kwargs) -> dict:
    t0 = time.monotonic()
    try:
        model, metrics = train(**kwargs)
    finally:
        # ensure cleanup happens even if this trial itself OOMs
        if "model" in dir():
            del model
        gc.collect()
        torch.cuda.empty_cache()
    elapsed = time.monotonic() - t0
    record = {
        "trial_id": trial_id,
        "elapsed_s": round(elapsed, 1),
        **{k: (str(v) if isinstance(v, Path) else v) for k, v in kwargs.items()
           if k not in ("data_dir", "splits_file", "unet_layers", "full_checkpoint")},
        **metrics,
    }
    log_result(record)
    print(f"[{trial_id}] score={metrics['best_score']:.4f}  ({elapsed:.0f}s)")
    return record


FULL_CHECKPOINT = ARTIFACTS_SRC / "weights" / METHOD / "split_0" / "edge_predictor_best.pth"
assert FULL_CHECKPOINT.exists(), f"not found: {FULL_CHECKPOINT}"

# -----------------------------------------------------------------------
# Now we are going to fix the variables we found in the previous searches 
# -----------------------------------------------------------------------
LR = 0.00005
DET_LOSS_WEIGHT = 4
DET_NEG_WEIGHT = 0.010
DET_TRHESHOLD = 0.80

FIXED = dict(
    data_dir=Path(DATA_PATH)/"train",
    splits_file=ARTIFACTS_WORK/"kaggle_train_val_splits.json",
    fold=0,
    n_epochs=4,
    max_iters=200,
    seed=0,
    data_parallel=False, #set it to False given the small batch_size
    batch_size=2,
    method="hp_search_tier1",
    full_checkpoint=FULL_CHECKPOINT,   # <-- warm-start every trial from the 0.80 baseline
    lr = LR,
    det_loss_weight = DET_LOSS_WEIGHT,
    det_neg_weight = DET_NEG_WEIGHT,
    det_threshold = DET_TRHESHOLD,
    
)


# tier1b_space = {
#     "lr": [1e-5, 3e-5, 5e-5],              # bracket below and around the current winner
#     "det_loss_weight": [2, 3, 4],          # move araound the optimal = 3
#     "det_neg_weight": [0.003, 0.01, 0.03], #similar best score: 0.003 -> best score 0.908 and 0.03 -> best score 0.907
#     "det_threshold": [0.8, 0.92, 0.99],      # move from 0.80 to 0.99
# }

#-----------------------------------------------------------------
#Set 2: The variables are
#pool_kernel_um
#window_size
#these values are set according to the results from the mean distance between cells
#-----------------------------------------------------------------
MEAN_NODE_DISTANCE = median #um
tier2_space = {
    "pool_kernel_um":     [0.1*MEAN_NODE_DISTANCE,0.3*MEAN_NODE_DISTANCE,MEAN_NODE_DISTANCE,0.7*MEAN_NODE_DISTANCE],  # fill from d_nn above. This sets the radius of a local max-pooling window to decide around that radius what is the voxel with the largest probability of being a cell
                                  # if it is too large, multiple cells might be merged but too small will create artificial cells.
 #   "max_match_distance": [7],  # fill from d_nn above. It sets how fall apart a detected peak and a GT node are allowed to be and still count
                                  # as the same cell. it's purely about scoring/labeling those detections against the answer key.
                                # 7 um is the value defined in the competition documentation
    "window_size":        [2, 3], #temporal windows to consider parent-child nodes
}


keys = list(tier2_space.keys())
combos = list(itertools.product(*tier2_space.values()))
random.shuffle(combos)


#for i, combo in enumerate(itertools.product(*tier1_space.values())):
# for i, combo in enumerate(combos[:1]): # to test one sample
for i, combo in enumerate(combos[:n_random_trials]):
    kwargs = dict(zip(keys, combo))
    run_trial(f"tier2_{i:03d}", **FIXED, **kwargs)
    print(torch.cuda.memory_allocated() / 1e9, "GB allocated")
    print(torch.cuda.memory_reserved() / 1e9, "GB reserved")

Fold 0: 8 train, 2 test
Loading train (8 datasets)...

train: 100%|██████████| 8/8 [00:04<00:00,  1.69it/s]

  train done: 787 windows total
Loading test (2 datasets)...

test: 100%|██████████| 2/2 [00:00<00:00,  2.28it/s]

  test done: 164 windows total
max_nodes=17

Using device: cuda | visible CUDA GPUs: 2
  Full checkpoint loaded from /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/weights/unet_transformer/split_0/edge_predictor_best.pth: 0 missing, 0 unexpected
Single-GPU training (--single-gpu set). For 2 GPUs set the Kaggle accelerator to 'GPU T4 x2'.
Model parameters: 2,076,706
Starting training for 4 epochs (batch_size=2)...

Training:   0%|          | 0/4 [00:00<?, ?it/s]

Detection loss: weight=4, neg_weight=0.01

  iters:   0%|          | 0/200 [00:00<?, ?it/s]
  iters:   0%|          | 1/200 [00:03<10:33,  3.18s/it]
  iters:   1%|          | 2/200 [00:04<06:18,  1.91s/it]
  iters:   2%|▏         | 3/200 [00:05<04:59,  1.52s/it]
  iters:   2%|▏         | 4/200 [00:06<04:21,  1.33s/it]
  iters:   2%|▎         | 5/200 [00:07<03:58,  1.22s/it]
  iters:   3%|▎         | 6/200 [00:08<03:45,  1.16s/it]
  iters:   4%|▎         | 7/200 [00:09<03:36,  1.12s/it]
  iters:   4%|▍         | 8/200 [00:10<03:29,  1.09s/it]
  iters:   4%|▍         | 9/200 [00:11<03:25,  1.08s/it]
  iters:   5%|▌         | 10/200 [00:12<03:22,  1.07s/it]
  iters:   6%|▌         | 11/200 [00:13<03:20,  1.06s/it]
  iters:   6%|▌         | 12/200 [00:14<03:18,  1.06s/it]
  iters:   6%|▋         | 13/200 [00:15<03:17,  1.05s/it]
  iters:   7%|▋         | 14/200 [00:16<03:15,  1.05s/it]
  iters:   8%|▊         | 15/200 [00:17<03:14,  1.05s/it]
  iters:   8%|▊         | 16/200 [00:18<03:13,  1.05s/it]
  iters:   8%|▊         | 17/200 [00:19<03:11,  1.05s/it]
  iters:   9%|▉         | 18/200 [00:20<03:10,  1.05s/it]
  iters:  10%|▉         | 19/200 [00:21<03:09,  1.05s/it]
  iters:  10%|█         | 20/200 [00:23<03:09,  1.05s/it]
  iters:  10%|█         | 21/200 [00:24<03:08,  1.05s/it]
  iters:  11%|█         | 22/200 [00:25<03:07,  1.05s/it]
  iters:  12%|█▏        | 23/200 [00:26<03:07,  1.06s/it]
  iters:  12%|█▏        | 24/200 [00:27<03:05,  1.06s/it]
  iters:  12%|█▎        | 25/200 [00:28<03:05,  1.06s/it]
  iters:  13%|█▎        | 26/200 [00:29<03:05,  1.06s/it]
  iters:  14%|█▎        | 27/200 [00:30<03:03,  1.06s/it]
  iters:  14%|█▍        | 28/200 [00:31<03:02,  1.06s/it]
  iters:  14%|█▍        | 29/200 [00:32<03:00,  1.05s/it]
  iters:  15%|█▌        | 30/200 [00:33<03:00,  1.06s/it]
  iters:  16%|█▌        | 31/200 [00:34<02:59,  1.06s/it]
  iters:  16%|█▌        | 32/200 [00:35<02:59,  1.07s/it]
  iters:  16%|█▋        | 33/200 [00:36<02:58,  1.07s/it]
  iters:  17%|█▋        | 34/200 [00:37<02:57,  1.07s/it]
  iters:  18%|█▊        | 35/200 [00:38<02:57,  1.07s/it]
  iters:  18%|█▊        | 36/200 [00:40<02:56,  1.07s/it]
  iters:  18%|█▊        | 37/200 [00:41<02:55,  1.07s/it]
  iters:  19%|█▉        | 38/200 [00:42<02:54,  1.07s/it]
  iters:  20%|█▉        | 39/200 [00:43<02:53,  1.08s/it]
  iters:  20%|██        | 40/200 [00:44<02:52,  1.08s/it]
  iters:  20%|██        | 41/200 [00:45<02:52,  1.08s/it]
  iters:  21%|██        | 42/200 [00:46<02:51,  1.09s/it]
  iters:  22%|██▏       | 43/200 [00:47<02:50,  1.09s/it]
  iters:  22%|██▏       | 44/200 [00:48<02:49,  1.09s/it]
  iters:  22%|██▎       | 45/200 [00:49<02:48,  1.09s/it]
  iters:  23%|██▎       | 46/200 [00:50<02:46,  1.08s/it]
  iters:  24%|██▎       | 47/200 [00:52<02:46,  1.09s/it]
  iters:  24%|██▍       | 48/200 [00:53<02:45,  1.09s/it]
  iters:  24%|██▍       | 49/200 [00:54<02:44,  1.09s/it]
  iters:  25%|██▌       | 50/200 [00:55<02:43,  1.09s/it]
  iters:  26%|██▌       | 51/200 [00:56<02:42,  1.09s/it]
  iters:  26%|██▌       | 52/200 [00:57<02:41,  1.09s/it]
  iters:  26%|██▋       | 53/200 [00:58<02:40,  1.09s/it]
  iters:  27%|██▋       | 54/200 [00:59<02:39,  1.09s/it]
  iters:  28%|██▊       | 55/200 [01:00<02:36,  1.08s/it]
  iters:  28%|██▊       | 56/200 [01:01<02:36,  1.09s/it]
  iters:  28%|██▊       | 57/200 [01:02<02:36,  1.10s/it]
  iters:  29%|██▉       | 58/200 [01:04<02:36,  1.10s/it]
  iters:  30%|██▉       | 59/200 [01:05<02:35,  1.10s/it]
  iters:  30%|███       | 60/200 [01:06<02:34,  1.10s/it]
  iters:  30%|███       | 61/200 [01:07<02:33,  1.10s/it]
  iters:  31%|███       | 62/200 [01:08<02:32,  1.11s/it]
  iters:  32%|███▏      | 63/200 [01:09<02:32,  1.11s/it]
  iters:  32%|███▏      | 64/200 [01:10<02:31,  1.11s/it]
  iters:  32%|███▎      | 65/200 [01:11<02:30,  1.11s/it]
  iters:  33%|███▎      | 66/200 [01:12<02:29,  1.11s/it]
  iters:  34%|███▎      | 67/200 [01:14<02:28,  1.12s/it]
  iters:  34%|███▍      | 68/200 [01:15<02:27,  1.12s/it]
  iters:  34%|███▍      | 69/200 [01:16<02:26,  1.12s/it]
  iters:  35%|███▌      | 70/200 [01:17<02:25,  1.12s/it]
  iters:  36%|███▌      | 71/200 [01:18<02:24,  1.12s/it]
  iters:  36%|███▌      | 72/200 [01:19<02:23,  1.12s/it]
  iters:  36%|███▋      | 73/200 [01:20<02:22,  1.12s/it]
  iters:  37%|███▋      | 74/200 [01:21<02:22,  1.13s/it]
  iters:  38%|███▊      | 75/200 [01:23<02:21,  1.13s/it]
  iters:  38%|███▊      | 76/200 [01:24<02:20,  1.13s/it]
  iters:  38%|███▊      | 77/200 [01:25<02:19,  1.13s/it]
  iters:  39%|███▉      | 78/200 [01:26<02:18,  1.13s/it]
  iters:  40%|███▉      | 79/200 [01:27<02:17,  1.14s/it]
  iters:  40%|████      | 80/200 [01:28<02:16,  1.14s/it]
  iters:  40%|████      | 81/200 [01:29<02:16,  1.14s/it]
  iters:  41%|████      | 82/200 [01:31<02:15,  1.15s/it]
  iters:  42%|████▏     | 83/200 [01:32<02:14,  1.15s/it]
  iters:  42%|████▏     | 84/200 [01:33<02:13,  1.15s/it]
  iters:  42%|████▎     | 85/200 [01:34<02:12,  1.15s/it]
  iters:  43%|████▎     | 86/200 [01:35<02:11,  1.15s/it]
  iters:  44%|████▎     | 87/200 [01:36<02:10,  1.15s/it]
  iters:  44%|████▍     | 88/200 [01:37<02:08,  1.15s/it]
  iters:  44%|████▍     | 89/200 [01:39<02:07,  1.15s/it]
  iters:  45%|████▌     | 90/200 [01:40<02:06,  1.15s/it]
  iters:  46%|████▌     | 91/200 [01:41<02:05,  1.15s/it]
  iters:  46%|████▌     | 92/200 [01:42<02:04,  1.16s/it]
  iters:  46%|████▋     | 93/200 [01:43<02:04,  1.16s/it]
  iters:  47%|████▋     | 94/200 [01:44<02:03,  1.16s/it]
  iters:  48%|████▊     | 95/200 [01:46<02:02,  1.16s/it]
  iters:  48%|████▊     | 96/200 [01:47<02:01,  1.17s/it]
  iters:  48%|████▊     | 97/200 [01:48<02:00,  1.17s/it]
  iters:  49%|████▉     | 98/200 [01:49<01:58,  1.17s/it]
  iters:  50%|████▉     | 99/200 [01:50<01:57,  1.17s/it]
  iters:  50%|█████     | 100/200 [01:51<01:56,  1.17s/it]
  iters:  50%|█████     | 101/200 [01:53<01:55,  1.17s/it]
  iters:  51%|█████     | 102/200 [01:54<01:55,  1.17s/it]
  iters:  52%|█████▏    | 103/200 [01:55<01:54,  1.18s/it]
  iters:  52%|█████▏    | 104/200 [01:56<01:52,  1.18s/it]
  iters:  52%|█████▎    | 105/200 [01:57<01:52,  1.18s/it]
  iters:  53%|█████▎    | 106/200 [01:59<01:51,  1.18s/it]
  iters:  54%|█████▎    | 107/200 [02:00<01:49,  1.18s/it]
  iters:  54%|█████▍    | 108/200 [02:01<01:49,  1.19s/it]
  iters:  55%|█████▍    | 109/200 [02:02<01:48,  1.19s/it]
  iters:  55%|█████▌    | 110/200 [02:03<01:47,  1.19s/it]
  iters:  56%|█████▌    | 111/200 [02:05<01:46,  1.19s/it]
  iters:  56%|█████▌    | 112/200 [02:06<01:43,  1.18s/it]
  iters:  56%|█████▋    | 113/200 [02:07<01:42,  1.18s/it]
  iters:  57%|█████▋    | 114/200 [02:08<01:42,  1.19s/it]
  iters:  57%|█████▊    | 115/200 [02:09<01:41,  1.20s/it]
  iters:  58%|█████▊    | 116/200 [02:10<01:40,  1.20s/it]
  iters:  58%|█████▊    | 117/200 [02:12<01:38,  1.19s/it]
  iters:  59%|█████▉    | 118/200 [02:13<01:38,  1.20s/it]
  iters:  60%|█████▉    | 119/200 [02:14<01:37,  1.20s/it]
  iters:  60%|██████    | 120/200 [02:15<01:36,  1.21s/it]
  iters:  60%|██████    | 121/200 [02:17<01:35,  1.21s/it]
  iters:  61%|██████    | 122/200 [02:18<01:34,  1.22s/it]
  iters:  62%|██████▏   | 123/200 [02:19<01:33,  1.22s/it]
  iters:  62%|██████▏   | 124/200 [02:20<01:32,  1.22s/it]
  iters:  62%|██████▎   | 125/200 [02:21<01:31,  1.22s/it]
  iters:  63%|██████▎   | 126/200 [02:23<01:30,  1.23s/it]
  iters:  64%|██████▎   | 127/200 [02:24<01:29,  1.23s/it]
  iters:  64%|██████▍   | 128/200 [02:25<01:28,  1.23s/it]
  iters:  64%|██████▍   | 129/200 [02:26<01:27,  1.24s/it]
  iters:  65%|██████▌   | 130/200 [02:28<01:26,  1.24s/it]
  iters:  66%|██████▌   | 131/200 [02:29<01:25,  1.24s/it]
  iters:  66%|██████▌   | 132/200 [02:30<01:24,  1.24s/it]
  iters:  66%|██████▋   | 133/200 [02:31<01:22,  1.24s/it]
  iters:  67%|██████▋   | 134/200 [02:33<01:21,  1.23s/it]
  iters:  68%|██████▊   | 135/200 [02:34<01:20,  1.23s/it]
  iters:  68%|██████▊   | 136/200 [02:35<01:18,  1.23s/it]
  iters:  68%|██████▊   | 137/200 [02:36<01:17,  1.23s/it]
  iters:  69%|██████▉   | 138/200 [02:37<01:15,  1.23s/it]
  iters:  70%|██████▉   | 139/200 [02:39<01:14,  1.23s/it]
  iters:  70%|███████   | 140/200 [02:40<01:13,  1.22s/it]
  iters:  70%|███████   | 141/200 [02:41<01:12,  1.22s/it]
  iters:  71%|███████   | 142/200 [02:42<01:10,  1.22s/it]
  iters:  72%|███████▏  | 143/200 [02:44<01:09,  1.22s/it]
  iters:  72%|███████▏  | 144/200 [02:45<01:08,  1.22s/it]
  iters:  72%|███████▎  | 145/200 [02:46<01:06,  1.22s/it]
  iters:  73%|███████▎  | 146/200 [02:47<01:05,  1.21s/it]
  iters:  74%|███████▎  | 147/200 [02:48<01:04,  1.21s/it]
  iters:  74%|███████▍  | 148/200 [02:50<01:02,  1.21s/it]
  iters:  74%|███████▍  | 149/200 [02:51<01:01,  1.20s/it]
  iters:  75%|███████▌  | 150/200 [02:52<01:00,  1.20s/it]
  iters:  76%|███████▌  | 151/200 [02:53<00:58,  1.20s/it]
  iters:  76%|███████▌  | 152/200 [02:54<00:57,  1.20s/it]
  iters:  76%|███████▋  | 153/200 [02:56<00:56,  1.20s/it]
  iters:  77%|███████▋  | 154/200 [02:57<00:55,  1.20s/it]
  iters:  78%|███████▊  | 155/200 [02:58<00:53,  1.20s/it]
  iters:  78%|███████▊  | 156/200 [02:59<00:52,  1.20s/it]
  iters:  78%|███████▊  | 157/200 [03:00<00:51,  1.20s/it]
  iters:  79%|███████▉  | 158/200 [03:02<00:50,  1.19s/it]
  iters:  80%|███████▉  | 159/200 [03:03<00:48,  1.19s/it]
  iters:  80%|████████  | 160/200 [03:04<00:47,  1.19s/it]
  iters:  80%|████████  | 161/200 [03:05<00:46,  1.19s/it]
  iters:  81%|████████  | 162/200 [03:06<00:45,  1.19s/it]
  iters:  82%|████████▏ | 163/200 [03:07<00:43,  1.19s/it]
  iters:  82%|████████▏ | 164/200 [03:09<00:42,  1.18s/it]
  iters:  82%|████████▎ | 165/200 [03:10<00:41,  1.19s/it]
  iters:  83%|████████▎ | 166/200 [03:11<00:40,  1.19s/it]
  iters:  84%|████████▎ | 167/200 [03:12<00:39,  1.19s/it]
  iters:  84%|████████▍ | 168/200 [03:13<00:38,  1.19s/it]
  iters:  84%|████████▍ | 169/200 [03:15<00:36,  1.19s/it]
  iters:  85%|████████▌ | 170/200 [03:16<00:35,  1.19s/it]
  iters:  86%|████████▌ | 171/200 [03:17<00:34,  1.19s/it]
  iters:  86%|████████▌ | 172/200 [03:18<00:33,  1.18s/it]
  iters:  86%|████████▋ | 173/200 [03:19<00:32,  1.19s/it]
  iters:  87%|████████▋ | 174/200 [03:21<00:30,  1.19s/it]
  iters:  88%|████████▊ | 175/200 [03:22<00:29,  1.19s/it]
  iters:  88%|████████▊ | 176/200 [03:23<00:28,  1.19s/it]
  iters:  88%|████████▊ | 177/200 [03:24<00:27,  1.19s/it]
  iters:  89%|████████▉ | 178/200 [03:25<00:26,  1.19s/it]
  iters:  90%|████████▉ | 179/200 [03:26<00:24,  1.18s/it]
  iters:  90%|█████████ | 180/200 [03:28<00:23,  1.18s/it]
  iters:  90%|█████████ | 181/200 [03:29<00:22,  1.19s/it]
  iters:  91%|█████████ | 182/200 [03:30<00:21,  1.19s/it]
  iters:  92%|█████████▏| 183/200 [03:31<00:20,  1.19s/it]
  iters:  92%|█████████▏| 184/200 [03:32<00:19,  1.19s/it]
  iters:  92%|█████████▎| 185/200 [03:34<00:17,  1.20s/it]
  iters:  93%|█████████▎| 186/200 [03:35<00:16,  1.20s/it]
  iters:  94%|█████████▎| 187/200 [03:36<00:15,  1.18s/it]
  iters:  94%|█████████▍| 188/200 [03:37<00:14,  1.19s/it]
  iters:  94%|█████████▍| 189/200 [03:38<00:13,  1.19s/it]
  iters:  95%|█████████▌| 190/200 [03:40<00:11,  1.19s/it]
  iters:  96%|█████████▌| 191/200 [03:41<00:10,  1.19s/it]
  iters:  96%|█████████▌| 192/200 [03:42<00:09,  1.19s/it]
  iters:  96%|█████████▋| 193/200 [03:43<00:08,  1.20s/it]
  iters:  97%|█████████▋| 194/200 [03:44<00:07,  1.20s/it]
  iters:  98%|█████████▊| 195/200 [03:46<00:05,  1.20s/it]
  iters:  98%|█████████▊| 196/200 [03:47<00:04,  1.20s/it]
  iters:  98%|█████████▊| 197/200 [03:48<00:03,  1.20s/it]
  iters:  99%|█████████▉| 198/200 [03:49<00:02,  1.19s/it]
  iters: 100%|█████████▉| 199/200 [03:50<00:01,  1.19s/it]
  iters: 100%|██████████| 200/200 [03:52<00:00,  1.20s/it]

  [timing] data: 2.4s (1%) | forward: 58.2s (25%) | backward: 171.4s (74%) | total: 232.0s

Training:   0%|          | 0/4 [04:15<?, ?it/s, acc=0.9992, det=0.0091, edge=0.0007]

  Epoch   0/4 | edge=0.0007 | det=0.0091 | test_loss=0.0007 | acc=0.9992 | recall=0.7647 | best=0.7640 * | train=232.2s test=23.6s

Training:  25%|██▌       | 1/4 [04:15<12:47, 255.85s/it, acc=0.9992, det=0.0091, edge=0.0007]
  iters:   0%|          | 0/200 [00:00<?, ?it/s]
  iters:   0%|          | 1/200 [00:01<04:22,  1.32s/it]
  iters:   1%|          | 2/200 [00:02<04:06,  1.25s/it]
  iters:   2%|▏         | 3/200 [00:03<04:02,  1.23s/it]
  iters:   2%|▏         | 4/200 [00:04<03:58,  1.22s/it]
  iters:   2%|▎         | 5/200 [00:06<03:55,  1.21s/it]
  iters:   3%|▎         | 6/200 [00:07<03:53,  1.20s/it]
  iters:   4%|▎         | 7/200 [00:08<03:51,  1.20s/it]
  iters:   4%|▍         | 8/200 [00:09<03:51,  1.20s/it]
  iters:   4%|▍         | 9/200 [00:10<03:49,  1.20s/it]
  iters:   5%|▌         | 10/200 [00:12<03:48,  1.20s/it]
  iters:   6%|▌         | 11/200 [00:13<03:47,  1.20s/it]
  iters:   6%|▌         | 12/200 [00:14<03:45,  1.20s/it]
  iters:   6%|▋         | 13/200 [00:15<03:41,  1.19s/it]
  iters:   7%|▋         | 14/200 [00:16<03:41,  1.19s/it]
  iters:   8%|▊         | 15/200 [00:18<03:40,  1.19s/it]
  iters:   8%|▊         | 16/200 [00:19<03:39,  1.19s/it]
  iters:   8%|▊         | 17/200 [00:20<03:38,  1.20s/it]
  iters:   9%|▉         | 18/200 [00:21<03:37,  1.19s/it]
  iters:  10%|▉         | 19/200 [00:22<03:36,  1.20s/it]
  iters:  10%|█         | 20/200 [00:24<03:34,  1.19s/it]
  iters:  10%|█         | 21/200 [00:25<03:34,  1.20s/it]
  iters:  11%|█         | 22/200 [00:26<03:30,  1.18s/it]
  iters:  12%|█▏        | 23/200 [00:27<03:29,  1.18s/it]
  iters:  12%|█▏        | 24/200 [00:28<03:29,  1.19s/it]
  iters:  12%|█▎        | 25/200 [00:30<03:41,  1.27s/it]
  iters:  13%|█▎        | 26/200 [00:31<03:36,  1.25s/it]
  iters:  14%|█▎        | 27/200 [00:32<03:33,  1.23s/it]
  iters:  14%|█▍        | 28/200 [00:33<03:30,  1.22s/it]
  iters:  14%|█▍        | 29/200 [00:35<03:27,  1.21s/it]
  iters:  15%|█▌        | 30/200 [00:36<03:25,  1.21s/it]
  iters:  16%|█▌        | 31/200 [00:37<03:23,  1.21s/it]
  iters:  16%|█▌        | 32/200 [00:38<03:21,  1.20s/it]
  iters:  16%|█▋        | 33/200 [00:39<03:20,  1.20s/it]
  iters:  17%|█▋        | 34/200 [00:41<03:18,  1.20s/it]
  iters:  18%|█▊        | 35/200 [00:42<03:17,  1.20s/it]
  iters:  18%|█▊        | 36/200 [00:43<03:16,  1.20s/it]
  iters:  18%|█▊        | 37/200 [00:44<03:15,  1.20s/it]
  iters:  19%|█▉        | 38/200 [00:45<03:14,  1.20s/it]
  iters:  20%|█▉        | 39/200 [00:46<03:12,  1.20s/it]
  iters:  20%|██        | 40/200 [00:48<03:11,  1.20s/it]
  iters:  20%|██        | 41/200 [00:49<03:10,  1.20s/it]
  iters:  21%|██        | 42/200 [00:50<03:09,  1.20s/it]
  iters:  22%|██▏       | 43/200 [00:51<03:08,  1.20s/it]
  iters:  22%|██▏       | 44/200 [00:52<03:06,  1.20s/it]
  iters:  22%|██▎       | 45/200 [00:54<03:05,  1.20s/it]
  iters:  23%|██▎       | 46/200 [00:55<03:04,  1.20s/it]
  iters:  24%|██▎       | 47/200 [00:56<03:02,  1.19s/it]
  iters:  24%|██▍       | 48/200 [00:57<03:01,  1.20s/it]
  iters:  24%|██▍       | 49/200 [00:58<03:00,  1.20s/it]
  iters:  25%|██▌       | 50/200 [01:00<02:59,  1.20s/it]
  iters:  26%|██▌       | 51/200 [01:01<02:58,  1.20s/it]
  iters:  26%|██▌       | 52/200 [01:02<02:56,  1.20s/it]
  iters:  26%|██▋       | 53/200 [01:03<02:55,  1.20s/it]
  iters:  27%|██▋       | 54/200 [01:04<02:54,  1.20s/it]
  iters:  28%|██▊       | 55/200 [01:06<02:53,  1.20s/it]
  iters:  28%|██▊       | 56/200 [01:07<02:52,  1.20s/it]
  iters:  28%|██▊       | 57/200 [01:08<02:51,  1.20s/it]
  iters:  29%|██▉       | 58/200 [01:09<02:49,  1.20s/it]
  iters:  30%|██▉       | 59/200 [01:10<02:48,  1.19s/it]
  iters:  30%|███       | 60/200 [01:12<02:47,  1.20s/it]
  iters:  30%|███       | 61/200 [01:13<02:46,  1.20s/it]
  iters:  31%|███       | 62/200 [01:14<02:45,  1.20s/it]
  iters:  32%|███▏      | 63/200 [01:15<02:43,  1.20s/it]
  iters:  32%|███▏      | 64/200 [01:16<02:42,  1.20s/it]
  iters:  32%|███▎      | 65/200 [01:18<02:39,  1.18s/it]
  iters:  33%|███▎      | 66/200 [01:19<02:38,  1.18s/it]
  iters:  34%|███▎      | 67/200 [01:20<02:38,  1.19s/it]
  iters:  34%|███▍      | 68/200 [01:21<02:37,  1.19s/it]
  iters:  34%|███▍      | 69/200 [01:22<02:36,  1.19s/it]
  iters:  35%|███▌      | 70/200 [01:23<02:33,  1.18s/it]
  iters:  36%|███▌      | 71/200 [01:25<02:31,  1.17s/it]
  iters:  36%|███▌      | 72/200 [01:26<02:29,  1.17s/it]
  iters:  36%|███▋      | 73/200 [01:27<02:29,  1.18s/it]
  iters:  37%|███▋      | 74/200 [01:28<02:28,  1.18s/it]
  iters:  38%|███▊      | 75/200 [01:29<02:28,  1.19s/it]
  iters:  38%|███▊      | 76/200 [01:31<02:27,  1.19s/it]
  iters:  38%|███▊      | 77/200 [01:32<02:26,  1.19s/it]
  iters:  39%|███▉      | 78/200 [01:33<02:25,  1.19s/it]
  iters:  40%|███▉      | 79/200 [01:34<02:24,  1.19s/it]
  iters:  40%|████      | 80/200 [01:35<02:23,  1.19s/it]
  iters:  40%|████      | 81/200 [01:37<02:21,  1.19s/it]
  iters:  41%|████      | 82/200 [01:38<02:20,  1.19s/it]
  iters:  42%|████▏     | 83/200 [01:39<02:19,  1.19s/it]
  iters:  42%|████▏     | 84/200 [01:40<02:18,  1.19s/it]
  iters:  42%|████▎     | 85/200 [01:41<02:15,  1.18s/it]
  iters:  43%|████▎     | 86/200 [01:42<02:15,  1.19s/it]
  iters:  44%|████▎     | 87/200 [01:44<02:14,  1.19s/it]
  iters:  44%|████▍     | 88/200 [01:45<02:13,  1.19s/it]
  iters:  44%|████▍     | 89/200 [01:46<02:12,  1.19s/it]
  iters:  45%|████▌     | 90/200 [01:47<02:11,  1.19s/it]
  iters:  46%|████▌     | 91/200 [01:48<02:10,  1.19s/it]
  iters:  46%|████▌     | 92/200 [01:50<02:08,  1.19s/it]
  iters:  46%|████▋     | 93/200 [01:51<02:07,  1.19s/it]
  iters:  47%|████▋     | 94/200 [01:52<02:07,  1.20s/it]
  iters:  48%|████▊     | 95/200 [01:53<02:05,  1.20s/it]
  iters:  48%|████▊     | 96/200 [01:54<02:04,  1.20s/it]
  iters:  48%|████▊     | 97/200 [01:56<02:03,  1.20s/it]
  iters:  49%|████▉     | 98/200 [01:57<02:02,  1.20s/it]
  iters:  50%|████▉     | 99/200 [01:58<02:01,  1.20s/it]
  iters:  50%|█████     | 100/200 [01:59<01:59,  1.20s/it]
  iters:  50%|█████     | 101/200 [02:00<01:58,  1.20s/it]
  iters:  51%|█████     | 102/200 [02:02<01:57,  1.20s/it]
  iters:  52%|█████▏    | 103/200 [02:03<01:56,  1.20s/it]
  iters:  52%|█████▏    | 104/200 [02:04<01:55,  1.20s/it]
  iters:  52%|█████▎    | 105/200 [02:05<01:53,  1.20s/it]
  iters:  53%|█████▎    | 106/200 [02:06<01:52,  1.19s/it]
  iters:  54%|█████▎    | 107/200 [02:08<01:51,  1.19s/it]
  iters:  54%|█████▍    | 108/200 [02:09<01:49,  1.20s/it]
  iters:  55%|█████▍    | 109/200 [02:10<01:48,  1.19s/it]
  iters:  55%|█████▌    | 110/200 [02:11<01:47,  1.19s/it]
  iters:  56%|█████▌    | 111/200 [02:12<01:46,  1.19s/it]
  iters:  56%|█████▌    | 112/200 [02:14<01:45,  1.19s/it]
  iters:  56%|█████▋    | 113/200 [02:15<01:43,  1.19s/it]
  iters:  57%|█████▋    | 114/200 [02:16<01:42,  1.20s/it]
  iters:  57%|█████▊    | 115/200 [02:17<01:42,  1.20s/it]
  iters:  58%|█████▊    | 116/200 [02:18<01:40,  1.20s/it]
  iters:  58%|█████▊    | 117/200 [02:20<01:39,  1.20s/it]
  iters:  59%|█████▉    | 118/200 [02:21<01:37,  1.19s/it]
  iters:  60%|█████▉    | 119/200 [02:22<01:36,  1.19s/it]
  iters:  60%|██████    | 120/200 [02:23<01:35,  1.19s/it]
  iters:  60%|██████    | 121/200 [02:24<01:34,  1.19s/it]
  iters:  61%|██████    | 122/200 [02:26<01:33,  1.19s/it]
  iters:  62%|██████▏   | 123/200 [02:27<01:31,  1.19s/it]
  iters:  62%|██████▏   | 124/200 [02:28<01:30,  1.20s/it]
  iters:  62%|██████▎   | 125/200 [02:29<01:29,  1.19s/it]
  iters:  63%|██████▎   | 126/200 [02:30<01:28,  1.20s/it]
  iters:  64%|██████▎   | 127/200 [02:32<01:27,  1.20s/it]
  iters:  64%|██████▍   | 128/200 [02:33<01:26,  1.20s/it]
  iters:  64%|██████▍   | 129/200 [02:34<01:24,  1.20s/it]
  iters:  65%|██████▌   | 130/200 [02:35<01:23,  1.20s/it]
  iters:  66%|██████▌   | 131/200 [02:36<01:22,  1.20s/it]
  iters:  66%|██████▌   | 132/200 [02:38<01:21,  1.20s/it]
  iters:  66%|██████▋   | 133/200 [02:39<01:20,  1.20s/it]
  iters:  67%|██████▋   | 134/200 [02:40<01:19,  1.20s/it]
  iters:  68%|██████▊   | 135/200 [02:41<01:17,  1.20s/it]
  iters:  68%|██████▊   | 136/200 [02:42<01:16,  1.19s/it]
  iters:  68%|██████▊   | 137/200 [02:43<01:15,  1.19s/it]
  iters:  69%|██████▉   | 138/200 [02:45<01:14,  1.20s/it]
  iters:  70%|██████▉   | 139/200 [02:46<01:13,  1.20s/it]
  iters:  70%|███████   | 140/200 [02:47<01:11,  1.20s/it]
  iters:  70%|███████   | 141/200 [02:48<01:10,  1.20s/it]
  iters:  71%|███████   | 142/200 [02:49<01:09,  1.20s/it]
  iters:  72%|███████▏  | 143/200 [02:51<01:07,  1.18s/it]
  iters:  72%|███████▏  | 144/200 [02:52<01:06,  1.19s/it]
  iters:  72%|███████▎  | 145/200 [02:53<01:05,  1.19s/it]
  iters:  73%|███████▎  | 146/200 [02:54<01:04,  1.19s/it]
  iters:  74%|███████▎  | 147/200 [02:55<01:03,  1.20s/it]
  iters:  74%|███████▍  | 148/200 [02:57<01:02,  1.20s/it]
  iters:  74%|███████▍  | 149/200 [02:58<01:01,  1.20s/it]
  iters:  75%|███████▌  | 150/200 [02:59<00:59,  1.20s/it]
  iters:  76%|███████▌  | 151/200 [03:00<00:58,  1.20s/it]
  iters:  76%|███████▌  | 152/200 [03:01<00:57,  1.20s/it]
  iters:  76%|███████▋  | 153/200 [03:03<00:56,  1.20s/it]
  iters:  77%|███████▋  | 154/200 [03:04<00:54,  1.20s/it]
  iters:  78%|███████▊  | 155/200 [03:05<00:53,  1.19s/it]
  iters:  78%|███████▊  | 156/200 [03:06<00:52,  1.20s/it]
  iters:  78%|███████▊  | 157/200 [03:07<00:51,  1.20s/it]
  iters:  79%|███████▉  | 158/200 [03:09<00:50,  1.20s/it]
  iters:  80%|███████▉  | 159/200 [03:10<00:49,  1.20s/it]
  iters:  80%|████████  | 160/200 [03:11<00:47,  1.20s/it]
  iters:  80%|████████  | 161/200 [03:12<00:46,  1.20s/it]
  iters:  81%|████████  | 162/200 [03:13<00:45,  1.20s/it]
  iters:  82%|████████▏ | 163/200 [03:15<00:44,  1.20s/it]
  iters:  82%|████████▏ | 164/200 [03:16<00:43,  1.20s/it]
  iters:  82%|████████▎ | 165/200 [03:17<00:41,  1.20s/it]
  iters:  83%|████████▎ | 166/200 [03:18<00:40,  1.20s/it]
  iters:  84%|████████▎ | 167/200 [03:19<00:39,  1.20s/it]
  iters:  84%|████████▍ | 168/200 [03:21<00:38,  1.20s/it]
  iters:  84%|████████▍ | 169/200 [03:22<00:37,  1.20s/it]
  iters:  85%|████████▌ | 170/200 [03:23<00:35,  1.20s/it]
  iters:  86%|████████▌ | 171/200 [03:24<00:34,  1.20s/it]
  iters:  86%|████████▌ | 172/200 [03:25<00:33,  1.20s/it]
  iters:  86%|████████▋ | 173/200 [03:27<00:32,  1.20s/it]
  iters:  87%|████████▋ | 174/200 [03:28<00:31,  1.20s/it]
  iters:  88%|████████▊ | 175/200 [03:29<00:29,  1.20s/it]
  iters:  88%|████████▊ | 176/200 [03:30<00:28,  1.20s/it]
  iters:  88%|████████▊ | 177/200 [03:31<00:27,  1.20s/it]
  iters:  89%|████████▉ | 178/200 [03:33<00:26,  1.20s/it]
  iters:  90%|████████▉ | 179/200 [03:34<00:25,  1.20s/it]
  iters:  90%|█████████ | 180/200 [03:35<00:23,  1.18s/it]
  iters:  90%|█████████ | 181/200 [03:36<00:22,  1.19s/it]
  iters:  91%|█████████ | 182/200 [03:37<00:21,  1.18s/it]
  iters:  92%|█████████▏| 183/200 [03:38<00:20,  1.18s/it]
  iters:  92%|█████████▏| 184/200 [03:40<00:19,  1.19s/it]
  iters:  92%|█████████▎| 185/200 [03:41<00:17,  1.19s/it]
  iters:  93%|█████████▎| 186/200 [03:42<00:16,  1.20s/it]
  iters:  94%|█████████▎| 187/200 [03:43<00:15,  1.20s/it]
  iters:  94%|█████████▍| 188/200 [03:44<00:14,  1.20s/it]
  iters:  94%|█████████▍| 189/200 [03:46<00:13,  1.20s/it]
  iters:  95%|█████████▌| 190/200 [03:47<00:12,  1.20s/it]
  iters:  96%|█████████▌| 191/200 [03:48<00:10,  1.20s/it]
  iters:  96%|█████████▌| 192/200 [03:49<00:09,  1.20s/it]
  iters:  96%|█████████▋| 193/200 [03:50<00:08,  1.20s/it]
  iters:  97%|█████████▋| 194/200 [03:52<00:07,  1.21s/it]
  iters:  98%|█████████▊| 195/200 [03:53<00:06,  1.21s/it]
  iters:  98%|█████████▊| 196/200 [03:54<00:04,  1.21s/it]
  iters:  98%|█████████▊| 197/200 [03:55<00:03,  1.21s/it]
  iters:  99%|█████████▉| 198/200 [03:56<00:02,  1.21s/it]
  iters: 100%|█████████▉| 199/200 [03:58<00:01,  1.21s/it]
  iters: 100%|██████████| 200/200 [03:59<00:00,  1.20s/it]

  [timing] data: 2.1s (1%) | forward: 59.1s (25%) | backward: 178.2s (74%) | total: 239.4s

Training:  25%|██▌       | 1/4 [08:38<12:47, 255.85s/it, acc=0.9996, det=0.0078, edge=0.0005]

  Epoch   1/4 | edge=0.0005 | det=0.0078 | test_loss=0.0005 | acc=0.9996 | recall=0.7887 | best=0.7883 * | train=239.6s test=23.3s

Training:  50%|█████     | 2/4 [08:38<08:40, 260.01s/it, acc=0.9996, det=0.0078, edge=0.0005]
  iters:   0%|          | 0/200 [00:00<?, ?it/s]
  iters:   0%|          | 1/200 [00:01<04:27,  1.35s/it]
  iters:   1%|          | 2/200 [00:02<04:09,  1.26s/it]
  iters:   2%|▏         | 3/200 [00:03<04:02,  1.23s/it]
  iters:   2%|▏         | 4/200 [00:04<03:58,  1.22s/it]
  iters:   2%|▎         | 5/200 [00:06<03:52,  1.19s/it]
  iters:   3%|▎         | 6/200 [00:07<03:48,  1.18s/it]
  iters:   4%|▎         | 7/200 [00:08<03:49,  1.19s/it]
  iters:   4%|▍         | 8/200 [00:09<03:48,  1.19s/it]
  iters:   4%|▍         | 9/200 [00:10<03:48,  1.19s/it]
  iters:   5%|▌         | 10/200 [00:12<03:47,  1.20s/it]
  iters:   6%|▌         | 11/200 [00:13<03:46,  1.20s/it]
  iters:   6%|▌         | 12/200 [00:14<03:42,  1.18s/it]
  iters:   6%|▋         | 13/200 [00:15<03:42,  1.19s/it]
  iters:   7%|▋         | 14/200 [00:16<03:41,  1.19s/it]
  iters:   8%|▊         | 15/200 [00:18<03:40,  1.19s/it]
  iters:   8%|▊         | 16/200 [00:19<03:39,  1.19s/it]
  iters:   8%|▊         | 17/200 [00:20<03:39,  1.20s/it]
  iters:   9%|▉         | 18/200 [00:21<03:37,  1.20s/it]
  iters:  10%|▉         | 19/200 [00:22<03:36,  1.20s/it]
  iters:  10%|█         | 20/200 [00:23<03:35,  1.20s/it]
  iters:  10%|█         | 21/200 [00:25<03:34,  1.20s/it]
  iters:  11%|█         | 22/200 [00:26<03:32,  1.20s/it]
  iters:  12%|█▏        | 23/200 [00:27<03:31,  1.20s/it]
  iters:  12%|█▏        | 24/200 [00:28<03:30,  1.20s/it]
  iters:  12%|█▎        | 25/200 [00:29<03:29,  1.20s/it]
  iters:  13%|█▎        | 26/200 [00:31<03:28,  1.20s/it]
  iters:  14%|█▎        | 27/200 [00:32<03:27,  1.20s/it]
  iters:  14%|█▍        | 28/200 [00:33<03:26,  1.20s/it]
  iters:  14%|█▍        | 29/200 [00:34<03:26,  1.20s/it]
  iters:  15%|█▌        | 30/200 [00:35<03:22,  1.19s/it]
  iters:  16%|█▌        | 31/200 [00:37<03:21,  1.19s/it]
  iters:  16%|█▌        | 32/200 [00:38<03:20,  1.19s/it]
  iters:  16%|█▋        | 33/200 [00:39<03:19,  1.20s/it]
  iters:  17%|█▋        | 34/200 [00:40<03:18,  1.20s/it]
  iters:  18%|█▊        | 35/200 [00:41<03:17,  1.20s/it]
  iters:  18%|█▊        | 36/200 [00:43<03:16,  1.20s/it]
  iters:  18%|█▊        | 37/200 [00:44<03:15,  1.20s/it]
  iters:  19%|█▉        | 38/200 [00:45<03:13,  1.20s/it]
  iters:  20%|█▉        | 39/200 [00:46<03:12,  1.20s/it]
  iters:  20%|██        | 40/200 [00:47<03:11,  1.19s/it]
  iters:  20%|██        | 41/200 [00:49<03:09,  1.19s/it]
  iters:  21%|██        | 42/200 [00:50<03:08,  1.20s/it]
  iters:  22%|██▏       | 43/200 [00:51<03:07,  1.20s/it]
  iters:  22%|██▏       | 44/200 [00:52<03:07,  1.20s/it]
  iters:  22%|██▎       | 45/200 [00:53<03:05,  1.20s/it]
  iters:  23%|██▎       | 46/200 [00:55<03:04,  1.20s/it]
  iters:  24%|██▎       | 47/200 [00:56<03:03,  1.20s/it]
  iters:  24%|██▍       | 48/200 [00:57<03:02,  1.20s/it]
  iters:  24%|██▍       | 49/200 [00:58<03:01,  1.20s/it]
  iters:  25%|██▌       | 50/200 [00:59<02:59,  1.20s/it]
  iters:  26%|██▌       | 51/200 [01:01<02:58,  1.20s/it]
  iters:  26%|██▌       | 52/200 [01:02<02:57,  1.20s/it]
  iters:  26%|██▋       | 53/200 [01:03<02:55,  1.20s/it]
  iters:  27%|██▋       | 54/200 [01:04<02:54,  1.19s/it]
  iters:  28%|██▊       | 55/200 [01:05<02:53,  1.19s/it]
  iters:  28%|██▊       | 56/200 [01:07<02:52,  1.20s/it]
  iters:  28%|██▊       | 57/200 [01:08<02:51,  1.20s/it]
  iters:  29%|██▉       | 58/200 [01:09<02:50,  1.20s/it]
  iters:  30%|██▉       | 59/200 [01:10<02:49,  1.20s/it]
  iters:  30%|███       | 60/200 [01:11<02:47,  1.20s/it]
  iters:  30%|███       | 61/200 [01:13<02:46,  1.20s/it]
  iters:  31%|███       | 62/200 [01:14<02:45,  1.20s/it]
  iters:  32%|███▏      | 63/200 [01:15<02:44,  1.20s/it]
  iters:  32%|███▏      | 64/200 [01:16<02:42,  1.20s/it]
  iters:  32%|███▎      | 65/200 [01:17<02:41,  1.20s/it]
  iters:  33%|███▎      | 66/200 [01:19<02:40,  1.20s/it]
  iters:  34%|███▎      | 67/200 [01:20<02:39,  1.20s/it]
  iters:  34%|███▍      | 68/200 [01:21<02:38,  1.20s/it]
  iters:  34%|███▍      | 69/200 [01:22<02:36,  1.20s/it]
  iters:  35%|███▌      | 70/200 [01:23<02:35,  1.19s/it]
  iters:  36%|███▌      | 71/200 [01:24<02:32,  1.18s/it]
  iters:  36%|███▌      | 72/200 [01:26<02:41,  1.26s/it]
  iters:  36%|███▋      | 73/200 [01:27<02:37,  1.24s/it]
  iters:  37%|███▋      | 74/200 [01:28<02:34,  1.23s/it]
  iters:  38%|███▊      | 75/200 [01:30<02:32,  1.22s/it]
  iters:  38%|███▊      | 76/200 [01:31<02:30,  1.21s/it]
  iters:  38%|███▊      | 77/200 [01:32<02:28,  1.21s/it]
  iters:  39%|███▉      | 78/200 [01:33<02:26,  1.20s/it]
  iters:  40%|███▉      | 79/200 [01:34<02:25,  1.20s/it]
  iters:  40%|████      | 80/200 [01:36<02:24,  1.20s/it]
  iters:  40%|████      | 81/200 [01:37<02:22,  1.20s/it]
  iters:  41%|████      | 82/200 [01:38<02:21,  1.20s/it]
  iters:  42%|████▏     | 83/200 [01:39<02:20,  1.20s/it]
  iters:  42%|████▏     | 84/200 [01:40<02:18,  1.20s/it]
  iters:  42%|████▎     | 85/200 [01:41<02:17,  1.20s/it]
  iters:  43%|████▎     | 86/200 [01:43<02:16,  1.20s/it]
  iters:  44%|████▎     | 87/200 [01:44<02:14,  1.19s/it]
  iters:  44%|████▍     | 88/200 [01:45<02:12,  1.18s/it]
  iters:  44%|████▍     | 89/200 [01:46<02:11,  1.18s/it]
  iters:  45%|████▌     | 90/200 [01:47<02:10,  1.19s/it]
  iters:  46%|████▌     | 91/200 [01:49<02:09,  1.19s/it]
  iters:  46%|████▌     | 92/200 [01:50<02:08,  1.19s/it]
  iters:  46%|████▋     | 93/200 [01:51<02:07,  1.19s/it]
  iters:  47%|████▋     | 94/200 [01:52<02:06,  1.19s/it]
  iters:  48%|████▊     | 95/200 [01:53<02:05,  1.19s/it]
  iters:  48%|████▊     | 96/200 [01:55<02:04,  1.19s/it]
  iters:  48%|████▊     | 97/200 [01:56<02:03,  1.20s/it]
  iters:  49%|████▉     | 98/200 [01:57<02:01,  1.19s/it]
  iters:  50%|████▉     | 99/200 [01:58<02:00,  1.20s/it]
  iters:  50%|█████     | 100/200 [01:59<01:58,  1.18s/it]
  iters:  50%|█████     | 101/200 [02:00<01:57,  1.18s/it]
  iters:  51%|█████     | 102/200 [02:02<01:56,  1.19s/it]
  iters:  52%|█████▏    | 103/200 [02:03<01:55,  1.19s/it]
  iters:  52%|█████▏    | 104/200 [02:04<01:54,  1.19s/it]
  iters:  52%|█████▎    | 105/200 [02:05<01:53,  1.19s/it]
  iters:  53%|█████▎    | 106/200 [02:06<01:52,  1.19s/it]
  iters:  54%|█████▎    | 107/200 [02:08<01:51,  1.20s/it]
  iters:  54%|█████▍    | 108/200 [02:09<01:49,  1.20s/it]
  iters:  55%|█████▍    | 109/200 [02:10<01:48,  1.19s/it]
  iters:  55%|█████▌    | 110/200 [02:11<01:47,  1.19s/it]
  iters:  56%|█████▌    | 111/200 [02:12<01:46,  1.19s/it]
  iters:  56%|█████▌    | 112/200 [02:14<01:45,  1.19s/it]
  iters:  56%|█████▋    | 113/200 [02:15<01:43,  1.19s/it]
  iters:  57%|█████▋    | 114/200 [02:16<01:42,  1.20s/it]
  iters:  57%|█████▊    | 115/200 [02:17<01:41,  1.20s/it]
  iters:  58%|█████▊    | 116/200 [02:18<01:40,  1.20s/it]
  iters:  58%|█████▊    | 117/200 [02:20<01:39,  1.19s/it]
  iters:  59%|█████▉    | 118/200 [02:21<01:37,  1.19s/it]
  iters:  60%|█████▉    | 119/200 [02:22<01:36,  1.19s/it]
  iters:  60%|██████    | 120/200 [02:23<01:35,  1.19s/it]
  iters:  60%|██████    | 121/200 [02:24<01:34,  1.20s/it]
  iters:  61%|██████    | 122/200 [02:26<01:33,  1.20s/it]
  iters:  62%|██████▏   | 123/200 [02:27<01:32,  1.20s/it]
  iters:  62%|██████▏   | 124/200 [02:28<01:31,  1.20s/it]
  iters:  62%|██████▎   | 125/200 [02:29<01:29,  1.20s/it]
  iters:  63%|██████▎   | 126/200 [02:30<01:28,  1.20s/it]
  iters:  64%|██████▎   | 127/200 [02:32<01:27,  1.20s/it]
  iters:  64%|██████▍   | 128/200 [02:33<01:25,  1.18s/it]
  iters:  64%|██████▍   | 129/200 [02:34<01:23,  1.17s/it]
  iters:  65%|██████▌   | 130/200 [02:35<01:22,  1.18s/it]
  iters:  66%|██████▌   | 131/200 [02:36<01:21,  1.19s/it]
  iters:  66%|██████▌   | 132/200 [02:37<01:20,  1.19s/it]
  iters:  66%|██████▋   | 133/200 [02:39<01:19,  1.19s/it]
  iters:  67%|██████▋   | 134/200 [02:40<01:18,  1.19s/it]
  iters:  68%|██████▊   | 135/200 [02:41<01:17,  1.19s/it]
  iters:  68%|██████▊   | 136/200 [02:42<01:16,  1.19s/it]
  iters:  68%|██████▊   | 137/200 [02:43<01:15,  1.19s/it]
  iters:  69%|██████▉   | 138/200 [02:45<01:14,  1.19s/it]
  iters:  70%|██████▉   | 139/200 [02:46<01:12,  1.20s/it]
  iters:  70%|███████   | 140/200 [02:47<01:10,  1.18s/it]
  iters:  70%|███████   | 141/200 [02:48<01:10,  1.19s/it]
  iters:  71%|███████   | 142/200 [02:49<01:08,  1.19s/it]
  iters:  72%|███████▏  | 143/200 [02:51<01:07,  1.19s/it]
  iters:  72%|███████▏  | 144/200 [02:52<01:06,  1.19s/it]
  iters:  72%|███████▎  | 145/200 [02:53<01:05,  1.19s/it]
  iters:  73%|███████▎  | 146/200 [02:54<01:04,  1.19s/it]
  iters:  74%|███████▎  | 147/200 [02:55<01:03,  1.19s/it]
  iters:  74%|███████▍  | 148/200 [02:57<01:02,  1.20s/it]
  iters:  74%|███████▍  | 149/200 [02:58<01:00,  1.19s/it]
  iters:  75%|███████▌  | 150/200 [02:59<00:59,  1.19s/it]
  iters:  76%|███████▌  | 151/200 [03:00<00:58,  1.20s/it]
  iters:  76%|███████▌  | 152/200 [03:01<00:57,  1.20s/it]
  iters:  76%|███████▋  | 153/200 [03:03<00:56,  1.20s/it]
  iters:  77%|███████▋  | 154/200 [03:04<00:55,  1.20s/it]
  iters:  78%|███████▊  | 155/200 [03:05<00:54,  1.20s/it]
  iters:  78%|███████▊  | 156/200 [03:06<00:52,  1.20s/it]
  iters:  78%|███████▊  | 157/200 [03:07<00:51,  1.20s/it]
  iters:  79%|███████▉  | 158/200 [03:09<00:50,  1.20s/it]
  iters:  80%|███████▉  | 159/200 [03:10<00:49,  1.20s/it]
  iters:  80%|████████  | 160/200 [03:11<00:47,  1.20s/it]
  iters:  80%|████████  | 161/200 [03:12<00:46,  1.20s/it]
  iters:  81%|████████  | 162/200 [03:13<00:45,  1.20s/it]
  iters:  82%|████████▏ | 163/200 [03:15<00:44,  1.20s/it]
  iters:  82%|████████▏ | 164/200 [03:16<00:42,  1.19s/it]
  iters:  82%|████████▎ | 165/200 [03:17<00:41,  1.19s/it]
  iters:  83%|████████▎ | 166/200 [03:18<00:40,  1.19s/it]
  iters:  84%|████████▎ | 167/200 [03:19<00:39,  1.19s/it]
  iters:  84%|████████▍ | 168/200 [03:20<00:38,  1.20s/it]
  iters:  84%|████████▍ | 169/200 [03:22<00:36,  1.18s/it]
  iters:  85%|████████▌ | 170/200 [03:23<00:35,  1.19s/it]
  iters:  86%|████████▌ | 171/200 [03:24<00:34,  1.19s/it]
  iters:  86%|████████▌ | 172/200 [03:25<00:33,  1.20s/it]
  iters:  86%|████████▋ | 173/200 [03:26<00:32,  1.20s/it]
  iters:  87%|████████▋ | 174/200 [03:28<00:31,  1.20s/it]
  iters:  88%|████████▊ | 175/200 [03:29<00:29,  1.20s/it]
  iters:  88%|████████▊ | 176/200 [03:30<00:28,  1.20s/it]
  iters:  88%|████████▊ | 177/200 [03:31<00:27,  1.20s/it]
  iters:  89%|████████▉ | 178/200 [03:32<00:26,  1.20s/it]
  iters:  90%|████████▉ | 179/200 [03:34<00:25,  1.20s/it]
  iters:  90%|█████████ | 180/200 [03:35<00:24,  1.20s/it]
  iters:  90%|█████████ | 181/200 [03:36<00:22,  1.20s/it]
  iters:  91%|█████████ | 182/200 [03:37<00:21,  1.20s/it]
  iters:  92%|█████████▏| 183/200 [03:38<00:20,  1.21s/it]
  iters:  92%|█████████▏| 184/200 [03:40<00:19,  1.20s/it]
  iters:  92%|█████████▎| 185/200 [03:41<00:18,  1.20s/it]
  iters:  93%|█████████▎| 186/200 [03:42<00:16,  1.20s/it]
  iters:  94%|█████████▎| 187/200 [03:43<00:15,  1.20s/it]
  iters:  94%|█████████▍| 188/200 [03:44<00:14,  1.20s/it]
  iters:  94%|█████████▍| 189/200 [03:46<00:13,  1.19s/it]
  iters:  95%|█████████▌| 190/200 [03:47<00:11,  1.19s/it]
  iters:  96%|█████████▌| 191/200 [03:48<00:10,  1.19s/it]
  iters:  96%|█████████▌| 192/200 [03:49<00:09,  1.20s/it]
  iters:  96%|█████████▋| 193/200 [03:50<00:08,  1.20s/it]
  iters:  97%|█████████▋| 194/200 [03:52<00:07,  1.20s/it]
  iters:  98%|█████████▊| 195/200 [03:53<00:05,  1.20s/it]
  iters:  98%|█████████▊| 196/200 [03:54<00:04,  1.20s/it]
  iters:  98%|█████████▊| 197/200 [03:55<00:03,  1.20s/it]
  iters:  99%|█████████▉| 198/200 [03:56<00:02,  1.20s/it]
  iters: 100%|█████████▉| 199/200 [03:58<00:01,  1.20s/it]
  iters: 100%|██████████| 200/200 [03:59<00:00,  1.20s/it]

  [timing] data: 2.1s (1%) | forward: 59.2s (25%) | backward: 178.0s (74%) | total: 239.3s

Training:  50%|█████     | 2/4 [13:01<08:40, 260.01s/it, acc=0.9996, det=0.0082, edge=0.0005]

  Epoch   2/4 | edge=0.0005 | det=0.0082 | test_loss=0.0005 | acc=0.9996 | recall=0.7986 | best=0.7982 * | train=239.5s test=23.2s

Training:  75%|███████▌  | 3/4 [13:01<04:21, 261.26s/it, acc=0.9996, det=0.0082, edge=0.0005]
  iters:   0%|          | 0/200 [00:00<?, ?it/s]
  iters:   0%|          | 1/200 [00:01<04:29,  1.35s/it]
  iters:   1%|          | 2/200 [00:02<04:09,  1.26s/it]
  iters:   2%|▏         | 3/200 [00:03<04:03,  1.24s/it]
  iters:   2%|▏         | 4/200 [00:04<03:58,  1.22s/it]
  iters:   2%|▎         | 5/200 [00:06<03:55,  1.21s/it]
  iters:   3%|▎         | 6/200 [00:07<03:53,  1.20s/it]
  iters:   4%|▎         | 7/200 [00:08<03:52,  1.20s/it]
  iters:   4%|▍         | 8/200 [00:09<03:50,  1.20s/it]
  iters:   4%|▍         | 9/200 [00:10<03:49,  1.20s/it]
  iters:   5%|▌         | 10/200 [00:12<03:48,  1.20s/it]
  iters:   6%|▌         | 11/200 [00:13<03:46,  1.20s/it]
  iters:   6%|▌         | 12/200 [00:14<03:45,  1.20s/it]
  iters:   6%|▋         | 13/200 [00:15<03:44,  1.20s/it]
  iters:   7%|▋         | 14/200 [00:16<03:42,  1.20s/it]
  iters:   8%|▊         | 15/200 [00:18<03:41,  1.20s/it]
  iters:   8%|▊         | 16/200 [00:19<03:40,  1.20s/it]
  iters:   8%|▊         | 17/200 [00:20<03:39,  1.20s/it]
  iters:   9%|▉         | 18/200 [00:21<03:35,  1.18s/it]
  iters:  10%|▉         | 19/200 [00:22<03:35,  1.19s/it]
  iters:  10%|█         | 20/200 [00:24<03:34,  1.19s/it]
  iters:  10%|█         | 21/200 [00:25<03:34,  1.20s/it]
  iters:  11%|█         | 22/200 [00:26<03:33,  1.20s/it]
  iters:  12%|█▏        | 23/200 [00:27<03:32,  1.20s/it]
  iters:  12%|█▏        | 24/200 [00:28<03:31,  1.20s/it]
  iters:  12%|█▎        | 25/200 [00:30<03:29,  1.20s/it]
  iters:  13%|█▎        | 26/200 [00:31<03:28,  1.20s/it]
  iters:  14%|█▎        | 27/200 [00:32<03:27,  1.20s/it]
  iters:  14%|█▍        | 28/200 [00:33<03:26,  1.20s/it]
  iters:  14%|█▍        | 29/200 [00:34<03:24,  1.20s/it]
  iters:  15%|█▌        | 30/200 [00:36<03:24,  1.20s/it]
  iters:  16%|█▌        | 31/200 [00:37<03:23,  1.20s/it]
  iters:  16%|█▌        | 32/200 [00:38<03:19,  1.19s/it]
  iters:  16%|█▋        | 33/200 [00:39<03:19,  1.19s/it]
  iters:  17%|█▋        | 34/200 [00:40<03:18,  1.20s/it]
  iters:  18%|█▊        | 35/200 [00:42<03:17,  1.20s/it]
  iters:  18%|█▊        | 36/200 [00:43<03:16,  1.20s/it]
  iters:  18%|█▊        | 37/200 [00:44<03:15,  1.20s/it]
  iters:  19%|█▉        | 38/200 [00:45<03:14,  1.20s/it]
  iters:  20%|█▉        | 39/200 [00:46<03:13,  1.20s/it]
  iters:  20%|██        | 40/200 [00:48<03:12,  1.20s/it]
  iters:  20%|██        | 41/200 [00:49<03:08,  1.19s/it]
  iters:  21%|██        | 42/200 [00:50<03:08,  1.19s/it]
  iters:  22%|██▏       | 43/200 [00:51<03:07,  1.20s/it]
  iters:  22%|██▏       | 44/200 [00:52<03:06,  1.20s/it]
  iters:  22%|██▎       | 45/200 [00:54<03:05,  1.20s/it]
  iters:  23%|██▎       | 46/200 [00:55<03:04,  1.20s/it]
  iters:  24%|██▎       | 47/200 [00:56<03:01,  1.19s/it]
  iters:  24%|██▍       | 48/200 [00:57<03:01,  1.19s/it]
  iters:  24%|██▍       | 49/200 [00:58<03:00,  1.19s/it]
  iters:  25%|██▌       | 50/200 [00:59<02:59,  1.19s/it]
  iters:  26%|██▌       | 51/200 [01:01<02:58,  1.20s/it]
  iters:  26%|██▌       | 52/200 [01:02<02:56,  1.20s/it]
  iters:  26%|██▋       | 53/200 [01:03<02:55,  1.20s/it]
  iters:  27%|██▋       | 54/200 [01:04<02:54,  1.20s/it]
  iters:  28%|██▊       | 55/200 [01:05<02:53,  1.20s/it]
  iters:  28%|██▊       | 56/200 [01:07<02:52,  1.20s/it]
  iters:  28%|██▊       | 57/200 [01:08<02:51,  1.20s/it]
  iters:  29%|██▉       | 58/200 [01:09<02:49,  1.20s/it]
  iters:  30%|██▉       | 59/200 [01:10<02:48,  1.19s/it]
  iters:  30%|███       | 60/200 [01:11<02:46,  1.19s/it]
  iters:  30%|███       | 61/200 [01:13<02:45,  1.19s/it]
  iters:  31%|███       | 62/200 [01:14<02:44,  1.19s/it]
  iters:  32%|███▏      | 63/200 [01:15<02:43,  1.19s/it]
  iters:  32%|███▏      | 64/200 [01:16<02:42,  1.19s/it]
  iters:  32%|███▎      | 65/200 [01:17<02:40,  1.19s/it]
  iters:  33%|███▎      | 66/200 [01:19<02:39,  1.19s/it]
  iters:  34%|███▎      | 67/200 [01:20<02:38,  1.19s/it]
  iters:  34%|███▍      | 68/200 [01:21<02:37,  1.19s/it]
  iters:  34%|███▍      | 69/200 [01:22<02:35,  1.19s/it]
  iters:  35%|███▌      | 70/200 [01:23<02:34,  1.19s/it]
  iters:  36%|███▌      | 71/200 [01:25<02:33,  1.19s/it]
  iters:  36%|███▌      | 72/200 [01:26<02:32,  1.19s/it]
  iters:  36%|███▋      | 73/200 [01:27<02:31,  1.19s/it]
  iters:  37%|███▋      | 74/200 [01:28<02:30,  1.19s/it]
  iters:  38%|███▊      | 75/200 [01:29<02:28,  1.19s/it]
  iters:  38%|███▊      | 76/200 [01:30<02:27,  1.19s/it]
  iters:  38%|███▊      | 77/200 [01:32<02:26,  1.19s/it]
  iters:  39%|███▉      | 78/200 [01:33<02:25,  1.19s/it]
  iters:  40%|███▉      | 79/200 [01:34<02:22,  1.18s/it]
  iters:  40%|████      | 80/200 [01:35<02:21,  1.18s/it]
  iters:  40%|████      | 81/200 [01:36<02:20,  1.18s/it]
  iters:  41%|████      | 82/200 [01:38<02:20,  1.19s/it]
  iters:  42%|████▏     | 83/200 [01:39<02:19,  1.19s/it]
  iters:  42%|████▏     | 84/200 [01:40<02:18,  1.19s/it]
  iters:  42%|████▎     | 85/200 [01:41<02:17,  1.19s/it]
  iters:  43%|████▎     | 86/200 [01:42<02:16,  1.19s/it]
  iters:  44%|████▎     | 87/200 [01:44<02:14,  1.19s/it]
  iters:  44%|████▍     | 88/200 [01:45<02:13,  1.19s/it]
  iters:  44%|████▍     | 89/200 [01:46<02:12,  1.19s/it]
  iters:  45%|████▌     | 90/200 [01:47<02:11,  1.19s/it]
  iters:  46%|████▌     | 91/200 [01:48<02:10,  1.20s/it]
  iters:  46%|████▌     | 92/200 [01:50<02:09,  1.20s/it]
  iters:  46%|████▋     | 93/200 [01:51<02:08,  1.20s/it]
  iters:  47%|████▋     | 94/200 [01:52<02:07,  1.20s/it]
  iters:  48%|████▊     | 95/200 [01:53<02:05,  1.20s/it]
  iters:  48%|████▊     | 96/200 [01:54<02:04,  1.20s/it]
  iters:  48%|████▊     | 97/200 [01:56<02:03,  1.20s/it]
  iters:  49%|████▉     | 98/200 [01:57<02:02,  1.20s/it]
  iters:  50%|████▉     | 99/200 [01:58<02:00,  1.20s/it]
  iters:  50%|█████     | 100/200 [01:59<01:59,  1.20s/it]
  iters:  50%|█████     | 101/200 [02:00<01:58,  1.20s/it]
  iters:  51%|█████     | 102/200 [02:02<01:58,  1.20s/it]
  iters:  52%|█████▏    | 103/200 [02:03<01:55,  1.19s/it]
  iters:  52%|█████▏    | 104/200 [02:04<01:54,  1.19s/it]
  iters:  52%|█████▎    | 105/200 [02:05<01:53,  1.19s/it]
  iters:  53%|█████▎    | 106/200 [02:06<01:52,  1.19s/it]
  iters:  54%|█████▎    | 107/200 [02:07<01:51,  1.19s/it]
  iters:  54%|█████▍    | 108/200 [02:09<01:50,  1.20s/it]
  iters:  55%|█████▍    | 109/200 [02:10<01:48,  1.20s/it]
  iters:  55%|█████▌    | 110/200 [02:11<01:47,  1.20s/it]
  iters:  56%|█████▌    | 111/200 [02:12<01:46,  1.20s/it]
  iters:  56%|█████▌    | 112/200 [02:13<01:45,  1.20s/it]
  iters:  56%|█████▋    | 113/200 [02:15<01:43,  1.20s/it]
  iters:  57%|█████▋    | 114/200 [02:16<01:42,  1.19s/it]
  iters:  57%|█████▊    | 115/200 [02:17<01:41,  1.19s/it]
  iters:  58%|█████▊    | 116/200 [02:18<01:40,  1.20s/it]
  iters:  58%|█████▊    | 117/200 [02:19<01:39,  1.20s/it]
  iters:  59%|█████▉    | 118/200 [02:21<01:38,  1.20s/it]
  iters:  60%|█████▉    | 119/200 [02:22<01:37,  1.20s/it]
  iters:  60%|██████    | 120/200 [02:23<01:41,  1.27s/it]
  iters:  60%|██████    | 121/200 [02:24<01:38,  1.25s/it]
  iters:  61%|██████    | 122/200 [02:26<01:36,  1.24s/it]
  iters:  62%|██████▏   | 123/200 [02:27<01:34,  1.22s/it]
  iters:  62%|██████▏   | 124/200 [02:28<01:32,  1.22s/it]
  iters:  62%|██████▎   | 125/200 [02:29<01:30,  1.21s/it]
  iters:  63%|██████▎   | 126/200 [02:30<01:29,  1.21s/it]
  iters:  64%|██████▎   | 127/200 [02:32<01:27,  1.20s/it]
  iters:  64%|██████▍   | 128/200 [02:33<01:26,  1.20s/it]
  iters:  64%|██████▍   | 129/200 [02:34<01:25,  1.20s/it]
  iters:  65%|██████▌   | 130/200 [02:35<01:24,  1.20s/it]
  iters:  66%|██████▌   | 131/200 [02:36<01:22,  1.20s/it]
  iters:  66%|██████▌   | 132/200 [02:38<01:21,  1.20s/it]
  iters:  66%|██████▋   | 133/200 [02:39<01:20,  1.20s/it]
  iters:  67%|██████▋   | 134/200 [02:40<01:18,  1.20s/it]
  iters:  68%|██████▊   | 135/200 [02:41<01:17,  1.20s/it]
  iters:  68%|██████▊   | 136/200 [02:42<01:16,  1.20s/it]
  iters:  68%|██████▊   | 137/200 [02:44<01:15,  1.19s/it]
  iters:  69%|██████▉   | 138/200 [02:45<01:14,  1.20s/it]
  iters:  70%|██████▉   | 139/200 [02:46<01:12,  1.19s/it]
  iters:  70%|███████   | 140/200 [02:47<01:11,  1.20s/it]
  iters:  70%|███████   | 141/200 [02:48<01:10,  1.20s/it]
  iters:  71%|███████   | 142/200 [02:50<01:09,  1.20s/it]
  iters:  72%|███████▏  | 143/200 [02:51<01:08,  1.19s/it]
  iters:  72%|███████▏  | 144/200 [02:52<01:06,  1.19s/it]
  iters:  72%|███████▎  | 145/200 [02:53<01:05,  1.19s/it]
  iters:  73%|███████▎  | 146/200 [02:54<01:04,  1.19s/it]
  iters:  74%|███████▎  | 147/200 [02:56<01:03,  1.19s/it]
  iters:  74%|███████▍  | 148/200 [02:57<01:01,  1.19s/it]
  iters:  74%|███████▍  | 149/200 [02:58<01:00,  1.19s/it]
  iters:  75%|███████▌  | 150/200 [02:59<00:58,  1.18s/it]
  iters:  76%|███████▌  | 151/200 [03:00<00:57,  1.18s/it]
  iters:  76%|███████▌  | 152/200 [03:02<00:57,  1.19s/it]
  iters:  76%|███████▋  | 153/200 [03:03<00:55,  1.19s/it]
  iters:  77%|███████▋  | 154/200 [03:04<00:54,  1.19s/it]
  iters:  78%|███████▊  | 155/200 [03:05<00:53,  1.19s/it]
  iters:  78%|███████▊  | 156/200 [03:06<00:52,  1.19s/it]
  iters:  78%|███████▊  | 157/200 [03:07<00:51,  1.19s/it]
  iters:  79%|███████▉  | 158/200 [03:09<00:49,  1.17s/it]
  iters:  80%|███████▉  | 159/200 [03:10<00:47,  1.17s/it]
  iters:  80%|████████  | 160/200 [03:11<00:47,  1.18s/it]
  iters:  80%|████████  | 161/200 [03:12<00:45,  1.17s/it]
  iters:  81%|████████  | 162/200 [03:13<00:44,  1.17s/it]
  iters:  82%|████████▏ | 163/200 [03:14<00:43,  1.18s/it]
  iters:  82%|████████▏ | 164/200 [03:16<00:42,  1.18s/it]
  iters:  82%|████████▎ | 165/200 [03:17<00:41,  1.19s/it]
  iters:  83%|████████▎ | 166/200 [03:18<00:40,  1.19s/it]
  iters:  84%|████████▎ | 167/200 [03:19<00:38,  1.18s/it]
  iters:  84%|████████▍ | 168/200 [03:20<00:37,  1.18s/it]
  iters:  84%|████████▍ | 169/200 [03:22<00:36,  1.19s/it]
  iters:  85%|████████▌ | 170/200 [03:23<00:35,  1.18s/it]
  iters:  86%|████████▌ | 171/200 [03:24<00:34,  1.18s/it]
  iters:  86%|████████▌ | 172/200 [03:25<00:33,  1.19s/it]
  iters:  86%|████████▋ | 173/200 [03:26<00:32,  1.19s/it]
  iters:  87%|████████▋ | 174/200 [03:28<00:31,  1.19s/it]
  iters:  88%|████████▊ | 175/200 [03:29<00:29,  1.19s/it]
  iters:  88%|████████▊ | 176/200 [03:30<00:28,  1.20s/it]
  iters:  88%|████████▊ | 177/200 [03:31<00:27,  1.20s/it]
  iters:  89%|████████▉ | 178/200 [03:32<00:26,  1.20s/it]
  iters:  90%|████████▉ | 179/200 [03:34<00:25,  1.20s/it]
  iters:  90%|█████████ | 180/200 [03:35<00:23,  1.20s/it]
  iters:  90%|█████████ | 181/200 [03:36<00:22,  1.20s/it]
  iters:  91%|█████████ | 182/200 [03:37<00:21,  1.20s/it]
  iters:  92%|█████████▏| 183/200 [03:38<00:20,  1.20s/it]
  iters:  92%|█████████▏| 184/200 [03:40<00:19,  1.20s/it]
  iters:  92%|█████████▎| 185/200 [03:41<00:17,  1.20s/it]
  iters:  93%|█████████▎| 186/200 [03:42<00:16,  1.20s/it]
  iters:  94%|█████████▎| 187/200 [03:43<00:15,  1.20s/it]
  iters:  94%|█████████▍| 188/200 [03:44<00:14,  1.20s/it]
  iters:  94%|█████████▍| 189/200 [03:46<00:13,  1.20s/it]
  iters:  95%|█████████▌| 190/200 [03:47<00:11,  1.20s/it]
  iters:  96%|█████████▌| 191/200 [03:48<00:10,  1.20s/it]
  iters:  96%|█████████▌| 192/200 [03:49<00:09,  1.20s/it]
  iters:  96%|█████████▋| 193/200 [03:50<00:08,  1.20s/it]
  iters:  97%|█████████▋| 194/200 [03:52<00:07,  1.21s/it]
  iters:  98%|█████████▊| 195/200 [03:53<00:06,  1.21s/it]
  iters:  98%|█████████▊| 196/200 [03:54<00:04,  1.20s/it]
  iters:  98%|█████████▊| 197/200 [03:55<00:03,  1.19s/it]
  iters:  99%|█████████▉| 198/200 [03:56<00:02,  1.19s/it]
  iters: 100%|█████████▉| 199/200 [03:58<00:01,  1.20s/it]
  iters: 100%|██████████| 200/200 [03:59<00:00,  1.20s/it]

  [timing] data: 2.1s (1%) | forward: 59.1s (25%) | backward: 178.0s (74%) | total: 239.2s

Training:  75%|███████▌  | 3/4 [17:24<04:21, 261.26s/it, acc=0.9994, det=0.0064, edge=0.0003]

  Epoch   3/4 | edge=0.0003 | det=0.0064 | test_loss=0.0005 | acc=0.9994 | recall=0.8071 | best=0.8066 * | train=239.4s test=23.2s

Training: 100%|██████████| 4/4 [17:24<00:00, 261.03s/it, acc=0.9994, det=0.0064, edge=0.0003]

Best score (acc*recall): 0.8066, saved to /kaggle/working/cellmot-baseline-artifacts/repo/weights/hp_search_tier1/split_0/edge_predictor_best.pth

[tier2_000] score=0.8066  (1056s)
0.019136512 GB allocated
0.14680064 GB reserved
Fold 0: 8 train, 2 test
Loading train (8 datasets)...

train: 100%|██████████| 8/8 [00:04<00:00,  1.61it/s]

  train done: 779 windows total
Loading test (2 datasets)...

test: 100%|██████████| 2/2 [00:00<00:00,  2.18it/s]

  test done: 161 windows total
max_nodes=17
Using device: cuda | visible CUDA GPUs: 2
  Full checkpoint loaded from /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/weights/unet_transformer/split_0/edge_predictor_best.pth: 0 missing, 0 unexpected
Single-GPU training (--single-gpu set). For 2 GPUs set the Kaggle accelerator to 'GPU T4 x2'.
Model parameters: 2,076,706
Starting training for 4 epochs (batch_size=2)...

Training:   0%|          | 0/4 [00:00<?, ?it/s]

Detection loss: weight=4, neg_weight=0.01

  iters:   0%|          | 0/200 [00:00<?, ?it/s]
  iters:   0%|          | 1/200 [00:02<07:13,  2.18s/it]
  iters:   1%|          | 2/200 [00:03<06:20,  1.92s/it]
  iters:   2%|▏         | 3/200 [00:05<06:07,  1.87s/it]
  iters:   2%|▏         | 4/200 [00:07<05:56,  1.82s/it]
  iters:   2%|▎         | 5/200 [00:09<05:50,  1.80s/it]
  iters:   3%|▎         | 6/200 [00:11<05:49,  1.80s/it]
  iters:   4%|▎         | 7/200 [00:12<05:51,  1.82s/it]
  iters:   4%|▍         | 8/200 [00:14<05:49,  1.82s/it]
  iters:   4%|▍         | 9/200 [00:16<05:44,  1.81s/it]
  iters:   5%|▌         | 10/200 [00:18<05:41,  1.80s/it]
  iters:   6%|▌         | 11/200 [00:20<05:40,  1.80s/it]
  iters:   6%|▌         | 12/200 [00:21<05:37,  1.79s/it]
  iters:   6%|▋         | 13/200 [00:23<05:39,  1.81s/it]
  iters:   7%|▋         | 14/200 [00:25<05:36,  1.81s/it]
  iters:   8%|▊         | 15/200 [00:27<05:34,  1.81s/it]
  iters:   8%|▊         | 16/200 [00:29<05:31,  1.80s/it]
  iters:   8%|▊         | 17/200 [00:30<05:30,  1.80s/it]
  iters:   9%|▉         | 18/200 [00:32<05:27,  1.80s/it]
  iters:  10%|▉         | 19/200 [00:34<05:37,  1.86s/it]
  iters:  10%|█         | 20/200 [00:36<05:31,  1.84s/it]
  iters:  10%|█         | 21/200 [00:38<05:26,  1.83s/it]
  iters:  11%|█         | 22/200 [00:40<05:33,  1.88s/it]
  iters:  12%|█▏        | 23/200 [00:42<05:26,  1.85s/it]
  iters:  12%|█▏        | 24/200 [00:43<05:20,  1.82s/it]
  iters:  12%|█▎        | 25/200 [00:45<05:15,  1.80s/it]
  iters:  13%|█▎        | 26/200 [00:47<05:12,  1.80s/it]
  iters:  14%|█▎        | 27/200 [00:49<05:08,  1.79s/it]
  iters:  14%|█▍        | 28/200 [00:50<05:10,  1.80s/it]
  iters:  14%|█▍        | 29/200 [00:52<05:05,  1.78s/it]
  iters:  15%|█▌        | 30/200 [00:54<05:01,  1.77s/it]
  iters:  16%|█▌        | 31/200 [00:56<04:58,  1.76s/it]
  iters:  16%|█▌        | 32/200 [00:57<04:54,  1.75s/it]
  iters:  16%|█▋        | 33/200 [00:59<04:52,  1.75s/it]
  iters:  17%|█▋        | 34/200 [01:01<04:49,  1.75s/it]
  iters:  18%|█▊        | 35/200 [01:03<04:49,  1.75s/it]
  iters:  18%|█▊        | 36/200 [01:04<04:47,  1.75s/it]
  iters:  18%|█▊        | 37/200 [01:06<04:43,  1.74s/it]
  iters:  19%|█▉        | 38/200 [01:08<04:41,  1.74s/it]
  iters:  20%|█▉        | 39/200 [01:10<04:39,  1.73s/it]
  iters:  20%|██        | 40/200 [01:11<04:36,  1.73s/it]
  iters:  20%|██        | 41/200 [01:13<04:34,  1.73s/it]
  iters:  21%|██        | 42/200 [01:15<04:45,  1.81s/it]
  iters:  22%|██▏       | 43/200 [01:17<04:39,  1.78s/it]
  iters:  22%|██▏       | 44/200 [01:19<04:36,  1.78s/it]
  iters:  22%|██▎       | 45/200 [01:20<04:33,  1.77s/it]
  iters:  23%|██▎       | 46/200 [01:22<04:49,  1.88s/it]
  iters:  24%|██▎       | 47/200 [01:24<04:40,  1.83s/it]
  iters:  24%|██▍       | 48/200 [01:26<04:33,  1.80s/it]
  iters:  24%|██▍       | 49/200 [01:28<04:29,  1.78s/it]
  iters:  25%|██▌       | 50/200 [01:29<04:25,  1.77s/it]
  iters:  26%|██▌       | 51/200 [01:31<04:22,  1.76s/it]
  iters:  26%|██▌       | 52/200 [01:33<04:25,  1.79s/it]
  iters:  26%|██▋       | 53/200 [01:35<04:21,  1.78s/it]
  iters:  27%|██▋       | 54/200 [01:36<04:17,  1.76s/it]
  iters:  28%|██▊       | 55/200 [01:38<04:15,  1.76s/it]
  iters:  28%|██▊       | 56/200 [01:40<04:30,  1.88s/it]
  iters:  28%|██▊       | 57/200 [01:42<04:23,  1.84s/it]
  iters:  29%|██▉       | 58/200 [01:44<04:18,  1.82s/it]
  iters:  30%|██▉       | 59/200 [01:46<04:22,  1.86s/it]
  iters:  30%|███       | 60/200 [01:48<04:17,  1.84s/it]
  iters:  30%|███       | 61/200 [01:50<04:23,  1.90s/it]
  iters:  31%|███       | 62/200 [01:51<04:16,  1.86s/it]
  iters:  32%|███▏      | 63/200 [01:53<04:10,  1.83s/it]
  iters:  32%|███▏      | 64/200 [01:55<04:06,  1.82s/it]
  iters:  32%|███▎      | 65/200 [01:57<04:02,  1.80s/it]
  iters:  33%|███▎      | 66/200 [01:59<04:07,  1.85s/it]
  iters:  34%|███▎      | 67/200 [02:00<04:02,  1.82s/it]
  iters:  34%|███▍      | 68/200 [02:02<03:58,  1.81s/it]
  iters:  34%|███▍      | 69/200 [02:04<03:54,  1.79s/it]
  iters:  35%|███▌      | 70/200 [02:06<03:50,  1.77s/it]
  iters:  36%|███▌      | 71/200 [02:08<03:51,  1.79s/it]
  iters:  36%|███▌      | 72/200 [02:09<03:48,  1.78s/it]
  iters:  36%|███▋      | 73/200 [02:11<03:54,  1.85s/it]
  iters:  37%|███▋      | 74/200 [02:13<03:52,  1.84s/it]
  iters:  38%|███▊      | 75/200 [02:15<03:46,  1.81s/it]
  iters:  38%|███▊      | 76/200 [02:17<03:45,  1.82s/it]
  iters:  38%|███▊      | 77/200 [02:18<03:41,  1.80s/it]
  iters:  39%|███▉      | 78/200 [02:20<03:38,  1.79s/it]
  iters:  40%|███▉      | 79/200 [02:22<03:34,  1.77s/it]
  iters:  40%|████      | 80/200 [02:24<03:34,  1.79s/it]
  iters:  40%|████      | 81/200 [02:26<03:34,  1.81s/it]
  iters:  41%|████      | 82/200 [02:27<03:30,  1.79s/it]
  iters:  42%|████▏     | 83/200 [02:29<03:27,  1.78s/it]
  iters:  42%|████▏     | 84/200 [02:31<03:24,  1.77s/it]
  iters:  42%|████▎     | 85/200 [02:33<03:22,  1.76s/it]
  iters:  43%|████▎     | 86/200 [02:34<03:22,  1.77s/it]
  iters:  44%|████▎     | 87/200 [02:36<03:19,  1.76s/it]
  iters:  44%|████▍     | 88/200 [02:38<03:19,  1.78s/it]
  iters:  44%|████▍     | 89/200 [02:40<03:16,  1.77s/it]
  iters:  45%|████▌     | 90/200 [02:41<03:13,  1.76s/it]
  iters:  46%|████▌     | 91/200 [02:43<03:11,  1.76s/it]
  iters:  46%|████▌     | 92/200 [02:45<03:12,  1.78s/it]
  iters:  46%|████▋     | 93/200 [02:47<03:09,  1.77s/it]
  iters:  47%|████▋     | 94/200 [02:49<03:18,  1.87s/it]
  iters:  48%|████▊     | 95/200 [02:51<03:23,  1.94s/it]
  iters:  48%|████▊     | 96/200 [02:53<03:16,  1.89s/it]
  iters:  48%|████▊     | 97/200 [02:55<03:17,  1.92s/it]
  iters:  49%|████▉     | 98/200 [02:56<03:10,  1.87s/it]
  iters:  50%|████▉     | 99/200 [02:58<03:05,  1.83s/it]
  iters:  50%|█████     | 100/200 [03:00<03:00,  1.81s/it]
  iters:  50%|█████     | 101/200 [03:02<02:58,  1.81s/it]
  iters:  51%|█████     | 102/200 [03:04<02:55,  1.79s/it]
  iters:  52%|█████▏    | 103/200 [03:05<02:52,  1.78s/it]
  iters:  52%|█████▏    | 104/200 [03:07<02:53,  1.81s/it]
  iters:  52%|█████▎    | 105/200 [03:09<02:58,  1.88s/it]
  iters:  53%|█████▎    | 106/200 [03:11<02:53,  1.84s/it]
  iters:  54%|█████▎    | 107/200 [03:13<02:49,  1.83s/it]
  iters:  54%|█████▍    | 108/200 [03:15<02:45,  1.80s/it]
  iters:  55%|█████▍    | 109/200 [03:16<02:44,  1.81s/it]
  iters:  55%|█████▌    | 110/200 [03:18<02:52,  1.91s/it]
  iters:  56%|█████▌    | 111/200 [03:20<02:46,  1.87s/it]
  iters:  56%|█████▌    | 112/200 [03:22<02:47,  1.90s/it]
  iters:  56%|█████▋    | 113/200 [03:24<02:41,  1.86s/it]
  iters:  57%|█████▋    | 114/200 [03:26<02:36,  1.83s/it]
  iters:  57%|█████▊    | 115/200 [03:27<02:33,  1.80s/it]
  iters:  58%|█████▊    | 116/200 [03:29<02:30,  1.79s/it]
  iters:  58%|█████▊    | 117/200 [03:31<02:27,  1.78s/it]
  iters:  59%|█████▉    | 118/200 [03:33<02:28,  1.81s/it]
  iters:  60%|█████▉    | 119/200 [03:35<02:33,  1.89s/it]
  iters:  60%|██████    | 120/200 [03:37<02:28,  1.85s/it]
  iters:  60%|██████    | 121/200 [03:38<02:23,  1.82s/it]
  iters:  61%|██████    | 122/200 [03:40<02:20,  1.80s/it]
  iters:  62%|██████▏   | 123/200 [03:42<02:16,  1.78s/it]
  iters:  62%|██████▏   | 124/200 [03:44<02:14,  1.78s/it]
  iters:  62%|██████▎   | 125/200 [03:46<02:18,  1.84s/it]
  iters:  63%|██████▎   | 126/200 [03:47<02:14,  1.82s/it]
  iters:  64%|██████▎   | 127/200 [03:49<02:10,  1.79s/it]
  iters:  64%|██████▍   | 128/200 [03:51<02:08,  1.78s/it]
  iters:  64%|██████▍   | 129/200 [03:53<02:06,  1.78s/it]
  iters:  65%|██████▌   | 130/200 [03:54<02:03,  1.77s/it]
  iters:  66%|██████▌   | 131/200 [03:57<02:09,  1.87s/it]
  iters:  66%|██████▌   | 132/200 [03:58<02:05,  1.85s/it]
  iters:  66%|██████▋   | 133/200 [04:00<02:02,  1.82s/it]
  iters:  67%|██████▋   | 134/200 [04:02<01:58,  1.80s/it]
  iters:  68%|██████▊   | 135/200 [04:04<01:56,  1.79s/it]
  iters:  68%|██████▊   | 136/200 [04:05<01:53,  1.78s/it]
  iters:  68%|██████▊   | 137/200 [04:07<01:52,  1.79s/it]
  iters:  69%|██████▉   | 138/200 [04:09<01:50,  1.78s/it]
  iters:  70%|██████▉   | 139/200 [04:11<01:47,  1.77s/it]
  iters:  70%|███████   | 140/200 [04:12<01:45,  1.76s/it]
  iters:  70%|███████   | 141/200 [04:14<01:47,  1.82s/it]
  iters:  71%|███████   | 142/200 [04:16<01:44,  1.80s/it]
  iters:  72%|███████▏  | 143/200 [04:18<01:41,  1.78s/it]
  iters:  72%|███████▏  | 144/200 [04:20<01:46,  1.89s/it]
  iters:  72%|███████▎  | 145/200 [04:22<01:41,  1.85s/it]
  iters:  73%|███████▎  | 146/200 [04:24<01:38,  1.82s/it]
  iters:  74%|███████▎  | 147/200 [04:25<01:34,  1.79s/it]
  iters:  74%|███████▍  | 148/200 [04:27<01:32,  1.77s/it]
  iters:  74%|███████▍  | 149/200 [04:29<01:29,  1.76s/it]
  iters:  75%|███████▌  | 150/200 [04:31<01:33,  1.88s/it]
  iters:  76%|███████▌  | 151/200 [04:33<01:30,  1.84s/it]
  iters:  76%|███████▌  | 152/200 [04:34<01:26,  1.81s/it]
  iters:  76%|███████▋  | 153/200 [04:36<01:25,  1.81s/it]
  iters:  77%|███████▋  | 154/200 [04:38<01:25,  1.87s/it]
  iters:  78%|███████▊  | 155/200 [04:40<01:23,  1.85s/it]
  iters:  78%|███████▊  | 156/200 [04:42<01:24,  1.91s/it]
  iters:  78%|███████▊  | 157/200 [04:44<01:20,  1.86s/it]
  iters:  79%|███████▉  | 158/200 [04:46<01:18,  1.86s/it]
  iters:  80%|███████▉  | 159/200 [04:47<01:14,  1.82s/it]
  iters:  80%|████████  | 160/200 [04:49<01:12,  1.82s/it]
  iters:  80%|████████  | 161/200 [04:51<01:10,  1.80s/it]
  iters:  81%|████████  | 162/200 [04:53<01:08,  1.79s/it]
  iters:  82%|████████▏ | 163/200 [04:55<01:09,  1.88s/it]
  iters:  82%|████████▏ | 164/200 [04:57<01:06,  1.84s/it]
  iters:  82%|████████▎ | 165/200 [04:59<01:08,  1.95s/it]
  iters:  83%|████████▎ | 166/200 [05:01<01:07,  1.99s/it]
  iters:  84%|████████▎ | 167/200 [05:03<01:07,  2.06s/it]
  iters:  84%|████████▍ | 168/200 [05:05<01:02,  1.97s/it]
  iters:  84%|████████▍ | 169/200 [05:07<00:58,  1.89s/it]
  iters:  85%|████████▌ | 170/200 [05:08<00:55,  1.85s/it]
  iters:  86%|████████▌ | 171/200 [05:10<00:52,  1.82s/it]
  iters:  86%|████████▌ | 172/200 [05:12<00:54,  1.94s/it]
  iters:  86%|████████▋ | 173/200 [05:14<00:50,  1.88s/it]
  iters:  87%|████████▋ | 174/200 [05:16<00:47,  1.84s/it]
  iters:  88%|████████▊ | 175/200 [05:18<00:47,  1.90s/it]
  iters:  88%|████████▊ | 176/200 [05:20<00:45,  1.89s/it]
  iters:  88%|████████▊ | 177/200 [05:21<00:42,  1.85s/it]
  iters:  89%|████████▉ | 178/200 [05:23<00:40,  1.82s/it]
  iters:  90%|████████▉ | 179/200 [05:25<00:38,  1.81s/it]
  iters:  90%|█████████ | 180/200 [05:27<00:35,  1.79s/it]
  iters:  90%|█████████ | 181/200 [05:28<00:33,  1.78s/it]
  iters:  91%|█████████ | 182/200 [05:30<00:31,  1.77s/it]
  iters:  92%|█████████▏| 183/200 [05:32<00:30,  1.77s/it]
  iters:  92%|█████████▏| 184/200 [05:34<00:28,  1.77s/it]
  iters:  92%|█████████▎| 185/200 [05:36<00:26,  1.76s/it]
  iters:  93%|█████████▎| 186/200 [05:38<00:25,  1.84s/it]
  iters:  94%|█████████▎| 187/200 [05:40<00:24,  1.88s/it]
  iters:  94%|█████████▍| 188/200 [05:41<00:22,  1.85s/it]
  iters:  94%|█████████▍| 189/200 [05:43<00:20,  1.82s/it]
  iters:  95%|█████████▌| 190/200 [05:45<00:17,  1.80s/it]
  iters:  96%|█████████▌| 191/200 [05:47<00:16,  1.78s/it]
  iters:  96%|█████████▌| 192/200 [05:48<00:14,  1.77s/it]
  iters:  96%|█████████▋| 193/200 [05:50<00:12,  1.76s/it]
  iters:  97%|█████████▋| 194/200 [05:52<00:10,  1.76s/it]
  iters:  98%|█████████▊| 195/200 [05:54<00:08,  1.80s/it]
  iters:  98%|█████████▊| 196/200 [05:55<00:07,  1.78s/it]
  iters:  98%|█████████▊| 197/200 [05:57<00:05,  1.76s/it]
  iters:  99%|█████████▉| 198/200 [05:59<00:03,  1.92s/it]
  iters: 100%|█████████▉| 199/200 [06:01<00:01,  1.87s/it]
  iters: 100%|██████████| 200/200 [06:03<00:00,  1.83s/it]

  [timing] data: 2.4s (1%) | forward: 89.5s (25%) | backward: 271.5s (75%) | total: 363.4s

Training:   0%|          | 0/4 [06:35<?, ?it/s, acc=0.9988, det=0.0087, edge=0.0007]

  Epoch   0/4 | edge=0.0007 | det=0.0087 | test_loss=0.0017 | acc=0.9988 | recall=0.9183 | best=0.9172 * | train=363.7s test=31.4s

Training:  25%|██▌       | 1/4 [06:35<19:45, 395.12s/it, acc=0.9988, det=0.0087, edge=0.0007]
  iters:   0%|          | 0/200 [00:00<?, ?it/s]
  iters:   0%|          | 1/200 [00:02<06:47,  2.05s/it]
  iters:   1%|          | 2/200 [00:03<06:10,  1.87s/it]
  iters:   2%|▏         | 3/200 [00:05<06:07,  1.87s/it]
  iters:   2%|▏         | 4/200 [00:07<06:35,  2.02s/it]
  iters:   2%|▎         | 5/200 [00:09<06:31,  2.01s/it]
  iters:   3%|▎         | 6/200 [00:11<06:12,  1.92s/it]
  iters:   4%|▎         | 7/200 [00:13<06:01,  1.87s/it]
  iters:   4%|▍         | 8/200 [00:15<05:51,  1.83s/it]
  iters:   4%|▍         | 9/200 [00:16<05:45,  1.81s/it]
  iters:   5%|▌         | 10/200 [00:18<05:51,  1.85s/it]
  iters:   6%|▌         | 11/200 [00:20<05:45,  1.83s/it]
  iters:   6%|▌         | 12/200 [00:22<05:42,  1.82s/it]
  iters:   6%|▋         | 13/200 [00:24<05:36,  1.80s/it]
  iters:   7%|▋         | 14/200 [00:25<05:32,  1.79s/it]
  iters:   8%|▊         | 15/200 [00:28<05:59,  1.94s/it]
  iters:   8%|▊         | 16/200 [00:30<05:46,  1.88s/it]
  iters:   8%|▊         | 17/200 [00:31<05:36,  1.84s/it]
  iters:   9%|▉         | 18/200 [00:33<05:37,  1.85s/it]
  iters:  10%|▉         | 19/200 [00:35<05:44,  1.91s/it]
  iters:  10%|█         | 20/200 [00:37<05:34,  1.86s/it]
  iters:  10%|█         | 21/200 [00:39<05:27,  1.83s/it]
  iters:  11%|█         | 22/200 [00:40<05:21,  1.81s/it]
  iters:  12%|█▏        | 23/200 [00:43<05:43,  1.94s/it]
  iters:  12%|█▏        | 24/200 [00:44<05:31,  1.88s/it]
  iters:  12%|█▎        | 25/200 [00:46<05:23,  1.85s/it]
  iters:  13%|█▎        | 26/200 [00:48<05:16,  1.82s/it]
  iters:  14%|█▎        | 27/200 [00:50<05:11,  1.80s/it]
  iters:  14%|█▍        | 28/200 [00:51<05:07,  1.79s/it]
  iters:  14%|█▍        | 29/200 [00:53<05:03,  1.77s/it]
  iters:  15%|█▌        | 30/200 [00:55<05:21,  1.89s/it]
  iters:  16%|█▌        | 31/200 [00:57<05:18,  1.89s/it]
  iters:  16%|█▌        | 32/200 [00:59<05:10,  1.85s/it]
  iters:  16%|█▋        | 33/200 [01:01<05:05,  1.83s/it]
  iters:  17%|█▋        | 34/200 [01:03<05:27,  1.98s/it]
  iters:  18%|█▊        | 35/200 [01:05<05:15,  1.91s/it]
  iters:  18%|█▊        | 36/200 [01:07<05:04,  1.86s/it]
  iters:  18%|█▊        | 37/200 [01:08<04:58,  1.83s/it]
  iters:  19%|█▉        | 38/200 [01:10<04:55,  1.82s/it]
  iters:  20%|█▉        | 39/200 [01:12<04:57,  1.85s/it]
  iters:  20%|██        | 40/200 [01:14<04:51,  1.82s/it]
  iters:  20%|██        | 41/200 [01:16<05:09,  1.95s/it]
  iters:  21%|██        | 42/200 [01:18<05:25,  2.06s/it]
  iters:  22%|██▏       | 43/200 [01:20<05:09,  1.97s/it]
  iters:  22%|██▏       | 44/200 [01:22<04:56,  1.90s/it]
  iters:  22%|██▎       | 45/200 [01:24<04:48,  1.86s/it]
  iters:  23%|██▎       | 46/200 [01:25<04:42,  1.83s/it]
  iters:  24%|██▎       | 47/200 [01:27<04:38,  1.82s/it]
  iters:  24%|██▍       | 48/200 [01:29<04:35,  1.81s/it]
  iters:  24%|██▍       | 49/200 [01:31<04:31,  1.80s/it]
  iters:  25%|██▌       | 50/200 [01:33<04:40,  1.87s/it]
  iters:  26%|██▌       | 51/200 [01:35<04:32,  1.83s/it]
  iters:  26%|██▌       | 52/200 [01:36<04:27,  1.80s/it]
  iters:  26%|██▋       | 53/200 [01:38<04:22,  1.79s/it]
  iters:  27%|██▋       | 54/200 [01:40<04:31,  1.86s/it]
  iters:  28%|██▊       | 55/200 [01:42<04:24,  1.82s/it]
  iters:  28%|██▊       | 56/200 [01:44<04:19,  1.80s/it]
  iters:  28%|██▊       | 57/200 [01:45<04:15,  1.79s/it]
  iters:  29%|██▉       | 58/200 [01:47<04:11,  1.77s/it]
  iters:  30%|██▉       | 59/200 [01:49<04:32,  1.93s/it]
  iters:  30%|███       | 60/200 [01:52<04:43,  2.02s/it]
  iters:  30%|███       | 61/200 [01:53<04:30,  1.94s/it]
  iters:  31%|███       | 62/200 [01:55<04:21,  1.90s/it]
  iters:  32%|███▏      | 63/200 [01:57<04:32,  1.99s/it]
  iters:  32%|███▏      | 64/200 [01:59<04:19,  1.91s/it]
  iters:  32%|███▎      | 65/200 [02:01<04:11,  1.86s/it]
  iters:  33%|███▎      | 66/200 [02:03<04:15,  1.90s/it]
  iters:  34%|███▎      | 67/200 [02:05<04:13,  1.90s/it]
  iters:  34%|███▍      | 68/200 [02:07<04:06,  1.87s/it]
  iters:  34%|███▍      | 69/200 [02:08<03:59,  1.83s/it]
  iters:  35%|███▌      | 70/200 [02:10<03:57,  1.83s/it]
  iters:  36%|███▌      | 71/200 [02:12<03:57,  1.84s/it]
  iters:  36%|███▌      | 72/200 [02:14<03:52,  1.81s/it]
  iters:  36%|███▋      | 73/200 [02:15<03:48,  1.80s/it]
  iters:  37%|███▋      | 74/200 [02:17<03:45,  1.79s/it]
  iters:  38%|███▊      | 75/200 [02:19<03:59,  1.91s/it]
  iters:  38%|███▊      | 76/200 [02:21<03:51,  1.86s/it]
  iters:  38%|███▊      | 77/200 [02:23<03:44,  1.83s/it]
  iters:  39%|███▉      | 78/200 [02:25<03:39,  1.80s/it]
  iters:  40%|███▉      | 79/200 [02:26<03:35,  1.78s/it]
  iters:  40%|████      | 80/200 [02:28<03:34,  1.79s/it]
  iters:  40%|████      | 81/200 [02:30<03:30,  1.77s/it]
  iters:  41%|████      | 82/200 [02:32<03:28,  1.77s/it]
  iters:  42%|████▏     | 83/200 [02:33<03:25,  1.76s/it]
  iters:  42%|████▏     | 84/200 [02:35<03:23,  1.75s/it]
  iters:  42%|████▎     | 85/200 [02:37<03:21,  1.75s/it]
  iters:  43%|████▎     | 86/200 [02:39<03:19,  1.75s/it]
  iters:  44%|████▎     | 87/200 [02:40<03:16,  1.74s/it]
  iters:  44%|████▍     | 88/200 [02:43<03:34,  1.91s/it]
  iters:  44%|████▍     | 89/200 [02:44<03:26,  1.86s/it]
  iters:  45%|████▌     | 90/200 [02:46<03:20,  1.82s/it]
  iters:  46%|████▌     | 91/200 [02:48<03:16,  1.80s/it]
  iters:  46%|████▌     | 92/200 [02:50<03:18,  1.83s/it]
  iters:  46%|████▋     | 93/200 [02:52<03:13,  1.81s/it]
  iters:  47%|████▋     | 94/200 [02:54<03:25,  1.94s/it]
  iters:  48%|████▊     | 95/200 [02:56<03:17,  1.88s/it]
  iters:  48%|████▊     | 96/200 [02:57<03:16,  1.89s/it]
  iters:  48%|████▊     | 97/200 [02:59<03:10,  1.85s/it]
  iters:  49%|████▉     | 98/200 [03:01<03:07,  1.84s/it]
  iters:  50%|████▉     | 99/200 [03:03<03:03,  1.82s/it]
  iters:  50%|█████     | 100/200 [03:05<02:59,  1.79s/it]
  iters:  50%|█████     | 101/200 [03:06<02:56,  1.78s/it]
  iters:  51%|█████     | 102/200 [03:08<02:53,  1.77s/it]
  iters:  52%|█████▏    | 103/200 [03:10<02:58,  1.84s/it]
  iters:  52%|█████▏    | 104/200 [03:12<02:54,  1.82s/it]
  iters:  52%|█████▎    | 105/200 [03:14<02:50,  1.79s/it]
  iters:  53%|█████▎    | 106/200 [03:15<02:46,  1.77s/it]
  iters:  54%|█████▎    | 107/200 [03:17<02:44,  1.77s/it]
  iters:  54%|█████▍    | 108/200 [03:19<02:41,  1.76s/it]
  iters:  55%|█████▍    | 109/200 [03:21<02:39,  1.76s/it]
  iters:  55%|█████▌    | 110/200 [03:22<02:37,  1.75s/it]
  iters:  56%|█████▌    | 111/200 [03:24<02:35,  1.75s/it]
  iters:  56%|█████▌    | 112/200 [03:26<02:33,  1.75s/it]
  iters:  56%|█████▋    | 113/200 [03:28<02:41,  1.86s/it]
  iters:  57%|█████▋    | 114/200 [03:30<02:36,  1.82s/it]
  iters:  57%|█████▊    | 115/200 [03:31<02:35,  1.82s/it]
  iters:  58%|█████▊    | 116/200 [03:33<02:31,  1.80s/it]
  iters:  58%|█████▊    | 117/200 [03:35<02:28,  1.79s/it]
  iters:  59%|█████▉    | 118/200 [03:37<02:25,  1.78s/it]
  iters:  60%|█████▉    | 119/200 [03:38<02:23,  1.77s/it]
  iters:  60%|██████    | 120/200 [03:40<02:21,  1.77s/it]
  iters:  60%|██████    | 121/200 [03:42<02:19,  1.76s/it]
  iters:  61%|██████    | 122/200 [03:44<02:16,  1.75s/it]
  iters:  62%|██████▏   | 123/200 [03:46<02:23,  1.86s/it]
  iters:  62%|██████▏   | 124/200 [03:48<02:19,  1.83s/it]
  iters:  62%|██████▎   | 125/200 [03:49<02:15,  1.81s/it]
  iters:  63%|██████▎   | 126/200 [03:51<02:12,  1.79s/it]
  iters:  64%|██████▎   | 127/200 [03:53<02:10,  1.78s/it]
  iters:  64%|██████▍   | 128/200 [03:55<02:07,  1.77s/it]
  iters:  64%|██████▍   | 129/200 [03:57<02:11,  1.86s/it]
  iters:  65%|██████▌   | 130/200 [03:58<02:07,  1.82s/it]
  iters:  66%|██████▌   | 131/200 [04:00<02:09,  1.88s/it]
  iters:  66%|██████▌   | 132/200 [04:02<02:10,  1.92s/it]
  iters:  66%|██████▋   | 133/200 [04:04<02:05,  1.87s/it]
  iters:  67%|██████▋   | 134/200 [04:06<02:00,  1.83s/it]
  iters:  68%|██████▊   | 135/200 [04:08<01:58,  1.82s/it]
  iters:  68%|██████▊   | 136/200 [04:09<01:54,  1.79s/it]
  iters:  68%|██████▊   | 137/200 [04:11<01:52,  1.78s/it]
  iters:  69%|██████▉   | 138/200 [04:13<01:49,  1.77s/it]
  iters:  70%|██████▉   | 139/200 [04:15<01:52,  1.85s/it]
  iters:  70%|███████   | 140/200 [04:17<01:48,  1.82s/it]
  iters:  70%|███████   | 141/200 [04:18<01:45,  1.79s/it]
  iters:  71%|███████   | 142/200 [04:20<01:46,  1.83s/it]
  iters:  72%|███████▏  | 143/200 [04:22<01:42,  1.81s/it]
  iters:  72%|███████▏  | 144/200 [04:24<01:40,  1.79s/it]
  iters:  72%|███████▎  | 145/200 [04:26<01:37,  1.77s/it]
  iters:  73%|███████▎  | 146/200 [04:27<01:34,  1.76s/it]
  iters:  74%|███████▎  | 147/200 [04:29<01:32,  1.75s/it]
  iters:  74%|███████▍  | 148/200 [04:31<01:30,  1.75s/it]
  iters:  74%|███████▍  | 149/200 [04:33<01:32,  1.82s/it]
  iters:  75%|███████▌  | 150/200 [04:34<01:29,  1.79s/it]
  iters:  76%|███████▌  | 151/200 [04:36<01:26,  1.77s/it]
  iters:  76%|███████▌  | 152/200 [04:38<01:24,  1.76s/it]
  iters:  76%|███████▋  | 153/200 [04:40<01:22,  1.75s/it]
  iters:  77%|███████▋  | 154/200 [04:41<01:20,  1.75s/it]
  iters:  78%|███████▊  | 155/200 [04:43<01:18,  1.75s/it]
  iters:  78%|███████▊  | 156/200 [04:45<01:16,  1.75s/it]
  iters:  78%|███████▊  | 157/200 [04:47<01:16,  1.78s/it]
  iters:  79%|███████▉  | 158/200 [04:48<01:14,  1.77s/it]
  iters:  80%|███████▉  | 159/200 [04:50<01:12,  1.76s/it]
  iters:  80%|████████  | 160/200 [04:52<01:09,  1.75s/it]
  iters:  80%|████████  | 161/200 [04:54<01:09,  1.78s/it]
  iters:  81%|████████  | 162/200 [04:56<01:07,  1.77s/it]
  iters:  82%|████████▏ | 163/200 [04:57<01:05,  1.77s/it]
  iters:  82%|████████▏ | 164/200 [04:59<01:03,  1.77s/it]
  iters:  82%|████████▎ | 165/200 [05:01<01:01,  1.76s/it]
  iters:  83%|████████▎ | 166/200 [05:03<00:59,  1.75s/it]
  iters:  84%|████████▎ | 167/200 [05:04<00:59,  1.80s/it]
  iters:  84%|████████▍ | 168/200 [05:06<00:57,  1.80s/it]
  iters:  84%|████████▍ | 169/200 [05:08<00:55,  1.79s/it]
  iters:  85%|████████▌ | 170/200 [05:10<00:55,  1.85s/it]
  iters:  86%|████████▌ | 171/200 [05:12<00:52,  1.82s/it]
  iters:  86%|████████▌ | 172/200 [05:14<00:51,  1.83s/it]
  iters:  86%|████████▋ | 173/200 [05:15<00:48,  1.81s/it]
  iters:  87%|████████▋ | 174/200 [05:17<00:46,  1.79s/it]
  iters:  88%|████████▊ | 175/200 [05:19<00:46,  1.85s/it]
  iters:  88%|████████▊ | 176/200 [05:21<00:45,  1.88s/it]
  iters:  88%|████████▊ | 177/200 [05:23<00:43,  1.91s/it]
  iters:  89%|████████▉ | 178/200 [05:25<00:42,  1.92s/it]
  iters:  90%|████████▉ | 179/200 [05:27<00:40,  1.93s/it]
  iters:  90%|█████████ | 180/200 [05:29<00:37,  1.88s/it]
  iters:  90%|█████████ | 181/200 [05:31<00:37,  1.97s/it]
  iters:  91%|█████████ | 182/200 [05:33<00:34,  1.93s/it]
  iters:  92%|█████████▏| 183/200 [05:34<00:31,  1.87s/it]
  iters:  92%|█████████▏| 184/200 [05:36<00:30,  1.90s/it]
  iters:  92%|█████████▎| 185/200 [05:38<00:27,  1.86s/it]
  iters:  93%|█████████▎| 186/200 [05:40<00:25,  1.82s/it]
  iters:  94%|█████████▎| 187/200 [05:42<00:24,  1.86s/it]
  iters:  94%|█████████▍| 188/200 [05:44<00:21,  1.83s/it]
  iters:  94%|█████████▍| 189/200 [05:45<00:19,  1.81s/it]
  iters:  95%|█████████▌| 190/200 [05:47<00:17,  1.78s/it]
  iters:  96%|█████████▌| 191/200 [05:49<00:15,  1.77s/it]
  iters:  96%|█████████▌| 192/200 [05:51<00:14,  1.77s/it]
  iters:  96%|█████████▋| 193/200 [05:52<00:12,  1.76s/it]
  iters:  97%|█████████▋| 194/200 [05:54<00:10,  1.76s/it]
  iters:  98%|█████████▊| 195/200 [05:56<00:09,  1.81s/it]
  iters:  98%|█████████▊| 196/200 [05:58<00:07,  1.78s/it]
  iters:  98%|█████████▊| 197/200 [05:59<00:05,  1.77s/it]
  iters:  99%|█████████▉| 198/200 [06:01<00:03,  1.76s/it]
  iters: 100%|█████████▉| 199/200 [06:03<00:01,  1.75s/it]
  iters: 100%|██████████| 200/200 [06:05<00:00,  1.74s/it]

  [timing] data: 2.4s (1%) | forward: 89.9s (25%) | backward: 272.9s (75%) | total: 365.2s

Training:  25%|██▌       | 1/4 [13:11<19:45, 395.12s/it, acc=0.9991, det=0.0075, edge=0.0007]

  Epoch   1/4 | edge=0.0007 | det=0.0075 | test_loss=0.0012 | acc=0.9991 | recall=0.8765 | best=0.9172   | train=365.4s test=31.0s

Training:  50%|█████     | 2/4 [13:11<13:11, 395.85s/it, acc=0.9991, det=0.0075, edge=0.0007]
  iters:   0%|          | 0/200 [00:00<?, ?it/s]
  iters:   0%|          | 1/200 [00:02<07:30,  2.26s/it]
  iters:   1%|          | 2/200 [00:03<06:24,  1.94s/it]
  iters:   2%|▏         | 3/200 [00:06<06:41,  2.04s/it]
  iters:   2%|▏         | 4/200 [00:07<06:15,  1.91s/it]
  iters:   2%|▎         | 5/200 [00:09<06:01,  1.86s/it]
  iters:   3%|▎         | 6/200 [00:11<05:52,  1.81s/it]
  iters:   4%|▎         | 7/200 [00:13<05:46,  1.79s/it]
  iters:   4%|▍         | 8/200 [00:15<05:57,  1.86s/it]
  iters:   4%|▍         | 9/200 [00:16<05:48,  1.82s/it]
  iters:   5%|▌         | 10/200 [00:18<05:45,  1.82s/it]
  iters:   6%|▌         | 11/200 [00:20<05:59,  1.90s/it]
  iters:   6%|▌         | 12/200 [00:22<05:48,  1.86s/it]
  iters:   6%|▋         | 13/200 [00:24<05:40,  1.82s/it]
  iters:   7%|▋         | 14/200 [00:25<05:34,  1.80s/it]
  iters:   8%|▊         | 15/200 [00:27<05:30,  1.78s/it]
  iters:   8%|▊         | 16/200 [00:29<05:26,  1.77s/it]
  iters:   8%|▊         | 17/200 [00:31<05:32,  1.82s/it]
  iters:   9%|▉         | 18/200 [00:33<05:27,  1.80s/it]
  iters:  10%|▉         | 19/200 [00:34<05:21,  1.78s/it]
  iters:  10%|█         | 20/200 [00:36<05:28,  1.83s/it]
  iters:  10%|█         | 21/200 [00:38<05:21,  1.80s/it]
  iters:  11%|█         | 22/200 [00:40<05:27,  1.84s/it]
  iters:  12%|█▏        | 23/200 [00:42<05:38,  1.91s/it]
  iters:  12%|█▏        | 24/200 [00:44<05:26,  1.86s/it]
  iters:  12%|█▎        | 25/200 [00:46<05:44,  1.97s/it]
  iters:  13%|█▎        | 26/200 [00:48<05:36,  1.93s/it]
  iters:  14%|█▎        | 27/200 [00:50<05:25,  1.88s/it]
  iters:  14%|█▍        | 28/200 [00:51<05:17,  1.85s/it]
  iters:  14%|█▍        | 29/200 [00:53<05:26,  1.91s/it]
  iters:  15%|█▌        | 30/200 [00:55<05:16,  1.86s/it]
  iters:  16%|█▌        | 31/200 [00:57<05:08,  1.82s/it]
  iters:  16%|█▌        | 32/200 [00:59<05:02,  1.80s/it]
  iters:  16%|█▋        | 33/200 [01:00<04:58,  1.79s/it]
  iters:  17%|█▋        | 34/200 [01:02<04:53,  1.77s/it]
  iters:  18%|█▊        | 35/200 [01:04<04:51,  1.76s/it]
  iters:  18%|█▊        | 36/200 [01:06<04:47,  1.75s/it]
  iters:  18%|█▊        | 37/200 [01:07<04:45,  1.75s/it]
  iters:  19%|█▉        | 38/200 [01:09<04:43,  1.75s/it]
  iters:  20%|█▉        | 39/200 [01:11<04:41,  1.75s/it]
  iters:  20%|██        | 40/200 [01:13<05:01,  1.89s/it]
  iters:  20%|██        | 41/200 [01:15<04:53,  1.84s/it]
  iters:  21%|██        | 42/200 [01:17<04:46,  1.81s/it]
  iters:  22%|██▏       | 43/200 [01:19<04:54,  1.88s/it]
  iters:  22%|██▏       | 44/200 [01:20<04:45,  1.83s/it]
  iters:  22%|██▎       | 45/200 [01:22<04:45,  1.84s/it]
  iters:  23%|██▎       | 46/200 [01:24<04:38,  1.81s/it]
  iters:  24%|██▎       | 47/200 [01:26<04:33,  1.79s/it]
  iters:  24%|██▍       | 48/200 [01:27<04:30,  1.78s/it]
  iters:  24%|██▍       | 49/200 [01:29<04:35,  1.82s/it]
  iters:  25%|██▌       | 50/200 [01:31<04:36,  1.84s/it]
  iters:  26%|██▌       | 51/200 [01:33<04:30,  1.81s/it]
  iters:  26%|██▌       | 52/200 [01:35<04:25,  1.80s/it]
  iters:  26%|██▋       | 53/200 [01:37<04:43,  1.93s/it]
  iters:  27%|██▋       | 54/200 [01:39<04:33,  1.87s/it]
  iters:  28%|██▊       | 55/200 [01:40<04:25,  1.83s/it]
  iters:  28%|██▊       | 56/200 [01:42<04:20,  1.81s/it]
  iters:  28%|██▊       | 57/200 [01:44<04:33,  1.91s/it]
  iters:  29%|██▉       | 58/200 [01:46<04:23,  1.86s/it]
  iters:  30%|██▉       | 59/200 [01:48<04:16,  1.82s/it]
  iters:  30%|███       | 60/200 [01:50<04:10,  1.79s/it]
  iters:  30%|███       | 61/200 [01:51<04:11,  1.81s/it]
  iters:  31%|███       | 62/200 [01:53<04:06,  1.79s/it]
  iters:  32%|███▏      | 63/200 [01:55<04:02,  1.77s/it]
  iters:  32%|███▏      | 64/200 [01:57<03:59,  1.76s/it]
  iters:  32%|███▎      | 65/200 [01:59<04:06,  1.83s/it]
  iters:  33%|███▎      | 66/200 [02:00<04:06,  1.84s/it]
  iters:  34%|███▎      | 67/200 [02:02<04:00,  1.81s/it]
  iters:  34%|███▍      | 68/200 [02:04<04:17,  1.95s/it]
  iters:  34%|███▍      | 69/200 [02:07<04:21,  2.00s/it]
  iters:  35%|███▌      | 70/200 [02:08<04:09,  1.92s/it]
  iters:  36%|███▌      | 71/200 [02:10<04:02,  1.88s/it]
  iters:  36%|███▌      | 72/200 [02:12<03:54,  1.83s/it]
  iters:  36%|███▋      | 73/200 [02:14<03:48,  1.80s/it]
  iters:  37%|███▋      | 74/200 [02:15<03:44,  1.79s/it]
  iters:  38%|███▊      | 75/200 [02:17<03:42,  1.78s/it]
  iters:  38%|███▊      | 76/200 [02:19<03:39,  1.77s/it]
  iters:  38%|███▊      | 77/200 [02:21<03:35,  1.75s/it]
  iters:  39%|███▉      | 78/200 [02:22<03:33,  1.75s/it]
  iters:  40%|███▉      | 79/200 [02:24<03:31,  1.75s/it]
  iters:  40%|████      | 80/200 [02:26<03:29,  1.75s/it]
  iters:  40%|████      | 81/200 [02:28<03:29,  1.76s/it]
  iters:  41%|████      | 82/200 [02:29<03:27,  1.76s/it]
  iters:  42%|████▏     | 83/200 [02:31<03:33,  1.83s/it]
  iters:  42%|████▏     | 84/200 [02:33<03:28,  1.80s/it]
  iters:  42%|████▎     | 85/200 [02:35<03:30,  1.83s/it]
  iters:  43%|████▎     | 86/200 [02:37<03:25,  1.80s/it]
  iters:  44%|████▎     | 87/200 [02:39<03:34,  1.90s/it]
  iters:  44%|████▍     | 88/200 [02:41<03:26,  1.85s/it]
  iters:  44%|████▍     | 89/200 [02:42<03:25,  1.85s/it]
  iters:  45%|████▌     | 90/200 [02:45<03:37,  1.98s/it]
  iters:  46%|████▌     | 91/200 [02:46<03:27,  1.91s/it]
  iters:  46%|████▌     | 92/200 [02:48<03:21,  1.87s/it]
  iters:  46%|████▋     | 93/200 [02:50<03:16,  1.84s/it]
  iters:  47%|████▋     | 94/200 [02:52<03:24,  1.93s/it]
  iters:  48%|████▊     | 95/200 [02:54<03:16,  1.87s/it]
  iters:  48%|████▊     | 96/200 [02:56<03:10,  1.83s/it]
  iters:  48%|████▊     | 97/200 [02:57<03:08,  1.83s/it]
  iters:  49%|████▉     | 98/200 [02:59<03:03,  1.80s/it]
  iters:  50%|████▉     | 99/200 [03:01<03:07,  1.85s/it]
  iters:  50%|█████     | 100/200 [03:03<03:02,  1.82s/it]
  iters:  50%|█████     | 101/200 [03:05<03:01,  1.84s/it]
  iters:  51%|█████     | 102/200 [03:06<02:57,  1.81s/it]
  iters:  52%|█████▏    | 103/200 [03:08<02:53,  1.79s/it]
  iters:  52%|█████▏    | 104/200 [03:10<02:50,  1.78s/it]
  iters:  52%|█████▎    | 105/200 [03:12<02:47,  1.77s/it]
  iters:  53%|█████▎    | 106/200 [03:13<02:45,  1.76s/it]
  iters:  54%|█████▎    | 107/200 [03:15<02:43,  1.76s/it]
  iters:  54%|█████▍    | 108/200 [03:17<02:41,  1.75s/it]
  iters:  55%|█████▍    | 109/200 [03:19<02:49,  1.86s/it]
  iters:  55%|█████▌    | 110/200 [03:21<02:51,  1.91s/it]
  iters:  56%|█████▌    | 111/200 [03:23<02:45,  1.86s/it]
  iters:  56%|█████▌    | 112/200 [03:25<02:40,  1.83s/it]
  iters:  56%|█████▋    | 113/200 [03:26<02:36,  1.80s/it]
  iters:  57%|█████▋    | 114/200 [03:28<02:38,  1.84s/it]
  iters:  57%|█████▊    | 115/200 [03:30<02:33,  1.81s/it]
  iters:  58%|█████▊    | 116/200 [03:32<02:30,  1.79s/it]
  iters:  58%|█████▊    | 117/200 [03:34<02:39,  1.92s/it]
  iters:  59%|█████▉    | 118/200 [03:36<02:33,  1.87s/it]
  iters:  60%|█████▉    | 119/200 [03:38<02:28,  1.84s/it]
  iters:  60%|██████    | 120/200 [03:39<02:24,  1.81s/it]
  iters:  60%|██████    | 121/200 [03:41<02:21,  1.79s/it]
  iters:  61%|██████    | 122/200 [03:43<02:24,  1.85s/it]
  iters:  62%|██████▏   | 123/200 [03:45<02:31,  1.96s/it]
  iters:  62%|██████▏   | 124/200 [03:47<02:24,  1.90s/it]
  iters:  62%|██████▎   | 125/200 [03:49<02:18,  1.85s/it]
  iters:  63%|██████▎   | 126/200 [03:50<02:14,  1.82s/it]
  iters:  64%|██████▎   | 127/200 [03:52<02:15,  1.86s/it]
  iters:  64%|██████▍   | 128/200 [03:55<02:21,  1.96s/it]
  iters:  64%|██████▍   | 129/200 [03:56<02:14,  1.89s/it]
  iters:  65%|██████▌   | 130/200 [03:58<02:09,  1.85s/it]
  iters:  66%|██████▌   | 131/200 [04:00<02:05,  1.82s/it]
  iters:  66%|██████▌   | 132/200 [04:02<02:02,  1.80s/it]
  iters:  66%|██████▋   | 133/200 [04:03<01:59,  1.78s/it]
  iters:  67%|██████▋   | 134/200 [04:05<01:59,  1.80s/it]
  iters:  68%|██████▊   | 135/200 [04:07<01:55,  1.78s/it]
  iters:  68%|██████▊   | 136/200 [04:09<01:53,  1.77s/it]
  iters:  68%|██████▊   | 137/200 [04:10<01:50,  1.76s/it]
  iters:  69%|██████▉   | 138/200 [04:12<01:49,  1.77s/it]
  iters:  70%|██████▉   | 139/200 [04:14<01:47,  1.76s/it]
  iters:  70%|███████   | 140/200 [04:16<01:45,  1.76s/it]
  iters:  70%|███████   | 141/200 [04:17<01:43,  1.75s/it]
  iters:  71%|███████   | 142/200 [04:19<01:41,  1.75s/it]
  iters:  72%|███████▏  | 143/200 [04:21<01:39,  1.75s/it]
  iters:  72%|███████▏  | 144/200 [04:23<01:38,  1.75s/it]
  iters:  72%|███████▎  | 145/200 [04:24<01:36,  1.75s/it]
  iters:  73%|███████▎  | 146/200 [04:26<01:34,  1.75s/it]
  iters:  74%|███████▎  | 147/200 [04:28<01:32,  1.75s/it]
  iters:  74%|███████▍  | 148/200 [04:30<01:32,  1.77s/it]
  iters:  74%|███████▍  | 149/200 [04:31<01:29,  1.76s/it]
  iters:  75%|███████▌  | 150/200 [04:33<01:27,  1.75s/it]
  iters:  76%|███████▌  | 151/200 [04:35<01:25,  1.75s/it]
  iters:  76%|███████▌  | 152/200 [04:37<01:23,  1.74s/it]
  iters:  76%|███████▋  | 153/200 [04:39<01:23,  1.77s/it]
  iters:  77%|███████▋  | 154/200 [04:41<01:27,  1.90s/it]
  iters:  78%|███████▊  | 155/200 [04:42<01:23,  1.85s/it]
  iters:  78%|███████▊  | 156/200 [04:44<01:20,  1.83s/it]
  iters:  78%|███████▊  | 157/200 [04:46<01:17,  1.80s/it]
  iters:  79%|███████▉  | 158/200 [04:48<01:14,  1.78s/it]
  iters:  80%|███████▉  | 159/200 [04:49<01:12,  1.77s/it]
  iters:  80%|████████  | 160/200 [04:51<01:10,  1.76s/it]
  iters:  80%|████████  | 161/200 [04:53<01:08,  1.74s/it]
  iters:  81%|████████  | 162/200 [04:55<01:09,  1.82s/it]
  iters:  82%|████████▏ | 163/200 [04:57<01:06,  1.79s/it]
  iters:  82%|████████▏ | 164/200 [04:58<01:03,  1.78s/it]
  iters:  82%|████████▎ | 165/200 [05:00<01:01,  1.76s/it]
  iters:  83%|████████▎ | 166/200 [05:02<00:59,  1.75s/it]
  iters:  84%|████████▎ | 167/200 [05:04<00:57,  1.75s/it]
  iters:  84%|████████▍ | 168/200 [05:05<00:55,  1.74s/it]
  iters:  84%|████████▍ | 169/200 [05:07<00:54,  1.74s/it]
  iters:  85%|████████▌ | 170/200 [05:09<00:52,  1.74s/it]
  iters:  86%|████████▌ | 171/200 [05:10<00:50,  1.74s/it]
  iters:  86%|████████▌ | 172/200 [05:12<00:48,  1.74s/it]
  iters:  86%|████████▋ | 173/200 [05:14<00:46,  1.74s/it]
  iters:  87%|████████▋ | 174/200 [05:16<00:45,  1.75s/it]
  iters:  88%|████████▊ | 175/200 [05:18<00:44,  1.78s/it]
  iters:  88%|████████▊ | 176/200 [05:19<00:42,  1.77s/it]
  iters:  88%|████████▊ | 177/200 [05:21<00:40,  1.76s/it]
  iters:  89%|████████▉ | 178/200 [05:23<00:38,  1.76s/it]
  iters:  90%|████████▉ | 179/200 [05:25<00:38,  1.83s/it]
  iters:  90%|█████████ | 180/200 [05:27<00:36,  1.80s/it]
  iters:  90%|█████████ | 181/200 [05:28<00:33,  1.78s/it]
  iters:  91%|█████████ | 182/200 [05:30<00:33,  1.84s/it]
  iters:  92%|█████████▏| 183/200 [05:32<00:30,  1.81s/it]
  iters:  92%|█████████▏| 184/200 [05:34<00:28,  1.79s/it]
  iters:  92%|█████████▎| 185/200 [05:35<00:26,  1.77s/it]
  iters:  93%|█████████▎| 186/200 [05:37<00:24,  1.78s/it]
  iters:  94%|█████████▎| 187/200 [05:39<00:23,  1.77s/it]
  iters:  94%|█████████▍| 188/200 [05:41<00:21,  1.76s/it]
  iters:  94%|█████████▍| 189/200 [05:43<00:19,  1.77s/it]
  iters:  95%|█████████▌| 190/200 [05:44<00:17,  1.75s/it]
  iters:  96%|█████████▌| 191/200 [05:46<00:15,  1.76s/it]
  iters:  96%|█████████▌| 192/200 [05:48<00:14,  1.76s/it]
  iters:  96%|█████████▋| 193/200 [05:50<00:12,  1.76s/it]
  iters:  97%|█████████▋| 194/200 [05:51<00:10,  1.76s/it]
  iters:  98%|█████████▊| 195/200 [05:53<00:08,  1.75s/it]
  iters:  98%|█████████▊| 196/200 [05:55<00:07,  1.75s/it]
  iters:  98%|█████████▊| 197/200 [05:57<00:05,  1.74s/it]
  iters:  99%|█████████▉| 198/200 [05:58<00:03,  1.74s/it]
  iters: 100%|█████████▉| 199/200 [06:00<00:01,  1.74s/it]
  iters: 100%|██████████| 200/200 [06:02<00:00,  1.73s/it]

  [timing] data: 2.3s (1%) | forward: 88.7s (25%) | backward: 271.1s (75%) | total: 362.2s

Training:  50%|█████     | 2/4 [19:44<13:11, 395.85s/it, acc=0.9989, det=0.0063, edge=0.0007]

  Epoch   2/4 | edge=0.0007 | det=0.0063 | test_loss=0.0012 | acc=0.9989 | recall=0.8462 | best=0.9172   | train=362.4s test=31.0s

Training:  75%|███████▌  | 3/4 [19:44<06:34, 394.76s/it, acc=0.9989, det=0.0063, edge=0.0007]
  iters:   0%|          | 0/200 [00:00<?, ?it/s]
  iters:   0%|          | 1/200 [00:02<06:49,  2.06s/it]
  iters:   1%|          | 2/200 [00:04<06:53,  2.09s/it]
  iters:   2%|▏         | 3/200 [00:06<06:48,  2.07s/it]
  iters:   2%|▏         | 4/200 [00:07<06:20,  1.94s/it]
  iters:   2%|▎         | 5/200 [00:09<06:04,  1.87s/it]
  iters:   3%|▎         | 6/200 [00:11<05:54,  1.82s/it]
  iters:   4%|▎         | 7/200 [00:13<05:46,  1.80s/it]
  iters:   4%|▍         | 8/200 [00:14<05:41,  1.78s/it]
  iters:   4%|▍         | 9/200 [00:16<05:37,  1.77s/it]
  iters:   5%|▌         | 10/200 [00:18<05:34,  1.76s/it]
  iters:   6%|▌         | 11/200 [00:20<05:32,  1.76s/it]
  iters:   6%|▌         | 12/200 [00:22<05:39,  1.80s/it]
  iters:   6%|▋         | 13/200 [00:24<06:00,  1.93s/it]
  iters:   7%|▋         | 14/200 [00:26<05:47,  1.87s/it]
  iters:   8%|▊         | 15/200 [00:27<05:38,  1.83s/it]
  iters:   8%|▊         | 16/200 [00:29<05:31,  1.80s/it]
  iters:   8%|▊         | 17/200 [00:31<05:26,  1.79s/it]
  iters:   9%|▉         | 18/200 [00:33<05:44,  1.89s/it]
  iters:  10%|▉         | 19/200 [00:35<05:34,  1.85s/it]
  iters:  10%|█         | 20/200 [00:36<05:27,  1.82s/it]
  iters:  10%|█         | 21/200 [00:38<05:20,  1.79s/it]
  iters:  11%|█         | 22/200 [00:40<05:15,  1.77s/it]
  iters:  12%|█▏        | 23/200 [00:42<05:12,  1.77s/it]
  iters:  12%|█▏        | 24/200 [00:44<05:23,  1.84s/it]
  iters:  12%|█▎        | 25/200 [00:45<05:17,  1.81s/it]
  iters:  13%|█▎        | 26/200 [00:48<05:38,  1.94s/it]
  iters:  14%|█▎        | 27/200 [00:50<05:40,  1.97s/it]
  iters:  14%|█▍        | 28/200 [00:51<05:30,  1.92s/it]
  iters:  14%|█▍        | 29/200 [00:53<05:22,  1.88s/it]
  iters:  15%|█▌        | 30/200 [00:55<05:28,  1.93s/it]
  iters:  16%|█▌        | 31/200 [00:57<05:17,  1.88s/it]
  iters:  16%|█▌        | 32/200 [00:59<05:07,  1.83s/it]
  iters:  16%|█▋        | 33/200 [01:01<05:23,  1.94s/it]
  iters:  17%|█▋        | 34/200 [01:03<05:12,  1.88s/it]
  iters:  18%|█▊        | 35/200 [01:04<05:03,  1.84s/it]
  iters:  18%|█▊        | 36/200 [01:06<05:02,  1.85s/it]
  iters:  18%|█▊        | 37/200 [01:08<04:55,  1.81s/it]
  iters:  19%|█▉        | 38/200 [01:10<04:49,  1.79s/it]
  iters:  20%|█▉        | 39/200 [01:12<04:45,  1.77s/it]
  iters:  20%|██        | 40/200 [01:13<04:42,  1.77s/it]
  iters:  20%|██        | 41/200 [01:15<04:39,  1.76s/it]
  iters:  21%|██        | 42/200 [01:17<04:36,  1.75s/it]
  iters:  22%|██▏       | 43/200 [01:19<04:46,  1.83s/it]
  iters:  22%|██▏       | 44/200 [01:20<04:41,  1.81s/it]
  iters:  22%|██▎       | 45/200 [01:22<04:37,  1.79s/it]
  iters:  23%|██▎       | 46/200 [01:24<04:34,  1.78s/it]
  iters:  24%|██▎       | 47/200 [01:26<04:37,  1.82s/it]
  iters:  24%|██▍       | 48/200 [01:28<04:31,  1.79s/it]
  iters:  24%|██▍       | 49/200 [01:29<04:29,  1.79s/it]
  iters:  25%|██▌       | 50/200 [01:31<04:25,  1.77s/it]
  iters:  26%|██▌       | 51/200 [01:33<04:21,  1.76s/it]
  iters:  26%|██▌       | 52/200 [01:35<04:18,  1.75s/it]
  iters:  26%|██▋       | 53/200 [01:36<04:15,  1.74s/it]
  iters:  27%|██▋       | 54/200 [01:38<04:14,  1.74s/it]
  iters:  28%|██▊       | 55/200 [01:40<04:11,  1.74s/it]
  iters:  28%|██▊       | 56/200 [01:42<04:10,  1.74s/it]
  iters:  28%|██▊       | 57/200 [01:43<04:08,  1.73s/it]
  iters:  29%|██▉       | 58/200 [01:45<04:06,  1.74s/it]
  iters:  30%|██▉       | 59/200 [01:47<04:04,  1.74s/it]
  iters:  30%|███       | 60/200 [01:48<04:03,  1.74s/it]
  iters:  30%|███       | 61/200 [01:50<04:07,  1.78s/it]
  iters:  31%|███       | 62/200 [01:52<04:03,  1.77s/it]
  iters:  32%|███▏      | 63/200 [01:54<04:00,  1.75s/it]
  iters:  32%|███▏      | 64/200 [01:56<03:57,  1.75s/it]
  iters:  32%|███▎      | 65/200 [01:57<03:58,  1.77s/it]
  iters:  33%|███▎      | 66/200 [01:59<03:55,  1.76s/it]
  iters:  34%|███▎      | 67/200 [02:01<03:55,  1.77s/it]
  iters:  34%|███▍      | 68/200 [02:03<03:51,  1.76s/it]
  iters:  34%|███▍      | 69/200 [02:04<03:48,  1.75s/it]
  iters:  35%|███▌      | 70/200 [02:06<03:46,  1.74s/it]
  iters:  36%|███▌      | 71/200 [02:08<03:45,  1.75s/it]
  iters:  36%|███▌      | 72/200 [02:10<03:44,  1.75s/it]
  iters:  36%|███▋      | 73/200 [02:12<03:58,  1.88s/it]
  iters:  37%|███▋      | 74/200 [02:13<03:51,  1.84s/it]
  iters:  38%|███▊      | 75/200 [02:16<03:57,  1.90s/it]
  iters:  38%|███▊      | 76/200 [02:17<03:49,  1.85s/it]
  iters:  38%|███▊      | 77/200 [02:19<03:52,  1.89s/it]
  iters:  39%|███▉      | 78/200 [02:21<03:44,  1.84s/it]
  iters:  40%|███▉      | 79/200 [02:23<03:39,  1.81s/it]
  iters:  40%|████      | 80/200 [02:24<03:35,  1.79s/it]
  iters:  40%|████      | 81/200 [02:26<03:31,  1.78s/it]
  iters:  41%|████      | 82/200 [02:28<03:28,  1.77s/it]
  iters:  42%|████▏     | 83/200 [02:30<03:26,  1.76s/it]
  iters:  42%|████▏     | 84/200 [02:31<03:23,  1.75s/it]
  iters:  42%|████▎     | 85/200 [02:33<03:24,  1.78s/it]
  iters:  43%|████▎     | 86/200 [02:35<03:21,  1.77s/it]
  iters:  44%|████▎     | 87/200 [02:37<03:29,  1.85s/it]
  iters:  44%|████▍     | 88/200 [02:39<03:23,  1.82s/it]
  iters:  44%|████▍     | 89/200 [02:41<03:19,  1.80s/it]
  iters:  45%|████▌     | 90/200 [02:43<03:23,  1.85s/it]
  iters:  46%|████▌     | 91/200 [02:44<03:18,  1.82s/it]
  iters:  46%|████▌     | 92/200 [02:46<03:14,  1.80s/it]
  iters:  46%|████▋     | 93/200 [02:48<03:12,  1.80s/it]
  iters:  47%|████▋     | 94/200 [02:50<03:08,  1.77s/it]
  iters:  48%|████▊     | 95/200 [02:51<03:06,  1.78s/it]
  iters:  48%|████▊     | 96/200 [02:53<03:03,  1.77s/it]
  iters:  48%|████▊     | 97/200 [02:55<03:08,  1.83s/it]
  iters:  49%|████▉     | 98/200 [02:57<03:04,  1.80s/it]
  iters:  50%|████▉     | 99/200 [02:59<03:07,  1.85s/it]
  iters:  50%|█████     | 100/200 [03:01<03:02,  1.82s/it]
  iters:  50%|█████     | 101/200 [03:02<03:00,  1.83s/it]
  iters:  51%|█████     | 102/200 [03:04<03:00,  1.84s/it]
  iters:  52%|█████▏    | 103/200 [03:06<02:56,  1.82s/it]
  iters:  52%|█████▏    | 104/200 [03:08<02:52,  1.80s/it]
  iters:  52%|█████▎    | 105/200 [03:10<02:49,  1.79s/it]
  iters:  53%|█████▎    | 106/200 [03:11<02:46,  1.78s/it]
  iters:  54%|█████▎    | 107/200 [03:13<02:44,  1.77s/it]
  iters:  54%|█████▍    | 108/200 [03:15<02:42,  1.77s/it]
  iters:  55%|█████▍    | 109/200 [03:17<02:39,  1.76s/it]
  iters:  55%|█████▌    | 110/200 [03:18<02:37,  1.75s/it]
  iters:  56%|█████▌    | 111/200 [03:20<02:35,  1.75s/it]
  iters:  56%|█████▌    | 112/200 [03:22<02:33,  1.75s/it]
  iters:  56%|█████▋    | 113/200 [03:24<02:33,  1.76s/it]
  iters:  57%|█████▋    | 114/200 [03:25<02:35,  1.81s/it]
  iters:  57%|█████▊    | 115/200 [03:27<02:32,  1.79s/it]
  iters:  58%|█████▊    | 116/200 [03:29<02:29,  1.78s/it]
  iters:  58%|█████▊    | 117/200 [03:31<02:39,  1.92s/it]
  iters:  59%|█████▉    | 118/200 [03:33<02:37,  1.92s/it]
  iters:  60%|█████▉    | 119/200 [03:35<02:30,  1.86s/it]
  iters:  60%|██████    | 120/200 [03:37<02:25,  1.82s/it]
  iters:  60%|██████    | 121/200 [03:38<02:21,  1.79s/it]
  iters:  61%|██████    | 122/200 [03:40<02:23,  1.84s/it]
  iters:  62%|██████▏   | 123/200 [03:42<02:18,  1.80s/it]
  iters:  62%|██████▏   | 124/200 [03:44<02:15,  1.79s/it]
  iters:  62%|██████▎   | 125/200 [03:46<02:21,  1.89s/it]
  iters:  63%|██████▎   | 126/200 [03:48<02:16,  1.84s/it]
  iters:  64%|██████▎   | 127/200 [03:49<02:13,  1.83s/it]
  iters:  64%|██████▍   | 128/200 [03:51<02:09,  1.80s/it]
  iters:  64%|██████▍   | 129/200 [03:53<02:06,  1.78s/it]
  iters:  65%|██████▌   | 130/200 [03:55<02:03,  1.77s/it]
  iters:  66%|██████▌   | 131/200 [03:57<02:06,  1.83s/it]
  iters:  66%|██████▌   | 132/200 [03:58<02:02,  1.80s/it]
  iters:  66%|██████▋   | 133/200 [04:00<01:59,  1.78s/it]
  iters:  67%|██████▋   | 134/200 [04:02<01:56,  1.77s/it]
  iters:  68%|██████▊   | 135/200 [04:04<01:56,  1.79s/it]
  iters:  68%|██████▊   | 136/200 [04:05<01:53,  1.77s/it]
  iters:  68%|██████▊   | 137/200 [04:07<01:51,  1.77s/it]
  iters:  69%|██████▉   | 138/200 [04:09<01:53,  1.84s/it]
  iters:  70%|██████▉   | 139/200 [04:11<01:51,  1.82s/it]
  iters:  70%|███████   | 140/200 [04:13<01:48,  1.80s/it]
  iters:  70%|███████   | 141/200 [04:14<01:46,  1.81s/it]
  iters:  71%|███████   | 142/200 [04:16<01:43,  1.79s/it]
  iters:  72%|███████▏  | 143/200 [04:18<01:41,  1.78s/it]
  iters:  72%|███████▏  | 144/200 [04:20<01:45,  1.88s/it]
  iters:  72%|███████▎  | 145/200 [04:22<01:43,  1.87s/it]
  iters:  73%|███████▎  | 146/200 [04:24<01:39,  1.84s/it]
  iters:  74%|███████▎  | 147/200 [04:25<01:35,  1.81s/it]
  iters:  74%|███████▍  | 148/200 [04:27<01:32,  1.79s/it]
  iters:  74%|███████▍  | 149/200 [04:29<01:30,  1.77s/it]
  iters:  75%|███████▌  | 150/200 [04:31<01:28,  1.76s/it]
  iters:  76%|███████▌  | 151/200 [04:33<01:28,  1.81s/it]
  iters:  76%|███████▌  | 152/200 [04:34<01:25,  1.78s/it]
  iters:  76%|███████▋  | 153/200 [04:36<01:23,  1.77s/it]
  iters:  77%|███████▋  | 154/200 [04:38<01:21,  1.77s/it]
  iters:  78%|███████▊  | 155/200 [04:40<01:19,  1.76s/it]
  iters:  78%|███████▊  | 156/200 [04:41<01:17,  1.76s/it]
  iters:  78%|███████▊  | 157/200 [04:43<01:15,  1.76s/it]
  iters:  79%|███████▉  | 158/200 [04:45<01:16,  1.81s/it]
  iters:  80%|███████▉  | 159/200 [04:47<01:13,  1.79s/it]
  iters:  80%|████████  | 160/200 [04:48<01:10,  1.77s/it]
  iters:  80%|████████  | 161/200 [04:50<01:08,  1.76s/it]
  iters:  81%|████████  | 162/200 [04:52<01:06,  1.76s/it]
  iters:  82%|████████▏ | 163/200 [04:54<01:04,  1.75s/it]
  iters:  82%|████████▏ | 164/200 [04:55<01:03,  1.75s/it]
  iters:  82%|████████▎ | 165/200 [04:57<01:01,  1.74s/it]
  iters:  83%|████████▎ | 166/200 [04:59<00:59,  1.75s/it]
  iters:  84%|████████▎ | 167/200 [05:01<00:59,  1.82s/it]
  iters:  84%|████████▍ | 168/200 [05:03<00:57,  1.79s/it]
  iters:  84%|████████▍ | 169/200 [05:05<00:59,  1.92s/it]
  iters:  85%|████████▌ | 170/200 [05:07<00:59,  1.98s/it]
  iters:  86%|████████▌ | 171/200 [05:09<00:55,  1.91s/it]
  iters:  86%|████████▌ | 172/200 [05:10<00:51,  1.86s/it]
  iters:  86%|████████▋ | 173/200 [05:12<00:49,  1.82s/it]
  iters:  87%|████████▋ | 174/200 [05:14<00:48,  1.88s/it]
  iters:  88%|████████▊ | 175/200 [05:16<00:49,  1.98s/it]
  iters:  88%|████████▊ | 176/200 [05:19<00:48,  2.04s/it]
  iters:  88%|████████▊ | 177/200 [05:20<00:45,  1.98s/it]
  iters:  89%|████████▉ | 178/200 [05:22<00:42,  1.92s/it]
  iters:  90%|████████▉ | 179/200 [05:24<00:42,  2.01s/it]
  iters:  90%|█████████ | 180/200 [05:26<00:38,  1.92s/it]
  iters:  90%|█████████ | 181/200 [05:28<00:35,  1.87s/it]
  iters:  91%|█████████ | 182/200 [05:30<00:33,  1.87s/it]
  iters:  92%|█████████▏| 183/200 [05:32<00:31,  1.83s/it]
  iters:  92%|█████████▏| 184/200 [05:33<00:28,  1.81s/it]
  iters:  92%|█████████▎| 185/200 [05:35<00:26,  1.79s/it]
  iters:  93%|█████████▎| 186/200 [05:37<00:24,  1.78s/it]
  iters:  94%|█████████▎| 187/200 [05:39<00:23,  1.77s/it]
  iters:  94%|█████████▍| 188/200 [05:41<00:22,  1.91s/it]
  iters:  94%|█████████▍| 189/200 [05:42<00:20,  1.86s/it]
  iters:  95%|█████████▌| 190/200 [05:44<00:18,  1.82s/it]
  iters:  96%|█████████▌| 191/200 [05:46<00:16,  1.80s/it]
  iters:  96%|█████████▌| 192/200 [05:48<00:14,  1.86s/it]
  iters:  96%|█████████▋| 193/200 [05:50<00:12,  1.83s/it]
  iters:  97%|█████████▋| 194/200 [05:52<00:11,  1.94s/it]
  iters:  98%|█████████▊| 195/200 [05:54<00:10,  2.01s/it]
  iters:  98%|█████████▊| 196/200 [05:56<00:07,  1.94s/it]
  iters:  98%|█████████▊| 197/200 [05:58<00:05,  1.87s/it]
  iters:  99%|█████████▉| 198/200 [06:00<00:03,  1.90s/it]
  iters: 100%|█████████▉| 199/200 [06:02<00:01,  1.98s/it]
  iters: 100%|██████████| 200/200 [06:04<00:00,  1.91s/it]

  [timing] data: 2.3s (1%) | forward: 89.5s (25%) | backward: 272.1s (75%) | total: 364.0s

Training:  75%|███████▌  | 3/4 [26:20<06:34, 394.76s/it, acc=0.9989, det=0.0070, edge=0.0006]

  Epoch   3/4 | edge=0.0006 | det=0.0070 | test_loss=0.0015 | acc=0.9989 | recall=0.8452 | best=0.9172   | train=364.2s test=31.0s

Training: 100%|██████████| 4/4 [26:20<00:00, 395.05s/it, acc=0.9989, det=0.0070, edge=0.0006]

Best score (acc*recall): 0.9172, saved to /kaggle/working/cellmot-baseline-artifacts/repo/weights/hp_search_tier1/split_0/edge_predictor_best.pth

[tier2_001] score=0.9172  (1587s)
0.019136512 GB allocated
0.205520896 GB reserved
Fold 0: 8 train, 2 test
Loading train (8 datasets)...

train: 100%|██████████| 8/8 [00:05<00:00,  1.57it/s]

  train done: 779 windows total
Loading test (2 datasets)...

test: 100%|██████████| 2/2 [00:00<00:00,  2.16it/s]

  test done: 161 windows total
max_nodes=17
Using device: cuda | visible CUDA GPUs: 2
  Full checkpoint loaded from /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/weights/unet_transformer/split_0/edge_predictor_best.pth: 0 missing, 0 unexpected
Single-GPU training (--single-gpu set). For 2 GPUs set the Kaggle accelerator to 'GPU T4 x2'.
Model parameters: 2,076,706
Starting training for 4 epochs (batch_size=2)...

Training:   0%|          | 0/4 [00:00<?, ?it/s]

Detection loss: weight=4, neg_weight=0.01

  iters:   0%|          | 0/200 [00:00<?, ?it/s]
  iters:   0%|          | 1/200 [00:02<07:01,  2.12s/it]
  iters:   1%|          | 2/200 [00:03<06:11,  1.87s/it]
  iters:   2%|▏         | 3/200 [00:05<05:53,  1.80s/it]
  iters:   2%|▏         | 4/200 [00:07<05:44,  1.76s/it]
  iters:   2%|▎         | 5/200 [00:08<05:39,  1.74s/it]
  iters:   3%|▎         | 6/200 [00:10<05:30,  1.71s/it]
  iters:   4%|▎         | 7/200 [00:12<05:31,  1.72s/it]
  iters:   4%|▍         | 8/200 [00:14<05:30,  1.72s/it]
  iters:   4%|▍         | 9/200 [00:15<05:30,  1.73s/it]
  iters:   5%|▌         | 10/200 [00:17<05:29,  1.73s/it]
  iters:   6%|▌         | 11/200 [00:19<05:28,  1.74s/it]
  iters:   6%|▌         | 12/200 [00:21<05:28,  1.75s/it]
  iters:   6%|▋         | 13/200 [00:22<05:27,  1.75s/it]
  iters:   7%|▋         | 14/200 [00:24<05:26,  1.76s/it]
  iters:   8%|▊         | 15/200 [00:26<05:25,  1.76s/it]
  iters:   8%|▊         | 16/200 [00:28<05:25,  1.77s/it]
  iters:   8%|▊         | 17/200 [00:29<05:23,  1.77s/it]
  iters:   9%|▉         | 18/200 [00:31<05:16,  1.74s/it]
  iters:  10%|▉         | 19/200 [00:33<05:16,  1.75s/it]
  iters:  10%|█         | 20/200 [00:35<05:15,  1.75s/it]
  iters:  10%|█         | 21/200 [00:36<05:13,  1.75s/it]
  iters:  11%|█         | 22/200 [00:38<05:11,  1.75s/it]
  iters:  12%|█▏        | 23/200 [00:40<05:09,  1.75s/it]
  iters:  12%|█▏        | 24/200 [00:42<05:07,  1.75s/it]
  iters:  12%|█▎        | 25/200 [00:43<05:05,  1.75s/it]
  iters:  13%|█▎        | 26/200 [00:45<05:03,  1.75s/it]
  iters:  14%|█▎        | 27/200 [00:47<05:01,  1.75s/it]
  iters:  14%|█▍        | 28/200 [00:49<04:59,  1.74s/it]
  iters:  14%|█▍        | 29/200 [00:50<04:57,  1.74s/it]
  iters:  15%|█▌        | 30/200 [00:52<04:51,  1.71s/it]
  iters:  16%|█▌        | 31/200 [00:54<04:50,  1.72s/it]
  iters:  16%|█▌        | 32/200 [00:55<04:50,  1.73s/it]
  iters:  16%|█▋        | 33/200 [00:57<04:44,  1.70s/it]
  iters:  17%|█▋        | 34/200 [00:59<04:43,  1.71s/it]
  iters:  18%|█▊        | 35/200 [01:01<04:42,  1.71s/it]
  iters:  18%|█▊        | 36/200 [01:02<04:41,  1.72s/it]
  iters:  18%|█▊        | 37/200 [01:04<04:40,  1.72s/it]
  iters:  19%|█▉        | 38/200 [01:06<04:39,  1.72s/it]
  iters:  20%|█▉        | 39/200 [01:07<04:37,  1.72s/it]
  iters:  20%|██        | 40/200 [01:09<04:35,  1.72s/it]
  iters:  20%|██        | 41/200 [01:11<04:33,  1.72s/it]
  iters:  21%|██        | 42/200 [01:13<04:31,  1.72s/it]
  iters:  22%|██▏       | 43/200 [01:14<04:29,  1.72s/it]
  iters:  22%|██▏       | 44/200 [01:16<04:27,  1.72s/it]
  iters:  22%|██▎       | 45/200 [01:18<04:26,  1.72s/it]
  iters:  23%|██▎       | 46/200 [01:19<04:24,  1.72s/it]
  iters:  24%|██▎       | 47/200 [01:21<04:23,  1.72s/it]
  iters:  24%|██▍       | 48/200 [01:23<04:21,  1.72s/it]
  iters:  24%|██▍       | 49/200 [01:25<04:19,  1.72s/it]
  iters:  25%|██▌       | 50/200 [01:26<04:17,  1.72s/it]
  iters:  26%|██▌       | 51/200 [01:28<04:15,  1.72s/it]
  iters:  26%|██▌       | 52/200 [01:30<04:14,  1.72s/it]
  iters:  26%|██▋       | 53/200 [01:31<04:12,  1.72s/it]
  iters:  27%|██▋       | 54/200 [01:33<04:11,  1.72s/it]
  iters:  28%|██▊       | 55/200 [01:35<04:09,  1.72s/it]
  iters:  28%|██▊       | 56/200 [01:37<04:04,  1.70s/it]
  iters:  28%|██▊       | 57/200 [01:38<04:04,  1.71s/it]
  iters:  29%|██▉       | 58/200 [01:40<04:03,  1.72s/it]
  iters:  30%|██▉       | 59/200 [01:42<04:02,  1.72s/it]
  iters:  30%|███       | 60/200 [01:44<04:01,  1.72s/it]
  iters:  30%|███       | 61/200 [01:45<03:59,  1.72s/it]
  iters:  31%|███       | 62/200 [01:47<03:58,  1.73s/it]
  iters:  32%|███▏      | 63/200 [01:49<03:56,  1.73s/it]
  iters:  32%|███▏      | 64/200 [01:50<03:55,  1.73s/it]
  iters:  32%|███▎      | 65/200 [01:52<03:53,  1.73s/it]
  iters:  33%|███▎      | 66/200 [01:54<03:52,  1.74s/it]
  iters:  34%|███▎      | 67/200 [01:56<03:51,  1.74s/it]
  iters:  34%|███▍      | 68/200 [01:57<03:50,  1.74s/it]
  iters:  34%|███▍      | 69/200 [01:59<03:48,  1.74s/it]
  iters:  35%|███▌      | 70/200 [02:01<03:46,  1.74s/it]
  iters:  36%|███▌      | 71/200 [02:03<03:44,  1.74s/it]
  iters:  36%|███▌      | 72/200 [02:04<03:42,  1.74s/it]
  iters:  36%|███▋      | 73/200 [02:06<03:40,  1.74s/it]
  iters:  37%|███▋      | 74/200 [02:08<03:39,  1.74s/it]
  iters:  38%|███▊      | 75/200 [02:10<03:37,  1.74s/it]
  iters:  38%|███▊      | 76/200 [02:11<03:35,  1.74s/it]
  iters:  38%|███▊      | 77/200 [02:13<03:34,  1.74s/it]
  iters:  39%|███▉      | 78/200 [02:15<03:32,  1.74s/it]
  iters:  40%|███▉      | 79/200 [02:17<03:30,  1.74s/it]
  iters:  40%|████      | 80/200 [02:18<03:27,  1.73s/it]
  iters:  40%|████      | 81/200 [02:20<03:26,  1.73s/it]
  iters:  41%|████      | 82/200 [02:22<03:22,  1.72s/it]
  iters:  42%|████▏     | 83/200 [02:23<03:21,  1.72s/it]
  iters:  42%|████▏     | 84/200 [02:25<03:20,  1.73s/it]
  iters:  42%|████▎     | 85/200 [02:27<03:19,  1.73s/it]
  iters:  43%|████▎     | 86/200 [02:29<03:17,  1.73s/it]
  iters:  44%|████▎     | 87/200 [02:30<03:15,  1.73s/it]
  iters:  44%|████▍     | 88/200 [02:32<03:20,  1.79s/it]
  iters:  44%|████▍     | 89/200 [02:34<03:16,  1.77s/it]
  iters:  45%|████▌     | 90/200 [02:36<03:14,  1.76s/it]
  iters:  46%|████▌     | 91/200 [02:38<03:11,  1.76s/it]
  iters:  46%|████▌     | 92/200 [02:39<03:08,  1.75s/it]
  iters:  46%|████▋     | 93/200 [02:41<03:06,  1.74s/it]
  iters:  47%|████▋     | 94/200 [02:43<03:04,  1.74s/it]
  iters:  48%|████▊     | 95/200 [02:44<03:02,  1.74s/it]
  iters:  48%|████▊     | 96/200 [02:46<03:00,  1.73s/it]
  iters:  48%|████▊     | 97/200 [02:48<02:58,  1.73s/it]
  iters:  49%|████▉     | 98/200 [02:50<02:56,  1.73s/it]
  iters:  50%|████▉     | 99/200 [02:51<02:53,  1.72s/it]
  iters:  50%|█████     | 100/200 [02:53<02:52,  1.73s/it]
  iters:  50%|█████     | 101/200 [02:55<02:50,  1.73s/it]
  iters:  51%|█████     | 102/200 [02:57<02:49,  1.73s/it]
  iters:  52%|█████▏    | 103/200 [02:58<02:47,  1.73s/it]
  iters:  52%|█████▏    | 104/200 [03:00<02:45,  1.73s/it]
  iters:  52%|█████▎    | 105/200 [03:02<02:43,  1.73s/it]
  iters:  53%|█████▎    | 106/200 [03:03<02:42,  1.73s/it]
  iters:  54%|█████▎    | 107/200 [03:05<02:40,  1.73s/it]
  iters:  54%|█████▍    | 108/200 [03:07<02:38,  1.72s/it]
  iters:  55%|█████▍    | 109/200 [03:09<02:36,  1.72s/it]
  iters:  55%|█████▌    | 110/200 [03:10<02:34,  1.72s/it]
  iters:  56%|█████▌    | 111/200 [03:12<02:33,  1.72s/it]
  iters:  56%|█████▌    | 112/200 [03:14<02:31,  1.73s/it]
  iters:  56%|█████▋    | 113/200 [03:15<02:30,  1.73s/it]
  iters:  57%|█████▋    | 114/200 [03:17<02:28,  1.73s/it]
  iters:  57%|█████▊    | 115/200 [03:19<02:26,  1.72s/it]
  iters:  58%|█████▊    | 116/200 [03:21<02:24,  1.72s/it]
  iters:  58%|█████▊    | 117/200 [03:22<02:23,  1.72s/it]
  iters:  59%|█████▉    | 118/200 [03:24<02:19,  1.70s/it]
  iters:  60%|█████▉    | 119/200 [03:26<02:18,  1.71s/it]
  iters:  60%|██████    | 120/200 [03:27<02:17,  1.72s/it]
  iters:  60%|██████    | 121/200 [03:29<02:15,  1.72s/it]
  iters:  61%|██████    | 122/200 [03:31<02:14,  1.72s/it]
  iters:  62%|██████▏   | 123/200 [03:33<02:12,  1.72s/it]
  iters:  62%|██████▏   | 124/200 [03:34<02:11,  1.73s/it]
  iters:  62%|██████▎   | 125/200 [03:36<02:09,  1.73s/it]
  iters:  63%|██████▎   | 126/200 [03:38<02:07,  1.73s/it]
  iters:  64%|██████▎   | 127/200 [03:40<02:06,  1.73s/it]
  iters:  64%|██████▍   | 128/200 [03:41<02:04,  1.73s/it]
  iters:  64%|██████▍   | 129/200 [03:43<02:02,  1.73s/it]
  iters:  65%|██████▌   | 130/200 [03:45<02:00,  1.72s/it]
  iters:  66%|██████▌   | 131/200 [03:46<01:58,  1.72s/it]
  iters:  66%|██████▌   | 132/200 [03:48<01:57,  1.72s/it]
  iters:  66%|██████▋   | 133/200 [03:50<01:55,  1.73s/it]
  iters:  67%|██████▋   | 134/200 [03:52<01:54,  1.73s/it]
  iters:  68%|██████▊   | 135/200 [03:53<01:52,  1.73s/it]
  iters:  68%|██████▊   | 136/200 [03:55<01:50,  1.73s/it]
  iters:  68%|██████▊   | 137/200 [03:57<01:48,  1.73s/it]
  iters:  69%|██████▉   | 138/200 [03:59<01:47,  1.73s/it]
  iters:  70%|██████▉   | 139/200 [04:00<01:43,  1.70s/it]
  iters:  70%|███████   | 140/200 [04:02<01:42,  1.71s/it]
  iters:  70%|███████   | 141/200 [04:04<01:41,  1.71s/it]
  iters:  71%|███████   | 142/200 [04:05<01:39,  1.72s/it]
  iters:  72%|███████▏  | 143/200 [04:07<01:38,  1.72s/it]
  iters:  72%|███████▏  | 144/200 [04:09<01:36,  1.73s/it]
  iters:  72%|███████▎  | 145/200 [04:11<01:34,  1.73s/it]
  iters:  73%|███████▎  | 146/200 [04:12<01:33,  1.73s/it]
  iters:  74%|███████▎  | 147/200 [04:14<01:31,  1.73s/it]
  iters:  74%|███████▍  | 148/200 [04:16<01:30,  1.74s/it]
  iters:  74%|███████▍  | 149/200 [04:18<01:28,  1.74s/it]
  iters:  75%|███████▌  | 150/200 [04:19<01:26,  1.73s/it]
  iters:  76%|███████▌  | 151/200 [04:21<01:25,  1.74s/it]
  iters:  76%|███████▌  | 152/200 [04:23<01:23,  1.73s/it]
  iters:  76%|███████▋  | 153/200 [04:24<01:21,  1.73s/it]
  iters:  77%|███████▋  | 154/200 [04:26<01:19,  1.73s/it]
  iters:  78%|███████▊  | 155/200 [04:28<01:17,  1.73s/it]
  iters:  78%|███████▊  | 156/200 [04:30<01:16,  1.73s/it]
  iters:  78%|███████▊  | 157/200 [04:31<01:13,  1.70s/it]
  iters:  79%|███████▉  | 158/200 [04:33<01:11,  1.71s/it]
  iters:  80%|███████▉  | 159/200 [04:35<01:10,  1.72s/it]
  iters:  80%|████████  | 160/200 [04:36<01:08,  1.72s/it]
  iters:  80%|████████  | 161/200 [04:38<01:07,  1.72s/it]
  iters:  81%|████████  | 162/200 [04:40<01:05,  1.73s/it]
  iters:  82%|████████▏ | 163/200 [04:42<01:03,  1.73s/it]
  iters:  82%|████████▏ | 164/200 [04:43<01:02,  1.73s/it]
  iters:  82%|████████▎ | 165/200 [04:45<01:00,  1.73s/it]
  iters:  83%|████████▎ | 166/200 [04:47<00:57,  1.70s/it]
  iters:  84%|████████▎ | 167/200 [04:48<00:55,  1.68s/it]
  iters:  84%|████████▍ | 168/200 [04:50<00:54,  1.70s/it]
  iters:  84%|████████▍ | 169/200 [04:52<00:52,  1.71s/it]
  iters:  85%|████████▌ | 170/200 [04:54<00:51,  1.71s/it]
  iters:  86%|████████▌ | 171/200 [04:55<00:49,  1.71s/it]
  iters:  86%|████████▌ | 172/200 [04:57<00:48,  1.72s/it]
  iters:  86%|████████▋ | 173/200 [04:59<00:46,  1.72s/it]
  iters:  87%|████████▋ | 174/200 [05:00<00:44,  1.72s/it]
  iters:  88%|████████▊ | 175/200 [05:02<00:43,  1.72s/it]
  iters:  88%|████████▊ | 176/200 [05:04<00:41,  1.72s/it]
  iters:  88%|████████▊ | 177/200 [05:06<00:39,  1.72s/it]
  iters:  89%|████████▉ | 178/200 [05:07<00:37,  1.72s/it]
  iters:  90%|████████▉ | 179/200 [05:09<00:36,  1.72s/it]
  iters:  90%|█████████ | 180/200 [05:11<00:34,  1.72s/it]
  iters:  90%|█████████ | 181/200 [05:13<00:32,  1.72s/it]
  iters:  91%|█████████ | 182/200 [05:14<00:31,  1.73s/it]
  iters:  92%|█████████▏| 183/200 [05:16<00:29,  1.73s/it]
  iters:  92%|█████████▏| 184/200 [05:18<00:27,  1.72s/it]
  iters:  92%|█████████▎| 185/200 [05:19<00:25,  1.73s/it]
  iters:  93%|█████████▎| 186/200 [05:21<00:24,  1.73s/it]
  iters:  94%|█████████▎| 187/200 [05:23<00:22,  1.72s/it]
  iters:  94%|█████████▍| 188/200 [05:25<00:20,  1.73s/it]
  iters:  94%|█████████▍| 189/200 [05:26<00:18,  1.73s/it]
  iters:  95%|█████████▌| 190/200 [05:28<00:17,  1.73s/it]
  iters:  96%|█████████▌| 191/200 [05:30<00:15,  1.73s/it]
  iters:  96%|█████████▌| 192/200 [05:32<00:13,  1.73s/it]
  iters:  96%|█████████▋| 193/200 [05:33<00:12,  1.73s/it]
  iters:  97%|█████████▋| 194/200 [05:35<00:10,  1.73s/it]
  iters:  98%|█████████▊| 195/200 [05:37<00:08,  1.73s/it]
  iters:  98%|█████████▊| 196/200 [05:38<00:06,  1.73s/it]
  iters:  98%|█████████▊| 197/200 [05:40<00:05,  1.80s/it]
  iters:  99%|█████████▉| 198/200 [05:42<00:03,  1.78s/it]
  iters: 100%|█████████▉| 199/200 [05:44<00:01,  1.77s/it]
  iters: 100%|██████████| 200/200 [05:46<00:00,  1.76s/it]

  [timing] data: 2.4s (1%) | forward: 86.5s (25%) | backward: 257.2s (74%) | total: 346.1s

Training:   0%|          | 0/4 [06:19<?, ?it/s, acc=0.9993, det=0.0100, edge=0.0010]

  Epoch   0/4 | edge=0.0010 | det=0.0100 | test_loss=0.0008 | acc=0.9993 | recall=0.7877 | best=0.7872 * | train=346.4s test=33.0s

Training:  25%|██▌       | 1/4 [06:19<18:58, 379.39s/it, acc=0.9993, det=0.0100, edge=0.0010]
  iters:   0%|          | 0/200 [00:00<?, ?it/s]
  iters:   0%|          | 1/200 [00:02<06:39,  2.01s/it]
  iters:   1%|          | 2/200 [00:03<06:05,  1.84s/it]
  iters:   2%|▏         | 3/200 [00:05<05:52,  1.79s/it]
  iters:   2%|▏         | 4/200 [00:07<05:38,  1.73s/it]
  iters:   2%|▎         | 5/200 [00:08<05:38,  1.73s/it]
  iters:   3%|▎         | 6/200 [00:10<05:35,  1.73s/it]
  iters:   4%|▎         | 7/200 [00:12<05:33,  1.73s/it]
  iters:   4%|▍         | 8/200 [00:14<05:31,  1.73s/it]
  iters:   4%|▍         | 9/200 [00:15<05:24,  1.70s/it]
  iters:   5%|▌         | 10/200 [00:17<05:23,  1.70s/it]
  iters:   6%|▌         | 11/200 [00:19<05:22,  1.71s/it]
  iters:   6%|▌         | 12/200 [00:20<05:21,  1.71s/it]
  iters:   6%|▋         | 13/200 [00:22<05:20,  1.71s/it]
  iters:   7%|▋         | 14/200 [00:24<05:19,  1.72s/it]
  iters:   8%|▊         | 15/200 [00:25<05:17,  1.72s/it]
  iters:   8%|▊         | 16/200 [00:27<05:16,  1.72s/it]
  iters:   8%|▊         | 17/200 [00:29<05:14,  1.72s/it]
  iters:   9%|▉         | 18/200 [00:31<05:12,  1.72s/it]
  iters:  10%|▉         | 19/200 [00:32<05:11,  1.72s/it]
  iters:  10%|█         | 20/200 [00:34<05:09,  1.72s/it]
  iters:  10%|█         | 21/200 [00:36<05:07,  1.72s/it]
  iters:  11%|█         | 22/200 [00:38<05:06,  1.72s/it]
  iters:  12%|█▏        | 23/200 [00:39<05:04,  1.72s/it]
  iters:  12%|█▏        | 24/200 [00:41<05:02,  1.72s/it]
  iters:  12%|█▎        | 25/200 [00:43<05:01,  1.72s/it]
  iters:  13%|█▎        | 26/200 [00:44<04:59,  1.72s/it]
  iters:  14%|█▎        | 27/200 [00:46<04:58,  1.72s/it]
  iters:  14%|█▍        | 28/200 [00:48<04:56,  1.73s/it]
  iters:  14%|█▍        | 29/200 [00:50<04:55,  1.73s/it]
  iters:  15%|█▌        | 30/200 [00:51<04:53,  1.72s/it]
  iters:  16%|█▌        | 31/200 [00:53<04:51,  1.73s/it]
  iters:  16%|█▌        | 32/200 [00:55<04:49,  1.73s/it]
  iters:  16%|█▋        | 33/200 [00:56<04:48,  1.73s/it]
  iters:  17%|█▋        | 34/200 [00:58<04:46,  1.73s/it]
  iters:  18%|█▊        | 35/200 [01:00<04:45,  1.73s/it]
  iters:  18%|█▊        | 36/200 [01:02<04:43,  1.73s/it]
  iters:  18%|█▊        | 37/200 [01:03<04:37,  1.70s/it]
  iters:  19%|█▉        | 38/200 [01:05<04:36,  1.71s/it]
  iters:  20%|█▉        | 39/200 [01:07<04:31,  1.69s/it]
  iters:  20%|██        | 40/200 [01:08<04:32,  1.70s/it]
  iters:  20%|██        | 41/200 [01:10<04:31,  1.71s/it]
  iters:  21%|██        | 42/200 [01:12<04:31,  1.72s/it]
  iters:  22%|██▏       | 43/200 [01:14<04:30,  1.72s/it]
  iters:  22%|██▏       | 44/200 [01:15<04:29,  1.73s/it]
  iters:  22%|██▎       | 45/200 [01:17<04:28,  1.73s/it]
  iters:  23%|██▎       | 46/200 [01:19<04:26,  1.73s/it]
  iters:  24%|██▎       | 47/200 [01:21<04:25,  1.74s/it]
  iters:  24%|██▍       | 48/200 [01:22<04:23,  1.74s/it]
  iters:  24%|██▍       | 49/200 [01:24<04:21,  1.73s/it]
  iters:  25%|██▌       | 50/200 [01:26<04:20,  1.73s/it]
  iters:  26%|██▌       | 51/200 [01:27<04:16,  1.72s/it]
  iters:  26%|██▌       | 52/200 [01:29<04:15,  1.73s/it]
  iters:  26%|██▋       | 53/200 [01:31<04:14,  1.73s/it]
  iters:  27%|██▋       | 54/200 [01:33<04:12,  1.73s/it]
  iters:  28%|██▊       | 55/200 [01:34<04:11,  1.74s/it]
  iters:  28%|██▊       | 56/200 [01:36<04:10,  1.74s/it]
  iters:  28%|██▊       | 57/200 [01:38<04:08,  1.74s/it]
  iters:  29%|██▉       | 58/200 [01:40<04:06,  1.74s/it]
  iters:  30%|██▉       | 59/200 [01:41<04:04,  1.73s/it]
  iters:  30%|███       | 60/200 [01:43<04:02,  1.73s/it]
  iters:  30%|███       | 61/200 [01:45<04:01,  1.74s/it]
  iters:  31%|███       | 62/200 [01:46<03:55,  1.71s/it]
  iters:  32%|███▏      | 63/200 [01:48<03:54,  1.71s/it]
  iters:  32%|███▏      | 64/200 [01:50<03:53,  1.72s/it]
  iters:  32%|███▎      | 65/200 [01:52<03:52,  1.72s/it]
  iters:  33%|███▎      | 66/200 [01:53<03:51,  1.72s/it]
  iters:  34%|███▎      | 67/200 [01:55<03:49,  1.72s/it]
  iters:  34%|███▍      | 68/200 [01:57<03:47,  1.73s/it]
  iters:  34%|███▍      | 69/200 [01:59<03:46,  1.73s/it]
  iters:  35%|███▌      | 70/200 [02:00<03:44,  1.73s/it]
  iters:  36%|███▌      | 71/200 [02:02<03:42,  1.73s/it]
  iters:  36%|███▌      | 72/200 [02:04<03:39,  1.71s/it]
  iters:  36%|███▋      | 73/200 [02:05<03:38,  1.72s/it]
  iters:  37%|███▋      | 74/200 [02:07<03:37,  1.72s/it]
  iters:  38%|███▊      | 75/200 [02:09<03:35,  1.73s/it]
  iters:  38%|███▊      | 76/200 [02:11<03:34,  1.73s/it]
  iters:  38%|███▊      | 77/200 [02:12<03:32,  1.73s/it]
  iters:  39%|███▉      | 78/200 [02:14<03:30,  1.73s/it]
  iters:  40%|███▉      | 79/200 [02:16<03:29,  1.73s/it]
  iters:  40%|████      | 80/200 [02:17<03:24,  1.70s/it]
  iters:  40%|████      | 81/200 [02:19<03:23,  1.71s/it]
  iters:  41%|████      | 82/200 [02:21<03:22,  1.71s/it]
  iters:  42%|████▏     | 83/200 [02:23<03:21,  1.72s/it]
  iters:  42%|████▏     | 84/200 [02:24<03:19,  1.72s/it]
  iters:  42%|████▎     | 85/200 [02:26<03:17,  1.72s/it]
  iters:  43%|████▎     | 86/200 [02:28<03:16,  1.72s/it]
  iters:  44%|████▎     | 87/200 [02:30<03:14,  1.72s/it]
  iters:  44%|████▍     | 88/200 [02:31<03:12,  1.72s/it]
  iters:  44%|████▍     | 89/200 [02:33<03:11,  1.72s/it]
  iters:  45%|████▌     | 90/200 [02:35<03:09,  1.72s/it]
  iters:  46%|████▌     | 91/200 [02:36<03:08,  1.73s/it]
  iters:  46%|████▌     | 92/200 [02:38<03:06,  1.73s/it]
  iters:  46%|████▋     | 93/200 [02:40<03:04,  1.72s/it]
  iters:  47%|████▋     | 94/200 [02:42<03:02,  1.73s/it]
  iters:  48%|████▊     | 95/200 [02:43<03:01,  1.72s/it]
  iters:  48%|████▊     | 96/200 [02:45<02:59,  1.72s/it]
  iters:  48%|████▊     | 97/200 [02:47<02:57,  1.72s/it]
  iters:  49%|████▉     | 98/200 [02:48<02:55,  1.72s/it]
  iters:  50%|████▉     | 99/200 [02:50<02:53,  1.72s/it]
  iters:  50%|█████     | 100/200 [02:52<02:52,  1.72s/it]
  iters:  50%|█████     | 101/200 [02:54<02:50,  1.73s/it]
  iters:  51%|█████     | 102/200 [02:56<03:00,  1.85s/it]
  iters:  52%|█████▏    | 103/200 [02:58<02:55,  1.81s/it]
  iters:  52%|█████▏    | 104/200 [02:59<02:51,  1.79s/it]
  iters:  52%|█████▎    | 105/200 [03:01<02:48,  1.77s/it]
  iters:  53%|█████▎    | 106/200 [03:03<02:45,  1.76s/it]
  iters:  54%|█████▎    | 107/200 [03:04<02:43,  1.76s/it]
  iters:  54%|█████▍    | 108/200 [03:06<02:41,  1.75s/it]
  iters:  55%|█████▍    | 109/200 [03:08<02:39,  1.75s/it]
  iters:  55%|█████▌    | 110/200 [03:10<02:36,  1.74s/it]
  iters:  56%|█████▌    | 111/200 [03:11<02:35,  1.74s/it]
  iters:  56%|█████▌    | 112/200 [03:13<02:33,  1.74s/it]
  iters:  56%|█████▋    | 113/200 [03:15<02:29,  1.71s/it]
  iters:  57%|█████▋    | 114/200 [03:17<02:28,  1.72s/it]
  iters:  57%|█████▊    | 115/200 [03:18<02:26,  1.73s/it]
  iters:  58%|█████▊    | 116/200 [03:20<02:25,  1.73s/it]
  iters:  58%|█████▊    | 117/200 [03:22<02:23,  1.73s/it]
  iters:  59%|█████▉    | 118/200 [03:24<02:22,  1.74s/it]
  iters:  60%|█████▉    | 119/200 [03:25<02:18,  1.71s/it]
  iters:  60%|██████    | 120/200 [03:27<02:17,  1.72s/it]
  iters:  60%|██████    | 121/200 [03:29<02:15,  1.72s/it]
  iters:  61%|██████    | 122/200 [03:30<02:14,  1.72s/it]
  iters:  62%|██████▏   | 123/200 [03:32<02:12,  1.72s/it]
  iters:  62%|██████▏   | 124/200 [03:34<02:11,  1.72s/it]
  iters:  62%|██████▎   | 125/200 [03:36<02:09,  1.73s/it]
  iters:  63%|██████▎   | 126/200 [03:37<02:07,  1.73s/it]
  iters:  64%|██████▎   | 127/200 [03:39<02:06,  1.73s/it]
  iters:  64%|██████▍   | 128/200 [03:41<02:04,  1.73s/it]
  iters:  64%|██████▍   | 129/200 [03:42<02:02,  1.73s/it]
  iters:  65%|██████▌   | 130/200 [03:44<02:00,  1.73s/it]
  iters:  66%|██████▌   | 131/200 [03:46<01:59,  1.73s/it]
  iters:  66%|██████▌   | 132/200 [03:48<01:55,  1.70s/it]
  iters:  66%|██████▋   | 133/200 [03:49<01:54,  1.71s/it]
  iters:  67%|██████▋   | 134/200 [03:51<01:53,  1.72s/it]
  iters:  68%|██████▊   | 135/200 [03:53<01:51,  1.72s/it]
  iters:  68%|██████▊   | 136/200 [03:54<01:50,  1.72s/it]
  iters:  68%|██████▊   | 137/200 [03:56<01:48,  1.72s/it]
  iters:  69%|██████▉   | 138/200 [03:58<01:46,  1.72s/it]
  iters:  70%|██████▉   | 139/200 [04:00<01:43,  1.70s/it]
  iters:  70%|███████   | 140/200 [04:01<01:42,  1.70s/it]
  iters:  70%|███████   | 141/200 [04:03<01:40,  1.71s/it]
  iters:  71%|███████   | 142/200 [04:05<01:39,  1.71s/it]
  iters:  72%|███████▏  | 143/200 [04:06<01:38,  1.72s/it]
  iters:  72%|███████▏  | 144/200 [04:08<01:36,  1.72s/it]
  iters:  72%|███████▎  | 145/200 [04:10<01:34,  1.72s/it]
  iters:  73%|███████▎  | 146/200 [04:12<01:33,  1.72s/it]
  iters:  74%|███████▎  | 147/200 [04:13<01:31,  1.72s/it]
  iters:  74%|███████▍  | 148/200 [04:15<01:29,  1.72s/it]
  iters:  74%|███████▍  | 149/200 [04:17<01:27,  1.71s/it]
  iters:  75%|███████▌  | 150/200 [04:18<01:25,  1.72s/it]
  iters:  76%|███████▌  | 151/200 [04:20<01:24,  1.72s/it]
  iters:  76%|███████▌  | 152/200 [04:22<01:22,  1.72s/it]
  iters:  76%|███████▋  | 153/200 [04:24<01:21,  1.73s/it]
  iters:  77%|███████▋  | 154/200 [04:25<01:19,  1.73s/it]
  iters:  78%|███████▊  | 155/200 [04:27<01:16,  1.70s/it]
  iters:  78%|███████▊  | 156/200 [04:29<01:15,  1.71s/it]
  iters:  78%|███████▊  | 157/200 [04:30<01:13,  1.71s/it]
  iters:  79%|███████▉  | 158/200 [04:32<01:12,  1.72s/it]
  iters:  80%|███████▉  | 159/200 [04:34<01:10,  1.72s/it]
  iters:  80%|████████  | 160/200 [04:36<01:08,  1.72s/it]
  iters:  80%|████████  | 161/200 [04:37<01:07,  1.73s/it]
  iters:  81%|████████  | 162/200 [04:39<01:05,  1.73s/it]
  iters:  82%|████████▏ | 163/200 [04:41<01:03,  1.73s/it]
  iters:  82%|████████▏ | 164/200 [04:43<01:02,  1.73s/it]
  iters:  82%|████████▎ | 165/200 [04:44<01:00,  1.73s/it]
  iters:  83%|████████▎ | 166/200 [04:46<00:58,  1.72s/it]
  iters:  84%|████████▎ | 167/200 [04:48<00:56,  1.72s/it]
  iters:  84%|████████▍ | 168/200 [04:49<00:55,  1.72s/it]
  iters:  84%|████████▍ | 169/200 [04:51<00:53,  1.73s/it]
  iters:  85%|████████▌ | 170/200 [04:53<00:51,  1.72s/it]
  iters:  86%|████████▌ | 171/200 [04:55<00:50,  1.72s/it]
  iters:  86%|████████▌ | 172/200 [04:56<00:48,  1.73s/it]
  iters:  86%|████████▋ | 173/200 [04:58<00:46,  1.73s/it]
  iters:  87%|████████▋ | 174/200 [05:00<00:44,  1.73s/it]
  iters:  88%|████████▊ | 175/200 [05:01<00:42,  1.70s/it]
  iters:  88%|████████▊ | 176/200 [05:03<00:41,  1.71s/it]
  iters:  88%|████████▊ | 177/200 [05:05<00:39,  1.71s/it]
  iters:  89%|████████▉ | 178/200 [05:07<00:37,  1.72s/it]
  iters:  90%|████████▉ | 179/200 [05:08<00:35,  1.69s/it]
  iters:  90%|█████████ | 180/200 [05:10<00:34,  1.70s/it]
  iters:  90%|█████████ | 181/200 [05:12<00:32,  1.71s/it]
  iters:  91%|█████████ | 182/200 [05:13<00:30,  1.71s/it]
  iters:  92%|█████████▏| 183/200 [05:15<00:28,  1.70s/it]
  iters:  92%|█████████▏| 184/200 [05:17<00:26,  1.68s/it]
  iters:  92%|█████████▎| 185/200 [05:19<00:25,  1.69s/it]
  iters:  93%|█████████▎| 186/200 [05:20<00:23,  1.70s/it]
  iters:  94%|█████████▎| 187/200 [05:22<00:22,  1.71s/it]
  iters:  94%|█████████▍| 188/200 [05:24<00:20,  1.72s/it]
  iters:  94%|█████████▍| 189/200 [05:25<00:18,  1.72s/it]
  iters:  95%|█████████▌| 190/200 [05:27<00:17,  1.72s/it]
  iters:  96%|█████████▌| 191/200 [05:29<00:15,  1.72s/it]
  iters:  96%|█████████▌| 192/200 [05:31<00:13,  1.72s/it]
  iters:  96%|█████████▋| 193/200 [05:32<00:12,  1.72s/it]
  iters:  97%|█████████▋| 194/200 [05:34<00:10,  1.72s/it]
  iters:  98%|█████████▊| 195/200 [05:36<00:08,  1.72s/it]
  iters:  98%|█████████▊| 196/200 [05:37<00:06,  1.73s/it]
  iters:  98%|█████████▊| 197/200 [05:39<00:05,  1.73s/it]
  iters:  99%|█████████▉| 198/200 [05:41<00:03,  1.72s/it]
  iters: 100%|█████████▉| 199/200 [05:43<00:01,  1.72s/it]
  iters: 100%|██████████| 200/200 [05:44<00:00,  1.73s/it]

  [timing] data: 2.4s (1%) | forward: 86.3s (25%) | backward: 256.2s (74%) | total: 344.9s

Training:  25%|██▌       | 1/4 [12:37<18:58, 379.39s/it, acc=0.9996, det=0.0068, edge=0.0007]

  Epoch   1/4 | edge=0.0007 | det=0.0068 | test_loss=0.0006 | acc=0.9996 | recall=0.7607 | best=0.7872   | train=345.1s test=32.8s

Training:  50%|█████     | 2/4 [12:37<12:37, 378.54s/it, acc=0.9996, det=0.0068, edge=0.0007]
  iters:   0%|          | 0/200 [00:00<?, ?it/s]
  iters:   0%|          | 1/200 [00:01<06:29,  1.96s/it]
  iters:   1%|          | 2/200 [00:03<06:02,  1.83s/it]
  iters:   2%|▏         | 3/200 [00:05<05:50,  1.78s/it]
  iters:   2%|▏         | 4/200 [00:07<06:02,  1.85s/it]
  iters:   2%|▎         | 5/200 [00:09<05:51,  1.80s/it]
  iters:   3%|▎         | 6/200 [00:10<05:44,  1.78s/it]
  iters:   4%|▎         | 7/200 [00:12<05:39,  1.76s/it]
  iters:   4%|▍         | 8/200 [00:14<05:34,  1.74s/it]
  iters:   4%|▍         | 9/200 [00:15<05:31,  1.74s/it]
  iters:   5%|▌         | 10/200 [00:17<05:28,  1.73s/it]
  iters:   6%|▌         | 11/200 [00:19<05:26,  1.73s/it]
  iters:   6%|▌         | 12/200 [00:21<05:24,  1.73s/it]
  iters:   6%|▋         | 13/200 [00:22<05:22,  1.73s/it]
  iters:   7%|▋         | 14/200 [00:24<05:20,  1.73s/it]
  iters:   8%|▊         | 15/200 [00:26<05:19,  1.73s/it]
  iters:   8%|▊         | 16/200 [00:28<05:17,  1.73s/it]
  iters:   8%|▊         | 17/200 [00:29<05:15,  1.73s/it]
  iters:   9%|▉         | 18/200 [00:31<05:13,  1.72s/it]
  iters:  10%|▉         | 19/200 [00:33<05:12,  1.73s/it]
  iters:  10%|█         | 20/200 [00:34<05:10,  1.72s/it]
  iters:  10%|█         | 21/200 [00:36<05:08,  1.73s/it]
  iters:  11%|█         | 22/200 [00:38<05:02,  1.70s/it]
  iters:  12%|█▏        | 23/200 [00:39<04:57,  1.68s/it]
  iters:  12%|█▏        | 24/200 [00:41<04:57,  1.69s/it]
  iters:  12%|█▎        | 25/200 [00:43<04:57,  1.70s/it]
  iters:  13%|█▎        | 26/200 [00:45<04:57,  1.71s/it]
  iters:  14%|█▎        | 27/200 [00:46<04:57,  1.72s/it]
  iters:  14%|█▍        | 28/200 [00:48<04:56,  1.73s/it]
  iters:  14%|█▍        | 29/200 [00:50<04:55,  1.73s/it]
  iters:  15%|█▌        | 30/200 [00:52<04:54,  1.73s/it]
  iters:  16%|█▌        | 31/200 [00:53<04:52,  1.73s/it]
  iters:  16%|█▌        | 32/200 [00:55<04:50,  1.73s/it]
  iters:  16%|█▋        | 33/200 [00:57<04:49,  1.73s/it]
  iters:  17%|█▋        | 34/200 [00:59<04:49,  1.74s/it]
  iters:  18%|█▊        | 35/200 [01:00<04:46,  1.74s/it]
  iters:  18%|█▊        | 36/200 [01:02<04:40,  1.71s/it]
  iters:  18%|█▊        | 37/200 [01:04<04:39,  1.72s/it]
  iters:  19%|█▉        | 38/200 [01:05<04:38,  1.72s/it]
  iters:  20%|█▉        | 39/200 [01:07<04:36,  1.72s/it]
  iters:  20%|██        | 40/200 [01:09<04:35,  1.72s/it]
  iters:  20%|██        | 41/200 [01:11<04:34,  1.73s/it]
  iters:  21%|██        | 42/200 [01:12<04:33,  1.73s/it]
  iters:  22%|██▏       | 43/200 [01:14<04:32,  1.74s/it]
  iters:  22%|██▏       | 44/200 [01:16<04:30,  1.73s/it]
  iters:  22%|██▎       | 45/200 [01:17<04:28,  1.73s/it]
  iters:  23%|██▎       | 46/200 [01:19<04:26,  1.73s/it]
  iters:  24%|██▎       | 47/200 [01:21<04:24,  1.73s/it]
  iters:  24%|██▍       | 48/200 [01:23<04:23,  1.73s/it]
  iters:  24%|██▍       | 49/200 [01:24<04:21,  1.73s/it]
  iters:  25%|██▌       | 50/200 [01:26<04:19,  1.73s/it]
  iters:  26%|██▌       | 51/200 [01:28<04:17,  1.73s/it]
  iters:  26%|██▌       | 52/200 [01:30<04:15,  1.73s/it]
  iters:  26%|██▋       | 53/200 [01:31<04:14,  1.73s/it]
  iters:  27%|██▋       | 54/200 [01:33<04:12,  1.73s/it]
  iters:  28%|██▊       | 55/200 [01:35<04:10,  1.73s/it]
  iters:  28%|██▊       | 56/200 [01:36<04:08,  1.72s/it]
  iters:  28%|██▊       | 57/200 [01:38<04:06,  1.72s/it]
  iters:  29%|██▉       | 58/200 [01:40<04:04,  1.72s/it]
  iters:  30%|██▉       | 59/200 [01:42<04:02,  1.72s/it]
  iters:  30%|███       | 60/200 [01:43<04:00,  1.72s/it]
  iters:  30%|███       | 61/200 [01:45<03:59,  1.72s/it]
  iters:  31%|███       | 62/200 [01:47<03:57,  1.72s/it]
  iters:  32%|███▏      | 63/200 [01:49<03:56,  1.73s/it]
  iters:  32%|███▏      | 64/200 [01:50<03:50,  1.70s/it]
  iters:  32%|███▎      | 65/200 [01:52<03:48,  1.69s/it]
  iters:  33%|███▎      | 66/200 [01:54<03:48,  1.70s/it]
  iters:  34%|███▎      | 67/200 [01:55<03:47,  1.71s/it]
  iters:  34%|███▍      | 68/200 [01:57<03:43,  1.69s/it]
  iters:  34%|███▍      | 69/200 [01:59<03:42,  1.70s/it]
  iters:  35%|███▌      | 70/200 [02:00<03:41,  1.71s/it]
  iters:  36%|███▌      | 71/200 [02:02<03:40,  1.71s/it]
  iters:  36%|███▌      | 72/200 [02:04<03:39,  1.72s/it]
  iters:  36%|███▋      | 73/200 [02:06<03:38,  1.72s/it]
  iters:  37%|███▋      | 74/200 [02:07<03:37,  1.72s/it]
  iters:  38%|███▊      | 75/200 [02:09<03:35,  1.73s/it]
  iters:  38%|███▊      | 76/200 [02:11<03:33,  1.73s/it]
  iters:  38%|███▊      | 77/200 [02:13<03:32,  1.73s/it]
  iters:  39%|███▉      | 78/200 [02:14<03:30,  1.73s/it]
  iters:  40%|███▉      | 79/200 [02:16<03:25,  1.70s/it]
  iters:  40%|████      | 80/200 [02:18<03:25,  1.71s/it]
  iters:  40%|████      | 81/200 [02:19<03:23,  1.71s/it]
  iters:  41%|████      | 82/200 [02:21<03:22,  1.71s/it]
  iters:  42%|████▏     | 83/200 [02:23<03:20,  1.72s/it]
  iters:  42%|████▏     | 84/200 [02:24<03:19,  1.72s/it]
  iters:  42%|████▎     | 85/200 [02:26<03:14,  1.69s/it]
  iters:  43%|████▎     | 86/200 [02:28<03:13,  1.70s/it]
  iters:  44%|████▎     | 87/200 [02:30<03:13,  1.71s/it]
  iters:  44%|████▍     | 88/200 [02:31<03:11,  1.71s/it]
  iters:  44%|████▍     | 89/200 [02:33<03:10,  1.72s/it]
  iters:  45%|████▌     | 90/200 [02:35<03:09,  1.72s/it]
  iters:  46%|████▌     | 91/200 [02:36<03:07,  1.72s/it]
  iters:  46%|████▌     | 92/200 [02:38<03:06,  1.72s/it]
  iters:  46%|████▋     | 93/200 [02:40<03:04,  1.72s/it]
  iters:  47%|████▋     | 94/200 [02:42<02:59,  1.70s/it]
  iters:  48%|████▊     | 95/200 [02:43<02:59,  1.70s/it]
  iters:  48%|████▊     | 96/200 [02:45<02:58,  1.72s/it]
  iters:  48%|████▊     | 97/200 [02:47<02:57,  1.72s/it]
  iters:  49%|████▉     | 98/200 [02:49<02:56,  1.73s/it]
  iters:  50%|████▉     | 99/200 [02:50<02:54,  1.73s/it]
  iters:  50%|█████     | 100/200 [02:52<02:53,  1.73s/it]
  iters:  50%|█████     | 101/200 [02:54<02:51,  1.73s/it]
  iters:  51%|█████     | 102/200 [02:55<02:49,  1.73s/it]
  iters:  52%|█████▏    | 103/200 [02:57<02:48,  1.73s/it]
  iters:  52%|█████▏    | 104/200 [02:59<02:46,  1.73s/it]
  iters:  52%|█████▎    | 105/200 [03:01<02:44,  1.73s/it]
  iters:  53%|█████▎    | 106/200 [03:02<02:41,  1.72s/it]
  iters:  54%|█████▎    | 107/200 [03:04<02:40,  1.73s/it]
  iters:  54%|█████▍    | 108/200 [03:06<02:39,  1.73s/it]
  iters:  55%|█████▍    | 109/200 [03:07<02:36,  1.72s/it]
  iters:  55%|█████▌    | 110/200 [03:09<02:41,  1.80s/it]
  iters:  56%|█████▌    | 111/200 [03:11<02:38,  1.78s/it]
  iters:  56%|█████▌    | 112/200 [03:13<02:35,  1.76s/it]
  iters:  56%|█████▋    | 113/200 [03:15<02:32,  1.76s/it]
  iters:  57%|█████▋    | 114/200 [03:16<02:30,  1.75s/it]
  iters:  57%|█████▊    | 115/200 [03:18<02:28,  1.75s/it]
  iters:  58%|█████▊    | 116/200 [03:20<02:26,  1.74s/it]
  iters:  58%|█████▊    | 117/200 [03:22<02:24,  1.74s/it]
  iters:  59%|█████▉    | 118/200 [03:23<02:22,  1.74s/it]
  iters:  60%|█████▉    | 119/200 [03:25<02:20,  1.74s/it]
  iters:  60%|██████    | 120/200 [03:27<02:19,  1.74s/it]
  iters:  60%|██████    | 121/200 [03:29<02:17,  1.74s/it]
  iters:  61%|██████    | 122/200 [03:30<02:15,  1.73s/it]
  iters:  62%|██████▏   | 123/200 [03:32<02:13,  1.74s/it]
  iters:  62%|██████▏   | 124/200 [03:34<02:11,  1.74s/it]
  iters:  62%|██████▎   | 125/200 [03:36<02:10,  1.73s/it]
  iters:  63%|██████▎   | 126/200 [03:37<02:08,  1.73s/it]
  iters:  64%|██████▎   | 127/200 [03:39<02:04,  1.70s/it]
  iters:  64%|██████▍   | 128/200 [03:41<02:03,  1.71s/it]
  iters:  64%|██████▍   | 129/200 [03:42<02:01,  1.72s/it]
  iters:  65%|██████▌   | 130/200 [03:44<02:00,  1.72s/it]
  iters:  66%|██████▌   | 131/200 [03:46<01:59,  1.73s/it]
  iters:  66%|██████▌   | 132/200 [03:48<01:57,  1.73s/it]
  iters:  66%|██████▋   | 133/200 [03:49<01:54,  1.72s/it]
  iters:  67%|██████▋   | 134/200 [03:51<01:53,  1.72s/it]
  iters:  68%|██████▊   | 135/200 [03:53<01:51,  1.72s/it]
  iters:  68%|██████▊   | 136/200 [03:54<01:50,  1.72s/it]
  iters:  68%|██████▊   | 137/200 [03:56<01:48,  1.73s/it]
  iters:  69%|██████▉   | 138/200 [03:58<01:47,  1.73s/it]
  iters:  70%|██████▉   | 139/200 [04:00<01:45,  1.73s/it]
  iters:  70%|███████   | 140/200 [04:01<01:43,  1.72s/it]
  iters:  70%|███████   | 141/200 [04:03<01:41,  1.72s/it]
  iters:  71%|███████   | 142/200 [04:05<01:39,  1.72s/it]
  iters:  72%|███████▏  | 143/200 [04:06<01:38,  1.73s/it]
  iters:  72%|███████▏  | 144/200 [04:08<01:36,  1.73s/it]
  iters:  72%|███████▎  | 145/200 [04:10<01:35,  1.73s/it]
  iters:  73%|███████▎  | 146/200 [04:12<01:33,  1.73s/it]
  iters:  74%|███████▎  | 147/200 [04:13<01:31,  1.73s/it]
  iters:  74%|███████▍  | 148/200 [04:15<01:30,  1.74s/it]
  iters:  74%|███████▍  | 149/200 [04:17<01:28,  1.74s/it]
  iters:  75%|███████▌  | 150/200 [04:19<01:26,  1.74s/it]
  iters:  76%|███████▌  | 151/200 [04:20<01:25,  1.74s/it]
  iters:  76%|███████▌  | 152/200 [04:22<01:23,  1.74s/it]
  iters:  76%|███████▋  | 153/200 [04:24<01:21,  1.74s/it]
  iters:  77%|███████▋  | 154/200 [04:26<01:19,  1.74s/it]
  iters:  78%|███████▊  | 155/200 [04:27<01:18,  1.74s/it]
  iters:  78%|███████▊  | 156/200 [04:29<01:16,  1.74s/it]
  iters:  78%|███████▊  | 157/200 [04:31<01:14,  1.74s/it]
  iters:  79%|███████▉  | 158/200 [04:33<01:12,  1.74s/it]
  iters:  80%|███████▉  | 159/200 [04:34<01:11,  1.73s/it]
  iters:  80%|████████  | 160/200 [04:36<01:09,  1.73s/it]
  iters:  80%|████████  | 161/200 [04:38<01:07,  1.73s/it]
  iters:  81%|████████  | 162/200 [04:39<01:05,  1.73s/it]
  iters:  82%|████████▏ | 163/200 [04:41<01:04,  1.73s/it]
  iters:  82%|████████▏ | 164/200 [04:43<01:02,  1.73s/it]
  iters:  82%|████████▎ | 165/200 [04:45<01:00,  1.73s/it]
  iters:  83%|████████▎ | 166/200 [04:46<00:58,  1.73s/it]
  iters:  84%|████████▎ | 167/200 [04:48<00:57,  1.73s/it]
  iters:  84%|████████▍ | 168/200 [04:50<00:55,  1.73s/it]
  iters:  84%|████████▍ | 169/200 [04:52<00:53,  1.73s/it]
  iters:  85%|████████▌ | 170/200 [04:53<00:51,  1.73s/it]
  iters:  86%|████████▌ | 171/200 [04:55<00:50,  1.73s/it]
  iters:  86%|████████▌ | 172/200 [04:57<00:48,  1.73s/it]
  iters:  86%|████████▋ | 173/200 [04:59<00:46,  1.73s/it]
  iters:  87%|████████▋ | 174/200 [05:00<00:44,  1.73s/it]
  iters:  88%|████████▊ | 175/200 [05:02<00:43,  1.73s/it]
  iters:  88%|████████▊ | 176/200 [05:04<00:41,  1.73s/it]
  iters:  88%|████████▊ | 177/200 [05:05<00:39,  1.73s/it]
  iters:  89%|████████▉ | 178/200 [05:07<00:37,  1.73s/it]
  iters:  90%|████████▉ | 179/200 [05:09<00:36,  1.73s/it]
  iters:  90%|█████████ | 180/200 [05:11<00:34,  1.73s/it]
  iters:  90%|█████████ | 181/200 [05:12<00:32,  1.73s/it]
  iters:  91%|█████████ | 182/200 [05:14<00:31,  1.73s/it]
  iters:  92%|█████████▏| 183/200 [05:16<00:29,  1.73s/it]
  iters:  92%|█████████▏| 184/200 [05:17<00:27,  1.73s/it]
  iters:  92%|█████████▎| 185/200 [05:19<00:25,  1.73s/it]
  iters:  93%|█████████▎| 186/200 [05:21<00:24,  1.73s/it]
  iters:  94%|█████████▎| 187/200 [05:23<00:22,  1.72s/it]
  iters:  94%|█████████▍| 188/200 [05:24<00:20,  1.73s/it]
  iters:  94%|█████████▍| 189/200 [05:26<00:18,  1.73s/it]
  iters:  95%|█████████▌| 190/200 [05:28<00:17,  1.73s/it]
  iters:  96%|█████████▌| 191/200 [05:30<00:15,  1.73s/it]
  iters:  96%|█████████▌| 192/200 [05:31<00:13,  1.73s/it]
  iters:  96%|█████████▋| 193/200 [05:33<00:12,  1.73s/it]
  iters:  97%|█████████▋| 194/200 [05:35<00:10,  1.73s/it]
  iters:  98%|█████████▊| 195/200 [05:36<00:08,  1.72s/it]
  iters:  98%|█████████▊| 196/200 [05:38<00:06,  1.73s/it]
  iters:  98%|█████████▊| 197/200 [05:40<00:05,  1.73s/it]
  iters:  99%|█████████▉| 198/200 [05:42<00:03,  1.73s/it]
  iters: 100%|█████████▉| 199/200 [05:43<00:01,  1.73s/it]
  iters: 100%|██████████| 200/200 [05:45<00:00,  1.73s/it]

  [timing] data: 2.3s (1%) | forward: 86.4s (25%) | backward: 256.8s (74%) | total: 345.6s

Training:  50%|█████     | 2/4 [18:55<12:37, 378.54s/it, acc=0.9995, det=0.0065, edge=0.0007]

  Epoch   2/4 | edge=0.0007 | det=0.0065 | test_loss=0.0005 | acc=0.9995 | recall=0.7911 | best=0.7907 * | train=345.9s test=32.7s

Training:  75%|███████▌  | 3/4 [18:55<06:18, 378.57s/it, acc=0.9995, det=0.0065, edge=0.0007]
  iters:   0%|          | 0/200 [00:00<?, ?it/s]
  iters:   0%|          | 1/200 [00:02<06:41,  2.02s/it]
  iters:   1%|          | 2/200 [00:03<06:06,  1.85s/it]
  iters:   2%|▏         | 3/200 [00:05<05:52,  1.79s/it]
  iters:   2%|▏         | 4/200 [00:07<05:46,  1.77s/it]
  iters:   2%|▎         | 5/200 [00:08<05:42,  1.76s/it]
  iters:   3%|▎         | 6/200 [00:10<05:39,  1.75s/it]
  iters:   4%|▎         | 7/200 [00:12<05:35,  1.74s/it]
  iters:   4%|▍         | 8/200 [00:14<05:33,  1.73s/it]
  iters:   4%|▍         | 9/200 [00:15<05:31,  1.74s/it]
  iters:   5%|▌         | 10/200 [00:17<05:29,  1.73s/it]
  iters:   6%|▌         | 11/200 [00:19<05:26,  1.73s/it]
  iters:   6%|▌         | 12/200 [00:20<05:22,  1.72s/it]
  iters:   6%|▋         | 13/200 [00:22<05:18,  1.71s/it]
  iters:   7%|▋         | 14/200 [00:24<05:18,  1.71s/it]
  iters:   8%|▊         | 15/200 [00:26<05:17,  1.71s/it]
  iters:   8%|▊         | 16/200 [00:27<05:16,  1.72s/it]
  iters:   8%|▊         | 17/200 [00:29<05:14,  1.72s/it]
  iters:   9%|▉         | 18/200 [00:31<05:13,  1.72s/it]
  iters:  10%|▉         | 19/200 [00:33<05:12,  1.72s/it]
  iters:  10%|█         | 20/200 [00:34<05:10,  1.72s/it]
  iters:  10%|█         | 21/200 [00:36<05:12,  1.75s/it]
  iters:  11%|█         | 22/200 [00:38<05:09,  1.74s/it]
  iters:  12%|█▏        | 23/200 [00:40<05:07,  1.74s/it]
  iters:  12%|█▏        | 24/200 [00:41<05:04,  1.73s/it]
  iters:  12%|█▎        | 25/200 [00:43<05:02,  1.73s/it]
  iters:  13%|█▎        | 26/200 [00:45<05:00,  1.73s/it]
  iters:  14%|█▎        | 27/200 [00:46<04:59,  1.73s/it]
  iters:  14%|█▍        | 28/200 [00:48<04:52,  1.70s/it]
  iters:  14%|█▍        | 29/200 [00:50<04:53,  1.72s/it]
  iters:  15%|█▌        | 30/200 [00:52<04:52,  1.72s/it]
  iters:  16%|█▌        | 31/200 [00:53<04:51,  1.72s/it]
  iters:  16%|█▌        | 32/200 [00:55<04:49,  1.72s/it]
  iters:  16%|█▋        | 33/200 [00:57<04:47,  1.72s/it]
  iters:  17%|█▋        | 34/200 [00:58<04:46,  1.72s/it]
  iters:  18%|█▊        | 35/200 [01:00<04:44,  1.72s/it]
  iters:  18%|█▊        | 36/200 [01:02<04:43,  1.73s/it]
  iters:  18%|█▊        | 37/200 [01:04<04:41,  1.73s/it]
  iters:  19%|█▉        | 38/200 [01:05<04:39,  1.73s/it]
  iters:  20%|█▉        | 39/200 [01:07<04:38,  1.73s/it]
  iters:  20%|██        | 40/200 [01:09<04:36,  1.73s/it]
  iters:  20%|██        | 41/200 [01:11<04:34,  1.73s/it]
  iters:  21%|██        | 42/200 [01:12<04:32,  1.73s/it]
  iters:  22%|██▏       | 43/200 [01:14<04:31,  1.73s/it]
  iters:  22%|██▏       | 44/200 [01:16<04:29,  1.73s/it]
  iters:  22%|██▎       | 45/200 [01:17<04:27,  1.73s/it]
  iters:  23%|██▎       | 46/200 [01:19<04:25,  1.73s/it]
  iters:  24%|██▎       | 47/200 [01:21<04:24,  1.73s/it]
  iters:  24%|██▍       | 48/200 [01:23<04:22,  1.73s/it]
  iters:  24%|██▍       | 49/200 [01:24<04:20,  1.72s/it]
  iters:  25%|██▌       | 50/200 [01:26<04:18,  1.72s/it]
  iters:  26%|██▌       | 51/200 [01:28<04:16,  1.72s/it]
  iters:  26%|██▌       | 52/200 [01:30<04:15,  1.73s/it]
  iters:  26%|██▋       | 53/200 [01:31<04:14,  1.73s/it]
  iters:  27%|██▋       | 54/200 [01:33<04:12,  1.73s/it]
  iters:  28%|██▊       | 55/200 [01:35<04:10,  1.73s/it]
  iters:  28%|██▊       | 56/200 [01:36<04:08,  1.73s/it]
  iters:  28%|██▊       | 57/200 [01:38<04:07,  1.73s/it]
  iters:  29%|██▉       | 58/200 [01:40<04:02,  1.71s/it]
  iters:  30%|██▉       | 59/200 [01:42<04:01,  1.71s/it]
  iters:  30%|███       | 60/200 [01:43<04:00,  1.72s/it]
  iters:  30%|███       | 61/200 [01:45<03:58,  1.72s/it]
  iters:  31%|███       | 62/200 [01:47<03:57,  1.72s/it]
  iters:  32%|███▏      | 63/200 [01:48<03:55,  1.72s/it]
  iters:  32%|███▏      | 64/200 [01:50<03:54,  1.72s/it]
  iters:  32%|███▎      | 65/200 [01:52<03:52,  1.72s/it]
  iters:  33%|███▎      | 66/200 [01:54<03:50,  1.72s/it]
  iters:  34%|███▎      | 67/200 [01:55<03:49,  1.73s/it]
  iters:  34%|███▍      | 68/200 [01:57<03:48,  1.73s/it]
  iters:  34%|███▍      | 69/200 [01:59<03:42,  1.70s/it]
  iters:  35%|███▌      | 70/200 [02:00<03:42,  1.71s/it]
  iters:  36%|███▌      | 71/200 [02:02<03:39,  1.70s/it]
  iters:  36%|███▌      | 72/200 [02:04<03:38,  1.71s/it]
  iters:  36%|███▋      | 73/200 [02:06<03:36,  1.70s/it]
  iters:  37%|███▋      | 74/200 [02:07<03:35,  1.71s/it]
  iters:  38%|███▊      | 75/200 [02:09<03:34,  1.72s/it]
  iters:  38%|███▊      | 76/200 [02:11<03:33,  1.72s/it]
  iters:  38%|███▊      | 77/200 [02:12<03:32,  1.73s/it]
  iters:  39%|███▉      | 78/200 [02:14<03:30,  1.73s/it]
  iters:  40%|███▉      | 79/200 [02:16<03:29,  1.73s/it]
  iters:  40%|████      | 80/200 [02:18<03:27,  1.73s/it]
  iters:  40%|████      | 81/200 [02:19<03:25,  1.73s/it]
  iters:  41%|████      | 82/200 [02:21<03:23,  1.73s/it]
  iters:  42%|████▏     | 83/200 [02:23<03:22,  1.73s/it]
  iters:  42%|████▏     | 84/200 [02:25<03:20,  1.73s/it]
  iters:  42%|████▎     | 85/200 [02:26<03:18,  1.73s/it]
  iters:  43%|████▎     | 86/200 [02:28<03:17,  1.73s/it]
  iters:  44%|████▎     | 87/200 [02:30<03:16,  1.74s/it]
  iters:  44%|████▍     | 88/200 [02:32<03:14,  1.73s/it]
  iters:  44%|████▍     | 89/200 [02:33<03:12,  1.73s/it]
  iters:  45%|████▌     | 90/200 [02:35<03:10,  1.73s/it]
  iters:  46%|████▌     | 91/200 [02:37<03:08,  1.73s/it]
  iters:  46%|████▌     | 92/200 [02:38<03:06,  1.73s/it]
  iters:  46%|████▋     | 93/200 [02:40<03:04,  1.73s/it]
  iters:  47%|████▋     | 94/200 [02:42<03:03,  1.73s/it]
  iters:  48%|████▊     | 95/200 [02:44<03:01,  1.73s/it]
  iters:  48%|████▊     | 96/200 [02:45<02:58,  1.72s/it]
  iters:  48%|████▊     | 97/200 [02:47<02:55,  1.71s/it]
  iters:  49%|████▉     | 98/200 [02:49<02:54,  1.71s/it]
  iters:  50%|████▉     | 99/200 [02:50<02:50,  1.69s/it]
  iters:  50%|█████     | 100/200 [02:52<02:50,  1.70s/it]
  iters:  50%|█████     | 101/200 [02:54<02:49,  1.71s/it]
  iters:  51%|█████     | 102/200 [02:55<02:46,  1.70s/it]
  iters:  52%|█████▏    | 103/200 [02:57<02:45,  1.71s/it]
  iters:  52%|█████▏    | 104/200 [02:59<02:44,  1.71s/it]
  iters:  52%|█████▎    | 105/200 [03:01<02:40,  1.69s/it]
  iters:  53%|█████▎    | 106/200 [03:02<02:40,  1.70s/it]
  iters:  54%|█████▎    | 107/200 [03:04<02:39,  1.71s/it]
  iters:  54%|█████▍    | 108/200 [03:06<02:38,  1.72s/it]
  iters:  55%|█████▍    | 109/200 [03:07<02:36,  1.72s/it]
  iters:  55%|█████▌    | 110/200 [03:09<02:35,  1.73s/it]
  iters:  56%|█████▌    | 111/200 [03:11<02:33,  1.72s/it]
  iters:  56%|█████▌    | 112/200 [03:13<02:31,  1.73s/it]
  iters:  56%|█████▋    | 113/200 [03:14<02:30,  1.73s/it]
  iters:  57%|█████▋    | 114/200 [03:16<02:28,  1.73s/it]
  iters:  57%|█████▊    | 115/200 [03:18<02:26,  1.73s/it]
  iters:  58%|█████▊    | 116/200 [03:20<02:24,  1.73s/it]
  iters:  58%|█████▊    | 117/200 [03:21<02:23,  1.73s/it]
  iters:  59%|█████▉    | 118/200 [03:23<02:21,  1.73s/it]
  iters:  60%|█████▉    | 119/200 [03:25<02:19,  1.72s/it]
  iters:  60%|██████    | 120/200 [03:26<02:18,  1.73s/it]
  iters:  60%|██████    | 121/200 [03:28<02:16,  1.72s/it]
  iters:  61%|██████    | 122/200 [03:30<02:14,  1.73s/it]
  iters:  62%|██████▏   | 123/200 [03:32<02:12,  1.73s/it]
  iters:  62%|██████▏   | 124/200 [03:33<02:11,  1.73s/it]
  iters:  62%|██████▎   | 125/200 [03:35<02:09,  1.73s/it]
  iters:  63%|██████▎   | 126/200 [03:37<02:07,  1.73s/it]
  iters:  64%|██████▎   | 127/200 [03:39<02:06,  1.73s/it]
  iters:  64%|██████▍   | 128/200 [03:40<02:04,  1.73s/it]
  iters:  64%|██████▍   | 129/200 [03:42<02:02,  1.73s/it]
  iters:  65%|██████▌   | 130/200 [03:44<02:05,  1.80s/it]
  iters:  66%|██████▌   | 131/200 [03:46<02:02,  1.78s/it]
  iters:  66%|██████▌   | 132/200 [03:47<01:59,  1.76s/it]
  iters:  66%|██████▋   | 133/200 [03:49<01:57,  1.75s/it]
  iters:  67%|██████▋   | 134/200 [03:51<01:55,  1.74s/it]
  iters:  68%|██████▊   | 135/200 [03:53<01:53,  1.74s/it]
  iters:  68%|██████▊   | 136/200 [03:54<01:51,  1.74s/it]
  iters:  68%|██████▊   | 137/200 [03:56<01:49,  1.74s/it]
  iters:  69%|██████▉   | 138/200 [03:58<01:47,  1.74s/it]
  iters:  70%|██████▉   | 139/200 [04:00<01:45,  1.74s/it]
  iters:  70%|███████   | 140/200 [04:01<01:44,  1.74s/it]
  iters:  70%|███████   | 141/200 [04:03<01:42,  1.74s/it]
  iters:  71%|███████   | 142/200 [04:05<01:40,  1.73s/it]
  iters:  72%|███████▏  | 143/200 [04:07<01:38,  1.73s/it]
  iters:  72%|███████▏  | 144/200 [04:08<01:36,  1.73s/it]
  iters:  72%|███████▎  | 145/200 [04:10<01:35,  1.73s/it]
  iters:  73%|███████▎  | 146/200 [04:12<01:33,  1.73s/it]
  iters:  74%|███████▎  | 147/200 [04:13<01:31,  1.73s/it]
  iters:  74%|███████▍  | 148/200 [04:15<01:30,  1.73s/it]
  iters:  74%|███████▍  | 149/200 [04:17<01:28,  1.73s/it]
  iters:  75%|███████▌  | 150/200 [04:19<01:26,  1.73s/it]
  iters:  76%|███████▌  | 151/200 [04:20<01:24,  1.73s/it]
  iters:  76%|███████▌  | 152/200 [04:22<01:23,  1.73s/it]
  iters:  76%|███████▋  | 153/200 [04:24<01:21,  1.74s/it]
  iters:  77%|███████▋  | 154/200 [04:26<01:19,  1.73s/it]
  iters:  78%|███████▊  | 155/200 [04:27<01:17,  1.73s/it]
  iters:  78%|███████▊  | 156/200 [04:29<01:16,  1.73s/it]
  iters:  78%|███████▊  | 157/200 [04:31<01:14,  1.73s/it]
  iters:  79%|███████▉  | 158/200 [04:33<01:12,  1.73s/it]
  iters:  80%|███████▉  | 159/200 [04:34<01:10,  1.73s/it]
  iters:  80%|████████  | 160/200 [04:36<01:09,  1.73s/it]
  iters:  80%|████████  | 161/200 [04:38<01:07,  1.73s/it]
  iters:  81%|████████  | 162/200 [04:39<01:05,  1.73s/it]
  iters:  82%|████████▏ | 163/200 [04:41<01:04,  1.73s/it]
  iters:  82%|████████▏ | 164/200 [04:43<01:02,  1.73s/it]
  iters:  82%|████████▎ | 165/200 [04:45<01:00,  1.73s/it]
  iters:  83%|████████▎ | 166/200 [04:46<00:58,  1.73s/it]
  iters:  84%|████████▎ | 167/200 [04:48<00:56,  1.72s/it]
  iters:  84%|████████▍ | 168/200 [04:50<00:55,  1.73s/it]
  iters:  84%|████████▍ | 169/200 [04:52<00:53,  1.73s/it]
  iters:  85%|████████▌ | 170/200 [04:53<00:51,  1.73s/it]
  iters:  86%|████████▌ | 171/200 [04:55<00:50,  1.73s/it]
  iters:  86%|████████▌ | 172/200 [04:57<00:48,  1.73s/it]
  iters:  86%|████████▋ | 173/200 [04:58<00:46,  1.72s/it]
  iters:  87%|████████▋ | 174/200 [05:00<00:44,  1.72s/it]
  iters:  88%|████████▊ | 175/200 [05:02<00:43,  1.72s/it]
  iters:  88%|████████▊ | 176/200 [05:04<00:41,  1.72s/it]
  iters:  88%|████████▊ | 177/200 [05:05<00:39,  1.72s/it]
  iters:  89%|████████▉ | 178/200 [05:07<00:37,  1.72s/it]
  iters:  90%|████████▉ | 179/200 [05:09<00:36,  1.72s/it]
  iters:  90%|█████████ | 180/200 [05:10<00:34,  1.72s/it]
  iters:  90%|█████████ | 181/200 [05:12<00:32,  1.72s/it]
  iters:  91%|█████████ | 182/200 [05:14<00:31,  1.72s/it]
  iters:  92%|█████████▏| 183/200 [05:16<00:29,  1.72s/it]
  iters:  92%|█████████▏| 184/200 [05:17<00:27,  1.72s/it]
  iters:  92%|█████████▎| 185/200 [05:19<00:25,  1.72s/it]
  iters:  93%|█████████▎| 186/200 [05:21<00:24,  1.72s/it]
  iters:  94%|█████████▎| 187/200 [05:23<00:22,  1.72s/it]
  iters:  94%|█████████▍| 188/200 [05:24<00:20,  1.72s/it]
  iters:  94%|█████████▍| 189/200 [05:26<00:18,  1.73s/it]
  iters:  95%|█████████▌| 190/200 [05:28<00:17,  1.73s/it]
  iters:  96%|█████████▌| 191/200 [05:29<00:15,  1.73s/it]
  iters:  96%|█████████▌| 192/200 [05:31<00:13,  1.73s/it]
  iters:  96%|█████████▋| 193/200 [05:33<00:12,  1.73s/it]
  iters:  97%|█████████▋| 194/200 [05:35<00:10,  1.73s/it]
  iters:  98%|█████████▊| 195/200 [05:36<00:08,  1.73s/it]
  iters:  98%|█████████▊| 196/200 [05:38<00:06,  1.73s/it]
  iters:  98%|█████████▊| 197/200 [05:40<00:05,  1.74s/it]
  iters:  99%|█████████▉| 198/200 [05:42<00:03,  1.73s/it]
  iters: 100%|█████████▉| 199/200 [05:43<00:01,  1.73s/it]
  iters: 100%|██████████| 200/200 [05:45<00:00,  1.73s/it]

  [timing] data: 2.3s (1%) | forward: 86.1s (25%) | backward: 257.0s (74%) | total: 345.5s

Training:  75%|███████▌  | 3/4 [25:14<06:18, 378.57s/it, acc=0.9995, det=0.0072, edge=0.0006]

  Epoch   3/4 | edge=0.0006 | det=0.0072 | test_loss=0.0005 | acc=0.9995 | recall=0.7925 | best=0.7921 * | train=345.7s test=32.7s

Training: 100%|██████████| 4/4 [25:14<00:00, 378.59s/it, acc=0.9995, det=0.0072, edge=0.0006]

Best score (acc*recall): 0.7921, saved to /kaggle/working/cellmot-baseline-artifacts/repo/weights/hp_search_tier1/split_0/edge_predictor_best.pth

[tier2_002] score=0.7921  (1521s)
0.019136512 GB allocated
0.14680064 GB reserved
Fold 0: 8 train, 2 test
Loading train (8 datasets)...

train: 100%|██████████| 8/8 [00:04<00:00,  1.83it/s]

  train done: 787 windows total
Loading test (2 datasets)...

test: 100%|██████████| 2/2 [00:00<00:00,  2.46it/s]

  test done: 164 windows total
max_nodes=17
Using device: cuda | visible CUDA GPUs: 2
  Full checkpoint loaded from /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/weights/unet_transformer/split_0/edge_predictor_best.pth: 0 missing, 0 unexpected
Single-GPU training (--single-gpu set). For 2 GPUs set the Kaggle accelerator to 'GPU T4 x2'.
Model parameters: 2,076,706
Starting training for 4 epochs (batch_size=2)...

Training:   0%|          | 0/4 [00:00<?, ?it/s]

Detection loss: weight=4, neg_weight=0.01

  iters:   0%|          | 0/200 [00:00<?, ?it/s]
  iters:   0%|          | 1/200 [00:01<04:58,  1.50s/it]
  iters:   1%|          | 2/200 [00:02<04:20,  1.32s/it]
  iters:   2%|▏         | 3/200 [00:03<04:08,  1.26s/it]
  iters:   2%|▏         | 4/200 [00:05<04:01,  1.23s/it]
  iters:   2%|▎         | 5/200 [00:06<03:57,  1.22s/it]
  iters:   3%|▎         | 6/200 [00:07<03:57,  1.22s/it]
  iters:   4%|▎         | 7/200 [00:08<03:54,  1.21s/it]
  iters:   4%|▍         | 8/200 [00:09<03:51,  1.21s/it]
  iters:   4%|▍         | 9/200 [00:11<03:52,  1.22s/it]
  iters:   5%|▌         | 10/200 [00:12<03:49,  1.21s/it]
  iters:   6%|▌         | 11/200 [00:13<03:48,  1.21s/it]
  iters:   6%|▌         | 12/200 [00:14<03:47,  1.21s/it]
  iters:   6%|▋         | 13/200 [00:15<03:46,  1.21s/it]
  iters:   7%|▋         | 14/200 [00:17<03:45,  1.21s/it]
  iters:   8%|▊         | 15/200 [00:18<03:47,  1.23s/it]
  iters:   8%|▊         | 16/200 [00:19<03:47,  1.24s/it]
  iters:   8%|▊         | 17/200 [00:20<03:50,  1.26s/it]
  iters:   9%|▉         | 18/200 [00:22<03:47,  1.25s/it]
  iters:  10%|▉         | 19/200 [00:23<03:44,  1.24s/it]
  iters:  10%|█         | 20/200 [00:24<03:42,  1.24s/it]
  iters:  10%|█         | 21/200 [00:25<03:41,  1.24s/it]
  iters:  11%|█         | 22/200 [00:27<03:39,  1.23s/it]
  iters:  12%|█▏        | 23/200 [00:28<03:37,  1.23s/it]
  iters:  12%|█▏        | 24/200 [00:29<03:35,  1.23s/it]
  iters:  12%|█▎        | 25/200 [00:30<03:34,  1.23s/it]
  iters:  13%|█▎        | 26/200 [00:32<03:38,  1.26s/it]
  iters:  14%|█▎        | 27/200 [00:33<03:38,  1.26s/it]
  iters:  14%|█▍        | 28/200 [00:34<03:35,  1.25s/it]
  iters:  14%|█▍        | 29/200 [00:35<03:33,  1.25s/it]
  iters:  15%|█▌        | 30/200 [00:37<03:29,  1.23s/it]
  iters:  16%|█▌        | 31/200 [00:38<03:27,  1.23s/it]
  iters:  16%|█▌        | 32/200 [00:39<03:25,  1.22s/it]
  iters:  16%|█▋        | 33/200 [00:40<03:23,  1.22s/it]
  iters:  17%|█▋        | 34/200 [00:41<03:21,  1.22s/it]
  iters:  18%|█▊        | 35/200 [00:43<03:20,  1.21s/it]
  iters:  18%|█▊        | 36/200 [00:44<03:18,  1.21s/it]
  iters:  18%|█▊        | 37/200 [00:45<03:17,  1.21s/it]
  iters:  19%|█▉        | 38/200 [00:46<03:16,  1.21s/it]
  iters:  20%|█▉        | 39/200 [00:47<03:15,  1.21s/it]
  iters:  20%|██        | 40/200 [00:49<03:14,  1.22s/it]
  iters:  20%|██        | 41/200 [00:50<03:12,  1.21s/it]
  iters:  21%|██        | 42/200 [00:51<03:15,  1.24s/it]
  iters:  22%|██▏       | 43/200 [00:52<03:12,  1.23s/it]
  iters:  22%|██▏       | 44/200 [00:54<03:14,  1.25s/it]
  iters:  22%|██▎       | 45/200 [00:55<03:15,  1.26s/it]
  iters:  23%|██▎       | 46/200 [00:56<03:11,  1.25s/it]
  iters:  24%|██▎       | 47/200 [00:57<03:08,  1.23s/it]
  iters:  24%|██▍       | 48/200 [00:59<03:05,  1.22s/it]
  iters:  24%|██▍       | 49/200 [01:00<03:03,  1.21s/it]
  iters:  25%|██▌       | 50/200 [01:01<03:01,  1.21s/it]
  iters:  26%|██▌       | 51/200 [01:02<03:02,  1.22s/it]
  iters:  26%|██▌       | 52/200 [01:03<02:59,  1.21s/it]
  iters:  26%|██▋       | 53/200 [01:05<03:01,  1.23s/it]
  iters:  27%|██▋       | 54/200 [01:06<02:59,  1.23s/it]
  iters:  28%|██▊       | 55/200 [01:07<03:01,  1.25s/it]
  iters:  28%|██▊       | 56/200 [01:08<02:57,  1.23s/it]
  iters:  28%|██▊       | 57/200 [01:10<02:54,  1.22s/it]
  iters:  29%|██▉       | 58/200 [01:11<02:57,  1.25s/it]
  iters:  30%|██▉       | 59/200 [01:12<02:53,  1.23s/it]
  iters:  30%|███       | 60/200 [01:13<02:50,  1.22s/it]
  iters:  30%|███       | 61/200 [01:15<02:51,  1.23s/it]
  iters:  31%|███       | 62/200 [01:16<02:48,  1.22s/it]
  iters:  32%|███▏      | 63/200 [01:17<02:46,  1.21s/it]
  iters:  32%|███▏      | 64/200 [01:18<02:44,  1.21s/it]
  iters:  32%|███▎      | 65/200 [01:19<02:42,  1.20s/it]
  iters:  33%|███▎      | 66/200 [01:21<02:41,  1.20s/it]
  iters:  34%|███▎      | 67/200 [01:22<02:39,  1.20s/it]
  iters:  34%|███▍      | 68/200 [01:23<02:38,  1.20s/it]
  iters:  34%|███▍      | 69/200 [01:24<02:37,  1.20s/it]
  iters:  35%|███▌      | 70/200 [01:25<02:35,  1.20s/it]
  iters:  36%|███▌      | 71/200 [01:27<02:35,  1.20s/it]
  iters:  36%|███▌      | 72/200 [01:28<02:33,  1.20s/it]
  iters:  36%|███▋      | 73/200 [01:29<02:33,  1.21s/it]
  iters:  37%|███▋      | 74/200 [01:30<02:32,  1.21s/it]
  iters:  38%|███▊      | 75/200 [01:31<02:30,  1.20s/it]
  iters:  38%|███▊      | 76/200 [01:33<02:28,  1.20s/it]
  iters:  38%|███▊      | 77/200 [01:34<02:28,  1.20s/it]
  iters:  39%|███▉      | 78/200 [01:35<02:26,  1.20s/it]
  iters:  40%|███▉      | 79/200 [01:36<02:25,  1.20s/it]
  iters:  40%|████      | 80/200 [01:37<02:23,  1.20s/it]
  iters:  40%|████      | 81/200 [01:39<02:22,  1.20s/it]
  iters:  41%|████      | 82/200 [01:40<02:21,  1.20s/it]
  iters:  42%|████▏     | 83/200 [01:41<02:20,  1.20s/it]
  iters:  42%|████▏     | 84/200 [01:42<02:19,  1.20s/it]
  iters:  42%|████▎     | 85/200 [01:43<02:18,  1.20s/it]
  iters:  43%|████▎     | 86/200 [01:45<02:17,  1.20s/it]
  iters:  44%|████▎     | 87/200 [01:46<02:15,  1.20s/it]
  iters:  44%|████▍     | 88/200 [01:47<02:14,  1.20s/it]
  iters:  44%|████▍     | 89/200 [01:48<02:13,  1.20s/it]
  iters:  45%|████▌     | 90/200 [01:49<02:11,  1.20s/it]
  iters:  46%|████▌     | 91/200 [01:51<02:11,  1.20s/it]
  iters:  46%|████▌     | 92/200 [01:52<02:09,  1.20s/it]
  iters:  46%|████▋     | 93/200 [01:53<02:08,  1.20s/it]
  iters:  47%|████▋     | 94/200 [01:54<02:08,  1.21s/it]
  iters:  48%|████▊     | 95/200 [01:55<02:06,  1.21s/it]
  iters:  48%|████▊     | 96/200 [01:57<02:05,  1.20s/it]
  iters:  48%|████▊     | 97/200 [01:58<02:07,  1.24s/it]
  iters:  49%|████▉     | 98/200 [01:59<02:05,  1.23s/it]
  iters:  50%|████▉     | 99/200 [02:00<02:03,  1.22s/it]
  iters:  50%|█████     | 100/200 [02:02<02:01,  1.22s/it]
  iters:  50%|█████     | 101/200 [02:03<02:00,  1.21s/it]
  iters:  51%|█████     | 102/200 [02:04<01:58,  1.21s/it]
  iters:  52%|█████▏    | 103/200 [02:05<01:57,  1.21s/it]
  iters:  52%|█████▏    | 104/200 [02:06<01:56,  1.21s/it]
  iters:  52%|█████▎    | 105/200 [02:08<01:54,  1.21s/it]
  iters:  53%|█████▎    | 106/200 [02:09<01:52,  1.20s/it]
  iters:  54%|█████▎    | 107/200 [02:10<01:51,  1.20s/it]
  iters:  54%|█████▍    | 108/200 [02:11<01:50,  1.20s/it]
  iters:  55%|█████▍    | 109/200 [02:12<01:49,  1.20s/it]
  iters:  55%|█████▌    | 110/200 [02:14<01:51,  1.24s/it]
  iters:  56%|█████▌    | 111/200 [02:15<01:49,  1.23s/it]
  iters:  56%|█████▌    | 112/200 [02:16<01:48,  1.23s/it]
  iters:  56%|█████▋    | 113/200 [02:17<01:50,  1.27s/it]
  iters:  57%|█████▋    | 114/200 [02:19<01:49,  1.27s/it]
  iters:  57%|█████▊    | 115/200 [02:20<01:46,  1.25s/it]
  iters:  58%|█████▊    | 116/200 [02:21<01:45,  1.25s/it]
  iters:  58%|█████▊    | 117/200 [02:22<01:43,  1.25s/it]
  iters:  59%|█████▉    | 118/200 [02:24<01:42,  1.25s/it]
  iters:  60%|█████▉    | 119/200 [02:25<01:40,  1.24s/it]
  iters:  60%|██████    | 120/200 [02:26<01:37,  1.22s/it]
  iters:  60%|██████    | 121/200 [02:27<01:35,  1.21s/it]
  iters:  61%|██████    | 122/200 [02:29<01:34,  1.22s/it]
  iters:  62%|██████▏   | 123/200 [02:30<01:35,  1.24s/it]
  iters:  62%|██████▏   | 124/200 [02:31<01:33,  1.23s/it]
  iters:  62%|██████▎   | 125/200 [02:32<01:32,  1.24s/it]
  iters:  63%|██████▎   | 126/200 [02:33<01:30,  1.22s/it]
  iters:  64%|██████▎   | 127/200 [02:35<01:28,  1.22s/it]
  iters:  64%|██████▍   | 128/200 [02:36<01:27,  1.21s/it]
  iters:  64%|██████▍   | 129/200 [02:37<01:25,  1.21s/it]
  iters:  65%|██████▌   | 130/200 [02:38<01:24,  1.21s/it]
  iters:  66%|██████▌   | 131/200 [02:40<01:25,  1.25s/it]
  iters:  66%|██████▌   | 132/200 [02:41<01:23,  1.23s/it]
  iters:  66%|██████▋   | 133/200 [02:42<01:21,  1.22s/it]
  iters:  67%|██████▋   | 134/200 [02:43<01:22,  1.25s/it]
  iters:  68%|██████▊   | 135/200 [02:45<01:20,  1.24s/it]
  iters:  68%|██████▊   | 136/200 [02:46<01:19,  1.24s/it]
  iters:  68%|██████▊   | 137/200 [02:47<01:17,  1.23s/it]
  iters:  69%|██████▉   | 138/200 [02:48<01:15,  1.22s/it]
  iters:  70%|██████▉   | 139/200 [02:49<01:14,  1.22s/it]
  iters:  70%|███████   | 140/200 [02:51<01:12,  1.21s/it]
  iters:  70%|███████   | 141/200 [02:52<01:11,  1.21s/it]
  iters:  71%|███████   | 142/200 [02:53<01:10,  1.21s/it]
  iters:  72%|███████▏  | 143/200 [02:54<01:08,  1.21s/it]
  iters:  72%|███████▏  | 144/200 [02:55<01:07,  1.21s/it]
  iters:  72%|███████▎  | 145/200 [02:57<01:06,  1.20s/it]
  iters:  73%|███████▎  | 146/200 [02:58<01:04,  1.20s/it]
  iters:  74%|███████▎  | 147/200 [02:59<01:03,  1.20s/it]
  iters:  74%|███████▍  | 148/200 [03:00<01:02,  1.20s/it]
  iters:  74%|███████▍  | 149/200 [03:02<01:02,  1.23s/it]
  iters:  75%|███████▌  | 150/200 [03:03<01:00,  1.22s/it]
  iters:  76%|███████▌  | 151/200 [03:04<00:59,  1.21s/it]
  iters:  76%|███████▌  | 152/200 [03:05<00:58,  1.22s/it]
  iters:  76%|███████▋  | 153/200 [03:06<00:56,  1.21s/it]
  iters:  77%|███████▋  | 154/200 [03:08<00:55,  1.21s/it]
  iters:  78%|███████▊  | 155/200 [03:09<00:54,  1.21s/it]
  iters:  78%|███████▊  | 156/200 [03:10<00:58,  1.32s/it]
  iters:  78%|███████▊  | 157/200 [03:12<00:55,  1.28s/it]
  iters:  79%|███████▉  | 158/200 [03:13<00:52,  1.26s/it]
  iters:  80%|███████▉  | 159/200 [03:14<00:50,  1.24s/it]
  iters:  80%|████████  | 160/200 [03:15<00:49,  1.23s/it]
  iters:  80%|████████  | 161/200 [03:16<00:47,  1.22s/it]
  iters:  81%|████████  | 162/200 [03:18<00:46,  1.22s/it]
  iters:  82%|████████▏ | 163/200 [03:19<00:44,  1.21s/it]
  iters:  82%|████████▏ | 164/200 [03:20<00:43,  1.21s/it]
  iters:  82%|████████▎ | 165/200 [03:21<00:42,  1.20s/it]
  iters:  83%|████████▎ | 166/200 [03:22<00:40,  1.20s/it]
  iters:  84%|████████▎ | 167/200 [03:24<00:39,  1.20s/it]
  iters:  84%|████████▍ | 168/200 [03:25<00:38,  1.20s/it]
  iters:  84%|████████▍ | 169/200 [03:26<00:37,  1.20s/it]
  iters:  85%|████████▌ | 170/200 [03:27<00:35,  1.20s/it]
  iters:  86%|████████▌ | 171/200 [03:28<00:34,  1.20s/it]
  iters:  86%|████████▌ | 172/200 [03:30<00:33,  1.20s/it]
  iters:  86%|████████▋ | 173/200 [03:31<00:32,  1.20s/it]
  iters:  87%|████████▋ | 174/200 [03:32<00:31,  1.23s/it]
  iters:  88%|████████▊ | 175/200 [03:33<00:30,  1.22s/it]
  iters:  88%|████████▊ | 176/200 [03:34<00:29,  1.23s/it]
  iters:  88%|████████▊ | 177/200 [03:36<00:28,  1.22s/it]
  iters:  89%|████████▉ | 178/200 [03:37<00:27,  1.24s/it]
  iters:  90%|████████▉ | 179/200 [03:38<00:25,  1.23s/it]
  iters:  90%|█████████ | 180/200 [03:39<00:24,  1.22s/it]
  iters:  90%|█████████ | 181/200 [03:41<00:23,  1.21s/it]
  iters:  91%|█████████ | 182/200 [03:42<00:21,  1.21s/it]
  iters:  92%|█████████▏| 183/200 [03:43<00:20,  1.21s/it]
  iters:  92%|█████████▏| 184/200 [03:44<00:19,  1.21s/it]
  iters:  92%|█████████▎| 185/200 [03:45<00:18,  1.20s/it]
  iters:  93%|█████████▎| 186/200 [03:47<00:16,  1.21s/it]
  iters:  94%|█████████▎| 187/200 [03:48<00:15,  1.21s/it]
  iters:  94%|█████████▍| 188/200 [03:49<00:14,  1.21s/it]
  iters:  94%|█████████▍| 189/200 [03:50<00:13,  1.23s/it]
  iters:  95%|█████████▌| 190/200 [03:51<00:12,  1.22s/it]
  iters:  96%|█████████▌| 191/200 [03:53<00:10,  1.21s/it]
  iters:  96%|█████████▌| 192/200 [03:54<00:09,  1.20s/it]
  iters:  96%|█████████▋| 193/200 [03:55<00:08,  1.21s/it]
  iters:  97%|█████████▋| 194/200 [03:56<00:07,  1.21s/it]
  iters:  98%|█████████▊| 195/200 [03:57<00:06,  1.20s/it]
  iters:  98%|█████████▊| 196/200 [03:59<00:04,  1.20s/it]
  iters:  98%|█████████▊| 197/200 [04:00<00:03,  1.20s/it]
  iters:  99%|█████████▉| 198/200 [04:01<00:02,  1.24s/it]
  iters: 100%|█████████▉| 199/200 [04:02<00:01,  1.24s/it]
  iters: 100%|██████████| 200/200 [04:04<00:00,  1.23s/it]

  [timing] data: 2.1s (1%) | forward: 58.9s (24%) | backward: 183.1s (75%) | total: 244.1s

Training:   0%|          | 0/4 [04:26<?, ?it/s, acc=0.9992, det=0.0085, edge=0.0004]

  Epoch   0/4 | edge=0.0004 | det=0.0085 | test_loss=0.0016 | acc=0.9992 | recall=0.9018 | best=0.9011 * | train=244.4s test=22.1s

Training:  25%|██▌       | 1/4 [04:26<13:19, 266.47s/it, acc=0.9992, det=0.0085, edge=0.0004]
  iters:   0%|          | 0/200 [00:00<?, ?it/s]
  iters:   0%|          | 1/200 [00:01<04:25,  1.33s/it]
  iters:   1%|          | 2/200 [00:02<04:09,  1.26s/it]
  iters:   2%|▏         | 3/200 [00:03<04:02,  1.23s/it]
  iters:   2%|▏         | 4/200 [00:04<04:01,  1.23s/it]
  iters:   2%|▎         | 5/200 [00:06<03:58,  1.22s/it]
  iters:   3%|▎         | 6/200 [00:07<03:55,  1.22s/it]
  iters:   4%|▎         | 7/200 [00:08<03:53,  1.21s/it]
  iters:   4%|▍         | 8/200 [00:09<03:51,  1.21s/it]
  iters:   4%|▍         | 9/200 [00:10<03:50,  1.21s/it]
  iters:   5%|▌         | 10/200 [00:12<03:50,  1.21s/it]
  iters:   6%|▌         | 11/200 [00:13<03:48,  1.21s/it]
  iters:   6%|▌         | 12/200 [00:14<03:46,  1.21s/it]
  iters:   6%|▋         | 13/200 [00:15<03:44,  1.20s/it]
  iters:   7%|▋         | 14/200 [00:17<03:43,  1.20s/it]
  iters:   8%|▊         | 15/200 [00:18<03:42,  1.20s/it]
  iters:   8%|▊         | 16/200 [00:19<03:41,  1.20s/it]
  iters:   8%|▊         | 17/200 [00:20<03:39,  1.20s/it]
  iters:   9%|▉         | 18/200 [00:21<03:38,  1.20s/it]
  iters:  10%|▉         | 19/200 [00:23<03:37,  1.20s/it]
  iters:  10%|█         | 20/200 [00:24<03:37,  1.21s/it]
  iters:  10%|█         | 21/200 [00:25<03:35,  1.20s/it]
  iters:  11%|█         | 22/200 [00:26<03:33,  1.20s/it]
  iters:  12%|█▏        | 23/200 [00:27<03:32,  1.20s/it]
  iters:  12%|█▏        | 24/200 [00:29<03:31,  1.20s/it]
  iters:  12%|█▎        | 25/200 [00:30<03:30,  1.20s/it]
  iters:  13%|█▎        | 26/200 [00:31<03:28,  1.20s/it]
  iters:  14%|█▎        | 27/200 [00:32<03:27,  1.20s/it]
  iters:  14%|█▍        | 28/200 [00:33<03:25,  1.20s/it]
  iters:  14%|█▍        | 29/200 [00:35<03:25,  1.20s/it]
  iters:  15%|█▌        | 30/200 [00:36<03:23,  1.20s/it]
  iters:  16%|█▌        | 31/200 [00:37<03:22,  1.20s/it]
  iters:  16%|█▌        | 32/200 [00:38<03:21,  1.20s/it]
  iters:  16%|█▋        | 33/200 [00:39<03:21,  1.21s/it]
  iters:  17%|█▋        | 34/200 [00:41<03:19,  1.20s/it]
  iters:  18%|█▊        | 35/200 [00:42<03:18,  1.21s/it]
  iters:  18%|█▊        | 36/200 [00:43<03:16,  1.20s/it]
  iters:  18%|█▊        | 37/200 [00:44<03:15,  1.20s/it]
  iters:  19%|█▉        | 38/200 [00:45<03:13,  1.20s/it]
  iters:  20%|█▉        | 39/200 [00:47<03:14,  1.21s/it]
  iters:  20%|██        | 40/200 [00:48<03:16,  1.23s/it]
  iters:  20%|██        | 41/200 [00:49<03:13,  1.22s/it]
  iters:  21%|██        | 42/200 [00:50<03:11,  1.21s/it]
  iters:  22%|██▏       | 43/200 [00:51<03:09,  1.21s/it]
  iters:  22%|██▏       | 44/200 [00:53<03:10,  1.22s/it]
  iters:  22%|██▎       | 45/200 [00:54<03:10,  1.23s/it]
  iters:  23%|██▎       | 46/200 [00:55<03:08,  1.22s/it]
  iters:  24%|██▎       | 47/200 [00:56<03:06,  1.22s/it]
  iters:  24%|██▍       | 48/200 [00:58<03:04,  1.21s/it]
  iters:  24%|██▍       | 49/200 [00:59<03:02,  1.21s/it]
  iters:  25%|██▌       | 50/200 [01:00<03:01,  1.21s/it]
  iters:  26%|██▌       | 51/200 [01:01<02:59,  1.21s/it]
  iters:  26%|██▌       | 52/200 [01:02<02:59,  1.22s/it]
  iters:  26%|██▋       | 53/200 [01:04<02:57,  1.21s/it]
  iters:  27%|██▋       | 54/200 [01:05<02:56,  1.21s/it]
  iters:  28%|██▊       | 55/200 [01:06<02:54,  1.20s/it]
  iters:  28%|██▊       | 56/200 [01:07<02:53,  1.20s/it]
  iters:  28%|██▊       | 57/200 [01:08<02:51,  1.20s/it]
  iters:  29%|██▉       | 58/200 [01:10<02:50,  1.20s/it]
  iters:  30%|██▉       | 59/200 [01:11<02:49,  1.20s/it]
  iters:  30%|███       | 60/200 [01:12<02:48,  1.20s/it]
  iters:  30%|███       | 61/200 [01:13<02:50,  1.22s/it]
  iters:  31%|███       | 62/200 [01:14<02:47,  1.22s/it]
  iters:  32%|███▏      | 63/200 [01:16<02:48,  1.23s/it]
  iters:  32%|███▏      | 64/200 [01:17<02:46,  1.22s/it]
  iters:  32%|███▎      | 65/200 [01:18<02:43,  1.21s/it]
  iters:  33%|███▎      | 66/200 [01:19<02:41,  1.21s/it]
  iters:  34%|███▎      | 67/200 [01:20<02:39,  1.20s/it]
  iters:  34%|███▍      | 68/200 [01:22<02:38,  1.20s/it]
  iters:  34%|███▍      | 69/200 [01:23<02:37,  1.20s/it]
  iters:  35%|███▌      | 70/200 [01:24<02:36,  1.20s/it]
  iters:  36%|███▌      | 71/200 [01:25<02:38,  1.23s/it]
  iters:  36%|███▌      | 72/200 [01:27<02:36,  1.22s/it]
  iters:  36%|███▋      | 73/200 [01:28<02:37,  1.24s/it]
  iters:  37%|███▋      | 74/200 [01:29<02:39,  1.26s/it]
  iters:  38%|███▊      | 75/200 [01:30<02:35,  1.24s/it]
  iters:  38%|███▊      | 76/200 [01:32<02:33,  1.24s/it]
  iters:  38%|███▊      | 77/200 [01:33<02:30,  1.23s/it]
  iters:  39%|███▉      | 78/200 [01:34<02:28,  1.22s/it]
  iters:  40%|███▉      | 79/200 [01:35<02:28,  1.23s/it]
  iters:  40%|████      | 80/200 [01:36<02:26,  1.22s/it]
  iters:  40%|████      | 81/200 [01:38<02:25,  1.22s/it]
  iters:  41%|████      | 82/200 [01:39<02:25,  1.23s/it]
  iters:  42%|████▏     | 83/200 [01:40<02:22,  1.22s/it]
  iters:  42%|████▏     | 84/200 [01:41<02:23,  1.23s/it]
  iters:  42%|████▎     | 85/200 [01:43<02:20,  1.22s/it]
  iters:  43%|████▎     | 86/200 [01:44<02:22,  1.25s/it]
  iters:  44%|████▎     | 87/200 [01:45<02:19,  1.23s/it]
  iters:  44%|████▍     | 88/200 [01:46<02:16,  1.22s/it]
  iters:  44%|████▍     | 89/200 [01:48<02:16,  1.23s/it]
  iters:  45%|████▌     | 90/200 [01:49<02:14,  1.22s/it]
  iters:  46%|████▌     | 91/200 [01:50<02:12,  1.21s/it]
  iters:  46%|████▌     | 92/200 [01:51<02:10,  1.21s/it]
  iters:  46%|████▋     | 93/200 [01:52<02:12,  1.24s/it]
  iters:  47%|████▋     | 94/200 [01:54<02:09,  1.23s/it]
  iters:  48%|████▊     | 95/200 [01:55<02:10,  1.25s/it]
  iters:  48%|████▊     | 96/200 [01:56<02:08,  1.23s/it]
  iters:  48%|████▊     | 97/200 [01:57<02:06,  1.22s/it]
  iters:  49%|████▉     | 98/200 [01:59<02:04,  1.22s/it]
  iters:  50%|████▉     | 99/200 [02:00<02:02,  1.21s/it]
  iters:  50%|█████     | 100/200 [02:01<02:03,  1.24s/it]
  iters:  50%|█████     | 101/200 [02:02<02:01,  1.22s/it]
  iters:  51%|█████     | 102/200 [02:03<02:00,  1.23s/it]
  iters:  52%|█████▏    | 103/200 [02:05<01:58,  1.22s/it]
  iters:  52%|█████▏    | 104/200 [02:06<01:56,  1.21s/it]
  iters:  52%|█████▎    | 105/200 [02:07<01:56,  1.23s/it]
  iters:  53%|█████▎    | 106/200 [02:08<01:57,  1.25s/it]
  iters:  54%|█████▎    | 107/200 [02:10<01:54,  1.23s/it]
  iters:  54%|█████▍    | 108/200 [02:11<01:52,  1.22s/it]
  iters:  55%|█████▍    | 109/200 [02:12<01:50,  1.22s/it]
  iters:  55%|█████▌    | 110/200 [02:13<01:48,  1.21s/it]
  iters:  56%|█████▌    | 111/200 [02:14<01:47,  1.21s/it]
  iters:  56%|█████▌    | 112/200 [02:16<01:46,  1.21s/it]
  iters:  56%|█████▋    | 113/200 [02:17<01:44,  1.21s/it]
  iters:  57%|█████▋    | 114/200 [02:18<01:43,  1.21s/it]
  iters:  57%|█████▊    | 115/200 [02:19<01:45,  1.24s/it]
  iters:  58%|█████▊    | 116/200 [02:21<01:46,  1.26s/it]
  iters:  58%|█████▊    | 117/200 [02:22<01:43,  1.25s/it]
  iters:  59%|█████▉    | 118/200 [02:23<01:40,  1.23s/it]
  iters:  60%|█████▉    | 119/200 [02:24<01:40,  1.24s/it]
  iters:  60%|██████    | 120/200 [02:26<01:37,  1.22s/it]
  iters:  60%|██████    | 121/200 [02:27<01:36,  1.22s/it]
  iters:  61%|██████    | 122/200 [02:28<01:34,  1.21s/it]
  iters:  62%|██████▏   | 123/200 [02:29<01:32,  1.20s/it]
  iters:  62%|██████▏   | 124/200 [02:30<01:31,  1.20s/it]
  iters:  62%|██████▎   | 125/200 [02:31<01:29,  1.20s/it]
  iters:  63%|██████▎   | 126/200 [02:33<01:28,  1.20s/it]
  iters:  64%|██████▎   | 127/200 [02:34<01:27,  1.20s/it]
  iters:  64%|██████▍   | 128/200 [02:35<01:28,  1.23s/it]
  iters:  64%|██████▍   | 129/200 [02:37<01:37,  1.37s/it]
  iters:  65%|██████▌   | 130/200 [02:38<01:32,  1.32s/it]
  iters:  66%|██████▌   | 131/200 [02:39<01:28,  1.28s/it]
  iters:  66%|██████▌   | 132/200 [02:40<01:25,  1.25s/it]
  iters:  66%|██████▋   | 133/200 [02:42<01:22,  1.24s/it]
  iters:  67%|██████▋   | 134/200 [02:43<01:20,  1.22s/it]
  iters:  68%|██████▊   | 135/200 [02:44<01:19,  1.23s/it]
  iters:  68%|██████▊   | 136/200 [02:45<01:20,  1.25s/it]
  iters:  68%|██████▊   | 137/200 [02:47<01:17,  1.23s/it]
  iters:  69%|██████▉   | 138/200 [02:48<01:15,  1.22s/it]
  iters:  70%|██████▉   | 139/200 [02:49<01:14,  1.21s/it]
  iters:  70%|███████   | 140/200 [02:50<01:12,  1.21s/it]
  iters:  70%|███████   | 141/200 [02:51<01:10,  1.20s/it]
  iters:  71%|███████   | 142/200 [02:53<01:09,  1.20s/it]
  iters:  72%|███████▏  | 143/200 [02:54<01:08,  1.21s/it]
  iters:  72%|███████▏  | 144/200 [02:55<01:07,  1.20s/it]
  iters:  72%|███████▎  | 145/200 [02:56<01:08,  1.24s/it]
  iters:  73%|███████▎  | 146/200 [02:58<01:06,  1.23s/it]
  iters:  74%|███████▎  | 147/200 [02:59<01:04,  1.22s/it]
  iters:  74%|███████▍  | 148/200 [03:00<01:03,  1.22s/it]
  iters:  74%|███████▍  | 149/200 [03:01<01:01,  1.21s/it]
  iters:  75%|███████▌  | 150/200 [03:02<01:00,  1.21s/it]
  iters:  76%|███████▌  | 151/200 [03:04<00:59,  1.21s/it]
  iters:  76%|███████▌  | 152/200 [03:05<00:58,  1.21s/it]
  iters:  76%|███████▋  | 153/200 [03:06<00:56,  1.21s/it]
  iters:  77%|███████▋  | 154/200 [03:07<00:55,  1.21s/it]
  iters:  78%|███████▊  | 155/200 [03:08<00:54,  1.21s/it]
  iters:  78%|███████▊  | 156/200 [03:10<00:53,  1.22s/it]
  iters:  78%|███████▊  | 157/200 [03:11<00:52,  1.21s/it]
  iters:  79%|███████▉  | 158/200 [03:12<00:50,  1.21s/it]
  iters:  80%|███████▉  | 159/200 [03:13<00:49,  1.21s/it]
  iters:  80%|████████  | 160/200 [03:14<00:48,  1.21s/it]
  iters:  80%|████████  | 161/200 [03:16<00:47,  1.21s/it]
  iters:  81%|████████  | 162/200 [03:17<00:45,  1.21s/it]
  iters:  82%|████████▏ | 163/200 [03:18<00:44,  1.21s/it]
  iters:  82%|████████▏ | 164/200 [03:19<00:43,  1.21s/it]
  iters:  82%|████████▎ | 165/200 [03:20<00:42,  1.21s/it]
  iters:  83%|████████▎ | 166/200 [03:22<00:41,  1.21s/it]
  iters:  84%|████████▎ | 167/200 [03:23<00:39,  1.21s/it]
  iters:  84%|████████▍ | 168/200 [03:24<00:39,  1.22s/it]
  iters:  84%|████████▍ | 169/200 [03:25<00:37,  1.22s/it]
  iters:  85%|████████▌ | 170/200 [03:27<00:36,  1.21s/it]
  iters:  86%|████████▌ | 171/200 [03:28<00:35,  1.21s/it]
  iters:  86%|████████▌ | 172/200 [03:29<00:34,  1.22s/it]
  iters:  86%|████████▋ | 173/200 [03:30<00:32,  1.22s/it]
  iters:  87%|████████▋ | 174/200 [03:31<00:32,  1.25s/it]
  iters:  88%|████████▊ | 175/200 [03:33<00:30,  1.23s/it]
  iters:  88%|████████▊ | 176/200 [03:34<00:29,  1.24s/it]
  iters:  88%|████████▊ | 177/200 [03:35<00:28,  1.23s/it]
  iters:  89%|████████▉ | 178/200 [03:36<00:26,  1.22s/it]
  iters:  90%|████████▉ | 179/200 [03:38<00:25,  1.22s/it]
  iters:  90%|█████████ | 180/200 [03:39<00:24,  1.24s/it]
  iters:  90%|█████████ | 181/200 [03:40<00:23,  1.23s/it]
  iters:  91%|█████████ | 182/200 [03:41<00:22,  1.24s/it]
  iters:  92%|█████████▏| 183/200 [03:43<00:20,  1.22s/it]
  iters:  92%|█████████▏| 184/200 [03:44<00:19,  1.22s/it]
  iters:  92%|█████████▎| 185/200 [03:45<00:18,  1.21s/it]
  iters:  93%|█████████▎| 186/200 [03:46<00:16,  1.21s/it]
  iters:  94%|█████████▎| 187/200 [03:47<00:15,  1.21s/it]
  iters:  94%|█████████▍| 188/200 [03:49<00:14,  1.21s/it]
  iters:  94%|█████████▍| 189/200 [03:50<00:13,  1.20s/it]
  iters:  95%|█████████▌| 190/200 [03:51<00:11,  1.20s/it]
  iters:  96%|█████████▌| 191/200 [03:52<00:10,  1.22s/it]
  iters:  96%|█████████▌| 192/200 [03:53<00:09,  1.21s/it]
  iters:  96%|█████████▋| 193/200 [03:55<00:08,  1.23s/it]
  iters:  97%|█████████▋| 194/200 [03:56<00:07,  1.22s/it]
  iters:  98%|█████████▊| 195/200 [03:57<00:06,  1.22s/it]
  iters:  98%|█████████▊| 196/200 [03:58<00:04,  1.21s/it]
  iters:  98%|█████████▊| 197/200 [03:59<00:03,  1.21s/it]
  iters:  99%|█████████▉| 198/200 [04:01<00:02,  1.23s/it]
  iters: 100%|█████████▉| 199/200 [04:02<00:01,  1.23s/it]
  iters: 100%|██████████| 200/200 [04:03<00:00,  1.22s/it]

  [timing] data: 2.1s (1%) | forward: 58.7s (24%) | backward: 182.9s (75%) | total: 243.6s

Training:  25%|██▌       | 1/4 [08:52<13:19, 266.47s/it, acc=0.9992, det=0.0078, edge=0.0006]

  Epoch   1/4 | edge=0.0006 | det=0.0078 | test_loss=0.0012 | acc=0.9992 | recall=0.9004 | best=0.9011   | train=243.8s test=21.8s

Training:  50%|█████     | 2/4 [08:52<08:51, 265.99s/it, acc=0.9992, det=0.0078, edge=0.0006]
  iters:   0%|          | 0/200 [00:00<?, ?it/s]
  iters:   0%|          | 1/200 [00:01<04:27,  1.34s/it]
  iters:   1%|          | 2/200 [00:02<04:08,  1.26s/it]
  iters:   2%|▏         | 3/200 [00:03<04:13,  1.29s/it]
  iters:   2%|▏         | 4/200 [00:05<04:05,  1.25s/it]
  iters:   2%|▎         | 5/200 [00:06<03:59,  1.23s/it]
  iters:   3%|▎         | 6/200 [00:07<04:02,  1.25s/it]
  iters:   4%|▎         | 7/200 [00:08<03:57,  1.23s/it]
  iters:   4%|▍         | 8/200 [00:09<03:54,  1.22s/it]
  iters:   4%|▍         | 9/200 [00:11<03:51,  1.21s/it]
  iters:   5%|▌         | 10/200 [00:12<03:49,  1.21s/it]
  iters:   6%|▌         | 11/200 [00:13<03:49,  1.21s/it]
  iters:   6%|▌         | 12/200 [00:14<03:47,  1.21s/it]
  iters:   6%|▋         | 13/200 [00:15<03:44,  1.20s/it]
  iters:   7%|▋         | 14/200 [00:17<03:43,  1.20s/it]
  iters:   8%|▊         | 15/200 [00:18<03:47,  1.23s/it]
  iters:   8%|▊         | 16/200 [00:19<03:44,  1.22s/it]
  iters:   8%|▊         | 17/200 [00:20<03:42,  1.21s/it]
  iters:   9%|▉         | 18/200 [00:22<03:40,  1.21s/it]
  iters:  10%|▉         | 19/200 [00:23<03:38,  1.21s/it]
  iters:  10%|█         | 20/200 [00:24<03:37,  1.21s/it]
  iters:  10%|█         | 21/200 [00:25<03:42,  1.24s/it]
  iters:  11%|█         | 22/200 [00:26<03:38,  1.23s/it]
  iters:  12%|█▏        | 23/200 [00:28<03:35,  1.22s/it]
  iters:  12%|█▏        | 24/200 [00:29<03:33,  1.21s/it]
  iters:  12%|█▎        | 25/200 [00:30<03:31,  1.21s/it]
  iters:  13%|█▎        | 26/200 [00:31<03:29,  1.21s/it]
  iters:  14%|█▎        | 27/200 [00:32<03:28,  1.20s/it]
  iters:  14%|█▍        | 28/200 [00:34<03:26,  1.20s/it]
  iters:  14%|█▍        | 29/200 [00:35<03:32,  1.24s/it]
  iters:  15%|█▌        | 30/200 [00:36<03:28,  1.23s/it]
  iters:  16%|█▌        | 31/200 [00:37<03:25,  1.22s/it]
  iters:  16%|█▌        | 32/200 [00:39<03:25,  1.22s/it]
  iters:  16%|█▋        | 33/200 [00:40<03:23,  1.22s/it]
  iters:  17%|█▋        | 34/200 [00:41<03:21,  1.21s/it]
  iters:  18%|█▊        | 35/200 [00:42<03:22,  1.23s/it]
  iters:  18%|█▊        | 36/200 [00:43<03:20,  1.22s/it]
  iters:  18%|█▊        | 37/200 [00:45<03:18,  1.22s/it]
  iters:  19%|█▉        | 38/200 [00:46<03:19,  1.23s/it]
  iters:  20%|█▉        | 39/200 [00:47<03:16,  1.22s/it]
  iters:  20%|██        | 40/200 [00:48<03:17,  1.23s/it]
  iters:  20%|██        | 41/200 [00:50<03:13,  1.22s/it]
  iters:  21%|██        | 42/200 [00:51<03:14,  1.23s/it]
  iters:  22%|██▏       | 43/200 [00:52<03:12,  1.22s/it]
  iters:  22%|██▏       | 44/200 [00:53<03:10,  1.22s/it]
  iters:  22%|██▎       | 45/200 [00:54<03:07,  1.21s/it]
  iters:  23%|██▎       | 46/200 [00:56<03:05,  1.21s/it]
  iters:  24%|██▎       | 47/200 [00:57<03:04,  1.20s/it]
  iters:  24%|██▍       | 48/200 [00:58<03:02,  1.20s/it]
  iters:  24%|██▍       | 49/200 [00:59<03:00,  1.20s/it]
  iters:  25%|██▌       | 50/200 [01:01<03:04,  1.23s/it]
  iters:  26%|██▌       | 51/200 [01:02<03:02,  1.22s/it]
  iters:  26%|██▌       | 52/200 [01:03<02:59,  1.21s/it]
  iters:  26%|██▋       | 53/200 [01:04<02:57,  1.21s/it]
  iters:  27%|██▋       | 54/200 [01:05<02:55,  1.20s/it]
  iters:  28%|██▊       | 55/200 [01:07<02:54,  1.20s/it]
  iters:  28%|██▊       | 56/200 [01:08<02:52,  1.20s/it]
  iters:  28%|██▊       | 57/200 [01:09<02:51,  1.20s/it]
  iters:  29%|██▉       | 58/200 [01:10<02:50,  1.20s/it]
  iters:  30%|██▉       | 59/200 [01:11<02:50,  1.21s/it]
  iters:  30%|███       | 60/200 [01:13<02:49,  1.21s/it]
  iters:  30%|███       | 61/200 [01:14<02:47,  1.20s/it]
  iters:  31%|███       | 62/200 [01:15<02:45,  1.20s/it]
  iters:  32%|███▏      | 63/200 [01:16<02:44,  1.20s/it]
  iters:  32%|███▏      | 64/200 [01:17<02:43,  1.20s/it]
  iters:  32%|███▎      | 65/200 [01:19<02:41,  1.20s/it]
  iters:  33%|███▎      | 66/200 [01:20<02:40,  1.20s/it]
  iters:  34%|███▎      | 67/200 [01:21<02:40,  1.20s/it]
  iters:  34%|███▍      | 68/200 [01:22<02:38,  1.20s/it]
  iters:  34%|███▍      | 69/200 [01:23<02:38,  1.21s/it]
  iters:  35%|███▌      | 70/200 [01:25<02:37,  1.21s/it]
  iters:  36%|███▌      | 71/200 [01:26<02:37,  1.22s/it]
  iters:  36%|███▌      | 72/200 [01:27<02:35,  1.21s/it]
  iters:  36%|███▋      | 73/200 [01:28<02:34,  1.21s/it]
  iters:  37%|███▋      | 74/200 [01:30<02:36,  1.24s/it]
  iters:  38%|███▊      | 75/200 [01:31<02:33,  1.23s/it]
  iters:  38%|███▊      | 76/200 [01:32<02:31,  1.22s/it]
  iters:  38%|███▊      | 77/200 [01:33<02:29,  1.21s/it]
  iters:  39%|███▉      | 78/200 [01:34<02:27,  1.21s/it]
  iters:  40%|███▉      | 79/200 [01:36<02:30,  1.24s/it]
  iters:  40%|████      | 80/200 [01:37<02:27,  1.23s/it]
  iters:  40%|████      | 81/200 [01:38<02:25,  1.22s/it]
  iters:  41%|████      | 82/200 [01:39<02:22,  1.21s/it]
  iters:  42%|████▏     | 83/200 [01:40<02:21,  1.21s/it]
  iters:  42%|████▏     | 84/200 [01:42<02:19,  1.21s/it]
  iters:  42%|████▎     | 85/200 [01:43<02:18,  1.21s/it]
  iters:  43%|████▎     | 86/200 [01:44<02:20,  1.23s/it]
  iters:  44%|████▎     | 87/200 [01:45<02:18,  1.23s/it]
  iters:  44%|████▍     | 88/200 [01:47<02:18,  1.23s/it]
  iters:  44%|████▍     | 89/200 [01:48<02:18,  1.24s/it]
  iters:  45%|████▌     | 90/200 [01:49<02:15,  1.23s/it]
  iters:  46%|████▌     | 91/200 [01:50<02:12,  1.22s/it]
  iters:  46%|████▌     | 92/200 [01:51<02:10,  1.21s/it]
  iters:  46%|████▋     | 93/200 [01:53<02:08,  1.21s/it]
  iters:  47%|████▋     | 94/200 [01:54<02:07,  1.20s/it]
  iters:  48%|████▊     | 95/200 [01:55<02:06,  1.20s/it]
  iters:  48%|████▊     | 96/200 [01:56<02:05,  1.20s/it]
  iters:  48%|████▊     | 97/200 [01:57<02:04,  1.21s/it]
  iters:  49%|████▉     | 98/200 [01:59<02:06,  1.24s/it]
  iters:  50%|████▉     | 99/200 [02:00<02:04,  1.23s/it]
  iters:  50%|█████     | 100/200 [02:01<02:01,  1.22s/it]
  iters:  50%|█████     | 101/200 [02:02<01:59,  1.21s/it]
  iters:  51%|█████     | 102/200 [02:04<01:58,  1.21s/it]
  iters:  52%|█████▏    | 103/200 [02:05<01:56,  1.20s/it]
  iters:  52%|█████▏    | 104/200 [02:06<01:55,  1.21s/it]
  iters:  52%|█████▎    | 105/200 [02:07<01:54,  1.21s/it]
  iters:  53%|█████▎    | 106/200 [02:08<01:53,  1.21s/it]
  iters:  54%|█████▎    | 107/200 [02:10<01:54,  1.23s/it]
  iters:  54%|█████▍    | 108/200 [02:11<01:52,  1.22s/it]
  iters:  55%|█████▍    | 109/200 [02:12<01:50,  1.21s/it]
  iters:  55%|█████▌    | 110/200 [02:13<01:50,  1.22s/it]
  iters:  56%|█████▌    | 111/200 [02:15<01:51,  1.25s/it]
  iters:  56%|█████▌    | 112/200 [02:16<01:48,  1.23s/it]
  iters:  56%|█████▋    | 113/200 [02:17<01:52,  1.29s/it]
  iters:  57%|█████▋    | 114/200 [02:18<01:49,  1.27s/it]
  iters:  57%|█████▊    | 115/200 [02:20<01:46,  1.25s/it]
  iters:  58%|█████▊    | 116/200 [02:21<01:43,  1.23s/it]
  iters:  58%|█████▊    | 117/200 [02:22<01:41,  1.23s/it]
  iters:  59%|█████▉    | 118/200 [02:23<01:41,  1.24s/it]
  iters:  60%|█████▉    | 119/200 [02:25<01:40,  1.24s/it]
  iters:  60%|██████    | 120/200 [02:26<01:37,  1.22s/it]
  iters:  60%|██████    | 121/200 [02:27<01:35,  1.21s/it]
  iters:  61%|██████    | 122/200 [02:28<01:34,  1.21s/it]
  iters:  62%|██████▏   | 123/200 [02:29<01:32,  1.20s/it]
  iters:  62%|██████▏   | 124/200 [02:31<01:32,  1.21s/it]
  iters:  62%|██████▎   | 125/200 [02:32<01:30,  1.21s/it]
  iters:  63%|██████▎   | 126/200 [02:33<01:30,  1.22s/it]
  iters:  64%|██████▎   | 127/200 [02:34<01:30,  1.24s/it]
  iters:  64%|██████▍   | 128/200 [02:36<01:28,  1.22s/it]
  iters:  64%|██████▍   | 129/200 [02:37<01:26,  1.22s/it]
  iters:  65%|██████▌   | 130/200 [02:38<01:26,  1.23s/it]
  iters:  66%|██████▌   | 131/200 [02:39<01:24,  1.22s/it]
  iters:  66%|██████▌   | 132/200 [02:40<01:22,  1.22s/it]
  iters:  66%|██████▋   | 133/200 [02:42<01:21,  1.21s/it]
  iters:  67%|██████▋   | 134/200 [02:43<01:19,  1.21s/it]
  iters:  68%|██████▊   | 135/200 [02:44<01:18,  1.20s/it]
  iters:  68%|██████▊   | 136/200 [02:45<01:16,  1.20s/it]
  iters:  68%|██████▊   | 137/200 [02:46<01:16,  1.22s/it]
  iters:  69%|██████▉   | 138/200 [02:48<01:15,  1.21s/it]
  iters:  70%|██████▉   | 139/200 [02:49<01:14,  1.22s/it]
  iters:  70%|███████   | 140/200 [02:50<01:12,  1.21s/it]
  iters:  70%|███████   | 141/200 [02:51<01:11,  1.21s/it]
  iters:  71%|███████   | 142/200 [02:52<01:09,  1.20s/it]
  iters:  72%|███████▏  | 143/200 [02:54<01:08,  1.21s/it]
  iters:  72%|███████▏  | 144/200 [02:55<01:07,  1.21s/it]
  iters:  72%|███████▎  | 145/200 [02:56<01:06,  1.20s/it]
  iters:  73%|███████▎  | 146/200 [02:57<01:04,  1.20s/it]
  iters:  74%|███████▎  | 147/200 [02:58<01:03,  1.20s/it]
  iters:  74%|███████▍  | 148/200 [03:00<01:02,  1.20s/it]
  iters:  74%|███████▍  | 149/200 [03:01<01:01,  1.20s/it]
  iters:  75%|███████▌  | 150/200 [03:02<00:59,  1.20s/it]
  iters:  76%|███████▌  | 151/200 [03:03<00:58,  1.20s/it]
  iters:  76%|███████▌  | 152/200 [03:04<00:57,  1.20s/it]
  iters:  76%|███████▋  | 153/200 [03:06<00:56,  1.20s/it]
  iters:  77%|███████▋  | 154/200 [03:07<00:55,  1.21s/it]
  iters:  78%|███████▊  | 155/200 [03:08<00:54,  1.21s/it]
  iters:  78%|███████▊  | 156/200 [03:09<00:53,  1.21s/it]
  iters:  78%|███████▊  | 157/200 [03:11<00:51,  1.20s/it]
  iters:  79%|███████▉  | 158/200 [03:12<00:51,  1.22s/it]
  iters:  80%|███████▉  | 159/200 [03:13<00:50,  1.24s/it]
  iters:  80%|████████  | 160/200 [03:14<00:49,  1.23s/it]
  iters:  80%|████████  | 161/200 [03:15<00:47,  1.22s/it]
  iters:  81%|████████  | 162/200 [03:17<00:46,  1.21s/it]
  iters:  82%|████████▏ | 163/200 [03:18<00:44,  1.21s/it]
  iters:  82%|████████▏ | 164/200 [03:19<00:43,  1.20s/it]
  iters:  82%|████████▎ | 165/200 [03:20<00:43,  1.24s/it]
  iters:  83%|████████▎ | 166/200 [03:22<00:41,  1.23s/it]
  iters:  84%|████████▎ | 167/200 [03:23<00:41,  1.24s/it]
  iters:  84%|████████▍ | 168/200 [03:24<00:40,  1.27s/it]
  iters:  84%|████████▍ | 169/200 [03:25<00:39,  1.26s/it]
  iters:  85%|████████▌ | 170/200 [03:27<00:37,  1.24s/it]
  iters:  86%|████████▌ | 171/200 [03:28<00:35,  1.23s/it]
  iters:  86%|████████▌ | 172/200 [03:29<00:34,  1.22s/it]
  iters:  86%|████████▋ | 173/200 [03:30<00:32,  1.22s/it]
  iters:  87%|████████▋ | 174/200 [03:31<00:31,  1.21s/it]
  iters:  88%|████████▊ | 175/200 [03:33<00:30,  1.20s/it]
  iters:  88%|████████▊ | 176/200 [03:34<00:28,  1.20s/it]
  iters:  88%|████████▊ | 177/200 [03:35<00:27,  1.20s/it]
  iters:  89%|████████▉ | 178/200 [03:36<00:26,  1.20s/it]
  iters:  90%|████████▉ | 179/200 [03:37<00:25,  1.19s/it]
  iters:  90%|█████████ | 180/200 [03:39<00:23,  1.20s/it]
  iters:  90%|█████████ | 181/200 [03:40<00:22,  1.19s/it]
  iters:  91%|█████████ | 182/200 [03:41<00:21,  1.19s/it]
  iters:  92%|█████████▏| 183/200 [03:42<00:20,  1.20s/it]
  iters:  92%|█████████▏| 184/200 [03:43<00:19,  1.22s/it]
  iters:  92%|█████████▎| 185/200 [03:45<00:18,  1.22s/it]
  iters:  93%|█████████▎| 186/200 [03:46<00:16,  1.21s/it]
  iters:  94%|█████████▎| 187/200 [03:47<00:15,  1.20s/it]
  iters:  94%|█████████▍| 188/200 [03:48<00:14,  1.20s/it]
  iters:  94%|█████████▍| 189/200 [03:49<00:13,  1.20s/it]
  iters:  95%|█████████▌| 190/200 [03:51<00:12,  1.20s/it]
  iters:  96%|█████████▌| 191/200 [03:52<00:10,  1.20s/it]
  iters:  96%|█████████▌| 192/200 [03:53<00:09,  1.21s/it]
  iters:  96%|█████████▋| 193/200 [03:54<00:08,  1.20s/it]
  iters:  97%|█████████▋| 194/200 [03:55<00:07,  1.22s/it]
  iters:  98%|█████████▊| 195/200 [03:57<00:06,  1.23s/it]
  iters:  98%|█████████▊| 196/200 [03:58<00:04,  1.22s/it]
  iters:  98%|█████████▊| 197/200 [03:59<00:03,  1.21s/it]
  iters:  99%|█████████▉| 198/200 [04:00<00:02,  1.20s/it]
  iters: 100%|█████████▉| 199/200 [04:02<00:01,  1.20s/it]
  iters: 100%|██████████| 200/200 [04:03<00:00,  1.20s/it]

  [timing] data: 2.1s (1%) | forward: 58.4s (24%) | backward: 182.7s (75%) | total: 243.2s

Training:  50%|█████     | 2/4 [13:17<08:51, 265.99s/it, acc=0.9997, det=0.0072, edge=0.0003]

  Epoch   2/4 | edge=0.0003 | det=0.0072 | test_loss=0.0009 | acc=0.9997 | recall=0.8714 | best=0.9011   | train=243.4s test=21.8s

Training:  75%|███████▌  | 3/4 [13:17<04:25, 265.60s/it, acc=0.9997, det=0.0072, edge=0.0003]
  iters:   0%|          | 0/200 [00:00<?, ?it/s]
  iters:   0%|          | 1/200 [00:01<04:52,  1.47s/it]
  iters:   1%|          | 2/200 [00:02<04:18,  1.30s/it]
  iters:   2%|▏         | 3/200 [00:03<04:07,  1.25s/it]
  iters:   2%|▏         | 4/200 [00:05<04:01,  1.23s/it]
  iters:   2%|▎         | 5/200 [00:06<04:01,  1.24s/it]
  iters:   3%|▎         | 6/200 [00:07<03:57,  1.22s/it]
  iters:   4%|▎         | 7/200 [00:08<03:54,  1.21s/it]
  iters:   4%|▍         | 8/200 [00:09<03:52,  1.21s/it]
  iters:   4%|▍         | 9/200 [00:11<03:50,  1.21s/it]
  iters:   5%|▌         | 10/200 [00:12<03:48,  1.21s/it]
  iters:   6%|▌         | 11/200 [00:13<03:47,  1.20s/it]
  iters:   6%|▌         | 12/200 [00:14<03:45,  1.20s/it]
  iters:   6%|▋         | 13/200 [00:15<03:44,  1.20s/it]
  iters:   7%|▋         | 14/200 [00:17<03:43,  1.20s/it]
  iters:   8%|▊         | 15/200 [00:18<03:41,  1.20s/it]
  iters:   8%|▊         | 16/200 [00:19<03:40,  1.20s/it]
  iters:   8%|▊         | 17/200 [00:20<03:38,  1.19s/it]
  iters:   9%|▉         | 18/200 [00:21<03:44,  1.23s/it]
  iters:  10%|▉         | 19/200 [00:23<03:41,  1.22s/it]
  iters:  10%|█         | 20/200 [00:24<03:42,  1.23s/it]
  iters:  10%|█         | 21/200 [00:25<03:38,  1.22s/it]
  iters:  11%|█         | 22/200 [00:26<03:36,  1.21s/it]
  iters:  12%|█▏        | 23/200 [00:28<03:34,  1.21s/it]
  iters:  12%|█▏        | 24/200 [00:29<03:32,  1.21s/it]
  iters:  12%|█▎        | 25/200 [00:30<03:30,  1.20s/it]
  iters:  13%|█▎        | 26/200 [00:31<03:29,  1.20s/it]
  iters:  14%|█▎        | 27/200 [00:32<03:28,  1.20s/it]
  iters:  14%|█▍        | 28/200 [00:34<03:26,  1.20s/it]
  iters:  14%|█▍        | 29/200 [00:35<03:25,  1.20s/it]
  iters:  15%|█▌        | 30/200 [00:36<03:24,  1.20s/it]
  iters:  16%|█▌        | 31/200 [00:37<03:23,  1.20s/it]
  iters:  16%|█▌        | 32/200 [00:38<03:27,  1.23s/it]
  iters:  16%|█▋        | 33/200 [00:40<03:24,  1.22s/it]
  iters:  17%|█▋        | 34/200 [00:41<03:22,  1.22s/it]
  iters:  18%|█▊        | 35/200 [00:42<03:21,  1.22s/it]
  iters:  18%|█▊        | 36/200 [00:43<03:20,  1.23s/it]
  iters:  18%|█▊        | 37/200 [00:45<03:21,  1.23s/it]
  iters:  19%|█▉        | 38/200 [00:46<03:20,  1.24s/it]
  iters:  20%|█▉        | 39/200 [00:47<03:17,  1.23s/it]
  iters:  20%|██        | 40/200 [00:48<03:20,  1.25s/it]
  iters:  20%|██        | 41/200 [00:50<03:20,  1.26s/it]
  iters:  21%|██        | 42/200 [00:51<03:16,  1.24s/it]
  iters:  22%|██▏       | 43/200 [00:52<03:12,  1.23s/it]
  iters:  22%|██▏       | 44/200 [00:53<03:10,  1.22s/it]
  iters:  22%|██▎       | 45/200 [00:54<03:07,  1.21s/it]
  iters:  23%|██▎       | 46/200 [00:56<03:05,  1.21s/it]
  iters:  24%|██▎       | 47/200 [00:57<03:06,  1.22s/it]
  iters:  24%|██▍       | 48/200 [00:58<03:09,  1.24s/it]
  iters:  24%|██▍       | 49/200 [00:59<03:05,  1.23s/it]
  iters:  25%|██▌       | 50/200 [01:01<03:02,  1.22s/it]
  iters:  26%|██▌       | 51/200 [01:02<03:00,  1.21s/it]
  iters:  26%|██▌       | 52/200 [01:03<02:58,  1.21s/it]
  iters:  26%|██▋       | 53/200 [01:04<03:01,  1.23s/it]
  iters:  27%|██▋       | 54/200 [01:05<02:58,  1.22s/it]
  iters:  28%|██▊       | 55/200 [01:07<02:56,  1.22s/it]
  iters:  28%|██▊       | 56/200 [01:08<02:56,  1.23s/it]
  iters:  28%|██▊       | 57/200 [01:09<02:54,  1.22s/it]
  iters:  29%|██▉       | 58/200 [01:10<02:52,  1.21s/it]
  iters:  30%|██▉       | 59/200 [01:11<02:49,  1.21s/it]
  iters:  30%|███       | 60/200 [01:13<02:48,  1.20s/it]
  iters:  30%|███       | 61/200 [01:14<02:47,  1.21s/it]
  iters:  31%|███       | 62/200 [01:15<02:46,  1.21s/it]
  iters:  32%|███▏      | 63/200 [01:16<02:44,  1.20s/it]
  iters:  32%|███▏      | 64/200 [01:17<02:43,  1.20s/it]
  iters:  32%|███▎      | 65/200 [01:19<02:42,  1.20s/it]
  iters:  33%|███▎      | 66/200 [01:20<02:40,  1.20s/it]
  iters:  34%|███▎      | 67/200 [01:21<02:39,  1.20s/it]
  iters:  34%|███▍      | 68/200 [01:22<02:37,  1.20s/it]
  iters:  34%|███▍      | 69/200 [01:24<02:40,  1.22s/it]
  iters:  35%|███▌      | 70/200 [01:25<02:40,  1.24s/it]
  iters:  36%|███▌      | 71/200 [01:26<02:37,  1.22s/it]
  iters:  36%|███▌      | 72/200 [01:27<02:35,  1.22s/it]
  iters:  36%|███▋      | 73/200 [01:28<02:33,  1.21s/it]
  iters:  37%|███▋      | 74/200 [01:30<02:31,  1.20s/it]
  iters:  38%|███▊      | 75/200 [01:31<02:29,  1.20s/it]
  iters:  38%|███▊      | 76/200 [01:32<02:28,  1.20s/it]
  iters:  38%|███▊      | 77/200 [01:33<02:27,  1.20s/it]
  iters:  39%|███▉      | 78/200 [01:34<02:26,  1.20s/it]
  iters:  40%|███▉      | 79/200 [01:36<02:29,  1.23s/it]
  iters:  40%|████      | 80/200 [01:37<02:26,  1.22s/it]
  iters:  40%|████      | 81/200 [01:38<02:24,  1.21s/it]
  iters:  41%|████      | 82/200 [01:39<02:23,  1.21s/it]
  iters:  42%|████▏     | 83/200 [01:41<02:22,  1.21s/it]
  iters:  42%|████▏     | 84/200 [01:42<02:22,  1.23s/it]
  iters:  42%|████▎     | 85/200 [01:43<02:20,  1.22s/it]
  iters:  43%|████▎     | 86/200 [01:44<02:18,  1.21s/it]
  iters:  44%|████▎     | 87/200 [01:45<02:16,  1.21s/it]
  iters:  44%|████▍     | 88/200 [01:47<02:15,  1.21s/it]
  iters:  44%|████▍     | 89/200 [01:48<02:13,  1.20s/it]
  iters:  45%|████▌     | 90/200 [01:49<02:12,  1.20s/it]
  iters:  46%|████▌     | 91/200 [01:50<02:10,  1.20s/it]
  iters:  46%|████▌     | 92/200 [01:51<02:09,  1.20s/it]
  iters:  46%|████▋     | 93/200 [01:53<02:08,  1.20s/it]
  iters:  47%|████▋     | 94/200 [01:54<02:07,  1.20s/it]
  iters:  48%|████▊     | 95/200 [01:55<02:13,  1.27s/it]
  iters:  48%|████▊     | 96/200 [01:56<02:10,  1.26s/it]
  iters:  48%|████▊     | 97/200 [01:58<02:07,  1.24s/it]
  iters:  49%|████▉     | 98/200 [01:59<02:05,  1.23s/it]
  iters:  50%|████▉     | 99/200 [02:00<02:04,  1.23s/it]
  iters:  50%|█████     | 100/200 [02:01<02:02,  1.22s/it]
  iters:  50%|█████     | 101/200 [02:02<02:00,  1.21s/it]
  iters:  51%|█████     | 102/200 [02:04<01:58,  1.21s/it]
  iters:  52%|█████▏    | 103/200 [02:05<01:59,  1.24s/it]
  iters:  52%|█████▏    | 104/200 [02:06<01:57,  1.23s/it]
  iters:  52%|█████▎    | 105/200 [02:07<01:55,  1.22s/it]
  iters:  53%|█████▎    | 106/200 [02:09<01:54,  1.22s/it]
  iters:  54%|█████▎    | 107/200 [02:10<01:52,  1.21s/it]
  iters:  54%|█████▍    | 108/200 [02:11<01:50,  1.20s/it]
  iters:  55%|█████▍    | 109/200 [02:12<01:49,  1.20s/it]
  iters:  55%|█████▌    | 110/200 [02:13<01:48,  1.20s/it]
  iters:  56%|█████▌    | 111/200 [02:15<01:46,  1.20s/it]
  iters:  56%|█████▌    | 112/200 [02:16<01:45,  1.20s/it]
  iters:  56%|█████▋    | 113/200 [02:17<01:44,  1.20s/it]
  iters:  57%|█████▋    | 114/200 [02:18<01:45,  1.22s/it]
  iters:  57%|█████▊    | 115/200 [02:19<01:43,  1.22s/it]
  iters:  58%|█████▊    | 116/200 [02:21<01:41,  1.21s/it]
  iters:  58%|█████▊    | 117/200 [02:22<01:41,  1.22s/it]
  iters:  59%|█████▉    | 118/200 [02:23<01:40,  1.22s/it]
  iters:  60%|█████▉    | 119/200 [02:24<01:38,  1.21s/it]
  iters:  60%|██████    | 120/200 [02:25<01:36,  1.21s/it]
  iters:  60%|██████    | 121/200 [02:27<01:35,  1.21s/it]
  iters:  61%|██████    | 122/200 [02:28<01:34,  1.21s/it]
  iters:  62%|██████▏   | 123/200 [02:29<01:33,  1.21s/it]
  iters:  62%|██████▏   | 124/200 [02:30<01:31,  1.21s/it]
  iters:  62%|██████▎   | 125/200 [02:31<01:30,  1.20s/it]
  iters:  63%|██████▎   | 126/200 [02:33<01:29,  1.20s/it]
  iters:  64%|██████▎   | 127/200 [02:34<01:27,  1.20s/it]
  iters:  64%|██████▍   | 128/200 [02:35<01:26,  1.20s/it]
  iters:  64%|██████▍   | 129/200 [02:36<01:25,  1.20s/it]
  iters:  65%|██████▌   | 130/200 [02:38<01:26,  1.23s/it]
  iters:  66%|██████▌   | 131/200 [02:39<01:25,  1.24s/it]
  iters:  66%|██████▌   | 132/200 [02:40<01:23,  1.23s/it]
  iters:  66%|██████▋   | 133/200 [02:41<01:21,  1.22s/it]
  iters:  67%|██████▋   | 134/200 [02:42<01:20,  1.21s/it]
  iters:  68%|██████▊   | 135/200 [02:44<01:18,  1.21s/it]
  iters:  68%|██████▊   | 136/200 [02:45<01:17,  1.20s/it]
  iters:  68%|██████▊   | 137/200 [02:46<01:15,  1.20s/it]
  iters:  69%|██████▉   | 138/200 [02:47<01:14,  1.20s/it]
  iters:  70%|██████▉   | 139/200 [02:48<01:13,  1.20s/it]
  iters:  70%|███████   | 140/200 [02:50<01:11,  1.20s/it]
  iters:  70%|███████   | 141/200 [02:51<01:10,  1.20s/it]
  iters:  71%|███████   | 142/200 [02:52<01:09,  1.20s/it]
  iters:  72%|███████▏  | 143/200 [02:53<01:08,  1.20s/it]
  iters:  72%|███████▏  | 144/200 [02:54<01:07,  1.20s/it]
  iters:  72%|███████▎  | 145/200 [02:56<01:06,  1.20s/it]
  iters:  73%|███████▎  | 146/200 [02:57<01:04,  1.20s/it]
  iters:  74%|███████▎  | 147/200 [02:58<01:05,  1.24s/it]
  iters:  74%|███████▍  | 148/200 [02:59<01:03,  1.23s/it]
  iters:  74%|███████▍  | 149/200 [03:01<01:02,  1.22s/it]
  iters:  75%|███████▌  | 150/200 [03:02<01:02,  1.25s/it]
  iters:  76%|███████▌  | 151/200 [03:03<01:00,  1.23s/it]
  iters:  76%|███████▌  | 152/200 [03:04<00:58,  1.22s/it]
  iters:  76%|███████▋  | 153/200 [03:05<00:57,  1.22s/it]
  iters:  77%|███████▋  | 154/200 [03:07<00:55,  1.21s/it]
  iters:  78%|███████▊  | 155/200 [03:08<00:54,  1.21s/it]
  iters:  78%|███████▊  | 156/200 [03:09<00:53,  1.22s/it]
  iters:  78%|███████▊  | 157/200 [03:10<00:52,  1.21s/it]
  iters:  79%|███████▉  | 158/200 [03:12<00:50,  1.21s/it]
  iters:  80%|███████▉  | 159/200 [03:13<00:50,  1.24s/it]
  iters:  80%|████████  | 160/200 [03:14<00:49,  1.23s/it]
  iters:  80%|████████  | 161/200 [03:15<00:48,  1.23s/it]
  iters:  81%|████████  | 162/200 [03:17<00:47,  1.24s/it]
  iters:  82%|████████▏ | 163/200 [03:18<00:45,  1.23s/it]
  iters:  82%|████████▏ | 164/200 [03:19<00:44,  1.22s/it]
  iters:  82%|████████▎ | 165/200 [03:20<00:42,  1.21s/it]
  iters:  83%|████████▎ | 166/200 [03:21<00:41,  1.21s/it]
  iters:  84%|████████▎ | 167/200 [03:23<00:39,  1.21s/it]
  iters:  84%|████████▍ | 168/200 [03:24<00:38,  1.21s/it]
  iters:  84%|████████▍ | 169/200 [03:25<00:37,  1.21s/it]
  iters:  85%|████████▌ | 170/200 [03:26<00:36,  1.23s/it]
  iters:  86%|████████▌ | 171/200 [03:28<00:36,  1.25s/it]
  iters:  86%|████████▌ | 172/200 [03:29<00:34,  1.24s/it]
  iters:  86%|████████▋ | 173/200 [03:30<00:33,  1.23s/it]
  iters:  87%|████████▋ | 174/200 [03:31<00:31,  1.23s/it]
  iters:  88%|████████▊ | 175/200 [03:32<00:30,  1.22s/it]
  iters:  88%|████████▊ | 176/200 [03:34<00:29,  1.21s/it]
  iters:  88%|████████▊ | 177/200 [03:35<00:27,  1.21s/it]
  iters:  89%|████████▉ | 178/200 [03:36<00:26,  1.22s/it]
  iters:  90%|████████▉ | 179/200 [03:37<00:25,  1.22s/it]
  iters:  90%|█████████ | 180/200 [03:38<00:24,  1.21s/it]
  iters:  90%|█████████ | 181/200 [03:40<00:22,  1.21s/it]
  iters:  91%|█████████ | 182/200 [03:41<00:21,  1.20s/it]
  iters:  92%|█████████▏| 183/200 [03:42<00:20,  1.23s/it]
  iters:  92%|█████████▏| 184/200 [03:43<00:19,  1.25s/it]
  iters:  92%|█████████▎| 185/200 [03:45<00:18,  1.24s/it]
  iters:  93%|█████████▎| 186/200 [03:46<00:17,  1.23s/it]
  iters:  94%|█████████▎| 187/200 [03:47<00:15,  1.23s/it]
  iters:  94%|█████████▍| 188/200 [03:48<00:15,  1.26s/it]
  iters:  94%|█████████▍| 189/200 [03:50<00:13,  1.25s/it]
  iters:  95%|█████████▌| 190/200 [03:51<00:12,  1.24s/it]
  iters:  96%|█████████▌| 191/200 [03:52<00:11,  1.25s/it]
  iters:  96%|█████████▌| 192/200 [03:53<00:09,  1.24s/it]
  iters:  96%|█████████▋| 193/200 [03:55<00:08,  1.23s/it]
  iters:  97%|█████████▋| 194/200 [03:56<00:07,  1.22s/it]
  iters:  98%|█████████▊| 195/200 [03:57<00:06,  1.22s/it]
  iters:  98%|█████████▊| 196/200 [03:58<00:04,  1.21s/it]
  iters:  98%|█████████▊| 197/200 [03:59<00:03,  1.24s/it]
  iters:  99%|█████████▉| 198/200 [04:01<00:02,  1.23s/it]
  iters: 100%|█████████▉| 199/200 [04:02<00:01,  1.24s/it]
  iters: 100%|██████████| 200/200 [04:03<00:00,  1.23s/it]

  [timing] data: 2.2s (1%) | forward: 58.5s (24%) | backward: 182.9s (75%) | total: 243.6s

Training:  75%|███████▌  | 3/4 [17:42<04:25, 265.60s/it, acc=0.9991, det=0.0067, edge=0.0005]

  Epoch   3/4 | edge=0.0005 | det=0.0067 | test_loss=0.0021 | acc=0.9991 | recall=0.9060 | best=0.9052 * | train=243.8s test=21.8s

Training: 100%|██████████| 4/4 [17:42<00:00, 265.71s/it, acc=0.9991, det=0.0067, edge=0.0005]

Best score (acc*recall): 0.9052, saved to /kaggle/working/cellmot-baseline-artifacts/repo/weights/hp_search_tier1/split_0/edge_predictor_best.pth

[tier2_003] score=0.9052  (1069s)
0.019136512 GB allocated
0.148897792 GB reserved
Fold 0: 8 train, 2 test
Loading train (8 datasets)...

train: 100%|██████████| 8/8 [00:04<00:00,  1.87it/s]

  train done: 787 windows total
Loading test (2 datasets)...

test: 100%|██████████| 2/2 [00:00<00:00,  2.48it/s]

  test done: 164 windows total
max_nodes=17
Using device: cuda | visible CUDA GPUs: 2
  Full checkpoint loaded from /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/weights/unet_transformer/split_0/edge_predictor_best.pth: 0 missing, 0 unexpected
Single-GPU training (--single-gpu set). For 2 GPUs set the Kaggle accelerator to 'GPU T4 x2'.
Model parameters: 2,076,706
Starting training for 4 epochs (batch_size=2)...

Training:   0%|          | 0/4 [00:00<?, ?it/s]

Detection loss: weight=4, neg_weight=0.01

  iters:   0%|          | 0/200 [00:00<?, ?it/s]
  iters:   0%|          | 1/200 [00:01<05:06,  1.54s/it]
  iters:   1%|          | 2/200 [00:02<04:24,  1.34s/it]
  iters:   2%|▏         | 3/200 [00:03<04:11,  1.28s/it]
  iters:   2%|▏         | 4/200 [00:05<04:03,  1.24s/it]
  iters:   2%|▎         | 5/200 [00:06<03:59,  1.23s/it]
  iters:   3%|▎         | 6/200 [00:07<04:02,  1.25s/it]
  iters:   4%|▎         | 7/200 [00:08<03:58,  1.24s/it]
  iters:   4%|▍         | 8/200 [00:10<03:54,  1.22s/it]
  iters:   4%|▍         | 9/200 [00:11<03:55,  1.23s/it]
  iters:   5%|▌         | 10/200 [00:12<03:51,  1.22s/it]
  iters:   6%|▌         | 11/200 [00:13<03:50,  1.22s/it]
  iters:   6%|▌         | 12/200 [00:14<03:48,  1.22s/it]
  iters:   6%|▋         | 13/200 [00:16<03:47,  1.22s/it]
  iters:   7%|▋         | 14/200 [00:17<03:45,  1.21s/it]
  iters:   8%|▊         | 15/200 [00:18<03:49,  1.24s/it]
  iters:   8%|▊         | 16/200 [00:19<03:51,  1.26s/it]
  iters:   8%|▊         | 17/200 [00:21<03:58,  1.30s/it]
  iters:   9%|▉         | 18/200 [00:22<03:52,  1.28s/it]
  iters:  10%|▉         | 19/200 [00:23<03:49,  1.27s/it]
  iters:  10%|█         | 20/200 [00:25<03:46,  1.26s/it]
  iters:  10%|█         | 21/200 [00:26<03:43,  1.25s/it]
  iters:  11%|█         | 22/200 [00:27<03:40,  1.24s/it]
  iters:  12%|█▏        | 23/200 [00:28<03:38,  1.23s/it]
  iters:  12%|█▏        | 24/200 [00:29<03:36,  1.23s/it]
  iters:  12%|█▎        | 25/200 [00:31<03:35,  1.23s/it]
  iters:  13%|█▎        | 26/200 [00:32<03:44,  1.29s/it]
  iters:  14%|█▎        | 27/200 [00:33<03:45,  1.31s/it]
  iters:  14%|█▍        | 28/200 [00:35<03:40,  1.28s/it]
  iters:  14%|█▍        | 29/200 [00:36<03:37,  1.27s/it]
  iters:  15%|█▌        | 30/200 [00:37<03:33,  1.26s/it]
  iters:  16%|█▌        | 31/200 [00:38<03:30,  1.24s/it]
  iters:  16%|█▌        | 32/200 [00:40<03:27,  1.23s/it]
  iters:  16%|█▋        | 33/200 [00:41<03:24,  1.23s/it]
  iters:  17%|█▋        | 34/200 [00:42<03:23,  1.23s/it]
  iters:  18%|█▊        | 35/200 [00:43<03:21,  1.22s/it]
  iters:  18%|█▊        | 36/200 [00:44<03:19,  1.22s/it]
  iters:  18%|█▊        | 37/200 [00:46<03:18,  1.21s/it]
  iters:  19%|█▉        | 38/200 [00:47<03:16,  1.21s/it]
  iters:  20%|█▉        | 39/200 [00:48<03:14,  1.21s/it]
  iters:  20%|██        | 40/200 [00:49<03:15,  1.22s/it]
  iters:  20%|██        | 41/200 [00:50<03:14,  1.22s/it]
  iters:  21%|██        | 42/200 [00:52<03:24,  1.29s/it]
  iters:  22%|██▏       | 43/200 [00:53<03:19,  1.27s/it]
  iters:  22%|██▏       | 44/200 [00:55<03:24,  1.31s/it]
  iters:  22%|██▎       | 45/200 [00:56<03:29,  1.35s/it]
  iters:  23%|██▎       | 46/200 [00:57<03:21,  1.31s/it]
  iters:  24%|██▎       | 47/200 [00:59<03:20,  1.31s/it]
  iters:  24%|██▍       | 48/200 [01:00<03:16,  1.29s/it]
  iters:  24%|██▍       | 49/200 [01:01<03:15,  1.30s/it]
  iters:  25%|██▌       | 50/200 [01:02<03:10,  1.27s/it]
  iters:  26%|██▌       | 51/200 [01:04<03:12,  1.29s/it]
  iters:  26%|██▌       | 52/200 [01:05<03:07,  1.27s/it]
  iters:  26%|██▋       | 53/200 [01:06<03:12,  1.31s/it]
  iters:  27%|██▋       | 54/200 [01:07<03:07,  1.29s/it]
  iters:  28%|██▊       | 55/200 [01:09<03:13,  1.33s/it]
  iters:  28%|██▊       | 56/200 [01:10<03:06,  1.29s/it]
  iters:  28%|██▊       | 57/200 [01:11<03:02,  1.28s/it]
  iters:  29%|██▉       | 58/200 [01:13<03:09,  1.33s/it]
  iters:  30%|██▉       | 59/200 [01:14<03:04,  1.31s/it]
  iters:  30%|███       | 60/200 [01:15<02:58,  1.28s/it]
  iters:  30%|███       | 61/200 [01:17<03:00,  1.30s/it]
  iters:  31%|███       | 62/200 [01:18<02:55,  1.27s/it]
  iters:  32%|███▏      | 63/200 [01:19<02:51,  1.25s/it]
  iters:  32%|███▏      | 64/200 [01:20<02:48,  1.24s/it]
  iters:  32%|███▎      | 65/200 [01:21<02:45,  1.23s/it]
  iters:  33%|███▎      | 66/200 [01:23<02:44,  1.23s/it]
  iters:  34%|███▎      | 67/200 [01:24<02:42,  1.22s/it]
  iters:  34%|███▍      | 68/200 [01:25<02:42,  1.23s/it]
  iters:  34%|███▍      | 69/200 [01:26<02:40,  1.22s/it]
  iters:  35%|███▌      | 70/200 [01:28<02:38,  1.22s/it]
  iters:  36%|███▌      | 71/200 [01:29<02:36,  1.22s/it]
  iters:  36%|███▌      | 72/200 [01:30<02:35,  1.21s/it]
  iters:  36%|███▋      | 73/200 [01:31<02:36,  1.24s/it]
  iters:  37%|███▋      | 74/200 [01:32<02:34,  1.23s/it]
  iters:  38%|███▊      | 75/200 [01:34<02:32,  1.22s/it]
  iters:  38%|███▊      | 76/200 [01:35<02:30,  1.22s/it]
  iters:  38%|███▊      | 77/200 [01:36<02:30,  1.22s/it]
  iters:  39%|███▉      | 78/200 [01:37<02:28,  1.21s/it]
  iters:  40%|███▉      | 79/200 [01:39<02:26,  1.21s/it]
  iters:  40%|████      | 80/200 [01:40<02:24,  1.20s/it]
  iters:  40%|████      | 81/200 [01:41<02:23,  1.21s/it]
  iters:  41%|████      | 82/200 [01:42<02:22,  1.21s/it]
  iters:  42%|████▏     | 83/200 [01:43<02:21,  1.21s/it]
  iters:  42%|████▏     | 84/200 [01:45<02:19,  1.20s/it]
  iters:  42%|████▎     | 85/200 [01:46<02:18,  1.21s/it]
  iters:  43%|████▎     | 86/200 [01:47<02:17,  1.20s/it]
  iters:  44%|████▎     | 87/200 [01:48<02:16,  1.20s/it]
  iters:  44%|████▍     | 88/200 [01:49<02:14,  1.20s/it]
  iters:  44%|████▍     | 89/200 [01:51<02:13,  1.20s/it]
  iters:  45%|████▌     | 90/200 [01:52<02:11,  1.20s/it]
  iters:  46%|████▌     | 91/200 [01:53<02:10,  1.20s/it]
  iters:  46%|████▌     | 92/200 [01:54<02:09,  1.20s/it]
  iters:  46%|████▋     | 93/200 [01:55<02:08,  1.20s/it]
  iters:  47%|████▋     | 94/200 [01:57<02:08,  1.21s/it]
  iters:  48%|████▊     | 95/200 [01:58<02:07,  1.21s/it]
  iters:  48%|████▊     | 96/200 [01:59<02:05,  1.21s/it]
  iters:  48%|████▊     | 97/200 [02:00<02:10,  1.27s/it]
  iters:  49%|████▉     | 98/200 [02:02<02:07,  1.25s/it]
  iters:  50%|████▉     | 99/200 [02:03<02:05,  1.24s/it]
  iters:  50%|█████     | 100/200 [02:04<02:02,  1.23s/it]
  iters:  50%|█████     | 101/200 [02:05<02:02,  1.23s/it]
  iters:  51%|█████     | 102/200 [02:06<02:00,  1.23s/it]
  iters:  52%|█████▏    | 103/200 [02:08<01:58,  1.22s/it]
  iters:  52%|█████▏    | 104/200 [02:09<01:57,  1.23s/it]
  iters:  52%|█████▎    | 105/200 [02:10<01:55,  1.22s/it]
  iters:  53%|█████▎    | 106/200 [02:11<01:54,  1.22s/it]
  iters:  54%|█████▎    | 107/200 [02:13<01:52,  1.21s/it]
  iters:  54%|█████▍    | 108/200 [02:14<01:51,  1.21s/it]
  iters:  55%|█████▍    | 109/200 [02:15<01:50,  1.21s/it]
  iters:  55%|█████▌    | 110/200 [02:16<01:55,  1.28s/it]
  iters:  56%|█████▌    | 111/200 [02:18<01:51,  1.26s/it]
  iters:  56%|█████▌    | 112/200 [02:19<01:52,  1.28s/it]
  iters:  56%|█████▋    | 113/200 [02:20<01:56,  1.33s/it]
  iters:  57%|█████▋    | 114/200 [02:22<01:55,  1.34s/it]
  iters:  57%|█████▊    | 115/200 [02:23<01:50,  1.30s/it]
  iters:  58%|█████▊    | 116/200 [02:24<01:50,  1.31s/it]
  iters:  58%|█████▊    | 117/200 [02:26<01:47,  1.30s/it]
  iters:  59%|█████▉    | 118/200 [02:27<01:47,  1.31s/it]
  iters:  60%|█████▉    | 119/200 [02:28<01:43,  1.28s/it]
  iters:  60%|██████    | 120/200 [02:29<01:40,  1.26s/it]
  iters:  60%|██████    | 121/200 [02:31<01:37,  1.24s/it]
  iters:  61%|██████    | 122/200 [02:32<01:36,  1.23s/it]
  iters:  62%|██████▏   | 123/200 [02:33<01:38,  1.27s/it]
  iters:  62%|██████▏   | 124/200 [02:34<01:35,  1.25s/it]
  iters:  62%|██████▎   | 125/200 [02:36<01:35,  1.27s/it]
  iters:  63%|██████▎   | 126/200 [02:37<01:32,  1.25s/it]
  iters:  64%|██████▎   | 127/200 [02:38<01:30,  1.23s/it]
  iters:  64%|██████▍   | 128/200 [02:39<01:28,  1.22s/it]
  iters:  64%|██████▍   | 129/200 [02:40<01:27,  1.23s/it]
  iters:  65%|██████▌   | 130/200 [02:42<01:25,  1.23s/it]
  iters:  66%|██████▌   | 131/200 [02:43<01:29,  1.30s/it]
  iters:  66%|██████▌   | 132/200 [02:44<01:26,  1.27s/it]
  iters:  66%|██████▋   | 133/200 [02:46<01:23,  1.25s/it]
  iters:  67%|██████▋   | 134/200 [02:47<01:25,  1.30s/it]
  iters:  68%|██████▊   | 135/200 [02:48<01:22,  1.27s/it]
  iters:  68%|██████▊   | 136/200 [02:49<01:22,  1.29s/it]
  iters:  68%|██████▊   | 137/200 [02:51<01:19,  1.26s/it]
  iters:  69%|██████▉   | 138/200 [02:52<01:17,  1.24s/it]
  iters:  70%|██████▉   | 139/200 [02:53<01:15,  1.23s/it]
  iters:  70%|███████   | 140/200 [02:54<01:13,  1.22s/it]
  iters:  70%|███████   | 141/200 [02:56<01:12,  1.22s/it]
  iters:  71%|███████   | 142/200 [02:57<01:10,  1.22s/it]
  iters:  72%|███████▏  | 143/200 [02:58<01:09,  1.22s/it]
  iters:  72%|███████▏  | 144/200 [02:59<01:08,  1.21s/it]
  iters:  72%|███████▎  | 145/200 [03:00<01:06,  1.22s/it]
  iters:  73%|███████▎  | 146/200 [03:02<01:05,  1.22s/it]
  iters:  74%|███████▎  | 147/200 [03:03<01:10,  1.33s/it]
  iters:  74%|███████▍  | 148/200 [03:04<01:07,  1.30s/it]
  iters:  74%|███████▍  | 149/200 [03:06<01:07,  1.33s/it]
  iters:  75%|███████▌  | 150/200 [03:07<01:04,  1.29s/it]
  iters:  76%|███████▌  | 151/200 [03:08<01:01,  1.26s/it]
  iters:  76%|███████▌  | 152/200 [03:09<01:00,  1.25s/it]
  iters:  76%|███████▋  | 153/200 [03:11<00:58,  1.24s/it]
  iters:  77%|███████▋  | 154/200 [03:12<00:56,  1.23s/it]
  iters:  78%|███████▊  | 155/200 [03:13<00:55,  1.23s/it]
  iters:  78%|███████▊  | 156/200 [03:14<00:53,  1.22s/it]
  iters:  78%|███████▊  | 157/200 [03:15<00:52,  1.22s/it]
  iters:  79%|███████▉  | 158/200 [03:17<00:51,  1.21s/it]
  iters:  80%|███████▉  | 159/200 [03:18<00:49,  1.21s/it]
  iters:  80%|████████  | 160/200 [03:19<00:49,  1.23s/it]
  iters:  80%|████████  | 161/200 [03:20<00:47,  1.22s/it]
  iters:  81%|████████  | 162/200 [03:22<00:46,  1.21s/it]
  iters:  82%|████████▏ | 163/200 [03:23<00:44,  1.21s/it]
  iters:  82%|████████▏ | 164/200 [03:24<00:43,  1.21s/it]
  iters:  82%|████████▎ | 165/200 [03:25<00:42,  1.21s/it]
  iters:  83%|████████▎ | 166/200 [03:26<00:41,  1.22s/it]
  iters:  84%|████████▎ | 167/200 [03:28<00:39,  1.21s/it]
  iters:  84%|████████▍ | 168/200 [03:29<00:38,  1.21s/it]
  iters:  84%|████████▍ | 169/200 [03:30<00:37,  1.21s/it]
  iters:  85%|████████▌ | 170/200 [03:31<00:36,  1.21s/it]
  iters:  86%|████████▌ | 171/200 [03:32<00:35,  1.21s/it]
  iters:  86%|████████▌ | 172/200 [03:34<00:33,  1.21s/it]
  iters:  86%|████████▋ | 173/200 [03:35<00:32,  1.20s/it]
  iters:  87%|████████▋ | 174/200 [03:36<00:32,  1.26s/it]
  iters:  88%|████████▊ | 175/200 [03:37<00:31,  1.24s/it]
  iters:  88%|████████▊ | 176/200 [03:39<00:30,  1.26s/it]
  iters:  88%|████████▊ | 177/200 [03:40<00:28,  1.25s/it]
  iters:  89%|████████▉ | 178/200 [03:41<00:28,  1.30s/it]
  iters:  90%|████████▉ | 179/200 [03:43<00:26,  1.28s/it]
  iters:  90%|█████████ | 180/200 [03:44<00:25,  1.26s/it]
  iters:  90%|█████████ | 181/200 [03:45<00:23,  1.24s/it]
  iters:  91%|█████████ | 182/200 [03:46<00:22,  1.25s/it]
  iters:  92%|█████████▏| 183/200 [03:48<00:21,  1.24s/it]
  iters:  92%|█████████▏| 184/200 [03:49<00:19,  1.23s/it]
  iters:  92%|█████████▎| 185/200 [03:50<00:18,  1.22s/it]
  iters:  93%|█████████▎| 186/200 [03:51<00:17,  1.23s/it]
  iters:  94%|█████████▎| 187/200 [03:52<00:16,  1.24s/it]
  iters:  94%|█████████▍| 188/200 [03:54<00:14,  1.24s/it]
  iters:  94%|█████████▍| 189/200 [03:55<00:13,  1.27s/it]
  iters:  95%|█████████▌| 190/200 [03:56<00:12,  1.25s/it]
  iters:  96%|█████████▌| 191/200 [03:57<00:11,  1.23s/it]
  iters:  96%|█████████▌| 192/200 [03:59<00:09,  1.22s/it]
  iters:  96%|█████████▋| 193/200 [04:00<00:08,  1.22s/it]
  iters:  97%|█████████▋| 194/200 [04:01<00:07,  1.21s/it]
  iters:  98%|█████████▊| 195/200 [04:02<00:06,  1.21s/it]
  iters:  98%|█████████▊| 196/200 [04:03<00:04,  1.21s/it]
  iters:  98%|█████████▊| 197/200 [04:05<00:03,  1.21s/it]
  iters:  99%|█████████▉| 198/200 [04:06<00:02,  1.29s/it]
  iters: 100%|█████████▉| 199/200 [04:07<00:01,  1.28s/it]
  iters: 100%|██████████| 200/200 [04:09<00:00,  1.26s/it]

  [timing] data: 2.2s (1%) | forward: 60.3s (24%) | backward: 186.5s (75%) | total: 249.1s

Training:   0%|          | 0/4 [04:31<?, ?it/s, acc=0.9989, det=0.0091, edge=0.0006]

  Epoch   0/4 | edge=0.0006 | det=0.0091 | test_loss=0.0015 | acc=0.9989 | recall=0.8537 | best=0.8528 * | train=249.3s test=22.1s

Training:  25%|██▌       | 1/4 [04:31<13:34, 271.43s/it, acc=0.9989, det=0.0091, edge=0.0006]
  iters:   0%|          | 0/200 [00:00<?, ?it/s]
  iters:   0%|          | 1/200 [00:01<04:32,  1.37s/it]
  iters:   1%|          | 2/200 [00:02<04:18,  1.31s/it]
  iters:   2%|▏         | 3/200 [00:03<04:08,  1.26s/it]
  iters:   2%|▏         | 4/200 [00:05<04:07,  1.26s/it]
  iters:   2%|▎         | 5/200 [00:06<04:02,  1.24s/it]
  iters:   3%|▎         | 6/200 [00:07<03:59,  1.23s/it]
  iters:   4%|▎         | 7/200 [00:08<03:56,  1.22s/it]
  iters:   4%|▍         | 8/200 [00:09<03:53,  1.22s/it]
  iters:   4%|▍         | 9/200 [00:11<03:52,  1.22s/it]
  iters:   5%|▌         | 10/200 [00:12<03:53,  1.23s/it]
  iters:   6%|▌         | 11/200 [00:13<03:50,  1.22s/it]
  iters:   6%|▌         | 12/200 [00:14<03:48,  1.22s/it]
  iters:   6%|▋         | 13/200 [00:16<03:46,  1.21s/it]
  iters:   7%|▋         | 14/200 [00:17<03:44,  1.21s/it]
  iters:   8%|▊         | 15/200 [00:18<03:44,  1.21s/it]
  iters:   8%|▊         | 16/200 [00:19<03:42,  1.21s/it]
  iters:   8%|▊         | 17/200 [00:20<03:41,  1.21s/it]
  iters:   9%|▉         | 18/200 [00:22<03:40,  1.21s/it]
  iters:  10%|▉         | 19/200 [00:23<03:38,  1.21s/it]
  iters:  10%|█         | 20/200 [00:24<03:41,  1.23s/it]
  iters:  10%|█         | 21/200 [00:25<03:38,  1.22s/it]
  iters:  11%|█         | 22/200 [00:26<03:36,  1.22s/it]
  iters:  12%|█▏        | 23/200 [00:28<03:34,  1.21s/it]
  iters:  12%|█▏        | 24/200 [00:29<03:33,  1.21s/it]
  iters:  12%|█▎        | 25/200 [00:30<03:31,  1.21s/it]
  iters:  13%|█▎        | 26/200 [00:31<03:29,  1.20s/it]
  iters:  14%|█▎        | 27/200 [00:32<03:27,  1.20s/it]
  iters:  14%|█▍        | 28/200 [00:34<03:26,  1.20s/it]
  iters:  14%|█▍        | 29/200 [00:35<03:26,  1.20s/it]
  iters:  15%|█▌        | 30/200 [00:36<03:24,  1.20s/it]
  iters:  16%|█▌        | 31/200 [00:37<03:23,  1.20s/it]
  iters:  16%|█▌        | 32/200 [00:38<03:22,  1.20s/it]
  iters:  16%|█▋        | 33/200 [00:40<03:24,  1.22s/it]
  iters:  17%|█▋        | 34/200 [00:41<03:22,  1.22s/it]
  iters:  18%|█▊        | 35/200 [00:42<03:21,  1.22s/it]
  iters:  18%|█▊        | 36/200 [00:43<03:18,  1.21s/it]
  iters:  18%|█▊        | 37/200 [00:45<03:17,  1.21s/it]
  iters:  19%|█▉        | 38/200 [00:46<03:14,  1.20s/it]
  iters:  20%|█▉        | 39/200 [00:47<03:18,  1.23s/it]
  iters:  20%|██        | 40/200 [00:48<03:23,  1.27s/it]
  iters:  20%|██        | 41/200 [00:50<03:18,  1.25s/it]
  iters:  21%|██        | 42/200 [00:51<03:14,  1.23s/it]
  iters:  22%|██▏       | 43/200 [00:52<03:11,  1.22s/it]
  iters:  22%|██▏       | 44/200 [00:53<03:13,  1.24s/it]
  iters:  22%|██▎       | 45/200 [00:55<03:15,  1.26s/it]
  iters:  23%|██▎       | 46/200 [00:56<03:11,  1.24s/it]
  iters:  24%|██▎       | 47/200 [00:57<03:10,  1.24s/it]
  iters:  24%|██▍       | 48/200 [00:58<03:07,  1.23s/it]
  iters:  24%|██▍       | 49/200 [00:59<03:05,  1.23s/it]
  iters:  25%|██▌       | 50/200 [01:01<03:03,  1.22s/it]
  iters:  26%|██▌       | 51/200 [01:02<03:01,  1.22s/it]
  iters:  26%|██▌       | 52/200 [01:03<03:02,  1.23s/it]
  iters:  26%|██▋       | 53/200 [01:04<02:59,  1.22s/it]
  iters:  27%|██▋       | 54/200 [01:06<02:58,  1.22s/it]
  iters:  28%|██▊       | 55/200 [01:07<02:55,  1.21s/it]
  iters:  28%|██▊       | 56/200 [01:08<02:53,  1.21s/it]
  iters:  28%|██▊       | 57/200 [01:09<02:52,  1.21s/it]
  iters:  29%|██▉       | 58/200 [01:10<02:50,  1.20s/it]
  iters:  30%|██▉       | 59/200 [01:12<02:49,  1.20s/it]
  iters:  30%|███       | 60/200 [01:13<02:49,  1.21s/it]
  iters:  30%|███       | 61/200 [01:14<02:52,  1.24s/it]
  iters:  31%|███       | 62/200 [01:15<02:50,  1.23s/it]
  iters:  32%|███▏      | 63/200 [01:17<02:54,  1.27s/it]
  iters:  32%|███▏      | 64/200 [01:18<02:49,  1.25s/it]
  iters:  32%|███▎      | 65/200 [01:19<02:46,  1.23s/it]
  iters:  33%|███▎      | 66/200 [01:20<02:43,  1.22s/it]
  iters:  34%|███▎      | 67/200 [01:21<02:41,  1.22s/it]
  iters:  34%|███▍      | 68/200 [01:23<02:39,  1.21s/it]
  iters:  34%|███▍      | 69/200 [01:24<02:38,  1.21s/it]
  iters:  35%|███▌      | 70/200 [01:25<02:39,  1.23s/it]
  iters:  36%|███▌      | 71/200 [01:27<02:44,  1.27s/it]
  iters:  36%|███▌      | 72/200 [01:28<02:40,  1.25s/it]
  iters:  36%|███▋      | 73/200 [01:29<02:44,  1.30s/it]
  iters:  37%|███▋      | 74/200 [01:31<02:49,  1.35s/it]
  iters:  38%|███▊      | 75/200 [01:32<02:43,  1.30s/it]
  iters:  38%|███▊      | 76/200 [01:33<02:40,  1.29s/it]
  iters:  38%|███▊      | 77/200 [01:34<02:35,  1.27s/it]
  iters:  39%|███▉      | 78/200 [01:35<02:32,  1.25s/it]
  iters:  40%|███▉      | 79/200 [01:37<02:31,  1.25s/it]
  iters:  40%|████      | 80/200 [01:38<02:28,  1.24s/it]
  iters:  40%|████      | 81/200 [01:39<02:28,  1.25s/it]
  iters:  41%|████      | 82/200 [01:41<02:30,  1.28s/it]
  iters:  42%|████▏     | 83/200 [01:42<02:26,  1.25s/it]
  iters:  42%|████▏     | 84/200 [01:43<02:27,  1.28s/it]
  iters:  42%|████▎     | 85/200 [01:44<02:24,  1.25s/it]
  iters:  43%|████▎     | 86/200 [01:46<02:28,  1.31s/it]
  iters:  44%|████▎     | 87/200 [01:47<02:23,  1.27s/it]
  iters:  44%|████▍     | 88/200 [01:48<02:19,  1.25s/it]
  iters:  44%|████▍     | 89/200 [01:49<02:20,  1.27s/it]
  iters:  45%|████▌     | 90/200 [01:51<02:16,  1.24s/it]
  iters:  46%|████▌     | 91/200 [01:52<02:13,  1.23s/it]
  iters:  46%|████▌     | 92/200 [01:53<02:11,  1.22s/it]
  iters:  46%|████▋     | 93/200 [01:54<02:16,  1.28s/it]
  iters:  47%|████▋     | 94/200 [01:56<02:12,  1.25s/it]
  iters:  48%|████▊     | 95/200 [01:57<02:15,  1.29s/it]
  iters:  48%|████▊     | 96/200 [01:58<02:11,  1.26s/it]
  iters:  48%|████▊     | 97/200 [01:59<02:08,  1.25s/it]
  iters:  49%|████▉     | 98/200 [02:01<02:05,  1.23s/it]
  iters:  50%|████▉     | 99/200 [02:02<02:03,  1.22s/it]
  iters:  50%|█████     | 100/200 [02:03<02:08,  1.28s/it]
  iters:  50%|█████     | 101/200 [02:05<02:15,  1.37s/it]
  iters:  51%|█████     | 102/200 [02:06<02:10,  1.33s/it]
  iters:  52%|█████▏    | 103/200 [02:07<02:05,  1.29s/it]
  iters:  52%|█████▏    | 104/200 [02:08<02:01,  1.27s/it]
  iters:  52%|█████▎    | 105/200 [02:10<02:02,  1.29s/it]
  iters:  53%|█████▎    | 106/200 [02:11<02:06,  1.34s/it]
  iters:  54%|█████▎    | 107/200 [02:12<02:00,  1.30s/it]
  iters:  54%|█████▍    | 108/200 [02:14<01:56,  1.27s/it]
  iters:  55%|█████▍    | 109/200 [02:15<01:53,  1.25s/it]
  iters:  55%|█████▌    | 110/200 [02:16<01:51,  1.24s/it]
  iters:  56%|█████▌    | 111/200 [02:17<01:49,  1.23s/it]
  iters:  56%|█████▌    | 112/200 [02:18<01:47,  1.22s/it]
  iters:  56%|█████▋    | 113/200 [02:20<01:45,  1.22s/it]
  iters:  57%|█████▋    | 114/200 [02:21<01:44,  1.22s/it]
  iters:  57%|█████▊    | 115/200 [02:22<01:49,  1.29s/it]
  iters:  58%|█████▊    | 116/200 [02:24<01:52,  1.34s/it]
  iters:  58%|█████▊    | 117/200 [02:25<01:48,  1.30s/it]
  iters:  59%|█████▉    | 118/200 [02:26<01:44,  1.27s/it]
  iters:  60%|█████▉    | 119/200 [02:28<01:44,  1.29s/it]
  iters:  60%|██████    | 120/200 [02:29<01:40,  1.26s/it]
  iters:  60%|██████    | 121/200 [02:30<01:38,  1.25s/it]
  iters:  61%|██████    | 122/200 [02:31<01:36,  1.24s/it]
  iters:  62%|██████▏   | 123/200 [02:32<01:34,  1.22s/it]
  iters:  62%|██████▏   | 124/200 [02:34<01:32,  1.22s/it]
  iters:  62%|██████▎   | 125/200 [02:35<01:31,  1.22s/it]
  iters:  63%|██████▎   | 126/200 [02:36<01:30,  1.22s/it]
  iters:  64%|██████▎   | 127/200 [02:37<01:28,  1.21s/it]
  iters:  64%|██████▍   | 128/200 [02:39<01:31,  1.28s/it]
  iters:  64%|██████▍   | 129/200 [02:40<01:34,  1.33s/it]
  iters:  65%|██████▌   | 130/200 [02:41<01:30,  1.29s/it]
  iters:  66%|██████▌   | 131/200 [02:42<01:27,  1.26s/it]
  iters:  66%|██████▌   | 132/200 [02:44<01:24,  1.25s/it]
  iters:  66%|██████▋   | 133/200 [02:45<01:22,  1.24s/it]
  iters:  67%|██████▋   | 134/200 [02:46<01:20,  1.23s/it]
  iters:  68%|██████▊   | 135/200 [02:47<01:21,  1.25s/it]
  iters:  68%|██████▊   | 136/200 [02:49<01:24,  1.32s/it]
  iters:  68%|██████▊   | 137/200 [02:50<01:21,  1.29s/it]
  iters:  69%|██████▉   | 138/200 [02:51<01:18,  1.26s/it]
  iters:  70%|██████▉   | 139/200 [02:53<01:16,  1.25s/it]
  iters:  70%|███████   | 140/200 [02:54<01:13,  1.23s/it]
  iters:  70%|███████   | 141/200 [02:55<01:12,  1.22s/it]
  iters:  71%|███████   | 142/200 [02:56<01:10,  1.22s/it]
  iters:  72%|███████▏  | 143/200 [02:57<01:10,  1.23s/it]
  iters:  72%|███████▏  | 144/200 [02:59<01:08,  1.22s/it]
  iters:  72%|███████▎  | 145/200 [03:00<01:11,  1.30s/it]
  iters:  73%|███████▎  | 146/200 [03:01<01:08,  1.27s/it]
  iters:  74%|███████▎  | 147/200 [03:03<01:06,  1.25s/it]
  iters:  74%|███████▍  | 148/200 [03:04<01:04,  1.24s/it]
  iters:  74%|███████▍  | 149/200 [03:05<01:02,  1.23s/it]
  iters:  75%|███████▌  | 150/200 [03:06<01:00,  1.22s/it]
  iters:  76%|███████▌  | 151/200 [03:07<00:59,  1.22s/it]
  iters:  76%|███████▌  | 152/200 [03:09<00:58,  1.22s/it]
  iters:  76%|███████▋  | 153/200 [03:10<00:57,  1.22s/it]
  iters:  77%|███████▋  | 154/200 [03:11<00:55,  1.21s/it]
  iters:  78%|███████▊  | 155/200 [03:12<00:55,  1.23s/it]
  iters:  78%|███████▊  | 156/200 [03:13<00:54,  1.23s/it]
  iters:  78%|███████▊  | 157/200 [03:15<00:52,  1.23s/it]
  iters:  79%|███████▉  | 158/200 [03:16<00:51,  1.22s/it]
  iters:  80%|███████▉  | 159/200 [03:17<00:49,  1.21s/it]
  iters:  80%|████████  | 160/200 [03:18<00:48,  1.21s/it]
  iters:  80%|████████  | 161/200 [03:20<00:47,  1.21s/it]
  iters:  81%|████████  | 162/200 [03:21<00:45,  1.21s/it]
  iters:  82%|████████▏ | 163/200 [03:22<00:44,  1.20s/it]
  iters:  82%|████████▏ | 164/200 [03:23<00:43,  1.20s/it]
  iters:  82%|████████▎ | 165/200 [03:24<00:42,  1.20s/it]
  iters:  83%|████████▎ | 166/200 [03:26<00:40,  1.20s/it]
  iters:  84%|████████▎ | 167/200 [03:27<00:39,  1.20s/it]
  iters:  84%|████████▍ | 168/200 [03:28<00:39,  1.24s/it]
  iters:  84%|████████▍ | 169/200 [03:29<00:37,  1.23s/it]
  iters:  85%|████████▌ | 170/200 [03:30<00:36,  1.23s/it]
  iters:  86%|████████▌ | 171/200 [03:32<00:35,  1.22s/it]
  iters:  86%|████████▌ | 172/200 [03:33<00:34,  1.24s/it]
  iters:  86%|████████▋ | 173/200 [03:34<00:33,  1.23s/it]
  iters:  87%|████████▋ | 174/200 [03:36<00:33,  1.29s/it]
  iters:  88%|████████▊ | 175/200 [03:37<00:31,  1.26s/it]
  iters:  88%|████████▊ | 176/200 [03:38<00:30,  1.28s/it]
  iters:  88%|████████▊ | 177/200 [03:39<00:28,  1.26s/it]
  iters:  89%|████████▉ | 178/200 [03:40<00:27,  1.24s/it]
  iters:  90%|████████▉ | 179/200 [03:42<00:25,  1.23s/it]
  iters:  90%|█████████ | 180/200 [03:43<00:25,  1.28s/it]
  iters:  90%|█████████ | 181/200 [03:44<00:23,  1.25s/it]
  iters:  91%|█████████ | 182/200 [03:46<00:22,  1.27s/it]
  iters:  92%|█████████▏| 183/200 [03:47<00:21,  1.25s/it]
  iters:  92%|█████████▏| 184/200 [03:48<00:19,  1.23s/it]
  iters:  92%|█████████▎| 185/200 [03:49<00:18,  1.22s/it]
  iters:  93%|█████████▎| 186/200 [03:50<00:17,  1.21s/it]
  iters:  94%|█████████▎| 187/200 [03:52<00:15,  1.21s/it]
  iters:  94%|█████████▍| 188/200 [03:53<00:14,  1.21s/it]
  iters:  94%|█████████▍| 189/200 [03:54<00:13,  1.21s/it]
  iters:  95%|█████████▌| 190/200 [03:55<00:12,  1.20s/it]
  iters:  96%|█████████▌| 191/200 [03:57<00:11,  1.24s/it]
  iters:  96%|█████████▌| 192/200 [03:58<00:09,  1.23s/it]
  iters:  96%|█████████▋| 193/200 [03:59<00:08,  1.28s/it]
  iters:  97%|█████████▋| 194/200 [04:00<00:07,  1.25s/it]
  iters:  98%|█████████▊| 195/200 [04:02<00:06,  1.24s/it]
  iters:  98%|█████████▊| 196/200 [04:03<00:04,  1.23s/it]
  iters:  98%|█████████▊| 197/200 [04:04<00:03,  1.22s/it]
  iters:  99%|█████████▉| 198/200 [04:05<00:02,  1.26s/it]
  iters: 100%|█████████▉| 199/200 [04:07<00:01,  1.26s/it]
  iters: 100%|██████████| 200/200 [04:08<00:00,  1.24s/it]

  [timing] data: 2.1s (1%) | forward: 59.9s (24%) | backward: 186.1s (75%) | total: 248.2s

Training:  25%|██▌       | 1/4 [09:01<13:34, 271.43s/it, acc=0.9985, det=0.0077, edge=0.0007]

  Epoch   1/4 | edge=0.0007 | det=0.0077 | test_loss=0.0019 | acc=0.9985 | recall=0.9152 | best=0.9138 * | train=248.4s test=21.8s

Training:  50%|█████     | 2/4 [09:01<09:01, 270.73s/it, acc=0.9985, det=0.0077, edge=0.0007]
  iters:   0%|          | 0/200 [00:00<?, ?it/s]
  iters:   0%|          | 1/200 [00:01<04:32,  1.37s/it]
  iters:   1%|          | 2/200 [00:02<04:11,  1.27s/it]
  iters:   2%|▏         | 3/200 [00:04<04:25,  1.35s/it]
  iters:   2%|▏         | 4/200 [00:05<04:13,  1.29s/it]
  iters:   2%|▎         | 5/200 [00:06<04:06,  1.26s/it]
  iters:   3%|▎         | 6/200 [00:07<04:13,  1.31s/it]
  iters:   4%|▎         | 7/200 [00:09<04:05,  1.27s/it]
  iters:   4%|▍         | 8/200 [00:10<03:59,  1.25s/it]
  iters:   4%|▍         | 9/200 [00:11<03:55,  1.23s/it]
  iters:   5%|▌         | 10/200 [00:12<03:52,  1.22s/it]
  iters:   6%|▌         | 11/200 [00:13<03:49,  1.22s/it]
  iters:   6%|▌         | 12/200 [00:15<03:48,  1.22s/it]
  iters:   6%|▋         | 13/200 [00:16<03:46,  1.21s/it]
  iters:   7%|▋         | 14/200 [00:17<03:44,  1.21s/it]
  iters:   8%|▊         | 15/200 [00:18<03:55,  1.27s/it]
  iters:   8%|▊         | 16/200 [00:20<03:50,  1.25s/it]
  iters:   8%|▊         | 17/200 [00:21<03:46,  1.24s/it]
  iters:   9%|▉         | 18/200 [00:22<03:43,  1.23s/it]
  iters:  10%|▉         | 19/200 [00:23<03:40,  1.22s/it]
  iters:  10%|█         | 20/200 [00:24<03:38,  1.21s/it]
  iters:  10%|█         | 21/200 [00:26<03:50,  1.29s/it]
  iters:  11%|█         | 22/200 [00:27<03:44,  1.26s/it]
  iters:  12%|█▏        | 23/200 [00:28<03:39,  1.24s/it]
  iters:  12%|█▏        | 24/200 [00:29<03:36,  1.23s/it]
  iters:  12%|█▎        | 25/200 [00:31<03:34,  1.23s/it]
  iters:  13%|█▎        | 26/200 [00:32<03:32,  1.22s/it]
  iters:  14%|█▎        | 27/200 [00:33<03:30,  1.22s/it]
  iters:  14%|█▍        | 28/200 [00:34<03:28,  1.21s/it]
  iters:  14%|█▍        | 29/200 [00:36<03:40,  1.29s/it]
  iters:  15%|█▌        | 30/200 [00:37<03:34,  1.26s/it]
  iters:  16%|█▌        | 31/200 [00:38<03:30,  1.24s/it]
  iters:  16%|█▌        | 32/200 [00:39<03:30,  1.25s/it]
  iters:  16%|█▋        | 33/200 [00:41<03:26,  1.24s/it]
  iters:  17%|█▋        | 34/200 [00:42<03:23,  1.23s/it]
  iters:  18%|█▊        | 35/200 [00:43<03:27,  1.26s/it]
  iters:  18%|█▊        | 36/200 [00:44<03:23,  1.24s/it]
  iters:  18%|█▊        | 37/200 [00:46<03:20,  1.23s/it]
  iters:  19%|█▉        | 38/200 [00:47<03:24,  1.26s/it]
  iters:  20%|█▉        | 39/200 [00:48<03:20,  1.24s/it]
  iters:  20%|██        | 40/200 [00:49<03:23,  1.27s/it]
  iters:  20%|██        | 41/200 [00:51<03:18,  1.25s/it]
  iters:  21%|██        | 42/200 [00:52<03:22,  1.28s/it]
  iters:  22%|██▏       | 43/200 [00:53<03:17,  1.26s/it]
  iters:  22%|██▏       | 44/200 [00:54<03:14,  1.25s/it]
  iters:  22%|██▎       | 45/200 [00:56<03:10,  1.23s/it]
  iters:  23%|██▎       | 46/200 [00:57<03:08,  1.22s/it]
  iters:  24%|██▎       | 47/200 [00:58<03:05,  1.21s/it]
  iters:  24%|██▍       | 48/200 [00:59<03:04,  1.21s/it]
  iters:  24%|██▍       | 49/200 [01:00<03:02,  1.21s/it]
  iters:  25%|██▌       | 50/200 [01:02<03:11,  1.28s/it]
  iters:  26%|██▌       | 51/200 [01:03<03:07,  1.26s/it]
  iters:  26%|██▌       | 52/200 [01:04<03:03,  1.24s/it]
  iters:  26%|██▋       | 53/200 [01:05<03:00,  1.23s/it]
  iters:  27%|██▋       | 54/200 [01:07<02:57,  1.22s/it]
  iters:  28%|██▊       | 55/200 [01:08<02:55,  1.21s/it]
  iters:  28%|██▊       | 56/200 [01:09<02:54,  1.21s/it]
  iters:  28%|██▊       | 57/200 [01:10<02:52,  1.21s/it]
  iters:  29%|██▉       | 58/200 [01:11<02:51,  1.21s/it]
  iters:  30%|██▉       | 59/200 [01:13<02:52,  1.22s/it]
  iters:  30%|███       | 60/200 [01:14<02:51,  1.23s/it]
  iters:  30%|███       | 61/200 [01:15<02:49,  1.22s/it]
  iters:  31%|███       | 62/200 [01:16<02:47,  1.21s/it]
  iters:  32%|███▏      | 63/200 [01:18<02:44,  1.20s/it]
  iters:  32%|███▏      | 64/200 [01:19<02:43,  1.20s/it]
  iters:  32%|███▎      | 65/200 [01:20<02:42,  1.20s/it]
  iters:  33%|███▎      | 66/200 [01:21<02:41,  1.21s/it]
  iters:  34%|███▎      | 67/200 [01:22<02:41,  1.22s/it]
  iters:  34%|███▍      | 68/200 [01:24<02:39,  1.21s/it]
  iters:  34%|███▍      | 69/200 [01:25<02:42,  1.24s/it]
  iters:  35%|███▌      | 70/200 [01:26<02:39,  1.23s/it]
  iters:  36%|███▌      | 71/200 [01:27<02:40,  1.25s/it]
  iters:  36%|███▌      | 72/200 [01:29<02:37,  1.23s/it]
  iters:  36%|███▋      | 73/200 [01:30<02:37,  1.24s/it]
  iters:  37%|███▋      | 74/200 [01:31<02:43,  1.30s/it]
  iters:  38%|███▊      | 75/200 [01:32<02:38,  1.27s/it]
  iters:  38%|███▊      | 76/200 [01:34<02:34,  1.25s/it]
  iters:  38%|███▊      | 77/200 [01:35<02:31,  1.24s/it]
  iters:  39%|███▉      | 78/200 [01:36<02:30,  1.23s/it]
  iters:  40%|███▉      | 79/200 [01:38<02:35,  1.29s/it]
  iters:  40%|████      | 80/200 [01:39<02:31,  1.27s/it]
  iters:  40%|████      | 81/200 [01:40<02:28,  1.25s/it]
  iters:  41%|████      | 82/200 [01:41<02:33,  1.30s/it]
  iters:  42%|████▏     | 83/200 [01:43<02:29,  1.28s/it]
  iters:  42%|████▏     | 84/200 [01:44<02:25,  1.26s/it]
  iters:  42%|████▎     | 85/200 [01:45<02:23,  1.24s/it]
  iters:  43%|████▎     | 86/200 [01:46<02:28,  1.30s/it]
  iters:  44%|████▎     | 87/200 [01:48<02:24,  1.28s/it]
  iters:  44%|████▍     | 88/200 [01:49<02:24,  1.29s/it]
  iters:  44%|████▍     | 89/200 [01:50<02:25,  1.31s/it]
  iters:  45%|████▌     | 90/200 [01:52<02:20,  1.28s/it]
  iters:  46%|████▌     | 91/200 [01:53<02:16,  1.26s/it]
  iters:  46%|████▌     | 92/200 [01:54<02:13,  1.24s/it]
  iters:  46%|████▋     | 93/200 [01:55<02:11,  1.23s/it]
  iters:  47%|████▋     | 94/200 [01:56<02:10,  1.23s/it]
  iters:  48%|████▊     | 95/200 [01:58<02:08,  1.22s/it]
  iters:  48%|████▊     | 96/200 [01:59<02:07,  1.22s/it]
  iters:  48%|████▊     | 97/200 [02:00<02:05,  1.22s/it]
  iters:  49%|████▉     | 98/200 [02:01<02:11,  1.29s/it]
  iters:  50%|████▉     | 99/200 [02:03<02:08,  1.27s/it]
  iters:  50%|█████     | 100/200 [02:04<02:05,  1.25s/it]
  iters:  50%|█████     | 101/200 [02:05<02:02,  1.24s/it]
  iters:  51%|█████     | 102/200 [02:06<02:00,  1.23s/it]
  iters:  52%|█████▏    | 103/200 [02:08<01:58,  1.22s/it]
  iters:  52%|█████▏    | 104/200 [02:09<01:58,  1.24s/it]
  iters:  52%|█████▎    | 105/200 [02:10<01:56,  1.23s/it]
  iters:  53%|█████▎    | 106/200 [02:11<01:55,  1.23s/it]
  iters:  54%|█████▎    | 107/200 [02:13<01:59,  1.29s/it]
  iters:  54%|█████▍    | 108/200 [02:14<01:56,  1.26s/it]
  iters:  55%|█████▍    | 109/200 [02:15<01:53,  1.24s/it]
  iters:  55%|█████▌    | 110/200 [02:16<01:54,  1.27s/it]
  iters:  56%|█████▌    | 111/200 [02:18<01:57,  1.31s/it]
  iters:  56%|█████▌    | 112/200 [02:19<01:52,  1.28s/it]
  iters:  56%|█████▋    | 113/200 [02:20<01:49,  1.26s/it]
  iters:  57%|█████▋    | 114/200 [02:21<01:47,  1.25s/it]
  iters:  57%|█████▊    | 115/200 [02:23<01:45,  1.24s/it]
  iters:  58%|█████▊    | 116/200 [02:24<01:43,  1.23s/it]
  iters:  58%|█████▊    | 117/200 [02:25<01:42,  1.24s/it]
  iters:  59%|█████▉    | 118/200 [02:27<01:44,  1.27s/it]
  iters:  60%|█████▉    | 119/200 [02:28<01:42,  1.27s/it]
  iters:  60%|██████    | 120/200 [02:29<01:39,  1.24s/it]
  iters:  60%|██████    | 121/200 [02:30<01:37,  1.23s/it]
  iters:  61%|██████    | 122/200 [02:31<01:35,  1.22s/it]
  iters:  62%|██████▏   | 123/200 [02:33<01:33,  1.21s/it]
  iters:  62%|██████▏   | 124/200 [02:34<01:32,  1.22s/it]
  iters:  62%|██████▎   | 125/200 [02:35<01:31,  1.22s/it]
  iters:  63%|██████▎   | 126/200 [02:36<01:32,  1.26s/it]
  iters:  64%|██████▎   | 127/200 [02:38<01:32,  1.27s/it]
  iters:  64%|██████▍   | 128/200 [02:39<01:30,  1.25s/it]
  iters:  64%|██████▍   | 129/200 [02:40<01:29,  1.26s/it]
  iters:  65%|██████▌   | 130/200 [02:41<01:29,  1.28s/it]
  iters:  66%|██████▌   | 131/200 [02:43<01:26,  1.25s/it]
  iters:  66%|██████▌   | 132/200 [02:44<01:24,  1.24s/it]
  iters:  66%|██████▋   | 133/200 [02:45<01:22,  1.23s/it]
  iters:  67%|██████▋   | 134/200 [02:46<01:20,  1.22s/it]
  iters:  68%|██████▊   | 135/200 [02:47<01:18,  1.21s/it]
  iters:  68%|██████▊   | 136/200 [02:49<01:17,  1.21s/it]
  iters:  68%|██████▊   | 137/200 [02:50<01:18,  1.25s/it]
  iters:  69%|██████▉   | 138/200 [02:51<01:16,  1.23s/it]
  iters:  70%|██████▉   | 139/200 [02:52<01:16,  1.25s/it]
  iters:  70%|███████   | 140/200 [02:54<01:14,  1.23s/it]
  iters:  70%|███████   | 141/200 [02:55<01:12,  1.22s/it]
  iters:  71%|███████   | 142/200 [02:56<01:10,  1.22s/it]
  iters:  72%|███████▏  | 143/200 [02:57<01:09,  1.22s/it]
  iters:  72%|███████▏  | 144/200 [02:59<01:08,  1.21s/it]
  iters:  72%|███████▎  | 145/200 [03:00<01:06,  1.21s/it]
  iters:  73%|███████▎  | 146/200 [03:01<01:04,  1.20s/it]
  iters:  74%|███████▎  | 147/200 [03:02<01:03,  1.20s/it]
  iters:  74%|███████▍  | 148/200 [03:03<01:02,  1.20s/it]
  iters:  74%|███████▍  | 149/200 [03:04<01:01,  1.20s/it]
  iters:  75%|███████▌  | 150/200 [03:06<01:00,  1.20s/it]
  iters:  76%|███████▌  | 151/200 [03:07<00:58,  1.20s/it]
  iters:  76%|███████▌  | 152/200 [03:08<00:57,  1.20s/it]
  iters:  76%|███████▋  | 153/200 [03:09<00:56,  1.20s/it]
  iters:  77%|███████▋  | 154/200 [03:11<00:56,  1.23s/it]
  iters:  78%|███████▊  | 155/200 [03:12<00:54,  1.22s/it]
  iters:  78%|███████▊  | 156/200 [03:13<00:53,  1.22s/it]
  iters:  78%|███████▊  | 157/200 [03:14<00:52,  1.21s/it]
  iters:  79%|███████▉  | 158/200 [03:16<00:52,  1.24s/it]
  iters:  80%|███████▉  | 159/200 [03:17<00:51,  1.27s/it]
  iters:  80%|████████  | 160/200 [03:18<00:49,  1.25s/it]
  iters:  80%|████████  | 161/200 [03:19<00:48,  1.23s/it]
  iters:  81%|████████  | 162/200 [03:20<00:46,  1.23s/it]
  iters:  82%|████████▏ | 163/200 [03:22<00:45,  1.22s/it]
  iters:  82%|████████▏ | 164/200 [03:23<00:43,  1.21s/it]
  iters:  82%|████████▎ | 165/200 [03:24<00:44,  1.28s/it]
  iters:  83%|████████▎ | 166/200 [03:25<00:42,  1.26s/it]
  iters:  84%|████████▎ | 167/200 [03:27<00:42,  1.29s/it]
  iters:  84%|████████▍ | 168/200 [03:28<00:42,  1.34s/it]
  iters:  84%|████████▍ | 169/200 [03:30<00:41,  1.34s/it]
  iters:  85%|████████▌ | 170/200 [03:31<00:38,  1.30s/it]
  iters:  86%|████████▌ | 171/200 [03:32<00:36,  1.27s/it]
  iters:  86%|████████▌ | 172/200 [03:33<00:35,  1.25s/it]
  iters:  86%|████████▋ | 173/200 [03:35<00:33,  1.25s/it]
  iters:  87%|████████▋ | 174/200 [03:36<00:32,  1.24s/it]
  iters:  88%|████████▊ | 175/200 [03:37<00:30,  1.22s/it]
  iters:  88%|████████▊ | 176/200 [03:38<00:29,  1.22s/it]
  iters:  88%|████████▊ | 177/200 [03:39<00:27,  1.21s/it]
  iters:  89%|████████▉ | 178/200 [03:41<00:26,  1.21s/it]
  iters:  90%|████████▉ | 179/200 [03:42<00:25,  1.21s/it]
  iters:  90%|█████████ | 180/200 [03:43<00:24,  1.21s/it]
  iters:  90%|█████████ | 181/200 [03:44<00:22,  1.21s/it]
  iters:  91%|█████████ | 182/200 [03:45<00:21,  1.21s/it]
  iters:  92%|█████████▏| 183/200 [03:47<00:20,  1.22s/it]
  iters:  92%|█████████▏| 184/200 [03:48<00:20,  1.26s/it]
  iters:  92%|█████████▎| 185/200 [03:49<00:18,  1.24s/it]
  iters:  93%|█████████▎| 186/200 [03:50<00:17,  1.23s/it]
  iters:  94%|█████████▎| 187/200 [03:52<00:15,  1.22s/it]
  iters:  94%|█████████▍| 188/200 [03:53<00:14,  1.22s/it]
  iters:  94%|█████████▍| 189/200 [03:54<00:13,  1.22s/it]
  iters:  95%|█████████▌| 190/200 [03:55<00:12,  1.22s/it]
  iters:  96%|█████████▌| 191/200 [03:56<00:10,  1.21s/it]
  iters:  96%|█████████▌| 192/200 [03:58<00:09,  1.21s/it]
  iters:  96%|█████████▋| 193/200 [03:59<00:08,  1.21s/it]
  iters:  97%|█████████▋| 194/200 [04:00<00:07,  1.25s/it]
  iters:  98%|█████████▊| 195/200 [04:01<00:06,  1.27s/it]
  iters:  98%|█████████▊| 196/200 [04:03<00:04,  1.25s/it]
  iters:  98%|█████████▊| 197/200 [04:04<00:03,  1.23s/it]
  iters:  99%|█████████▉| 198/200 [04:05<00:02,  1.22s/it]
  iters: 100%|█████████▉| 199/200 [04:06<00:01,  1.22s/it]
  iters: 100%|██████████| 200/200 [04:07<00:00,  1.22s/it]

  [timing] data: 2.1s (1%) | forward: 59.7s (24%) | backward: 186.1s (75%) | total: 248.0s

Training:  50%|█████     | 2/4 [13:31<09:01, 270.73s/it, acc=0.9992, det=0.0071, edge=0.0006]

  Epoch   2/4 | edge=0.0006 | det=0.0071 | test_loss=0.0011 | acc=0.9992 | recall=0.9081 | best=0.9138   | train=248.2s test=22.0s

Training:  75%|███████▌  | 3/4 [13:31<04:30, 270.49s/it, acc=0.9992, det=0.0071, edge=0.0006]
  iters:   0%|          | 0/200 [00:00<?, ?it/s]
  iters:   0%|          | 1/200 [00:01<04:52,  1.47s/it]
  iters:   1%|          | 2/200 [00:02<04:18,  1.31s/it]
  iters:   2%|▏         | 3/200 [00:03<04:07,  1.26s/it]
  iters:   2%|▏         | 4/200 [00:05<04:04,  1.25s/it]
  iters:   2%|▎         | 5/200 [00:06<04:08,  1.27s/it]
  iters:   3%|▎         | 6/200 [00:07<04:02,  1.25s/it]
  iters:   4%|▎         | 7/200 [00:08<03:58,  1.24s/it]
  iters:   4%|▍         | 8/200 [00:10<03:55,  1.23s/it]
  iters:   4%|▍         | 9/200 [00:11<03:53,  1.22s/it]
  iters:   5%|▌         | 10/200 [00:12<03:50,  1.21s/it]
  iters:   6%|▌         | 11/200 [00:13<03:48,  1.21s/it]
  iters:   6%|▌         | 12/200 [00:14<03:46,  1.21s/it]
  iters:   6%|▋         | 13/200 [00:16<03:45,  1.20s/it]
  iters:   7%|▋         | 14/200 [00:17<03:44,  1.21s/it]
  iters:   8%|▊         | 15/200 [00:18<03:42,  1.20s/it]
  iters:   8%|▊         | 16/200 [00:19<03:41,  1.20s/it]
  iters:   8%|▊         | 17/200 [00:20<03:39,  1.20s/it]
  iters:   9%|▉         | 18/200 [00:22<03:52,  1.27s/it]
  iters:  10%|▉         | 19/200 [00:23<03:46,  1.25s/it]
  iters:  10%|█         | 20/200 [00:24<03:49,  1.27s/it]
  iters:  10%|█         | 21/200 [00:26<03:43,  1.25s/it]
  iters:  11%|█         | 22/200 [00:27<03:40,  1.24s/it]
  iters:  12%|█▏        | 23/200 [00:28<03:37,  1.23s/it]
  iters:  12%|█▏        | 24/200 [00:29<03:34,  1.22s/it]
  iters:  12%|█▎        | 25/200 [00:30<03:31,  1.21s/it]
  iters:  13%|█▎        | 26/200 [00:32<03:30,  1.21s/it]
  iters:  14%|█▎        | 27/200 [00:33<03:28,  1.21s/it]
  iters:  14%|█▍        | 28/200 [00:34<03:27,  1.20s/it]
  iters:  14%|█▍        | 29/200 [00:35<03:25,  1.20s/it]
  iters:  15%|█▌        | 30/200 [00:36<03:24,  1.20s/it]
  iters:  16%|█▌        | 31/200 [00:38<03:23,  1.20s/it]
  iters:  16%|█▌        | 32/200 [00:39<03:33,  1.27s/it]
  iters:  16%|█▋        | 33/200 [00:40<03:29,  1.25s/it]
  iters:  17%|█▋        | 34/200 [00:41<03:25,  1.24s/it]
  iters:  18%|█▊        | 35/200 [00:43<03:27,  1.26s/it]
  iters:  18%|█▊        | 36/200 [00:44<03:25,  1.25s/it]
  iters:  18%|█▊        | 37/200 [00:45<03:27,  1.27s/it]
  iters:  19%|█▉        | 38/200 [00:47<03:28,  1.28s/it]
  iters:  20%|█▉        | 39/200 [00:48<03:22,  1.26s/it]
  iters:  20%|██        | 40/200 [00:49<03:31,  1.32s/it]
  iters:  20%|██        | 41/200 [00:51<03:30,  1.33s/it]
  iters:  21%|██        | 42/200 [00:52<03:23,  1.29s/it]
  iters:  22%|██▏       | 43/200 [00:53<03:17,  1.26s/it]
  iters:  22%|██▏       | 44/200 [00:54<03:14,  1.25s/it]
  iters:  22%|██▎       | 45/200 [00:55<03:10,  1.23s/it]
  iters:  23%|██▎       | 46/200 [00:57<03:07,  1.22s/it]
  iters:  24%|██▎       | 47/200 [00:58<03:10,  1.25s/it]
  iters:  24%|██▍       | 48/200 [00:59<03:16,  1.29s/it]
  iters:  24%|██▍       | 49/200 [01:00<03:11,  1.27s/it]
  iters:  25%|██▌       | 50/200 [01:02<03:06,  1.24s/it]
  iters:  26%|██▌       | 51/200 [01:03<03:03,  1.23s/it]
  iters:  26%|██▌       | 52/200 [01:04<03:04,  1.25s/it]
  iters:  26%|██▋       | 53/200 [01:06<03:09,  1.29s/it]
  iters:  27%|██▋       | 54/200 [01:07<03:04,  1.27s/it]
  iters:  28%|██▊       | 55/200 [01:08<03:00,  1.25s/it]
  iters:  28%|██▊       | 56/200 [01:09<03:01,  1.26s/it]
  iters:  28%|██▊       | 57/200 [01:10<02:57,  1.24s/it]
  iters:  29%|██▉       | 58/200 [01:12<02:54,  1.23s/it]
  iters:  30%|██▉       | 59/200 [01:13<02:51,  1.22s/it]
  iters:  30%|███       | 60/200 [01:14<02:49,  1.21s/it]
  iters:  30%|███       | 61/200 [01:15<02:50,  1.23s/it]
  iters:  31%|███       | 62/200 [01:16<02:48,  1.22s/it]
  iters:  32%|███▏      | 63/200 [01:18<02:46,  1.21s/it]
  iters:  32%|███▏      | 64/200 [01:19<02:44,  1.21s/it]
  iters:  32%|███▎      | 65/200 [01:20<02:43,  1.21s/it]
  iters:  33%|███▎      | 66/200 [01:21<02:41,  1.20s/it]
  iters:  34%|███▎      | 67/200 [01:22<02:39,  1.20s/it]
  iters:  34%|███▍      | 68/200 [01:24<02:38,  1.20s/it]
  iters:  34%|███▍      | 69/200 [01:25<02:43,  1.25s/it]
  iters:  35%|███▌      | 70/200 [01:26<02:45,  1.27s/it]
  iters:  36%|███▌      | 71/200 [01:28<02:41,  1.25s/it]
  iters:  36%|███▌      | 72/200 [01:29<02:38,  1.24s/it]
  iters:  36%|███▋      | 73/200 [01:30<02:35,  1.22s/it]
  iters:  37%|███▋      | 74/200 [01:31<02:33,  1.22s/it]
  iters:  38%|███▊      | 75/200 [01:32<02:31,  1.21s/it]
  iters:  38%|███▊      | 76/200 [01:34<02:29,  1.20s/it]
  iters:  38%|███▊      | 77/200 [01:35<02:27,  1.20s/it]
  iters:  39%|███▉      | 78/200 [01:36<02:26,  1.20s/it]
  iters:  40%|███▉      | 79/200 [01:37<02:32,  1.26s/it]
  iters:  40%|████      | 80/200 [01:39<02:29,  1.25s/it]
  iters:  40%|████      | 81/200 [01:40<02:26,  1.23s/it]
  iters:  41%|████      | 82/200 [01:41<02:24,  1.23s/it]
  iters:  42%|████▏     | 83/200 [01:42<02:23,  1.23s/it]
  iters:  42%|████▏     | 84/200 [01:44<02:26,  1.26s/it]
  iters:  42%|████▎     | 85/200 [01:45<02:22,  1.24s/it]
  iters:  43%|████▎     | 86/200 [01:46<02:19,  1.23s/it]
  iters:  44%|████▎     | 87/200 [01:47<02:17,  1.22s/it]
  iters:  44%|████▍     | 88/200 [01:48<02:16,  1.22s/it]
  iters:  44%|████▍     | 89/200 [01:50<02:14,  1.21s/it]
  iters:  45%|████▌     | 90/200 [01:51<02:13,  1.21s/it]
  iters:  46%|████▌     | 91/200 [01:52<02:11,  1.21s/it]
  iters:  46%|████▌     | 92/200 [01:53<02:10,  1.21s/it]
  iters:  46%|████▋     | 93/200 [01:54<02:08,  1.20s/it]
  iters:  47%|████▋     | 94/200 [01:56<02:07,  1.21s/it]
  iters:  48%|████▊     | 95/200 [01:57<02:06,  1.20s/it]
  iters:  48%|████▊     | 96/200 [01:58<02:06,  1.22s/it]
  iters:  48%|████▊     | 97/200 [01:59<02:05,  1.21s/it]
  iters:  49%|████▉     | 98/200 [02:00<02:03,  1.21s/it]
  iters:  50%|████▉     | 99/200 [02:02<02:04,  1.23s/it]
  iters:  50%|█████     | 100/200 [02:03<02:02,  1.23s/it]
  iters:  50%|█████     | 101/200 [02:04<02:00,  1.21s/it]
  iters:  51%|█████     | 102/200 [02:05<01:58,  1.21s/it]
  iters:  52%|█████▏    | 103/200 [02:07<02:03,  1.28s/it]
  iters:  52%|█████▏    | 104/200 [02:08<02:00,  1.26s/it]
  iters:  52%|█████▎    | 105/200 [02:09<01:57,  1.24s/it]
  iters:  53%|█████▎    | 106/200 [02:10<01:56,  1.24s/it]
  iters:  54%|█████▎    | 107/200 [02:12<01:53,  1.23s/it]
  iters:  54%|█████▍    | 108/200 [02:13<01:52,  1.22s/it]
  iters:  55%|█████▍    | 109/200 [02:14<01:50,  1.21s/it]
  iters:  55%|█████▌    | 110/200 [02:15<01:48,  1.21s/it]
  iters:  56%|█████▌    | 111/200 [02:16<01:47,  1.20s/it]
  iters:  56%|█████▌    | 112/200 [02:18<01:45,  1.20s/it]
  iters:  56%|█████▋    | 113/200 [02:19<01:45,  1.22s/it]
  iters:  57%|█████▋    | 114/200 [02:20<01:47,  1.25s/it]
  iters:  57%|█████▊    | 115/200 [02:21<01:45,  1.24s/it]
  iters:  58%|█████▊    | 116/200 [02:23<01:43,  1.23s/it]
  iters:  58%|█████▊    | 117/200 [02:24<01:44,  1.25s/it]
  iters:  59%|█████▉    | 118/200 [02:25<01:42,  1.25s/it]
  iters:  60%|█████▉    | 119/200 [02:26<01:40,  1.23s/it]
  iters:  60%|██████    | 120/200 [02:27<01:37,  1.22s/it]
  iters:  60%|██████    | 121/200 [02:29<01:36,  1.22s/it]
  iters:  61%|██████    | 122/200 [02:30<01:34,  1.21s/it]
  iters:  62%|██████▏   | 123/200 [02:31<01:32,  1.21s/it]
  iters:  62%|██████▏   | 124/200 [02:32<01:31,  1.20s/it]
  iters:  62%|██████▎   | 125/200 [02:33<01:30,  1.20s/it]
  iters:  63%|██████▎   | 126/200 [02:35<01:28,  1.20s/it]
  iters:  64%|██████▎   | 127/200 [02:36<01:27,  1.20s/it]
  iters:  64%|██████▍   | 128/200 [02:37<01:26,  1.20s/it]
  iters:  64%|██████▍   | 129/200 [02:38<01:25,  1.21s/it]
  iters:  65%|██████▌   | 130/200 [02:40<01:28,  1.27s/it]
  iters:  66%|██████▌   | 131/200 [02:41<01:28,  1.29s/it]
  iters:  66%|██████▌   | 132/200 [02:42<01:25,  1.26s/it]
  iters:  66%|██████▋   | 133/200 [02:43<01:23,  1.24s/it]
  iters:  67%|██████▋   | 134/200 [02:45<01:21,  1.23s/it]
  iters:  68%|██████▊   | 135/200 [02:46<01:19,  1.22s/it]
  iters:  68%|██████▊   | 136/200 [02:47<01:17,  1.21s/it]
  iters:  68%|██████▊   | 137/200 [02:48<01:16,  1.21s/it]
  iters:  69%|██████▉   | 138/200 [02:49<01:14,  1.21s/it]
  iters:  70%|██████▉   | 139/200 [02:51<01:13,  1.21s/it]
  iters:  70%|███████   | 140/200 [02:52<01:12,  1.20s/it]
  iters:  70%|███████   | 141/200 [02:53<01:10,  1.20s/it]
  iters:  71%|███████   | 142/200 [02:54<01:09,  1.20s/it]
  iters:  72%|███████▏  | 143/200 [02:55<01:08,  1.20s/it]
  iters:  72%|███████▏  | 144/200 [02:57<01:07,  1.20s/it]
  iters:  72%|███████▎  | 145/200 [02:58<01:06,  1.20s/it]
  iters:  73%|███████▎  | 146/200 [02:59<01:04,  1.20s/it]
  iters:  74%|███████▎  | 147/200 [03:01<01:07,  1.28s/it]
  iters:  74%|███████▍  | 148/200 [03:02<01:05,  1.26s/it]
  iters:  74%|███████▍  | 149/200 [03:03<01:03,  1.25s/it]
  iters:  75%|███████▌  | 150/200 [03:04<01:04,  1.29s/it]
  iters:  76%|███████▌  | 151/200 [03:06<01:02,  1.27s/it]
  iters:  76%|███████▌  | 152/200 [03:07<00:59,  1.24s/it]
  iters:  76%|███████▋  | 153/200 [03:08<00:57,  1.23s/it]
  iters:  77%|███████▋  | 154/200 [03:09<00:56,  1.22s/it]
  iters:  78%|███████▊  | 155/200 [03:10<00:54,  1.22s/it]
  iters:  78%|███████▊  | 156/200 [03:12<00:53,  1.22s/it]
  iters:  78%|███████▊  | 157/200 [03:13<00:52,  1.21s/it]
  iters:  79%|███████▉  | 158/200 [03:14<00:51,  1.22s/it]
  iters:  80%|███████▉  | 159/200 [03:15<00:51,  1.27s/it]
  iters:  80%|████████  | 160/200 [03:17<00:49,  1.25s/it]
  iters:  80%|████████  | 161/200 [03:18<00:49,  1.26s/it]
  iters:  81%|████████  | 162/200 [03:19<00:48,  1.28s/it]
  iters:  82%|████████▏ | 163/200 [03:20<00:46,  1.26s/it]
  iters:  82%|████████▏ | 164/200 [03:22<00:44,  1.24s/it]
  iters:  82%|████████▎ | 165/200 [03:23<00:43,  1.23s/it]
  iters:  83%|████████▎ | 166/200 [03:24<00:41,  1.22s/it]
  iters:  84%|████████▎ | 167/200 [03:25<00:40,  1.23s/it]
  iters:  84%|████████▍ | 168/200 [03:26<00:39,  1.22s/it]
  iters:  84%|████████▍ | 169/200 [03:28<00:37,  1.21s/it]
  iters:  85%|████████▌ | 170/200 [03:29<00:37,  1.26s/it]
  iters:  86%|████████▌ | 171/200 [03:30<00:37,  1.30s/it]
  iters:  86%|████████▌ | 172/200 [03:32<00:35,  1.27s/it]
  iters:  86%|████████▋ | 173/200 [03:33<00:33,  1.25s/it]
  iters:  87%|████████▋ | 174/200 [03:34<00:32,  1.25s/it]
  iters:  88%|████████▊ | 175/200 [03:35<00:30,  1.24s/it]
  iters:  88%|████████▊ | 176/200 [03:36<00:29,  1.23s/it]
  iters:  88%|████████▊ | 177/200 [03:38<00:28,  1.22s/it]
  iters:  89%|████████▉ | 178/200 [03:39<00:27,  1.25s/it]
  iters:  90%|████████▉ | 179/200 [03:40<00:25,  1.23s/it]
  iters:  90%|█████████ | 180/200 [03:41<00:24,  1.23s/it]
  iters:  90%|█████████ | 181/200 [03:43<00:23,  1.22s/it]
  iters:  91%|█████████ | 182/200 [03:44<00:21,  1.21s/it]
  iters:  92%|█████████▏| 183/200 [03:45<00:21,  1.26s/it]
  iters:  92%|█████████▏| 184/200 [03:47<00:20,  1.31s/it]
  iters:  92%|█████████▎| 185/200 [03:48<00:19,  1.29s/it]
  iters:  93%|█████████▎| 186/200 [03:49<00:17,  1.26s/it]
  iters:  94%|█████████▎| 187/200 [03:50<00:16,  1.26s/it]
  iters:  94%|█████████▍| 188/200 [03:52<00:15,  1.31s/it]
  iters:  94%|█████████▍| 189/200 [03:53<00:14,  1.29s/it]
  iters:  95%|█████████▌| 190/200 [03:54<00:12,  1.28s/it]
  iters:  96%|█████████▌| 191/200 [03:56<00:11,  1.31s/it]
  iters:  96%|█████████▌| 192/200 [03:57<00:10,  1.28s/it]
  iters:  96%|█████████▋| 193/200 [03:58<00:08,  1.26s/it]
  iters:  97%|█████████▋| 194/200 [03:59<00:07,  1.24s/it]
  iters:  98%|█████████▊| 195/200 [04:00<00:06,  1.23s/it]
  iters:  98%|█████████▊| 196/200 [04:02<00:04,  1.22s/it]
  iters:  98%|█████████▊| 197/200 [04:03<00:03,  1.28s/it]
  iters:  99%|█████████▉| 198/200 [04:04<00:02,  1.26s/it]
  iters: 100%|█████████▉| 199/200 [04:06<00:01,  1.29s/it]
  iters: 100%|██████████| 200/200 [04:07<00:00,  1.26s/it]

  [timing] data: 2.1s (1%) | forward: 59.4s (24%) | backward: 185.7s (75%) | total: 247.2s

Training:  75%|███████▌  | 3/4 [18:01<04:30, 270.49s/it, acc=0.9988, det=0.0065, edge=0.0006]

  Epoch   3/4 | edge=0.0006 | det=0.0065 | test_loss=0.0020 | acc=0.9988 | recall=0.8671 | best=0.9138   | train=247.4s test=21.8s

Training: 100%|██████████| 4/4 [18:01<00:00, 270.27s/it, acc=0.9988, det=0.0065, edge=0.0006]

Best score (acc*recall): 0.9138, saved to /kaggle/working/cellmot-baseline-artifacts/repo/weights/hp_search_tier1/split_0/edge_predictor_best.pth

[tier2_004] score=0.9138  (1087s)
0.019136512 GB allocated
0.249561088 GB reserved
Fold 0: 8 train, 2 test
Loading train (8 datasets)...

train: 100%|██████████| 8/8 [00:05<00:00,  1.53it/s]

  train done: 779 windows total
Loading test (2 datasets)...

test: 100%|██████████| 2/2 [00:00<00:00,  2.03it/s]

  test done: 161 windows total
max_nodes=17
Using device: cuda | visible CUDA GPUs: 2
  Full checkpoint loaded from /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/weights/unet_transformer/split_0/edge_predictor_best.pth: 0 missing, 0 unexpected
Single-GPU training (--single-gpu set). For 2 GPUs set the Kaggle accelerator to 'GPU T4 x2'.
Model parameters: 2,076,706
Starting training for 4 epochs (batch_size=2)...

Training:   0%|          | 0/4 [00:00<?, ?it/s]

Detection loss: weight=4, neg_weight=0.01

  iters:   0%|          | 0/200 [00:00<?, ?it/s]
  iters:   0%|          | 1/200 [00:02<07:03,  2.13s/it]
  iters:   1%|          | 2/200 [00:03<06:14,  1.89s/it]
  iters:   2%|▏         | 3/200 [00:05<05:56,  1.81s/it]
  iters:   2%|▏         | 4/200 [00:07<05:47,  1.77s/it]
  iters:   2%|▎         | 5/200 [00:09<05:44,  1.76s/it]
  iters:   3%|▎         | 6/200 [00:10<05:40,  1.76s/it]
  iters:   4%|▎         | 7/200 [00:12<05:38,  1.75s/it]
  iters:   4%|▍         | 8/200 [00:14<05:37,  1.76s/it]
  iters:   4%|▍         | 9/200 [00:16<05:34,  1.75s/it]
  iters:   5%|▌         | 10/200 [00:17<05:32,  1.75s/it]
  iters:   6%|▌         | 11/200 [00:19<05:32,  1.76s/it]
  iters:   6%|▌         | 12/200 [00:21<05:30,  1.76s/it]
  iters:   6%|▋         | 13/200 [00:23<05:29,  1.76s/it]
  iters:   7%|▋         | 14/200 [00:24<05:28,  1.77s/it]
  iters:   8%|▊         | 15/200 [00:26<05:28,  1.78s/it]
  iters:   8%|▊         | 16/200 [00:28<05:28,  1.78s/it]
  iters:   8%|▊         | 17/200 [00:30<05:26,  1.79s/it]
  iters:   9%|▉         | 18/200 [00:32<05:25,  1.79s/it]
  iters:  10%|▉         | 19/200 [00:33<05:30,  1.82s/it]
  iters:  10%|█         | 20/200 [00:35<05:26,  1.81s/it]
  iters:  10%|█         | 21/200 [00:37<05:23,  1.81s/it]
  iters:  11%|█         | 22/200 [00:39<05:27,  1.84s/it]
  iters:  12%|█▏        | 23/200 [00:41<05:22,  1.82s/it]
  iters:  12%|█▏        | 24/200 [00:42<05:17,  1.81s/it]
  iters:  12%|█▎        | 25/200 [00:44<05:14,  1.79s/it]
  iters:  13%|█▎        | 26/200 [00:46<05:11,  1.79s/it]
  iters:  14%|█▎        | 27/200 [00:48<05:07,  1.78s/it]
  iters:  14%|█▍        | 28/200 [00:50<05:06,  1.78s/it]
  iters:  14%|█▍        | 29/200 [00:51<05:02,  1.77s/it]
  iters:  15%|█▌        | 30/200 [00:53<04:59,  1.76s/it]
  iters:  16%|█▌        | 31/200 [00:55<04:57,  1.76s/it]
  iters:  16%|█▌        | 32/200 [00:57<04:55,  1.76s/it]
  iters:  16%|█▋        | 33/200 [00:58<04:52,  1.75s/it]
  iters:  17%|█▋        | 34/200 [01:00<04:50,  1.75s/it]
  iters:  18%|█▊        | 35/200 [01:02<04:47,  1.74s/it]
  iters:  18%|█▊        | 36/200 [01:04<04:45,  1.74s/it]
  iters:  18%|█▊        | 37/200 [01:05<04:42,  1.74s/it]
  iters:  19%|█▉        | 38/200 [01:07<04:40,  1.73s/it]
  iters:  20%|█▉        | 39/200 [01:09<04:40,  1.74s/it]
  iters:  20%|██        | 40/200 [01:10<04:36,  1.73s/it]
  iters:  20%|██        | 41/200 [01:12<04:34,  1.73s/it]
  iters:  21%|██        | 42/200 [01:14<04:38,  1.76s/it]
  iters:  22%|██▏       | 43/200 [01:16<04:34,  1.75s/it]
  iters:  22%|██▏       | 44/200 [01:17<04:32,  1.75s/it]
  iters:  22%|██▎       | 45/200 [01:19<04:30,  1.75s/it]
  iters:  23%|██▎       | 46/200 [01:21<04:27,  1.74s/it]
  iters:  24%|██▎       | 47/200 [01:23<04:24,  1.73s/it]
  iters:  24%|██▍       | 48/200 [01:24<04:22,  1.73s/it]
  iters:  24%|██▍       | 49/200 [01:26<04:21,  1.73s/it]
  iters:  25%|██▌       | 50/200 [01:28<04:19,  1.73s/it]
  iters:  26%|██▌       | 51/200 [01:30<04:18,  1.74s/it]
  iters:  26%|██▌       | 52/200 [01:31<04:18,  1.75s/it]
  iters:  26%|██▋       | 53/200 [01:33<04:34,  1.87s/it]
  iters:  27%|██▋       | 54/200 [01:35<04:25,  1.82s/it]
  iters:  28%|██▊       | 55/200 [01:37<04:20,  1.80s/it]
  iters:  28%|██▊       | 56/200 [01:39<04:24,  1.84s/it]
  iters:  28%|██▊       | 57/200 [01:41<04:18,  1.81s/it]
  iters:  29%|██▉       | 58/200 [01:42<04:14,  1.79s/it]
  iters:  30%|██▉       | 59/200 [01:44<04:14,  1.80s/it]
  iters:  30%|███       | 60/200 [01:46<04:09,  1.78s/it]
  iters:  30%|███       | 61/200 [01:48<04:11,  1.81s/it]
  iters:  31%|███       | 62/200 [01:50<04:06,  1.79s/it]
  iters:  32%|███▏      | 63/200 [01:51<04:02,  1.77s/it]
  iters:  32%|███▏      | 64/200 [01:53<04:00,  1.77s/it]
  iters:  32%|███▎      | 65/200 [01:55<03:58,  1.77s/it]
  iters:  33%|███▎      | 66/200 [01:57<03:59,  1.79s/it]
  iters:  34%|███▎      | 67/200 [01:58<03:56,  1.78s/it]
  iters:  34%|███▍      | 68/200 [02:00<03:53,  1.77s/it]
  iters:  34%|███▍      | 69/200 [02:02<03:50,  1.76s/it]
  iters:  35%|███▌      | 70/200 [02:04<03:47,  1.75s/it]
  iters:  36%|███▌      | 71/200 [02:05<03:47,  1.76s/it]
  iters:  36%|███▌      | 72/200 [02:07<03:44,  1.76s/it]
  iters:  36%|███▋      | 73/200 [02:09<03:46,  1.78s/it]
  iters:  37%|███▋      | 74/200 [02:11<03:43,  1.78s/it]
  iters:  38%|███▊      | 75/200 [02:12<03:40,  1.77s/it]
  iters:  38%|███▊      | 76/200 [02:14<03:38,  1.76s/it]
  iters:  38%|███▊      | 77/200 [02:16<03:36,  1.76s/it]
  iters:  39%|███▉      | 78/200 [02:18<03:33,  1.75s/it]
  iters:  40%|███▉      | 79/200 [02:19<03:31,  1.75s/it]
  iters:  40%|████      | 80/200 [02:21<03:30,  1.75s/it]
  iters:  40%|████      | 81/200 [02:23<03:30,  1.77s/it]
  iters:  41%|████      | 82/200 [02:25<03:27,  1.76s/it]
  iters:  42%|████▏     | 83/200 [02:27<03:25,  1.76s/it]
  iters:  42%|████▏     | 84/200 [02:28<03:23,  1.75s/it]
  iters:  42%|████▎     | 85/200 [02:30<03:20,  1.75s/it]
  iters:  43%|████▎     | 86/200 [02:32<03:20,  1.76s/it]
  iters:  44%|████▎     | 87/200 [02:34<03:18,  1.75s/it]
  iters:  44%|████▍     | 88/200 [02:35<03:17,  1.76s/it]
  iters:  44%|████▍     | 89/200 [02:37<03:15,  1.76s/it]
  iters:  45%|████▌     | 90/200 [02:39<03:13,  1.76s/it]
  iters:  46%|████▌     | 91/200 [02:41<03:10,  1.75s/it]
  iters:  46%|████▌     | 92/200 [02:42<03:09,  1.75s/it]
  iters:  46%|████▋     | 93/200 [02:44<03:06,  1.75s/it]
  iters:  47%|████▋     | 94/200 [02:46<03:11,  1.80s/it]
  iters:  48%|████▊     | 95/200 [02:48<03:12,  1.83s/it]
  iters:  48%|████▊     | 96/200 [02:50<03:07,  1.80s/it]
  iters:  48%|████▊     | 97/200 [02:51<03:03,  1.78s/it]
  iters:  49%|████▉     | 98/200 [02:53<03:00,  1.77s/it]
  iters:  50%|████▉     | 99/200 [02:55<02:57,  1.76s/it]
  iters:  50%|█████     | 100/200 [02:57<02:55,  1.75s/it]
  iters:  50%|█████     | 101/200 [02:58<02:53,  1.75s/it]
  iters:  51%|█████     | 102/200 [03:00<02:51,  1.75s/it]
  iters:  52%|█████▏    | 103/200 [03:02<02:49,  1.74s/it]
  iters:  52%|█████▏    | 104/200 [03:04<02:48,  1.76s/it]
  iters:  52%|█████▎    | 105/200 [03:05<02:49,  1.79s/it]
  iters:  53%|█████▎    | 106/200 [03:07<02:46,  1.77s/it]
  iters:  54%|█████▎    | 107/200 [03:09<02:43,  1.76s/it]
  iters:  54%|█████▍    | 108/200 [03:11<02:40,  1.75s/it]
  iters:  55%|█████▍    | 109/200 [03:12<02:39,  1.76s/it]
  iters:  55%|█████▌    | 110/200 [03:14<02:42,  1.81s/it]
  iters:  56%|█████▌    | 111/200 [03:16<02:39,  1.79s/it]
  iters:  56%|█████▌    | 112/200 [03:18<02:38,  1.81s/it]
  iters:  56%|█████▋    | 113/200 [03:20<02:35,  1.79s/it]
  iters:  57%|█████▋    | 114/200 [03:21<02:32,  1.77s/it]
  iters:  57%|█████▊    | 115/200 [03:23<02:35,  1.83s/it]
  iters:  58%|█████▊    | 116/200 [03:25<02:31,  1.80s/it]
  iters:  58%|█████▊    | 117/200 [03:27<02:27,  1.78s/it]
  iters:  59%|█████▉    | 118/200 [03:29<02:25,  1.77s/it]
  iters:  60%|█████▉    | 119/200 [03:30<02:26,  1.80s/it]
  iters:  60%|██████    | 120/200 [03:32<02:22,  1.79s/it]
  iters:  60%|██████    | 121/200 [03:34<02:19,  1.77s/it]
  iters:  61%|██████    | 122/200 [03:36<02:16,  1.76s/it]
  iters:  62%|██████▏   | 123/200 [03:37<02:14,  1.75s/it]
  iters:  62%|██████▏   | 124/200 [03:39<02:12,  1.75s/it]
  iters:  62%|██████▎   | 125/200 [03:41<02:13,  1.77s/it]
  iters:  63%|██████▎   | 126/200 [03:43<02:10,  1.76s/it]
  iters:  64%|██████▎   | 127/200 [03:44<02:08,  1.76s/it]
  iters:  64%|██████▍   | 128/200 [03:46<02:05,  1.75s/it]
  iters:  64%|██████▍   | 129/200 [03:48<02:03,  1.74s/it]
  iters:  65%|██████▌   | 130/200 [03:50<02:01,  1.74s/it]
  iters:  66%|██████▌   | 131/200 [03:52<02:03,  1.79s/it]
  iters:  66%|██████▌   | 132/200 [03:53<02:00,  1.78s/it]
  iters:  66%|██████▋   | 133/200 [03:55<01:58,  1.77s/it]
  iters:  67%|██████▋   | 134/200 [03:57<01:56,  1.76s/it]
  iters:  68%|██████▊   | 135/200 [03:59<01:54,  1.76s/it]
  iters:  68%|██████▊   | 136/200 [04:00<01:52,  1.75s/it]
  iters:  68%|██████▊   | 137/200 [04:02<01:50,  1.76s/it]
  iters:  69%|██████▉   | 138/200 [04:04<01:48,  1.75s/it]
  iters:  70%|██████▉   | 139/200 [04:05<01:46,  1.74s/it]
  iters:  70%|███████   | 140/200 [04:07<01:44,  1.74s/it]
  iters:  70%|███████   | 141/200 [04:09<01:44,  1.77s/it]
  iters:  71%|███████   | 142/200 [04:11<01:42,  1.76s/it]
  iters:  72%|███████▏  | 143/200 [04:13<01:39,  1.75s/it]
  iters:  72%|███████▏  | 144/200 [04:14<01:41,  1.81s/it]
  iters:  72%|███████▎  | 145/200 [04:16<01:38,  1.79s/it]
  iters:  73%|███████▎  | 146/200 [04:18<01:35,  1.77s/it]
  iters:  74%|███████▎  | 147/200 [04:20<01:33,  1.76s/it]
  iters:  74%|███████▍  | 148/200 [04:21<01:31,  1.75s/it]
  iters:  74%|███████▍  | 149/200 [04:23<01:29,  1.75s/it]
  iters:  75%|███████▌  | 150/200 [04:25<01:30,  1.80s/it]
  iters:  76%|███████▌  | 151/200 [04:27<01:27,  1.79s/it]
  iters:  76%|███████▌  | 152/200 [04:29<01:25,  1.77s/it]
  iters:  76%|███████▋  | 153/200 [04:30<01:23,  1.77s/it]
  iters:  77%|███████▋  | 154/200 [04:32<01:22,  1.80s/it]
  iters:  78%|███████▊  | 155/200 [04:34<01:20,  1.79s/it]
  iters:  78%|███████▊  | 156/200 [04:36<01:19,  1.80s/it]
  iters:  78%|███████▊  | 157/200 [04:38<01:16,  1.78s/it]
  iters:  79%|███████▉  | 158/200 [04:39<01:14,  1.79s/it]
  iters:  80%|███████▉  | 159/200 [04:41<01:12,  1.77s/it]
  iters:  80%|████████  | 160/200 [04:43<01:11,  1.78s/it]
  iters:  80%|████████  | 161/200 [04:45<01:09,  1.77s/it]
  iters:  81%|████████  | 162/200 [04:46<01:07,  1.77s/it]
  iters:  82%|████████▏ | 163/200 [04:48<01:06,  1.81s/it]
  iters:  82%|████████▏ | 164/200 [04:50<01:04,  1.79s/it]
  iters:  82%|████████▎ | 165/200 [04:52<01:05,  1.86s/it]
  iters:  83%|████████▎ | 166/200 [04:54<01:03,  1.88s/it]
  iters:  84%|████████▎ | 167/200 [04:56<01:03,  1.92s/it]
  iters:  84%|████████▍ | 168/200 [04:58<00:59,  1.87s/it]
  iters:  84%|████████▍ | 169/200 [04:59<00:56,  1.83s/it]
  iters:  85%|████████▌ | 170/200 [05:01<00:54,  1.81s/it]
  iters:  86%|████████▌ | 171/200 [05:03<00:51,  1.79s/it]
  iters:  86%|████████▌ | 172/200 [05:05<00:53,  1.93s/it]
  iters:  86%|████████▋ | 173/200 [05:07<00:50,  1.87s/it]
  iters:  87%|████████▋ | 174/200 [05:09<00:47,  1.84s/it]
  iters:  88%|████████▊ | 175/200 [05:11<00:46,  1.86s/it]
  iters:  88%|████████▊ | 176/200 [05:12<00:44,  1.84s/it]
  iters:  88%|████████▊ | 177/200 [05:14<00:41,  1.82s/it]
  iters:  89%|████████▉ | 178/200 [05:16<00:39,  1.80s/it]
  iters:  90%|████████▉ | 179/200 [05:18<00:37,  1.79s/it]
  iters:  90%|█████████ | 180/200 [05:20<00:35,  1.78s/it]
  iters:  90%|█████████ | 181/200 [05:21<00:33,  1.77s/it]
  iters:  91%|█████████ | 182/200 [05:23<00:31,  1.77s/it]
  iters:  92%|█████████▏| 183/200 [05:25<00:29,  1.76s/it]
  iters:  92%|█████████▏| 184/200 [05:27<00:28,  1.76s/it]
  iters:  92%|█████████▎| 185/200 [05:28<00:26,  1.75s/it]
  iters:  93%|█████████▎| 186/200 [05:30<00:25,  1.79s/it]
  iters:  94%|█████████▎| 187/200 [05:32<00:23,  1.81s/it]
  iters:  94%|█████████▍| 188/200 [05:34<00:21,  1.79s/it]
  iters:  94%|█████████▍| 189/200 [05:35<00:19,  1.78s/it]
  iters:  95%|█████████▌| 190/200 [05:37<00:17,  1.77s/it]
  iters:  96%|█████████▌| 191/200 [05:39<00:15,  1.77s/it]
  iters:  96%|█████████▌| 192/200 [05:41<00:14,  1.76s/it]
  iters:  96%|█████████▋| 193/200 [05:42<00:12,  1.76s/it]
  iters:  97%|█████████▋| 194/200 [05:44<00:10,  1.75s/it]
  iters:  98%|█████████▊| 195/200 [05:46<00:08,  1.78s/it]
  iters:  98%|█████████▊| 196/200 [05:48<00:07,  1.77s/it]
  iters:  98%|█████████▊| 197/200 [05:50<00:05,  1.75s/it]
  iters:  99%|█████████▉| 198/200 [05:52<00:03,  1.83s/it]
  iters: 100%|█████████▉| 199/200 [05:53<00:01,  1.80s/it]
  iters: 100%|██████████| 200/200 [05:55<00:00,  1.78s/it]

  [timing] data: 2.4s (1%) | forward: 87.2s (25%) | backward: 265.9s (75%) | total: 355.5s

Training:   0%|          | 0/4 [06:27<?, ?it/s, acc=0.9993, det=0.0091, edge=0.0006]

  Epoch   0/4 | edge=0.0006 | det=0.0091 | test_loss=0.0010 | acc=0.9993 | recall=0.8813 | best=0.8807 * | train=355.8s test=31.3s

Training:  25%|██▌       | 1/4 [06:27<19:21, 387.09s/it, acc=0.9993, det=0.0091, edge=0.0006]
  iters:   0%|          | 0/200 [00:00<?, ?it/s]
  iters:   0%|          | 1/200 [00:02<06:52,  2.07s/it]
  iters:   1%|          | 2/200 [00:03<06:12,  1.88s/it]
  iters:   2%|▏         | 3/200 [00:05<06:01,  1.84s/it]
  iters:   2%|▏         | 4/200 [00:07<06:12,  1.90s/it]
  iters:   2%|▎         | 5/200 [00:09<06:06,  1.88s/it]
  iters:   3%|▎         | 6/200 [00:11<05:55,  1.83s/it]
  iters:   4%|▎         | 7/200 [00:12<05:47,  1.80s/it]
  iters:   4%|▍         | 8/200 [00:14<05:41,  1.78s/it]
  iters:   4%|▍         | 9/200 [00:16<05:37,  1.77s/it]
  iters:   5%|▌         | 10/200 [00:18<05:33,  1.75s/it]
  iters:   6%|▌         | 11/200 [00:19<05:31,  1.75s/it]
  iters:   6%|▌         | 12/200 [00:21<05:29,  1.75s/it]
  iters:   6%|▋         | 13/200 [00:23<05:25,  1.74s/it]
  iters:   7%|▋         | 14/200 [00:25<05:24,  1.75s/it]
  iters:   8%|▊         | 15/200 [00:27<05:38,  1.83s/it]
  iters:   8%|▊         | 16/200 [00:28<05:31,  1.80s/it]
  iters:   8%|▊         | 17/200 [00:30<05:26,  1.78s/it]
  iters:   9%|▉         | 18/200 [00:32<05:25,  1.79s/it]
  iters:  10%|▉         | 19/200 [00:34<05:27,  1.81s/it]
  iters:  10%|█         | 20/200 [00:35<05:22,  1.79s/it]
  iters:  10%|█         | 21/200 [00:37<05:18,  1.78s/it]
  iters:  11%|█         | 22/200 [00:39<05:14,  1.77s/it]
  iters:  12%|█▏        | 23/200 [00:41<05:23,  1.83s/it]
  iters:  12%|█▏        | 24/200 [00:43<05:19,  1.81s/it]
  iters:  12%|█▎        | 25/200 [00:44<05:13,  1.79s/it]
  iters:  13%|█▎        | 26/200 [00:46<05:09,  1.78s/it]
  iters:  14%|█▎        | 27/200 [00:48<05:06,  1.77s/it]
  iters:  14%|█▍        | 28/200 [00:50<05:02,  1.76s/it]
  iters:  14%|█▍        | 29/200 [00:51<05:00,  1.76s/it]
  iters:  15%|█▌        | 30/200 [00:53<05:08,  1.82s/it]
  iters:  16%|█▌        | 31/200 [00:55<05:05,  1.81s/it]
  iters:  16%|█▌        | 32/200 [00:57<05:20,  1.91s/it]
  iters:  16%|█▋        | 33/200 [00:59<05:09,  1.85s/it]
  iters:  17%|█▋        | 34/200 [01:01<05:16,  1.91s/it]
  iters:  18%|█▊        | 35/200 [01:03<05:06,  1.86s/it]
  iters:  18%|█▊        | 36/200 [01:05<04:59,  1.82s/it]
  iters:  18%|█▊        | 37/200 [01:06<04:53,  1.80s/it]
  iters:  19%|█▉        | 38/200 [01:08<04:49,  1.79s/it]
  iters:  20%|█▉        | 39/200 [01:10<04:48,  1.79s/it]
  iters:  20%|██        | 40/200 [01:12<04:45,  1.78s/it]
  iters:  20%|██        | 41/200 [01:14<04:53,  1.85s/it]
  iters:  21%|██        | 42/200 [01:16<05:00,  1.90s/it]
  iters:  22%|██▏       | 43/200 [01:17<04:51,  1.86s/it]
  iters:  22%|██▏       | 44/200 [01:19<04:43,  1.82s/it]
  iters:  22%|██▎       | 45/200 [01:21<04:38,  1.80s/it]
  iters:  23%|██▎       | 46/200 [01:23<04:33,  1.78s/it]
  iters:  24%|██▎       | 47/200 [01:24<04:31,  1.77s/it]
  iters:  24%|██▍       | 48/200 [01:26<04:29,  1.78s/it]
  iters:  24%|██▍       | 49/200 [01:28<04:26,  1.76s/it]
  iters:  25%|██▌       | 50/200 [01:30<04:29,  1.80s/it]
  iters:  26%|██▌       | 51/200 [01:32<04:24,  1.78s/it]
  iters:  26%|██▌       | 52/200 [01:33<04:21,  1.77s/it]
  iters:  26%|██▋       | 53/200 [01:35<04:18,  1.76s/it]
  iters:  27%|██▋       | 54/200 [01:37<04:22,  1.80s/it]
  iters:  28%|██▊       | 55/200 [01:39<04:17,  1.77s/it]
  iters:  28%|██▊       | 56/200 [01:40<04:14,  1.77s/it]
  iters:  28%|██▊       | 57/200 [01:42<04:11,  1.76s/it]
  iters:  29%|██▉       | 58/200 [01:44<04:09,  1.76s/it]
  iters:  30%|██▉       | 59/200 [01:46<04:18,  1.83s/it]
  iters:  30%|███       | 60/200 [01:48<04:22,  1.87s/it]
  iters:  30%|███       | 61/200 [01:50<04:14,  1.83s/it]
  iters:  31%|███       | 62/200 [01:51<04:09,  1.81s/it]
  iters:  32%|███▏      | 63/200 [01:53<04:15,  1.86s/it]
  iters:  32%|███▏      | 64/200 [01:55<04:07,  1.82s/it]
  iters:  32%|███▎      | 65/200 [01:57<04:02,  1.80s/it]
  iters:  33%|███▎      | 66/200 [01:59<03:58,  1.78s/it]
  iters:  34%|███▎      | 67/200 [02:00<03:56,  1.78s/it]
  iters:  34%|███▍      | 68/200 [02:02<03:55,  1.79s/it]
  iters:  34%|███▍      | 69/200 [02:04<03:51,  1.77s/it]
  iters:  35%|███▌      | 70/200 [02:06<03:51,  1.78s/it]
  iters:  36%|███▌      | 71/200 [02:07<03:49,  1.78s/it]
  iters:  36%|███▌      | 72/200 [02:09<03:46,  1.77s/it]
  iters:  36%|███▋      | 73/200 [02:11<03:44,  1.76s/it]
  iters:  37%|███▋      | 74/200 [02:13<03:42,  1.76s/it]
  iters:  38%|███▊      | 75/200 [02:15<03:48,  1.82s/it]
  iters:  38%|███▊      | 76/200 [02:16<03:43,  1.80s/it]
  iters:  38%|███▊      | 77/200 [02:18<03:39,  1.78s/it]
  iters:  39%|███▉      | 78/200 [02:20<03:35,  1.76s/it]
  iters:  40%|███▉      | 79/200 [02:22<03:33,  1.77s/it]
  iters:  40%|████      | 80/200 [02:23<03:31,  1.76s/it]
  iters:  40%|████      | 81/200 [02:25<03:28,  1.75s/it]
  iters:  41%|████      | 82/200 [02:27<03:26,  1.75s/it]
  iters:  42%|████▏     | 83/200 [02:29<03:24,  1.74s/it]
  iters:  42%|████▏     | 84/200 [02:30<03:21,  1.74s/it]
  iters:  42%|████▎     | 85/200 [02:32<03:28,  1.82s/it]
  iters:  43%|████▎     | 86/200 [02:34<03:24,  1.79s/it]
  iters:  44%|████▎     | 87/200 [02:36<03:20,  1.77s/it]
  iters:  44%|████▍     | 88/200 [02:38<03:24,  1.83s/it]
  iters:  44%|████▍     | 89/200 [02:39<03:19,  1.80s/it]
  iters:  45%|████▌     | 90/200 [02:41<03:15,  1.78s/it]
  iters:  46%|████▌     | 91/200 [02:43<03:12,  1.77s/it]
  iters:  46%|████▌     | 92/200 [02:45<03:12,  1.78s/it]
  iters:  46%|████▋     | 93/200 [02:46<03:09,  1.77s/it]
  iters:  47%|████▋     | 94/200 [02:48<03:14,  1.83s/it]
  iters:  48%|████▊     | 95/200 [02:50<03:09,  1.80s/it]
  iters:  48%|████▊     | 96/200 [02:52<03:07,  1.80s/it]
  iters:  48%|████▊     | 97/200 [02:54<03:03,  1.78s/it]
  iters:  49%|████▉     | 98/200 [02:55<03:00,  1.77s/it]
  iters:  50%|████▉     | 99/200 [02:57<02:58,  1.77s/it]
  iters:  50%|█████     | 100/200 [02:59<02:55,  1.75s/it]
  iters:  50%|█████     | 101/200 [03:01<02:53,  1.75s/it]
  iters:  51%|█████     | 102/200 [03:02<02:50,  1.74s/it]
  iters:  52%|█████▏    | 103/200 [03:04<02:52,  1.78s/it]
  iters:  52%|█████▏    | 104/200 [03:06<02:49,  1.77s/it]
  iters:  52%|█████▎    | 105/200 [03:08<02:47,  1.76s/it]
  iters:  53%|█████▎    | 106/200 [03:09<02:44,  1.75s/it]
  iters:  54%|█████▎    | 107/200 [03:11<02:42,  1.75s/it]
  iters:  54%|█████▍    | 108/200 [03:13<02:40,  1.74s/it]
  iters:  55%|█████▍    | 109/200 [03:15<02:38,  1.74s/it]
  iters:  55%|█████▌    | 110/200 [03:16<02:35,  1.73s/it]
  iters:  56%|█████▌    | 111/200 [03:18<02:34,  1.74s/it]
  iters:  56%|█████▌    | 112/200 [03:20<02:32,  1.74s/it]
  iters:  56%|█████▋    | 113/200 [03:22<02:35,  1.79s/it]
  iters:  57%|█████▋    | 114/200 [03:24<02:32,  1.77s/it]
  iters:  57%|█████▊    | 115/200 [03:25<02:30,  1.78s/it]
  iters:  58%|█████▊    | 116/200 [03:27<02:27,  1.76s/it]
  iters:  58%|█████▊    | 117/200 [03:29<02:25,  1.75s/it]
  iters:  59%|█████▉    | 118/200 [03:30<02:23,  1.75s/it]
  iters:  60%|█████▉    | 119/200 [03:32<02:20,  1.74s/it]
  iters:  60%|██████    | 120/200 [03:34<02:18,  1.74s/it]
  iters:  60%|██████    | 121/200 [03:36<02:17,  1.74s/it]
  iters:  61%|██████    | 122/200 [03:37<02:15,  1.73s/it]
  iters:  62%|██████▏   | 123/200 [03:39<02:17,  1.78s/it]
  iters:  62%|██████▏   | 124/200 [03:41<02:14,  1.77s/it]
  iters:  62%|██████▎   | 125/200 [03:43<02:12,  1.76s/it]
  iters:  63%|██████▎   | 126/200 [03:45<02:09,  1.75s/it]
  iters:  64%|██████▎   | 127/200 [03:46<02:07,  1.75s/it]
  iters:  64%|██████▍   | 128/200 [03:48<02:05,  1.74s/it]
  iters:  64%|██████▍   | 129/200 [03:50<02:04,  1.75s/it]
  iters:  65%|██████▌   | 130/200 [03:51<02:02,  1.74s/it]
  iters:  66%|██████▌   | 131/200 [03:53<02:02,  1.78s/it]
  iters:  66%|██████▌   | 132/200 [03:55<02:02,  1.81s/it]
  iters:  66%|██████▋   | 133/200 [03:57<01:59,  1.79s/it]
  iters:  67%|██████▋   | 134/200 [03:59<01:56,  1.77s/it]
  iters:  68%|██████▊   | 135/200 [04:00<01:54,  1.76s/it]
  iters:  68%|██████▊   | 136/200 [04:02<01:52,  1.75s/it]
  iters:  68%|██████▊   | 137/200 [04:04<01:50,  1.75s/it]
  iters:  69%|██████▉   | 138/200 [04:06<01:48,  1.75s/it]
  iters:  70%|██████▉   | 139/200 [04:07<01:48,  1.78s/it]
  iters:  70%|███████   | 140/200 [04:09<01:45,  1.77s/it]
  iters:  70%|███████   | 141/200 [04:11<01:43,  1.75s/it]
  iters:  71%|███████   | 142/200 [04:13<01:42,  1.77s/it]
  iters:  72%|███████▏  | 143/200 [04:15<01:40,  1.76s/it]
  iters:  72%|███████▏  | 144/200 [04:16<01:38,  1.76s/it]
  iters:  72%|███████▎  | 145/200 [04:18<01:36,  1.75s/it]
  iters:  73%|███████▎  | 146/200 [04:20<01:34,  1.74s/it]
  iters:  74%|███████▎  | 147/200 [04:21<01:32,  1.74s/it]
  iters:  74%|███████▍  | 148/200 [04:23<01:30,  1.74s/it]
  iters:  74%|███████▍  | 149/200 [04:25<01:30,  1.77s/it]
  iters:  75%|███████▌  | 150/200 [04:27<01:27,  1.76s/it]
  iters:  76%|███████▌  | 151/200 [04:28<01:25,  1.75s/it]
  iters:  76%|███████▌  | 152/200 [04:30<01:23,  1.75s/it]
  iters:  76%|███████▋  | 153/200 [04:32<01:21,  1.74s/it]
  iters:  77%|███████▋  | 154/200 [04:34<01:23,  1.82s/it]
  iters:  78%|███████▊  | 155/200 [04:36<01:20,  1.79s/it]
  iters:  78%|███████▊  | 156/200 [04:37<01:18,  1.78s/it]
  iters:  78%|███████▊  | 157/200 [04:39<01:16,  1.78s/it]
  iters:  79%|███████▉  | 158/200 [04:41<01:14,  1.76s/it]
  iters:  80%|███████▉  | 159/200 [04:43<01:11,  1.75s/it]
  iters:  80%|████████  | 160/200 [04:44<01:09,  1.75s/it]
  iters:  80%|████████  | 161/200 [04:46<01:08,  1.76s/it]
  iters:  81%|████████  | 162/200 [04:48<01:06,  1.76s/it]
  iters:  82%|████████▏ | 163/200 [04:50<01:04,  1.76s/it]
  iters:  82%|████████▏ | 164/200 [04:51<01:03,  1.76s/it]
  iters:  82%|████████▎ | 165/200 [04:53<01:01,  1.75s/it]
  iters:  83%|████████▎ | 166/200 [04:55<00:59,  1.75s/it]
  iters:  84%|████████▎ | 167/200 [04:57<00:58,  1.77s/it]
  iters:  84%|████████▍ | 168/200 [04:59<00:56,  1.77s/it]
  iters:  84%|████████▍ | 169/200 [05:00<00:54,  1.76s/it]
  iters:  85%|████████▌ | 170/200 [05:02<00:53,  1.79s/it]
  iters:  86%|████████▌ | 171/200 [05:04<00:51,  1.78s/it]
  iters:  86%|████████▌ | 172/200 [05:06<00:49,  1.78s/it]
  iters:  86%|████████▋ | 173/200 [05:07<00:47,  1.77s/it]
  iters:  87%|████████▋ | 174/200 [05:09<00:45,  1.76s/it]
  iters:  88%|████████▊ | 175/200 [05:11<00:44,  1.79s/it]
  iters:  88%|████████▊ | 176/200 [05:13<00:43,  1.81s/it]
  iters:  88%|████████▊ | 177/200 [05:15<00:41,  1.82s/it]
  iters:  89%|████████▉ | 178/200 [05:17<00:40,  1.83s/it]
  iters:  90%|████████▉ | 179/200 [05:18<00:38,  1.83s/it]
  iters:  90%|█████████ | 180/200 [05:20<00:36,  1.81s/it]
  iters:  90%|█████████ | 181/200 [05:22<00:35,  1.86s/it]
  iters:  91%|█████████ | 182/200 [05:24<00:33,  1.84s/it]
  iters:  92%|█████████▏| 183/200 [05:26<00:30,  1.81s/it]
  iters:  92%|█████████▏| 184/200 [05:28<00:29,  1.83s/it]
  iters:  92%|█████████▎| 185/200 [05:29<00:27,  1.80s/it]
  iters:  93%|█████████▎| 186/200 [05:31<00:24,  1.78s/it]
  iters:  94%|█████████▎| 187/200 [05:33<00:22,  1.77s/it]
  iters:  94%|█████████▍| 188/200 [05:34<00:21,  1.76s/it]
  iters:  94%|█████████▍| 189/200 [05:36<00:19,  1.76s/it]
  iters:  95%|█████████▌| 190/200 [05:38<00:17,  1.75s/it]
  iters:  96%|█████████▌| 191/200 [05:40<00:15,  1.75s/it]
  iters:  96%|█████████▌| 192/200 [05:41<00:14,  1.75s/it]
  iters:  96%|█████████▋| 193/200 [05:43<00:12,  1.75s/it]
  iters:  97%|█████████▋| 194/200 [05:45<00:10,  1.75s/it]
  iters:  98%|█████████▊| 195/200 [05:47<00:08,  1.77s/it]
  iters:  98%|█████████▊| 196/200 [05:49<00:07,  1.76s/it]
  iters:  98%|█████████▊| 197/200 [05:50<00:05,  1.75s/it]
  iters:  99%|█████████▉| 198/200 [05:52<00:03,  1.75s/it]
  iters: 100%|█████████▉| 199/200 [05:54<00:01,  1.74s/it]
  iters: 100%|██████████| 200/200 [05:55<00:00,  1.74s/it]

  [timing] data: 2.4s (1%) | forward: 87.3s (25%) | backward: 266.3s (75%) | total: 355.9s

Training:  25%|██▌       | 1/4 [12:54<19:21, 387.09s/it, acc=0.9993, det=0.0069, edge=0.0005]

  Epoch   1/4 | edge=0.0005 | det=0.0069 | test_loss=0.0014 | acc=0.9993 | recall=0.8865 | best=0.8859 * | train=356.1s test=31.0s

Training:  50%|█████     | 2/4 [12:54<12:54, 387.11s/it, acc=0.9993, det=0.0069, edge=0.0005]
  iters:   0%|          | 0/200 [00:00<?, ?it/s]
  iters:   0%|          | 1/200 [00:02<06:54,  2.08s/it]
  iters:   1%|          | 2/200 [00:03<06:11,  1.87s/it]
  iters:   2%|▏         | 3/200 [00:05<06:14,  1.90s/it]
  iters:   2%|▏         | 4/200 [00:07<05:58,  1.83s/it]
  iters:   2%|▎         | 5/200 [00:09<05:50,  1.80s/it]
  iters:   3%|▎         | 6/200 [00:10<05:43,  1.77s/it]
  iters:   4%|▎         | 7/200 [00:12<05:39,  1.76s/it]
  iters:   4%|▍         | 8/200 [00:14<05:43,  1.79s/it]
  iters:   4%|▍         | 9/200 [00:16<05:38,  1.77s/it]
  iters:   5%|▌         | 10/200 [00:17<05:35,  1.77s/it]
  iters:   6%|▌         | 11/200 [00:19<05:40,  1.80s/it]
  iters:   6%|▌         | 12/200 [00:21<05:35,  1.78s/it]
  iters:   6%|▋         | 13/200 [00:23<05:30,  1.77s/it]
  iters:   7%|▋         | 14/200 [00:25<05:28,  1.76s/it]
  iters:   8%|▊         | 15/200 [00:26<05:25,  1.76s/it]
  iters:   8%|▊         | 16/200 [00:28<05:21,  1.75s/it]
  iters:   8%|▊         | 17/200 [00:30<05:23,  1.77s/it]
  iters:   9%|▉         | 18/200 [00:32<05:19,  1.76s/it]
  iters:  10%|▉         | 19/200 [00:33<05:16,  1.75s/it]
  iters:  10%|█         | 20/200 [00:35<05:21,  1.79s/it]
  iters:  10%|█         | 21/200 [00:37<05:16,  1.77s/it]
  iters:  11%|█         | 22/200 [00:39<05:17,  1.79s/it]
  iters:  12%|█▏        | 23/200 [00:41<05:22,  1.82s/it]
  iters:  12%|█▏        | 24/200 [00:42<05:15,  1.79s/it]
  iters:  12%|█▎        | 25/200 [00:44<05:23,  1.85s/it]
  iters:  13%|█▎        | 26/200 [00:46<05:19,  1.84s/it]
  iters:  14%|█▎        | 27/200 [00:48<05:12,  1.81s/it]
  iters:  14%|█▍        | 28/200 [00:50<05:07,  1.79s/it]
  iters:  14%|█▍        | 29/200 [00:52<05:11,  1.82s/it]
  iters:  15%|█▌        | 30/200 [00:53<05:05,  1.79s/it]
  iters:  16%|█▌        | 31/200 [00:55<05:00,  1.78s/it]
  iters:  16%|█▌        | 32/200 [00:57<04:56,  1.76s/it]
  iters:  16%|█▋        | 33/200 [00:59<04:52,  1.75s/it]
  iters:  17%|█▋        | 34/200 [01:00<04:49,  1.75s/it]
  iters:  18%|█▊        | 35/200 [01:02<04:47,  1.75s/it]
  iters:  18%|█▊        | 36/200 [01:04<04:45,  1.74s/it]
  iters:  18%|█▊        | 37/200 [01:05<04:44,  1.75s/it]
  iters:  19%|█▉        | 38/200 [01:07<04:42,  1.74s/it]
  iters:  20%|█▉        | 39/200 [01:09<04:40,  1.74s/it]
  iters:  20%|██        | 40/200 [01:11<04:48,  1.80s/it]
  iters:  20%|██        | 41/200 [01:13<04:43,  1.78s/it]
  iters:  21%|██        | 42/200 [01:14<04:40,  1.77s/it]
  iters:  22%|██▏       | 43/200 [01:16<04:36,  1.76s/it]
  iters:  22%|██▏       | 44/200 [01:18<04:33,  1.75s/it]
  iters:  22%|██▎       | 45/200 [01:20<04:33,  1.77s/it]
  iters:  23%|██▎       | 46/200 [01:21<04:30,  1.76s/it]
  iters:  24%|██▎       | 47/200 [01:23<04:28,  1.75s/it]
  iters:  24%|██▍       | 48/200 [01:25<04:26,  1.75s/it]
  iters:  24%|██▍       | 49/200 [01:27<04:27,  1.77s/it]
  iters:  25%|██▌       | 50/200 [01:28<04:26,  1.78s/it]
  iters:  26%|██▌       | 51/200 [01:30<04:23,  1.77s/it]
  iters:  26%|██▌       | 52/200 [01:32<04:20,  1.76s/it]
  iters:  26%|██▋       | 53/200 [01:34<04:27,  1.82s/it]
  iters:  27%|██▋       | 54/200 [01:36<04:22,  1.79s/it]
  iters:  28%|██▊       | 55/200 [01:37<04:18,  1.78s/it]
  iters:  28%|██▊       | 56/200 [01:39<04:14,  1.77s/it]
  iters:  28%|██▊       | 57/200 [01:41<04:21,  1.83s/it]
  iters:  29%|██▉       | 58/200 [01:43<04:14,  1.79s/it]
  iters:  30%|██▉       | 59/200 [01:45<04:11,  1.78s/it]
  iters:  30%|███       | 60/200 [01:46<04:07,  1.76s/it]
  iters:  30%|███       | 61/200 [01:48<04:06,  1.77s/it]
  iters:  31%|███       | 62/200 [01:50<04:02,  1.76s/it]
  iters:  32%|███▏      | 63/200 [01:52<04:00,  1.76s/it]
  iters:  32%|███▏      | 64/200 [01:53<03:57,  1.75s/it]
  iters:  32%|███▎      | 65/200 [01:55<04:00,  1.78s/it]
  iters:  33%|███▎      | 66/200 [01:57<03:59,  1.79s/it]
  iters:  34%|███▎      | 67/200 [01:59<03:55,  1.77s/it]
  iters:  34%|███▍      | 68/200 [02:01<04:03,  1.84s/it]
  iters:  34%|███▍      | 69/200 [02:03<04:04,  1.87s/it]
  iters:  35%|███▌      | 70/200 [02:04<03:57,  1.83s/it]
  iters:  36%|███▌      | 71/200 [02:06<03:53,  1.81s/it]
  iters:  36%|███▌      | 72/200 [02:08<03:48,  1.78s/it]
  iters:  36%|███▋      | 73/200 [02:10<03:45,  1.77s/it]
  iters:  37%|███▋      | 74/200 [02:11<03:42,  1.77s/it]
  iters:  38%|███▊      | 75/200 [02:13<03:40,  1.76s/it]
  iters:  38%|███▊      | 76/200 [02:15<03:37,  1.75s/it]
  iters:  38%|███▊      | 77/200 [02:17<03:34,  1.75s/it]
  iters:  39%|███▉      | 78/200 [02:18<03:33,  1.75s/it]
  iters:  40%|███▉      | 79/200 [02:20<03:31,  1.75s/it]
  iters:  40%|████      | 80/200 [02:22<03:32,  1.77s/it]
  iters:  40%|████      | 81/200 [02:24<03:29,  1.76s/it]
  iters:  41%|████      | 82/200 [02:25<03:27,  1.76s/it]
  iters:  42%|████▏     | 83/200 [02:27<03:29,  1.79s/it]
  iters:  42%|████▏     | 84/200 [02:29<03:25,  1.77s/it]
  iters:  42%|████▎     | 85/200 [02:31<03:25,  1.79s/it]
  iters:  43%|████▎     | 86/200 [02:33<03:21,  1.77s/it]
  iters:  44%|████▎     | 87/200 [02:34<03:25,  1.82s/it]
  iters:  44%|████▍     | 88/200 [02:36<03:20,  1.79s/it]
  iters:  44%|████▍     | 89/200 [02:38<03:18,  1.79s/it]
  iters:  45%|████▌     | 90/200 [02:40<03:22,  1.84s/it]
  iters:  46%|████▌     | 91/200 [02:42<03:17,  1.81s/it]
  iters:  46%|████▌     | 92/200 [02:43<03:13,  1.79s/it]
  iters:  46%|████▋     | 93/200 [02:45<03:09,  1.78s/it]
  iters:  47%|████▋     | 94/200 [02:47<03:13,  1.83s/it]
  iters:  48%|████▊     | 95/200 [02:49<03:08,  1.80s/it]
  iters:  48%|████▊     | 96/200 [02:51<03:04,  1.78s/it]
  iters:  48%|████▊     | 97/200 [02:52<03:03,  1.78s/it]
  iters:  49%|████▉     | 98/200 [02:54<03:00,  1.76s/it]
  iters:  50%|████▉     | 99/200 [02:56<02:56,  1.75s/it]
  iters:  50%|█████     | 100/200 [02:58<02:54,  1.75s/it]
  iters:  50%|█████     | 101/200 [02:59<02:54,  1.76s/it]
  iters:  51%|█████     | 102/200 [03:01<02:51,  1.75s/it]
  iters:  52%|█████▏    | 103/200 [03:03<02:49,  1.75s/it]
  iters:  52%|█████▏    | 104/200 [03:05<02:48,  1.76s/it]
  iters:  52%|█████▎    | 105/200 [03:06<02:45,  1.75s/it]
  iters:  53%|█████▎    | 106/200 [03:08<02:43,  1.74s/it]
  iters:  54%|█████▎    | 107/200 [03:10<02:41,  1.74s/it]
  iters:  54%|█████▍    | 108/200 [03:11<02:39,  1.73s/it]
  iters:  55%|█████▍    | 109/200 [03:13<02:43,  1.79s/it]
  iters:  55%|█████▌    | 110/200 [03:15<02:43,  1.81s/it]
  iters:  56%|█████▌    | 111/200 [03:17<02:39,  1.79s/it]
  iters:  56%|█████▌    | 112/200 [03:19<02:36,  1.78s/it]
  iters:  56%|█████▋    | 113/200 [03:20<02:33,  1.76s/it]
  iters:  57%|█████▋    | 114/200 [03:22<02:33,  1.78s/it]
  iters:  57%|█████▊    | 115/200 [03:24<02:30,  1.77s/it]
  iters:  58%|█████▊    | 116/200 [03:26<02:27,  1.76s/it]
  iters:  58%|█████▊    | 117/200 [03:28<02:31,  1.83s/it]
  iters:  59%|█████▉    | 118/200 [03:30<02:27,  1.80s/it]
  iters:  60%|█████▉    | 119/200 [03:31<02:24,  1.78s/it]
  iters:  60%|██████    | 120/200 [03:33<02:21,  1.77s/it]
  iters:  60%|██████    | 121/200 [03:35<02:19,  1.76s/it]
  iters:  61%|██████    | 122/200 [03:37<02:19,  1.79s/it]
  iters:  62%|██████▏   | 123/200 [03:39<02:22,  1.85s/it]
  iters:  62%|██████▏   | 124/200 [03:40<02:17,  1.81s/it]
  iters:  62%|██████▎   | 125/200 [03:42<02:14,  1.79s/it]
  iters:  63%|██████▎   | 126/200 [03:44<02:11,  1.78s/it]
  iters:  64%|██████▎   | 127/200 [03:46<02:10,  1.79s/it]
  iters:  64%|██████▍   | 128/200 [03:48<02:13,  1.85s/it]
  iters:  64%|██████▍   | 129/200 [03:49<02:08,  1.81s/it]
  iters:  65%|██████▌   | 130/200 [03:51<02:05,  1.79s/it]
  iters:  66%|██████▌   | 131/200 [03:53<02:02,  1.78s/it]
  iters:  66%|██████▌   | 132/200 [03:55<02:00,  1.77s/it]
  iters:  66%|██████▋   | 133/200 [03:56<01:58,  1.76s/it]
  iters:  67%|██████▋   | 134/200 [03:58<01:56,  1.77s/it]
  iters:  68%|██████▊   | 135/200 [04:00<01:54,  1.75s/it]
  iters:  68%|██████▊   | 136/200 [04:02<01:51,  1.75s/it]
  iters:  68%|██████▊   | 137/200 [04:03<01:49,  1.75s/it]
  iters:  69%|██████▉   | 138/200 [04:05<01:48,  1.75s/it]
  iters:  70%|██████▉   | 139/200 [04:07<01:46,  1.75s/it]
  iters:  70%|███████   | 140/200 [04:09<01:44,  1.74s/it]
  iters:  70%|███████   | 141/200 [04:10<01:42,  1.74s/it]
  iters:  71%|███████   | 142/200 [04:12<01:40,  1.74s/it]
  iters:  72%|███████▏  | 143/200 [04:14<01:39,  1.74s/it]
  iters:  72%|███████▏  | 144/200 [04:15<01:37,  1.74s/it]
  iters:  72%|███████▎  | 145/200 [04:17<01:35,  1.74s/it]
  iters:  73%|███████▎  | 146/200 [04:19<01:33,  1.74s/it]
  iters:  74%|███████▎  | 147/200 [04:21<01:32,  1.74s/it]
  iters:  74%|███████▍  | 148/200 [04:23<01:34,  1.82s/it]
  iters:  74%|███████▍  | 149/200 [04:24<01:31,  1.79s/it]
  iters:  75%|███████▌  | 150/200 [04:26<01:28,  1.78s/it]
  iters:  76%|███████▌  | 151/200 [04:28<01:26,  1.76s/it]
  iters:  76%|███████▌  | 152/200 [04:30<01:23,  1.75s/it]
  iters:  76%|███████▋  | 153/200 [04:31<01:22,  1.76s/it]
  iters:  77%|███████▋  | 154/200 [04:33<01:23,  1.82s/it]
  iters:  78%|███████▊  | 155/200 [04:35<01:20,  1.79s/it]
  iters:  78%|███████▊  | 156/200 [04:37<01:17,  1.77s/it]
  iters:  78%|███████▊  | 157/200 [04:39<01:15,  1.76s/it]
  iters:  79%|███████▉  | 158/200 [04:40<01:13,  1.76s/it]
  iters:  80%|███████▉  | 159/200 [04:42<01:11,  1.75s/it]
  iters:  80%|████████  | 160/200 [04:44<01:09,  1.74s/it]
  iters:  80%|████████  | 161/200 [04:45<01:07,  1.73s/it]
  iters:  81%|████████  | 162/200 [04:47<01:07,  1.77s/it]
  iters:  82%|████████▏ | 163/200 [04:49<01:05,  1.76s/it]
  iters:  82%|████████▏ | 164/200 [04:51<01:03,  1.75s/it]
  iters:  82%|████████▎ | 165/200 [04:53<01:01,  1.74s/it]
  iters:  83%|████████▎ | 166/200 [04:54<00:59,  1.74s/it]
  iters:  84%|████████▎ | 167/200 [04:56<00:57,  1.74s/it]
  iters:  84%|████████▍ | 168/200 [04:58<00:55,  1.73s/it]
  iters:  84%|████████▍ | 169/200 [04:59<00:53,  1.73s/it]
  iters:  85%|████████▌ | 170/200 [05:01<00:51,  1.73s/it]
  iters:  86%|████████▌ | 171/200 [05:03<00:50,  1.73s/it]
  iters:  86%|████████▌ | 172/200 [05:05<00:48,  1.73s/it]
  iters:  86%|████████▋ | 173/200 [05:06<00:46,  1.74s/it]
  iters:  87%|████████▋ | 174/200 [05:08<00:45,  1.74s/it]
  iters:  88%|████████▊ | 175/200 [05:10<00:43,  1.76s/it]
  iters:  88%|████████▊ | 176/200 [05:12<00:41,  1.75s/it]
  iters:  88%|████████▊ | 177/200 [05:13<00:40,  1.74s/it]
  iters:  89%|████████▉ | 178/200 [05:15<00:38,  1.74s/it]
  iters:  90%|████████▉ | 179/200 [05:17<00:37,  1.78s/it]
  iters:  90%|█████████ | 180/200 [05:19<00:35,  1.76s/it]
  iters:  90%|█████████ | 181/200 [05:20<00:33,  1.75s/it]
  iters:  91%|█████████ | 182/200 [05:22<00:32,  1.78s/it]
  iters:  92%|█████████▏| 183/200 [05:24<00:30,  1.77s/it]
  iters:  92%|█████████▏| 184/200 [05:26<00:28,  1.76s/it]
  iters:  92%|█████████▎| 185/200 [05:27<00:26,  1.75s/it]
  iters:  93%|█████████▎| 186/200 [05:29<00:24,  1.75s/it]
  iters:  94%|█████████▎| 187/200 [05:31<00:22,  1.75s/it]
  iters:  94%|█████████▍| 188/200 [05:33<00:20,  1.74s/it]
  iters:  94%|█████████▍| 189/200 [05:34<00:19,  1.74s/it]
  iters:  95%|█████████▌| 190/200 [05:36<00:17,  1.73s/it]
  iters:  96%|█████████▌| 191/200 [05:38<00:15,  1.74s/it]
  iters:  96%|█████████▌| 192/200 [05:40<00:13,  1.74s/it]
  iters:  96%|█████████▋| 193/200 [05:41<00:12,  1.74s/it]
  iters:  97%|█████████▋| 194/200 [05:43<00:10,  1.74s/it]
  iters:  98%|█████████▊| 195/200 [05:45<00:08,  1.73s/it]
  iters:  98%|█████████▊| 196/200 [05:47<00:06,  1.74s/it]
  iters:  98%|█████████▊| 197/200 [05:48<00:05,  1.73s/it]
  iters:  99%|█████████▉| 198/200 [05:50<00:03,  1.73s/it]
  iters: 100%|█████████▉| 199/200 [05:52<00:01,  1.73s/it]
  iters: 100%|██████████| 200/200 [05:53<00:00,  1.73s/it]

  [timing] data: 2.3s (1%) | forward: 86.3s (24%) | backward: 265.4s (75%) | total: 354.0s

Training:  50%|█████     | 2/4 [19:19<12:54, 387.11s/it, acc=0.9994, det=0.0065, edge=0.0005]

  Epoch   2/4 | edge=0.0005 | det=0.0065 | test_loss=0.0008 | acc=0.9994 | recall=0.8941 | best=0.8936 * | train=354.2s test=31.1s

Training:  75%|███████▌  | 3/4 [19:19<06:26, 386.27s/it, acc=0.9994, det=0.0065, edge=0.0005]
  iters:   0%|          | 0/200 [00:00<?, ?it/s]
  iters:   0%|          | 1/200 [00:01<06:33,  1.98s/it]
  iters:   1%|          | 2/200 [00:03<06:26,  1.95s/it]
  iters:   2%|▏         | 3/200 [00:05<06:19,  1.92s/it]
  iters:   2%|▏         | 4/200 [00:07<06:02,  1.85s/it]
  iters:   2%|▎         | 5/200 [00:09<05:53,  1.81s/it]
  iters:   3%|▎         | 6/200 [00:11<05:45,  1.78s/it]
  iters:   4%|▎         | 7/200 [00:12<05:40,  1.76s/it]
  iters:   4%|▍         | 8/200 [00:14<05:37,  1.76s/it]
  iters:   4%|▍         | 9/200 [00:16<05:34,  1.75s/it]
  iters:   5%|▌         | 10/200 [00:17<05:31,  1.74s/it]
  iters:   6%|▌         | 11/200 [00:19<05:29,  1.74s/it]
  iters:   6%|▌         | 12/200 [00:21<05:30,  1.76s/it]
  iters:   6%|▋         | 13/200 [00:23<05:38,  1.81s/it]
  iters:   7%|▋         | 14/200 [00:25<05:32,  1.79s/it]
  iters:   8%|▊         | 15/200 [00:26<05:27,  1.77s/it]
  iters:   8%|▊         | 16/200 [00:28<05:24,  1.76s/it]
  iters:   8%|▊         | 17/200 [00:30<05:20,  1.75s/it]
  iters:   9%|▉         | 18/200 [00:32<05:21,  1.77s/it]
  iters:  10%|▉         | 19/200 [00:34<05:32,  1.84s/it]
  iters:  10%|█         | 20/200 [00:35<05:25,  1.81s/it]
  iters:  10%|█         | 21/200 [00:37<05:19,  1.78s/it]
  iters:  11%|█         | 22/200 [00:39<05:14,  1.77s/it]
  iters:  12%|█▏        | 23/200 [00:41<05:10,  1.76s/it]
  iters:  12%|█▏        | 24/200 [00:42<05:14,  1.79s/it]
  iters:  12%|█▎        | 25/200 [00:44<05:10,  1.78s/it]
  iters:  13%|█▎        | 26/200 [00:46<05:19,  1.84s/it]
  iters:  14%|█▎        | 27/200 [00:48<05:19,  1.85s/it]
  iters:  14%|█▍        | 28/200 [00:50<05:13,  1.82s/it]
  iters:  14%|█▍        | 29/200 [00:52<05:07,  1.80s/it]
  iters:  15%|█▌        | 30/200 [00:53<05:09,  1.82s/it]
  iters:  16%|█▌        | 31/200 [00:55<05:04,  1.80s/it]
  iters:  16%|█▌        | 32/200 [00:57<04:59,  1.78s/it]
  iters:  16%|█▋        | 33/200 [00:59<05:07,  1.84s/it]
  iters:  17%|█▋        | 34/200 [01:01<05:01,  1.81s/it]
  iters:  18%|█▊        | 35/200 [01:02<04:55,  1.79s/it]
  iters:  18%|█▊        | 36/200 [01:04<04:54,  1.79s/it]
  iters:  18%|█▊        | 37/200 [01:06<04:49,  1.78s/it]
  iters:  19%|█▉        | 38/200 [01:08<04:45,  1.76s/it]
  iters:  20%|█▉        | 39/200 [01:09<04:43,  1.76s/it]
  iters:  20%|██        | 40/200 [01:11<04:41,  1.76s/it]
  iters:  20%|██        | 41/200 [01:13<04:38,  1.75s/it]
  iters:  21%|██        | 42/200 [01:15<04:35,  1.74s/it]
  iters:  22%|██▏       | 43/200 [01:16<04:39,  1.78s/it]
  iters:  22%|██▏       | 44/200 [01:18<04:36,  1.77s/it]
  iters:  22%|██▎       | 45/200 [01:20<04:33,  1.76s/it]
  iters:  23%|██▎       | 46/200 [01:22<04:31,  1.76s/it]
  iters:  24%|██▎       | 47/200 [01:24<04:32,  1.78s/it]
  iters:  24%|██▍       | 48/200 [01:25<04:28,  1.77s/it]
  iters:  24%|██▍       | 49/200 [01:27<04:26,  1.76s/it]
  iters:  25%|██▌       | 50/200 [01:29<04:22,  1.75s/it]
  iters:  26%|██▌       | 51/200 [01:31<04:20,  1.75s/it]
  iters:  26%|██▌       | 52/200 [01:32<04:17,  1.74s/it]
  iters:  26%|██▋       | 53/200 [01:34<04:15,  1.74s/it]
  iters:  27%|██▋       | 54/200 [01:36<04:14,  1.74s/it]
  iters:  28%|██▊       | 55/200 [01:37<04:12,  1.74s/it]
  iters:  28%|██▊       | 56/200 [01:39<04:11,  1.74s/it]
  iters:  28%|██▊       | 57/200 [01:41<04:08,  1.74s/it]
  iters:  29%|██▉       | 58/200 [01:43<04:07,  1.74s/it]
  iters:  30%|██▉       | 59/200 [01:44<04:05,  1.74s/it]
  iters:  30%|███       | 60/200 [01:46<04:03,  1.74s/it]
  iters:  30%|███       | 61/200 [01:48<04:04,  1.76s/it]
  iters:  31%|███       | 62/200 [01:50<04:01,  1.75s/it]
  iters:  32%|███▏      | 63/200 [01:51<03:58,  1.74s/it]
  iters:  32%|███▏      | 64/200 [01:53<03:56,  1.74s/it]
  iters:  32%|███▎      | 65/200 [01:55<03:57,  1.76s/it]
  iters:  33%|███▎      | 66/200 [01:57<03:55,  1.76s/it]
  iters:  34%|███▎      | 67/200 [01:58<03:54,  1.76s/it]
  iters:  34%|███▍      | 68/200 [02:00<03:51,  1.75s/it]
  iters:  34%|███▍      | 69/200 [02:02<03:48,  1.75s/it]
  iters:  35%|███▌      | 70/200 [02:04<03:46,  1.74s/it]
  iters:  36%|███▌      | 71/200 [02:05<03:44,  1.74s/it]
  iters:  36%|███▌      | 72/200 [02:07<03:43,  1.75s/it]
  iters:  36%|███▋      | 73/200 [02:09<03:50,  1.82s/it]
  iters:  37%|███▋      | 74/200 [02:11<03:46,  1.79s/it]
  iters:  38%|███▊      | 75/200 [02:13<03:47,  1.82s/it]
  iters:  38%|███▊      | 76/200 [02:15<03:42,  1.79s/it]
  iters:  38%|███▊      | 77/200 [02:16<03:38,  1.78s/it]
  iters:  39%|███▉      | 78/200 [02:18<03:35,  1.76s/it]
  iters:  40%|███▉      | 79/200 [02:20<03:32,  1.75s/it]
  iters:  40%|████      | 80/200 [02:21<03:30,  1.75s/it]
  iters:  40%|████      | 81/200 [02:23<03:28,  1.75s/it]
  iters:  41%|████      | 82/200 [02:25<03:34,  1.82s/it]
  iters:  42%|████▏     | 83/200 [02:27<03:30,  1.80s/it]
  iters:  42%|████▏     | 84/200 [02:29<03:26,  1.78s/it]
  iters:  42%|████▎     | 85/200 [02:30<03:24,  1.78s/it]
  iters:  43%|████▎     | 86/200 [02:32<03:21,  1.77s/it]
  iters:  44%|████▎     | 87/200 [02:34<03:23,  1.80s/it]
  iters:  44%|████▍     | 88/200 [02:36<03:19,  1.78s/it]
  iters:  44%|████▍     | 89/200 [02:38<03:16,  1.77s/it]
  iters:  45%|████▌     | 90/200 [02:39<03:17,  1.80s/it]
  iters:  46%|████▌     | 91/200 [02:41<03:14,  1.78s/it]
  iters:  46%|████▌     | 92/200 [02:43<03:11,  1.77s/it]
  iters:  46%|████▋     | 93/200 [02:45<03:08,  1.76s/it]
  iters:  47%|████▋     | 94/200 [02:46<03:06,  1.76s/it]
  iters:  48%|████▊     | 95/200 [02:48<03:04,  1.75s/it]
  iters:  48%|████▊     | 96/200 [02:50<03:01,  1.75s/it]
  iters:  48%|████▊     | 97/200 [02:52<03:02,  1.77s/it]
  iters:  49%|████▉     | 98/200 [02:53<02:59,  1.76s/it]
  iters:  50%|████▉     | 99/200 [02:55<03:00,  1.79s/it]
  iters:  50%|█████     | 100/200 [02:57<02:57,  1.78s/it]
  iters:  50%|█████     | 101/200 [02:59<02:55,  1.77s/it]
  iters:  51%|█████     | 102/200 [03:01<02:54,  1.78s/it]
  iters:  52%|█████▏    | 103/200 [03:02<02:51,  1.77s/it]
  iters:  52%|█████▏    | 104/200 [03:04<02:48,  1.76s/it]
  iters:  52%|█████▎    | 105/200 [03:06<02:46,  1.75s/it]
  iters:  53%|█████▎    | 106/200 [03:08<02:44,  1.75s/it]
  iters:  54%|█████▎    | 107/200 [03:09<02:42,  1.75s/it]
  iters:  54%|█████▍    | 108/200 [03:11<02:40,  1.75s/it]
  iters:  55%|█████▍    | 109/200 [03:13<02:38,  1.74s/it]
  iters:  55%|█████▌    | 110/200 [03:15<02:36,  1.74s/it]
  iters:  56%|█████▌    | 111/200 [03:16<02:34,  1.74s/it]
  iters:  56%|█████▌    | 112/200 [03:18<02:32,  1.73s/it]
  iters:  56%|█████▋    | 113/200 [03:20<02:31,  1.75s/it]
  iters:  57%|█████▋    | 114/200 [03:22<02:31,  1.76s/it]
  iters:  57%|█████▊    | 115/200 [03:23<02:29,  1.76s/it]
  iters:  58%|█████▊    | 116/200 [03:25<02:27,  1.75s/it]
  iters:  58%|█████▊    | 117/200 [03:27<02:30,  1.82s/it]
  iters:  59%|█████▉    | 118/200 [03:29<02:29,  1.82s/it]
  iters:  60%|█████▉    | 119/200 [03:31<02:24,  1.79s/it]
  iters:  60%|██████    | 120/200 [03:32<02:21,  1.77s/it]
  iters:  60%|██████    | 121/200 [03:34<02:18,  1.76s/it]
  iters:  61%|██████    | 122/200 [03:36<02:18,  1.78s/it]
  iters:  62%|██████▏   | 123/200 [03:38<02:15,  1.76s/it]
  iters:  62%|██████▏   | 124/200 [03:39<02:14,  1.77s/it]
  iters:  62%|██████▎   | 125/200 [03:41<02:16,  1.81s/it]
  iters:  63%|██████▎   | 126/200 [03:43<02:12,  1.79s/it]
  iters:  64%|██████▎   | 127/200 [03:45<02:10,  1.78s/it]
  iters:  64%|██████▍   | 128/200 [03:46<02:06,  1.76s/it]
  iters:  64%|██████▍   | 129/200 [03:48<02:04,  1.75s/it]
  iters:  65%|██████▌   | 130/200 [03:50<02:02,  1.75s/it]
  iters:  66%|██████▌   | 131/200 [03:52<02:02,  1.78s/it]
  iters:  66%|██████▌   | 132/200 [03:54<01:59,  1.76s/it]
  iters:  66%|██████▋   | 133/200 [03:55<01:57,  1.75s/it]
  iters:  67%|██████▋   | 134/200 [03:57<01:55,  1.75s/it]
  iters:  68%|██████▊   | 135/200 [03:59<01:54,  1.76s/it]
  iters:  68%|██████▊   | 136/200 [04:00<01:52,  1.75s/it]
  iters:  68%|██████▊   | 137/200 [04:02<01:50,  1.75s/it]
  iters:  69%|██████▉   | 138/200 [04:04<01:48,  1.75s/it]
  iters:  70%|██████▉   | 139/200 [04:06<01:46,  1.75s/it]
  iters:  70%|███████   | 140/200 [04:07<01:44,  1.75s/it]
  iters:  70%|███████   | 141/200 [04:09<01:44,  1.76s/it]
  iters:  71%|███████   | 142/200 [04:11<01:41,  1.75s/it]
  iters:  72%|███████▏  | 143/200 [04:13<01:39,  1.75s/it]
  iters:  72%|███████▏  | 144/200 [04:15<01:44,  1.87s/it]
  iters:  72%|███████▎  | 145/200 [04:17<01:41,  1.85s/it]
  iters:  73%|███████▎  | 146/200 [04:18<01:38,  1.82s/it]
  iters:  74%|███████▎  | 147/200 [04:20<01:34,  1.79s/it]
  iters:  74%|███████▍  | 148/200 [04:22<01:32,  1.78s/it]
  iters:  74%|███████▍  | 149/200 [04:24<01:30,  1.77s/it]
  iters:  75%|███████▌  | 150/200 [04:25<01:27,  1.75s/it]
  iters:  76%|███████▌  | 151/200 [04:27<01:26,  1.77s/it]
  iters:  76%|███████▌  | 152/200 [04:29<01:24,  1.76s/it]
  iters:  76%|███████▋  | 153/200 [04:31<01:22,  1.75s/it]
  iters:  77%|███████▋  | 154/200 [04:32<01:20,  1.75s/it]
  iters:  78%|███████▊  | 155/200 [04:34<01:18,  1.75s/it]
  iters:  78%|███████▊  | 156/200 [04:36<01:16,  1.75s/it]
  iters:  78%|███████▊  | 157/200 [04:38<01:15,  1.75s/it]
  iters:  79%|███████▉  | 158/200 [04:39<01:14,  1.77s/it]
  iters:  80%|███████▉  | 159/200 [04:41<01:12,  1.76s/it]
  iters:  80%|████████  | 160/200 [04:43<01:09,  1.75s/it]
  iters:  80%|████████  | 161/200 [04:45<01:08,  1.74s/it]
  iters:  81%|████████  | 162/200 [04:46<01:06,  1.74s/it]
  iters:  82%|████████▏ | 163/200 [04:48<01:04,  1.74s/it]
  iters:  82%|████████▏ | 164/200 [04:50<01:02,  1.74s/it]
  iters:  82%|████████▎ | 165/200 [04:52<01:00,  1.74s/it]
  iters:  83%|████████▎ | 166/200 [04:53<00:59,  1.74s/it]
  iters:  84%|████████▎ | 167/200 [04:55<00:58,  1.77s/it]
  iters:  84%|████████▍ | 168/200 [04:57<00:56,  1.76s/it]
  iters:  84%|████████▍ | 169/200 [04:59<00:56,  1.82s/it]
  iters:  85%|████████▌ | 170/200 [05:01<00:55,  1.85s/it]
  iters:  86%|████████▌ | 171/200 [05:03<00:52,  1.82s/it]
  iters:  86%|████████▌ | 172/200 [05:04<00:50,  1.79s/it]
  iters:  86%|████████▋ | 173/200 [05:06<00:47,  1.77s/it]
  iters:  87%|████████▋ | 174/200 [05:08<00:46,  1.79s/it]
  iters:  88%|████████▊ | 175/200 [05:10<00:46,  1.84s/it]
  iters:  88%|████████▊ | 176/200 [05:12<00:45,  1.88s/it]
  iters:  88%|████████▊ | 177/200 [05:14<00:42,  1.84s/it]
  iters:  89%|████████▉ | 178/200 [05:15<00:39,  1.82s/it]
  iters:  90%|████████▉ | 179/200 [05:17<00:38,  1.86s/it]
  iters:  90%|█████████ | 180/200 [05:19<00:36,  1.82s/it]
  iters:  90%|█████████ | 181/200 [05:21<00:33,  1.79s/it]
  iters:  91%|█████████ | 182/200 [05:22<00:32,  1.79s/it]
  iters:  92%|█████████▏| 183/200 [05:24<00:30,  1.78s/it]
  iters:  92%|█████████▏| 184/200 [05:26<00:28,  1.76s/it]
  iters:  92%|█████████▎| 185/200 [05:28<00:26,  1.76s/it]
  iters:  93%|█████████▎| 186/200 [05:29<00:24,  1.76s/it]
  iters:  94%|█████████▎| 187/200 [05:31<00:22,  1.75s/it]
  iters:  94%|█████████▍| 188/200 [05:33<00:21,  1.82s/it]
  iters:  94%|█████████▍| 189/200 [05:35<00:19,  1.79s/it]
  iters:  95%|█████████▌| 190/200 [05:37<00:17,  1.77s/it]
  iters:  96%|█████████▌| 191/200 [05:38<00:15,  1.76s/it]
  iters:  96%|█████████▌| 192/200 [05:40<00:13,  1.75s/it]
  iters:  96%|█████████▋| 193/200 [05:42<00:12,  1.75s/it]
  iters:  97%|█████████▋| 194/200 [05:44<00:10,  1.81s/it]
  iters:  98%|█████████▊| 195/200 [05:46<00:09,  1.85s/it]
  iters:  98%|█████████▊| 196/200 [05:47<00:07,  1.81s/it]
  iters:  98%|█████████▊| 197/200 [05:49<00:05,  1.78s/it]
  iters:  99%|█████████▉| 198/200 [05:51<00:03,  1.80s/it]
  iters: 100%|█████████▉| 199/200 [05:53<00:01,  1.84s/it]
  iters: 100%|██████████| 200/200 [05:55<00:00,  1.81s/it]

  [timing] data: 2.3s (1%) | forward: 86.9s (24%) | backward: 265.9s (75%) | total: 355.1s

Training:  75%|███████▌  | 3/4 [25:45<06:26, 386.27s/it, acc=0.9994, det=0.0065, edge=0.0005]

  Epoch   3/4 | edge=0.0005 | det=0.0065 | test_loss=0.0013 | acc=0.9994 | recall=0.8647 | best=0.8936   | train=355.4s test=31.0s

Training: 100%|██████████| 4/4 [25:45<00:00, 386.47s/it, acc=0.9994, det=0.0065, edge=0.0005]

Best score (acc*recall): 0.8936, saved to /kaggle/working/cellmot-baseline-artifacts/repo/weights/hp_search_tier1/split_0/edge_predictor_best.pth

[tier2_005] score=0.8936  (1553s)
0.019136512 GB allocated
0.312475648 GB reserved
Fold 0: 8 train, 2 test
Loading train (8 datasets)...

train: 100%|██████████| 8/8 [00:05<00:00,  1.59it/s]

  train done: 779 windows total
Loading test (2 datasets)...

test: 100%|██████████| 2/2 [00:00<00:00,  2.13it/s]

  test done: 161 windows total
max_nodes=17
Using device: cuda | visible CUDA GPUs: 2
  Full checkpoint loaded from /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/weights/unet_transformer/split_0/edge_predictor_best.pth: 0 missing, 0 unexpected
Single-GPU training (--single-gpu set). For 2 GPUs set the Kaggle accelerator to 'GPU T4 x2'.
Model parameters: 2,076,706
Starting training for 4 epochs (batch_size=2)...

Training:   0%|          | 0/4 [00:00<?, ?it/s]

Detection loss: weight=4, neg_weight=0.01

  iters:   0%|          | 0/200 [00:00<?, ?it/s]
  iters:   0%|          | 1/200 [00:02<07:00,  2.11s/it]
  iters:   1%|          | 2/200 [00:03<06:10,  1.87s/it]
  iters:   2%|▏         | 3/200 [00:05<05:53,  1.79s/it]
  iters:   2%|▏         | 4/200 [00:07<05:45,  1.76s/it]
  iters:   2%|▎         | 5/200 [00:08<05:41,  1.75s/it]
  iters:   3%|▎         | 6/200 [00:10<05:36,  1.74s/it]
  iters:   4%|▎         | 7/200 [00:12<05:34,  1.73s/it]
  iters:   4%|▍         | 8/200 [00:14<05:32,  1.73s/it]
  iters:   4%|▍         | 9/200 [00:15<05:31,  1.74s/it]
  iters:   5%|▌         | 10/200 [00:17<05:30,  1.74s/it]
  iters:   6%|▌         | 11/200 [00:19<05:30,  1.75s/it]
  iters:   6%|▌         | 12/200 [00:21<05:29,  1.75s/it]
  iters:   6%|▋         | 13/200 [00:22<05:27,  1.75s/it]
  iters:   7%|▋         | 14/200 [00:24<05:26,  1.76s/it]
  iters:   8%|▊         | 15/200 [00:26<05:26,  1.76s/it]
  iters:   8%|▊         | 16/200 [00:28<05:25,  1.77s/it]
  iters:   8%|▊         | 17/200 [00:29<05:23,  1.77s/it]
  iters:   9%|▉         | 18/200 [00:31<05:21,  1.77s/it]
  iters:  10%|▉         | 19/200 [00:33<05:19,  1.77s/it]
  iters:  10%|█         | 20/200 [00:35<05:17,  1.76s/it]
  iters:  10%|█         | 21/200 [00:37<05:16,  1.77s/it]
  iters:  11%|█         | 22/200 [00:38<05:13,  1.76s/it]
  iters:  12%|█▏        | 23/200 [00:40<05:11,  1.76s/it]
  iters:  12%|█▏        | 24/200 [00:42<05:09,  1.76s/it]
  iters:  12%|█▎        | 25/200 [00:44<05:06,  1.75s/it]
  iters:  13%|█▎        | 26/200 [00:45<05:04,  1.75s/it]
  iters:  14%|█▎        | 27/200 [00:47<05:02,  1.75s/it]
  iters:  14%|█▍        | 28/200 [00:49<05:00,  1.74s/it]
  iters:  14%|█▍        | 29/200 [00:51<04:57,  1.74s/it]
  iters:  15%|█▌        | 30/200 [00:52<04:54,  1.73s/it]
  iters:  16%|█▌        | 31/200 [00:54<04:53,  1.73s/it]
  iters:  16%|█▌        | 32/200 [00:56<04:51,  1.73s/it]
  iters:  16%|█▋        | 33/200 [00:57<04:48,  1.73s/it]
  iters:  17%|█▋        | 34/200 [00:59<04:47,  1.73s/it]
  iters:  18%|█▊        | 35/200 [01:01<04:45,  1.73s/it]
  iters:  18%|█▊        | 36/200 [01:03<04:43,  1.73s/it]
  iters:  18%|█▊        | 37/200 [01:04<04:40,  1.72s/it]
  iters:  19%|█▉        | 38/200 [01:06<04:39,  1.72s/it]
  iters:  20%|█▉        | 39/200 [01:08<04:37,  1.72s/it]
  iters:  20%|██        | 40/200 [01:09<04:34,  1.72s/it]
  iters:  20%|██        | 41/200 [01:11<04:32,  1.71s/it]
  iters:  21%|██        | 42/200 [01:13<04:30,  1.72s/it]
  iters:  22%|██▏       | 43/200 [01:15<04:28,  1.71s/it]
  iters:  22%|██▏       | 44/200 [01:16<04:26,  1.71s/it]
  iters:  22%|██▎       | 45/200 [01:18<04:25,  1.71s/it]
  iters:  23%|██▎       | 46/200 [01:20<04:24,  1.72s/it]
  iters:  24%|██▎       | 47/200 [01:21<04:22,  1.71s/it]
  iters:  24%|██▍       | 48/200 [01:23<04:20,  1.71s/it]
  iters:  24%|██▍       | 49/200 [01:25<04:19,  1.72s/it]
  iters:  25%|██▌       | 50/200 [01:27<04:17,  1.71s/it]
  iters:  26%|██▌       | 51/200 [01:28<04:15,  1.72s/it]
  iters:  26%|██▌       | 52/200 [01:30<04:14,  1.72s/it]
  iters:  26%|██▋       | 53/200 [01:32<04:12,  1.72s/it]
  iters:  27%|██▋       | 54/200 [01:33<04:10,  1.72s/it]
  iters:  28%|██▊       | 55/200 [01:35<04:09,  1.72s/it]
  iters:  28%|██▊       | 56/200 [01:37<04:08,  1.72s/it]
  iters:  28%|██▊       | 57/200 [01:39<04:06,  1.73s/it]
  iters:  29%|██▉       | 58/200 [01:40<04:05,  1.73s/it]
  iters:  30%|██▉       | 59/200 [01:42<04:03,  1.73s/it]
  iters:  30%|███       | 60/200 [01:44<04:01,  1.73s/it]
  iters:  30%|███       | 61/200 [01:46<03:59,  1.73s/it]
  iters:  31%|███       | 62/200 [01:47<03:58,  1.73s/it]
  iters:  32%|███▏      | 63/200 [01:49<03:56,  1.73s/it]
  iters:  32%|███▏      | 64/200 [01:51<03:55,  1.73s/it]
  iters:  32%|███▎      | 65/200 [01:52<03:53,  1.73s/it]
  iters:  33%|███▎      | 66/200 [01:54<03:52,  1.73s/it]
  iters:  34%|███▎      | 67/200 [01:56<03:50,  1.73s/it]
  iters:  34%|███▍      | 68/200 [01:58<03:57,  1.80s/it]
  iters:  34%|███▍      | 69/200 [02:00<03:53,  1.78s/it]
  iters:  35%|███▌      | 70/200 [02:01<03:49,  1.76s/it]
  iters:  36%|███▌      | 71/200 [02:03<03:46,  1.76s/it]
  iters:  36%|███▌      | 72/200 [02:05<03:44,  1.75s/it]
  iters:  36%|███▋      | 73/200 [02:07<03:41,  1.75s/it]
  iters:  37%|███▋      | 74/200 [02:08<03:39,  1.74s/it]
  iters:  38%|███▊      | 75/200 [02:10<03:37,  1.74s/it]
  iters:  38%|███▊      | 76/200 [02:12<03:35,  1.74s/it]
  iters:  38%|███▊      | 77/200 [02:14<03:33,  1.74s/it]
  iters:  39%|███▉      | 78/200 [02:15<03:31,  1.74s/it]
  iters:  40%|███▉      | 79/200 [02:17<03:30,  1.74s/it]
  iters:  40%|████      | 80/200 [02:19<03:26,  1.72s/it]
  iters:  40%|████      | 81/200 [02:20<03:25,  1.73s/it]
  iters:  41%|████      | 82/200 [02:22<03:23,  1.73s/it]
  iters:  42%|████▏     | 83/200 [02:24<03:22,  1.73s/it]
  iters:  42%|████▏     | 84/200 [02:26<03:21,  1.73s/it]
  iters:  42%|████▎     | 85/200 [02:27<03:19,  1.73s/it]
  iters:  43%|████▎     | 86/200 [02:29<03:17,  1.73s/it]
  iters:  44%|████▎     | 87/200 [02:31<03:15,  1.73s/it]
  iters:  44%|████▍     | 88/200 [02:33<03:14,  1.73s/it]
  iters:  44%|████▍     | 89/200 [02:34<03:12,  1.73s/it]
  iters:  45%|████▌     | 90/200 [02:36<03:10,  1.73s/it]
  iters:  46%|████▌     | 91/200 [02:38<03:08,  1.73s/it]
  iters:  46%|████▌     | 92/200 [02:39<03:06,  1.73s/it]
  iters:  46%|████▋     | 93/200 [02:41<03:04,  1.72s/it]
  iters:  47%|████▋     | 94/200 [02:43<03:03,  1.73s/it]
  iters:  48%|████▊     | 95/200 [02:45<03:01,  1.73s/it]
  iters:  48%|████▊     | 96/200 [02:46<02:59,  1.73s/it]
  iters:  48%|████▊     | 97/200 [02:48<02:57,  1.72s/it]
  iters:  49%|████▉     | 98/200 [02:50<02:55,  1.72s/it]
  iters:  50%|████▉     | 99/200 [02:52<02:53,  1.72s/it]
  iters:  50%|█████     | 100/200 [02:53<02:52,  1.72s/it]
  iters:  50%|█████     | 101/200 [02:55<02:50,  1.72s/it]
  iters:  51%|█████     | 102/200 [02:57<02:49,  1.73s/it]
  iters:  52%|█████▏    | 103/200 [02:58<02:47,  1.72s/it]
  iters:  52%|█████▏    | 104/200 [03:00<02:45,  1.72s/it]
  iters:  52%|█████▎    | 105/200 [03:02<02:43,  1.73s/it]
  iters:  53%|█████▎    | 106/200 [03:04<02:41,  1.72s/it]
  iters:  54%|█████▎    | 107/200 [03:05<02:40,  1.72s/it]
  iters:  54%|█████▍    | 108/200 [03:07<02:38,  1.72s/it]
  iters:  55%|█████▍    | 109/200 [03:09<02:36,  1.72s/it]
  iters:  55%|█████▌    | 110/200 [03:10<02:34,  1.72s/it]
  iters:  56%|█████▌    | 111/200 [03:12<02:32,  1.72s/it]
  iters:  56%|█████▌    | 112/200 [03:14<02:31,  1.72s/it]
  iters:  56%|█████▋    | 113/200 [03:16<02:29,  1.72s/it]
  iters:  57%|█████▋    | 114/200 [03:17<02:27,  1.72s/it]
  iters:  57%|█████▊    | 115/200 [03:19<02:26,  1.72s/it]
  iters:  58%|█████▊    | 116/200 [03:21<02:24,  1.72s/it]
  iters:  58%|█████▊    | 117/200 [03:23<02:22,  1.72s/it]
  iters:  59%|█████▉    | 118/200 [03:24<02:20,  1.72s/it]
  iters:  60%|█████▉    | 119/200 [03:26<02:19,  1.72s/it]
  iters:  60%|██████    | 120/200 [03:28<02:17,  1.72s/it]
  iters:  60%|██████    | 121/200 [03:29<02:15,  1.72s/it]
  iters:  61%|██████    | 122/200 [03:31<02:14,  1.72s/it]
  iters:  62%|██████▏   | 123/200 [03:33<02:12,  1.72s/it]
  iters:  62%|██████▏   | 124/200 [03:35<02:10,  1.72s/it]
  iters:  62%|██████▎   | 125/200 [03:36<02:09,  1.72s/it]
  iters:  63%|██████▎   | 126/200 [03:38<02:07,  1.72s/it]
  iters:  64%|██████▎   | 127/200 [03:40<02:06,  1.73s/it]
  iters:  64%|██████▍   | 128/200 [03:41<02:04,  1.73s/it]
  iters:  64%|██████▍   | 129/200 [03:43<02:02,  1.73s/it]
  iters:  65%|██████▌   | 130/200 [03:45<01:58,  1.69s/it]
  iters:  66%|██████▌   | 131/200 [03:47<01:57,  1.71s/it]
  iters:  66%|██████▌   | 132/200 [03:48<01:56,  1.71s/it]
  iters:  66%|██████▋   | 133/200 [03:50<01:54,  1.72s/it]
  iters:  67%|██████▋   | 134/200 [03:52<01:53,  1.72s/it]
  iters:  68%|██████▊   | 135/200 [03:53<01:51,  1.72s/it]
  iters:  68%|██████▊   | 136/200 [03:55<01:50,  1.72s/it]
  iters:  68%|██████▊   | 137/200 [03:57<01:48,  1.72s/it]
  iters:  69%|██████▉   | 138/200 [03:59<01:46,  1.72s/it]
  iters:  70%|██████▉   | 139/200 [04:00<01:43,  1.69s/it]
  iters:  70%|███████   | 140/200 [04:02<01:41,  1.70s/it]
  iters:  70%|███████   | 141/200 [04:04<01:40,  1.71s/it]
  iters:  71%|███████   | 142/200 [04:05<01:39,  1.71s/it]
  iters:  72%|███████▏  | 143/200 [04:07<01:37,  1.72s/it]
  iters:  72%|███████▏  | 144/200 [04:09<01:36,  1.72s/it]
  iters:  72%|███████▎  | 145/200 [04:11<01:34,  1.72s/it]
  iters:  73%|███████▎  | 146/200 [04:12<01:33,  1.72s/it]
  iters:  74%|███████▎  | 147/200 [04:14<01:31,  1.72s/it]
  iters:  74%|███████▍  | 148/200 [04:16<01:29,  1.73s/it]
  iters:  74%|███████▍  | 149/200 [04:17<01:27,  1.72s/it]
  iters:  75%|███████▌  | 150/200 [04:19<01:26,  1.73s/it]
  iters:  76%|███████▌  | 151/200 [04:21<01:24,  1.73s/it]
  iters:  76%|███████▌  | 152/200 [04:23<01:22,  1.72s/it]
  iters:  76%|███████▋  | 153/200 [04:24<01:20,  1.72s/it]
  iters:  77%|███████▋  | 154/200 [04:26<01:19,  1.73s/it]
  iters:  78%|███████▊  | 155/200 [04:28<01:17,  1.73s/it]
  iters:  78%|███████▊  | 156/200 [04:30<01:16,  1.73s/it]
  iters:  78%|███████▊  | 157/200 [04:31<01:14,  1.72s/it]
  iters:  79%|███████▉  | 158/200 [04:33<01:15,  1.79s/it]
  iters:  80%|███████▉  | 159/200 [04:35<01:12,  1.77s/it]
  iters:  80%|████████  | 160/200 [04:37<01:10,  1.76s/it]
  iters:  80%|████████  | 161/200 [04:38<01:08,  1.75s/it]
  iters:  81%|████████  | 162/200 [04:40<01:06,  1.74s/it]
  iters:  82%|████████▏ | 163/200 [04:42<01:04,  1.74s/it]
  iters:  82%|████████▏ | 164/200 [04:44<01:02,  1.73s/it]
  iters:  82%|████████▎ | 165/200 [04:45<01:00,  1.73s/it]
  iters:  83%|████████▎ | 166/200 [04:47<00:58,  1.73s/it]
  iters:  84%|████████▎ | 167/200 [04:49<00:56,  1.73s/it]
  iters:  84%|████████▍ | 168/200 [04:50<00:55,  1.72s/it]
  iters:  84%|████████▍ | 169/200 [04:52<00:53,  1.72s/it]
  iters:  85%|████████▌ | 170/200 [04:54<00:51,  1.72s/it]
  iters:  86%|████████▌ | 171/200 [04:56<00:49,  1.72s/it]
  iters:  86%|████████▌ | 172/200 [04:57<00:48,  1.72s/it]
  iters:  86%|████████▋ | 173/200 [04:59<00:46,  1.73s/it]
  iters:  87%|████████▋ | 174/200 [05:01<00:44,  1.73s/it]
  iters:  88%|████████▊ | 175/200 [05:03<00:43,  1.72s/it]
  iters:  88%|████████▊ | 176/200 [05:04<00:41,  1.72s/it]
  iters:  88%|████████▊ | 177/200 [05:06<00:39,  1.72s/it]
  iters:  89%|████████▉ | 178/200 [05:08<00:37,  1.72s/it]
  iters:  90%|████████▉ | 179/200 [05:09<00:36,  1.72s/it]
  iters:  90%|█████████ | 180/200 [05:11<00:34,  1.73s/it]
  iters:  90%|█████████ | 181/200 [05:13<00:32,  1.72s/it]
  iters:  91%|█████████ | 182/200 [05:15<00:31,  1.73s/it]
  iters:  92%|█████████▏| 183/200 [05:16<00:29,  1.72s/it]
  iters:  92%|█████████▏| 184/200 [05:18<00:27,  1.72s/it]
  iters:  92%|█████████▎| 185/200 [05:20<00:25,  1.73s/it]
  iters:  93%|█████████▎| 186/200 [05:22<00:24,  1.72s/it]
  iters:  94%|█████████▎| 187/200 [05:23<00:22,  1.72s/it]
  iters:  94%|█████████▍| 188/200 [05:25<00:20,  1.73s/it]
  iters:  94%|█████████▍| 189/200 [05:27<00:18,  1.72s/it]
  iters:  95%|█████████▌| 190/200 [05:28<00:17,  1.72s/it]
  iters:  96%|█████████▌| 191/200 [05:30<00:15,  1.72s/it]
  iters:  96%|█████████▌| 192/200 [05:32<00:13,  1.72s/it]
  iters:  96%|█████████▋| 193/200 [05:34<00:12,  1.72s/it]
  iters:  97%|█████████▋| 194/200 [05:35<00:10,  1.72s/it]
  iters:  98%|█████████▊| 195/200 [05:37<00:08,  1.73s/it]
  iters:  98%|█████████▊| 196/200 [05:39<00:06,  1.73s/it]
  iters:  98%|█████████▊| 197/200 [05:40<00:05,  1.72s/it]
  iters:  99%|█████████▉| 198/200 [05:42<00:03,  1.73s/it]
  iters: 100%|█████████▉| 199/200 [05:44<00:01,  1.73s/it]
  iters: 100%|██████████| 200/200 [05:46<00:00,  1.73s/it]

  [timing] data: 2.4s (1%) | forward: 84.7s (24%) | backward: 259.0s (75%) | total: 346.1s

Training:   0%|          | 0/4 [06:18<?, ?it/s, acc=0.9994, det=0.0091, edge=0.0007]

  Epoch   0/4 | edge=0.0007 | det=0.0091 | test_loss=0.0008 | acc=0.9994 | recall=0.8476 | best=0.8471 * | train=346.4s test=31.9s

Training:  25%|██▌       | 1/4 [06:18<18:54, 378.33s/it, acc=0.9994, det=0.0091, edge=0.0007]
  iters:   0%|          | 0/200 [00:00<?, ?it/s]
  iters:   0%|          | 1/200 [00:02<06:47,  2.05s/it]
  iters:   1%|          | 2/200 [00:03<06:07,  1.86s/it]
  iters:   2%|▏         | 3/200 [00:05<05:53,  1.80s/it]
  iters:   2%|▏         | 4/200 [00:07<05:46,  1.77s/it]
  iters:   2%|▎         | 5/200 [00:08<05:41,  1.75s/it]
  iters:   3%|▎         | 6/200 [00:10<05:38,  1.74s/it]
  iters:   4%|▎         | 7/200 [00:12<05:35,  1.74s/it]
  iters:   4%|▍         | 8/200 [00:14<05:32,  1.73s/it]
  iters:   4%|▍         | 9/200 [00:15<05:29,  1.73s/it]
  iters:   5%|▌         | 10/200 [00:17<05:26,  1.72s/it]
  iters:   6%|▌         | 11/200 [00:19<05:24,  1.72s/it]
  iters:   6%|▌         | 12/200 [00:20<05:22,  1.72s/it]
  iters:   6%|▋         | 13/200 [00:22<05:21,  1.72s/it]
  iters:   7%|▋         | 14/200 [00:24<05:20,  1.72s/it]
  iters:   8%|▊         | 15/200 [00:26<05:18,  1.72s/it]
  iters:   8%|▊         | 16/200 [00:27<05:16,  1.72s/it]
  iters:   8%|▊         | 17/200 [00:29<05:14,  1.72s/it]
  iters:   9%|▉         | 18/200 [00:31<05:13,  1.72s/it]
  iters:  10%|▉         | 19/200 [00:33<05:11,  1.72s/it]
  iters:  10%|█         | 20/200 [00:34<05:09,  1.72s/it]
  iters:  10%|█         | 21/200 [00:36<05:08,  1.72s/it]
  iters:  11%|█         | 22/200 [00:38<05:04,  1.71s/it]
  iters:  12%|█▏        | 23/200 [00:39<05:03,  1.71s/it]
  iters:  12%|█▏        | 24/200 [00:41<05:02,  1.72s/it]
  iters:  12%|█▎        | 25/200 [00:43<05:00,  1.72s/it]
  iters:  13%|█▎        | 26/200 [00:45<04:58,  1.72s/it]
  iters:  14%|█▎        | 27/200 [00:46<04:56,  1.72s/it]
  iters:  14%|█▍        | 28/200 [00:48<04:55,  1.72s/it]
  iters:  14%|█▍        | 29/200 [00:50<04:54,  1.72s/it]
  iters:  15%|█▌        | 30/200 [00:51<04:52,  1.72s/it]
  iters:  16%|█▌        | 31/200 [00:53<04:50,  1.72s/it]
  iters:  16%|█▌        | 32/200 [00:55<04:49,  1.72s/it]
  iters:  16%|█▋        | 33/200 [00:57<04:47,  1.72s/it]
  iters:  17%|█▋        | 34/200 [00:58<04:45,  1.72s/it]
  iters:  18%|█▊        | 35/200 [01:00<04:44,  1.72s/it]
  iters:  18%|█▊        | 36/200 [01:02<04:42,  1.72s/it]
  iters:  18%|█▊        | 37/200 [01:03<04:40,  1.72s/it]
  iters:  19%|█▉        | 38/200 [01:05<04:39,  1.72s/it]
  iters:  20%|█▉        | 39/200 [01:07<04:35,  1.71s/it]
  iters:  20%|██        | 40/200 [01:09<04:34,  1.72s/it]
  iters:  20%|██        | 41/200 [01:10<04:33,  1.72s/it]
  iters:  21%|██        | 42/200 [01:12<04:32,  1.72s/it]
  iters:  22%|██▏       | 43/200 [01:14<04:31,  1.73s/it]
  iters:  22%|██▏       | 44/200 [01:16<04:47,  1.84s/it]
  iters:  22%|██▎       | 45/200 [01:18<04:40,  1.81s/it]
  iters:  23%|██▎       | 46/200 [01:19<04:35,  1.79s/it]
  iters:  24%|██▎       | 47/200 [01:21<04:31,  1.77s/it]
  iters:  24%|██▍       | 48/200 [01:23<04:27,  1.76s/it]
  iters:  24%|██▍       | 49/200 [01:25<04:24,  1.75s/it]
  iters:  25%|██▌       | 50/200 [01:26<04:21,  1.74s/it]
  iters:  26%|██▌       | 51/200 [01:28<04:18,  1.74s/it]
  iters:  26%|██▌       | 52/200 [01:30<04:16,  1.73s/it]
  iters:  26%|██▋       | 53/200 [01:31<04:14,  1.73s/it]
  iters:  27%|██▋       | 54/200 [01:33<04:12,  1.73s/it]
  iters:  28%|██▊       | 55/200 [01:35<04:10,  1.73s/it]
  iters:  28%|██▊       | 56/200 [01:37<04:09,  1.73s/it]
  iters:  28%|██▊       | 57/200 [01:38<04:07,  1.73s/it]
  iters:  29%|██▉       | 58/200 [01:40<04:05,  1.73s/it]
  iters:  30%|██▉       | 59/200 [01:42<04:04,  1.73s/it]
  iters:  30%|███       | 60/200 [01:44<04:02,  1.73s/it]
  iters:  30%|███       | 61/200 [01:45<04:01,  1.73s/it]
  iters:  31%|███       | 62/200 [01:47<03:58,  1.73s/it]
  iters:  32%|███▏      | 63/200 [01:49<03:57,  1.73s/it]
  iters:  32%|███▏      | 64/200 [01:51<03:55,  1.73s/it]
  iters:  32%|███▎      | 65/200 [01:52<03:53,  1.73s/it]
  iters:  33%|███▎      | 66/200 [01:54<03:51,  1.73s/it]
  iters:  34%|███▎      | 67/200 [01:56<03:49,  1.72s/it]
  iters:  34%|███▍      | 68/200 [01:57<03:48,  1.73s/it]
  iters:  34%|███▍      | 69/200 [01:59<03:46,  1.73s/it]
  iters:  35%|███▌      | 70/200 [02:01<03:44,  1.73s/it]
  iters:  36%|███▌      | 71/200 [02:03<03:43,  1.73s/it]
  iters:  36%|███▌      | 72/200 [02:04<03:40,  1.73s/it]
  iters:  36%|███▋      | 73/200 [02:06<03:39,  1.73s/it]
  iters:  37%|███▋      | 74/200 [02:08<03:38,  1.74s/it]
  iters:  38%|███▊      | 75/200 [02:10<03:36,  1.73s/it]
  iters:  38%|███▊      | 76/200 [02:11<03:34,  1.73s/it]
  iters:  38%|███▊      | 77/200 [02:13<03:32,  1.73s/it]
  iters:  39%|███▉      | 78/200 [02:15<03:30,  1.73s/it]
  iters:  40%|███▉      | 79/200 [02:16<03:28,  1.73s/it]
  iters:  40%|████      | 80/200 [02:18<03:26,  1.72s/it]
  iters:  40%|████      | 81/200 [02:20<03:25,  1.72s/it]
  iters:  41%|████      | 82/200 [02:22<03:23,  1.73s/it]
  iters:  42%|████▏     | 83/200 [02:23<03:21,  1.73s/it]
  iters:  42%|████▏     | 84/200 [02:25<03:19,  1.72s/it]
  iters:  42%|████▎     | 85/200 [02:27<03:18,  1.73s/it]
  iters:  43%|████▎     | 86/200 [02:29<03:16,  1.72s/it]
  iters:  44%|████▎     | 87/200 [02:30<03:14,  1.72s/it]
  iters:  44%|████▍     | 88/200 [02:32<03:13,  1.72s/it]
  iters:  44%|████▍     | 89/200 [02:34<03:11,  1.72s/it]
  iters:  45%|████▌     | 90/200 [02:35<03:09,  1.72s/it]
  iters:  46%|████▌     | 91/200 [02:37<03:07,  1.72s/it]
  iters:  46%|████▌     | 92/200 [02:39<03:06,  1.72s/it]
  iters:  46%|████▋     | 93/200 [02:41<03:04,  1.72s/it]
  iters:  47%|████▋     | 94/200 [02:42<03:02,  1.72s/it]
  iters:  48%|████▊     | 95/200 [02:44<03:00,  1.72s/it]
  iters:  48%|████▊     | 96/200 [02:46<02:59,  1.72s/it]
  iters:  48%|████▊     | 97/200 [02:47<02:57,  1.72s/it]
  iters:  49%|████▉     | 98/200 [02:49<02:55,  1.72s/it]
  iters:  50%|████▉     | 99/200 [02:51<02:54,  1.72s/it]
  iters:  50%|█████     | 100/200 [02:53<02:52,  1.72s/it]
  iters:  50%|█████     | 101/200 [02:54<02:50,  1.72s/it]
  iters:  51%|█████     | 102/200 [02:56<02:48,  1.72s/it]
  iters:  52%|█████▏    | 103/200 [02:58<02:47,  1.73s/it]
  iters:  52%|█████▏    | 104/200 [03:00<02:45,  1.73s/it]
  iters:  52%|█████▎    | 105/200 [03:01<02:43,  1.73s/it]
  iters:  53%|█████▎    | 106/200 [03:03<02:42,  1.72s/it]
  iters:  54%|█████▎    | 107/200 [03:05<02:40,  1.72s/it]
  iters:  54%|█████▍    | 108/200 [03:06<02:38,  1.72s/it]
  iters:  55%|█████▍    | 109/200 [03:08<02:36,  1.72s/it]
  iters:  55%|█████▌    | 110/200 [03:10<02:34,  1.72s/it]
  iters:  56%|█████▌    | 111/200 [03:12<02:33,  1.72s/it]
  iters:  56%|█████▌    | 112/200 [03:13<02:31,  1.72s/it]
  iters:  56%|█████▋    | 113/200 [03:15<02:27,  1.69s/it]
  iters:  57%|█████▋    | 114/200 [03:17<02:26,  1.70s/it]
  iters:  57%|█████▊    | 115/200 [03:18<02:25,  1.71s/it]
  iters:  58%|█████▊    | 116/200 [03:20<02:23,  1.71s/it]
  iters:  58%|█████▊    | 117/200 [03:22<02:22,  1.71s/it]
  iters:  59%|█████▉    | 118/200 [03:24<02:20,  1.72s/it]
  iters:  60%|█████▉    | 119/200 [03:25<02:17,  1.70s/it]
  iters:  60%|██████    | 120/200 [03:27<02:16,  1.70s/it]
  iters:  60%|██████    | 121/200 [03:29<02:14,  1.71s/it]
  iters:  61%|██████    | 122/200 [03:30<02:13,  1.71s/it]
  iters:  62%|██████▏   | 123/200 [03:32<02:11,  1.71s/it]
  iters:  62%|██████▏   | 124/200 [03:34<02:10,  1.71s/it]
  iters:  62%|██████▎   | 125/200 [03:35<02:08,  1.71s/it]
  iters:  63%|██████▎   | 126/200 [03:37<02:06,  1.71s/it]
  iters:  64%|██████▎   | 127/200 [03:39<02:04,  1.71s/it]
  iters:  64%|██████▍   | 128/200 [03:41<02:03,  1.71s/it]
  iters:  64%|██████▍   | 129/200 [03:42<02:01,  1.72s/it]
  iters:  65%|██████▌   | 130/200 [03:44<02:00,  1.72s/it]
  iters:  66%|██████▌   | 131/200 [03:46<01:58,  1.72s/it]
  iters:  66%|██████▌   | 132/200 [03:48<01:56,  1.72s/it]
  iters:  66%|██████▋   | 133/200 [03:49<01:55,  1.72s/it]
  iters:  67%|██████▋   | 134/200 [03:51<01:58,  1.79s/it]
  iters:  68%|██████▊   | 135/200 [03:53<01:54,  1.76s/it]
  iters:  68%|██████▊   | 136/200 [03:55<01:51,  1.75s/it]
  iters:  68%|██████▊   | 137/200 [03:56<01:49,  1.74s/it]
  iters:  69%|██████▉   | 138/200 [03:58<01:46,  1.72s/it]
  iters:  70%|██████▉   | 139/200 [04:00<01:43,  1.69s/it]
  iters:  70%|███████   | 140/200 [04:01<01:41,  1.70s/it]
  iters:  70%|███████   | 141/200 [04:03<01:40,  1.71s/it]
  iters:  71%|███████   | 142/200 [04:05<01:39,  1.71s/it]
  iters:  72%|███████▏  | 143/200 [04:06<01:37,  1.71s/it]
  iters:  72%|███████▏  | 144/200 [04:08<01:35,  1.71s/it]
  iters:  72%|███████▎  | 145/200 [04:10<01:34,  1.72s/it]
  iters:  73%|███████▎  | 146/200 [04:12<01:32,  1.72s/it]
  iters:  74%|███████▎  | 147/200 [04:13<01:31,  1.72s/it]
  iters:  74%|███████▍  | 148/200 [04:15<01:29,  1.72s/it]
  iters:  74%|███████▍  | 149/200 [04:17<01:27,  1.72s/it]
  iters:  75%|███████▌  | 150/200 [04:19<01:25,  1.72s/it]
  iters:  76%|███████▌  | 151/200 [04:20<01:24,  1.72s/it]
  iters:  76%|███████▌  | 152/200 [04:22<01:22,  1.72s/it]
  iters:  76%|███████▋  | 153/200 [04:24<01:20,  1.72s/it]
  iters:  77%|███████▋  | 154/200 [04:25<01:19,  1.72s/it]
  iters:  78%|███████▊  | 155/200 [04:27<01:16,  1.69s/it]
  iters:  78%|███████▊  | 156/200 [04:29<01:14,  1.70s/it]
  iters:  78%|███████▊  | 157/200 [04:30<01:13,  1.71s/it]
  iters:  79%|███████▉  | 158/200 [04:32<01:11,  1.71s/it]
  iters:  80%|███████▉  | 159/200 [04:34<01:10,  1.71s/it]
  iters:  80%|████████  | 160/200 [04:36<01:08,  1.72s/it]
  iters:  80%|████████  | 161/200 [04:37<01:07,  1.72s/it]
  iters:  81%|████████  | 162/200 [04:39<01:05,  1.73s/it]
  iters:  82%|████████▏ | 163/200 [04:41<01:03,  1.73s/it]
  iters:  82%|████████▏ | 164/200 [04:43<01:02,  1.73s/it]
  iters:  82%|████████▎ | 165/200 [04:44<01:00,  1.73s/it]
  iters:  83%|████████▎ | 166/200 [04:46<00:58,  1.72s/it]
  iters:  84%|████████▎ | 167/200 [04:48<00:56,  1.72s/it]
  iters:  84%|████████▍ | 168/200 [04:49<00:55,  1.73s/it]
  iters:  84%|████████▍ | 169/200 [04:51<00:53,  1.72s/it]
  iters:  85%|████████▌ | 170/200 [04:53<00:51,  1.72s/it]
  iters:  86%|████████▌ | 171/200 [04:55<00:49,  1.72s/it]
  iters:  86%|████████▌ | 172/200 [04:56<00:48,  1.72s/it]
  iters:  86%|████████▋ | 173/200 [04:58<00:46,  1.72s/it]
  iters:  87%|████████▋ | 174/200 [05:00<00:44,  1.72s/it]
  iters:  88%|████████▊ | 175/200 [05:02<00:42,  1.72s/it]
  iters:  88%|████████▊ | 176/200 [05:03<00:41,  1.72s/it]
  iters:  88%|████████▊ | 177/200 [05:05<00:39,  1.72s/it]
  iters:  89%|████████▉ | 178/200 [05:07<00:37,  1.72s/it]
  iters:  90%|████████▉ | 179/200 [05:08<00:36,  1.72s/it]
  iters:  90%|█████████ | 180/200 [05:10<00:34,  1.72s/it]
  iters:  90%|█████████ | 181/200 [05:12<00:32,  1.73s/it]
  iters:  91%|█████████ | 182/200 [05:14<00:31,  1.73s/it]
  iters:  92%|█████████▏| 183/200 [05:15<00:29,  1.73s/it]
  iters:  92%|█████████▏| 184/200 [05:17<00:27,  1.73s/it]
  iters:  92%|█████████▎| 185/200 [05:19<00:25,  1.73s/it]
  iters:  93%|█████████▎| 186/200 [05:20<00:24,  1.72s/it]
  iters:  94%|█████████▎| 187/200 [05:22<00:22,  1.72s/it]
  iters:  94%|█████████▍| 188/200 [05:24<00:20,  1.72s/it]
  iters:  94%|█████████▍| 189/200 [05:26<00:18,  1.73s/it]
  iters:  95%|█████████▌| 190/200 [05:27<00:17,  1.73s/it]
  iters:  96%|█████████▌| 191/200 [05:29<00:15,  1.73s/it]
  iters:  96%|█████████▌| 192/200 [05:31<00:13,  1.72s/it]
  iters:  96%|█████████▋| 193/200 [05:33<00:12,  1.72s/it]
  iters:  97%|█████████▋| 194/200 [05:34<00:10,  1.72s/it]
  iters:  98%|█████████▊| 195/200 [05:36<00:08,  1.72s/it]
  iters:  98%|█████████▊| 196/200 [05:38<00:06,  1.72s/it]
  iters:  98%|█████████▊| 197/200 [05:39<00:05,  1.72s/it]
  iters:  99%|█████████▉| 198/200 [05:41<00:03,  1.72s/it]
  iters: 100%|█████████▉| 199/200 [05:43<00:01,  1.72s/it]
  iters: 100%|██████████| 200/200 [05:45<00:00,  1.72s/it]

  [timing] data: 2.4s (1%) | forward: 84.5s (24%) | backward: 258.2s (75%) | total: 345.1s

Training:  25%|██▌       | 1/4 [12:35<18:54, 378.33s/it, acc=0.9994, det=0.0070, edge=0.0004]

  Epoch   1/4 | edge=0.0004 | det=0.0070 | test_loss=0.0010 | acc=0.9994 | recall=0.8310 | best=0.8471   | train=345.3s test=31.7s

Training:  50%|█████     | 2/4 [12:35<12:35, 377.54s/it, acc=0.9994, det=0.0070, edge=0.0004]
  iters:   0%|          | 0/200 [00:00<?, ?it/s]
  iters:   0%|          | 1/200 [00:02<06:59,  2.11s/it]
  iters:   1%|          | 2/200 [00:03<06:12,  1.88s/it]
  iters:   2%|▏         | 3/200 [00:05<05:56,  1.81s/it]
  iters:   2%|▏         | 4/200 [00:07<05:47,  1.77s/it]
  iters:   2%|▎         | 5/200 [00:08<05:42,  1.76s/it]
  iters:   3%|▎         | 6/200 [00:10<05:38,  1.74s/it]
  iters:   4%|▎         | 7/200 [00:12<05:35,  1.74s/it]
  iters:   4%|▍         | 8/200 [00:14<05:32,  1.73s/it]
  iters:   4%|▍         | 9/200 [00:15<05:30,  1.73s/it]
  iters:   5%|▌         | 10/200 [00:17<05:28,  1.73s/it]
  iters:   6%|▌         | 11/200 [00:19<05:26,  1.73s/it]
  iters:   6%|▌         | 12/200 [00:21<05:25,  1.73s/it]
  iters:   6%|▋         | 13/200 [00:22<05:23,  1.73s/it]
  iters:   7%|▋         | 14/200 [00:24<05:21,  1.73s/it]
  iters:   8%|▊         | 15/200 [00:26<05:19,  1.73s/it]
  iters:   8%|▊         | 16/200 [00:27<05:17,  1.73s/it]
  iters:   8%|▊         | 17/200 [00:29<05:15,  1.72s/it]
  iters:   9%|▉         | 18/200 [00:31<05:14,  1.73s/it]
  iters:  10%|▉         | 19/200 [00:33<05:12,  1.73s/it]
  iters:  10%|█         | 20/200 [00:34<05:10,  1.72s/it]
  iters:  10%|█         | 21/200 [00:36<05:21,  1.79s/it]
  iters:  11%|█         | 22/200 [00:38<05:14,  1.77s/it]
  iters:  12%|█▏        | 23/200 [00:40<05:09,  1.75s/it]
  iters:  12%|█▏        | 24/200 [00:41<05:05,  1.74s/it]
  iters:  12%|█▎        | 25/200 [00:43<05:02,  1.73s/it]
  iters:  13%|█▎        | 26/200 [00:45<05:01,  1.73s/it]
  iters:  14%|█▎        | 27/200 [00:47<04:58,  1.73s/it]
  iters:  14%|█▍        | 28/200 [00:48<04:57,  1.73s/it]
  iters:  14%|█▍        | 29/200 [00:50<04:55,  1.73s/it]
  iters:  15%|█▌        | 30/200 [00:52<04:52,  1.72s/it]
  iters:  16%|█▌        | 31/200 [00:54<04:51,  1.72s/it]
  iters:  16%|█▌        | 32/200 [00:55<04:48,  1.72s/it]
  iters:  16%|█▋        | 33/200 [00:57<04:47,  1.72s/it]
  iters:  17%|█▋        | 34/200 [00:59<04:45,  1.72s/it]
  iters:  18%|█▊        | 35/200 [01:00<04:43,  1.72s/it]
  iters:  18%|█▊        | 36/200 [01:02<04:41,  1.72s/it]
  iters:  18%|█▊        | 37/200 [01:04<04:40,  1.72s/it]
  iters:  19%|█▉        | 38/200 [01:06<04:38,  1.72s/it]
  iters:  20%|█▉        | 39/200 [01:07<04:36,  1.72s/it]
  iters:  20%|██        | 40/200 [01:09<04:35,  1.72s/it]
  iters:  20%|██        | 41/200 [01:11<04:33,  1.72s/it]
  iters:  21%|██        | 42/200 [01:12<04:32,  1.72s/it]
  iters:  22%|██▏       | 43/200 [01:14<04:30,  1.72s/it]
  iters:  22%|██▏       | 44/200 [01:16<04:28,  1.72s/it]
  iters:  22%|██▎       | 45/200 [01:18<04:26,  1.72s/it]
  iters:  23%|██▎       | 46/200 [01:19<04:24,  1.72s/it]
  iters:  24%|██▎       | 47/200 [01:21<04:22,  1.72s/it]
  iters:  24%|██▍       | 48/200 [01:23<04:21,  1.72s/it]
  iters:  24%|██▍       | 49/200 [01:24<04:19,  1.72s/it]
  iters:  25%|██▌       | 50/200 [01:26<04:17,  1.72s/it]
  iters:  26%|██▌       | 51/200 [01:28<04:15,  1.72s/it]
  iters:  26%|██▌       | 52/200 [01:30<04:14,  1.72s/it]
  iters:  26%|██▋       | 53/200 [01:31<04:12,  1.72s/it]
  iters:  27%|██▋       | 54/200 [01:33<04:11,  1.72s/it]
  iters:  28%|██▊       | 55/200 [01:35<04:09,  1.72s/it]
  iters:  28%|██▊       | 56/200 [01:36<04:07,  1.72s/it]
  iters:  28%|██▊       | 57/200 [01:38<04:06,  1.72s/it]
  iters:  29%|██▉       | 58/200 [01:40<04:04,  1.73s/it]
  iters:  30%|██▉       | 59/200 [01:42<04:03,  1.72s/it]
  iters:  30%|███       | 60/200 [01:43<04:00,  1.72s/it]
  iters:  30%|███       | 61/200 [01:45<03:59,  1.73s/it]
  iters:  31%|███       | 62/200 [01:47<03:57,  1.72s/it]
  iters:  32%|███▏      | 63/200 [01:49<03:56,  1.72s/it]
  iters:  32%|███▏      | 64/200 [01:50<03:50,  1.69s/it]
  iters:  32%|███▎      | 65/200 [01:52<03:49,  1.70s/it]
  iters:  33%|███▎      | 66/200 [01:54<03:49,  1.71s/it]
  iters:  34%|███▎      | 67/200 [01:55<03:48,  1.72s/it]
  iters:  34%|███▍      | 68/200 [01:57<03:47,  1.72s/it]
  iters:  34%|███▍      | 69/200 [01:59<03:45,  1.72s/it]
  iters:  35%|███▌      | 70/200 [02:01<03:44,  1.73s/it]
  iters:  36%|███▌      | 71/200 [02:02<03:42,  1.73s/it]
  iters:  36%|███▌      | 72/200 [02:04<03:40,  1.73s/it]
  iters:  36%|███▋      | 73/200 [02:06<03:39,  1.73s/it]
  iters:  37%|███▋      | 74/200 [02:07<03:37,  1.73s/it]
  iters:  38%|███▊      | 75/200 [02:09<03:36,  1.73s/it]
  iters:  38%|███▊      | 76/200 [02:11<03:34,  1.73s/it]
  iters:  38%|███▊      | 77/200 [02:13<03:32,  1.73s/it]
  iters:  39%|███▉      | 78/200 [02:14<03:30,  1.73s/it]
  iters:  40%|███▉      | 79/200 [02:16<03:28,  1.72s/it]
  iters:  40%|████      | 80/200 [02:18<03:26,  1.72s/it]
  iters:  40%|████      | 81/200 [02:20<03:24,  1.72s/it]
  iters:  41%|████      | 82/200 [02:21<03:23,  1.72s/it]
  iters:  42%|████▏     | 83/200 [02:23<03:21,  1.72s/it]
  iters:  42%|████▏     | 84/200 [02:25<03:19,  1.72s/it]
  iters:  42%|████▎     | 85/200 [02:26<03:17,  1.72s/it]
  iters:  43%|████▎     | 86/200 [02:28<03:16,  1.72s/it]
  iters:  44%|████▎     | 87/200 [02:30<03:14,  1.72s/it]
  iters:  44%|████▍     | 88/200 [02:32<03:12,  1.72s/it]
  iters:  44%|████▍     | 89/200 [02:33<03:11,  1.72s/it]
  iters:  45%|████▌     | 90/200 [02:35<03:09,  1.72s/it]
  iters:  46%|████▌     | 91/200 [02:37<03:07,  1.72s/it]
  iters:  46%|████▌     | 92/200 [02:38<03:06,  1.73s/it]
  iters:  46%|████▋     | 93/200 [02:40<03:04,  1.73s/it]
  iters:  47%|████▋     | 94/200 [02:42<03:01,  1.71s/it]
  iters:  48%|████▊     | 95/200 [02:44<03:00,  1.72s/it]
  iters:  48%|████▊     | 96/200 [02:45<02:58,  1.72s/it]
  iters:  48%|████▊     | 97/200 [02:47<02:57,  1.73s/it]
  iters:  49%|████▉     | 98/200 [02:49<02:55,  1.72s/it]
  iters:  50%|████▉     | 99/200 [02:51<02:54,  1.73s/it]
  iters:  50%|█████     | 100/200 [02:52<02:52,  1.73s/it]
  iters:  50%|█████     | 101/200 [02:54<02:50,  1.73s/it]
  iters:  51%|█████     | 102/200 [02:56<02:48,  1.72s/it]
  iters:  52%|█████▏    | 103/200 [02:57<02:47,  1.72s/it]
  iters:  52%|█████▏    | 104/200 [02:59<02:45,  1.72s/it]
  iters:  52%|█████▎    | 105/200 [03:01<02:44,  1.73s/it]
  iters:  53%|█████▎    | 106/200 [03:03<02:42,  1.73s/it]
  iters:  54%|█████▎    | 107/200 [03:04<02:40,  1.73s/it]
  iters:  54%|█████▍    | 108/200 [03:06<02:38,  1.72s/it]
  iters:  55%|█████▍    | 109/200 [03:08<02:37,  1.73s/it]
  iters:  55%|█████▌    | 110/200 [03:10<02:35,  1.72s/it]
  iters:  56%|█████▌    | 111/200 [03:11<02:33,  1.73s/it]
  iters:  56%|█████▌    | 112/200 [03:13<02:31,  1.73s/it]
  iters:  56%|█████▋    | 113/200 [03:15<02:30,  1.73s/it]
  iters:  57%|█████▋    | 114/200 [03:16<02:28,  1.73s/it]
  iters:  57%|█████▊    | 115/200 [03:18<02:26,  1.73s/it]
  iters:  58%|█████▊    | 116/200 [03:20<02:24,  1.72s/it]
  iters:  58%|█████▊    | 117/200 [03:22<02:29,  1.80s/it]
  iters:  59%|█████▉    | 118/200 [03:24<02:25,  1.78s/it]
  iters:  60%|█████▉    | 119/200 [03:25<02:22,  1.76s/it]
  iters:  60%|██████    | 120/200 [03:27<02:19,  1.75s/it]
  iters:  60%|██████    | 121/200 [03:29<02:17,  1.74s/it]
  iters:  61%|██████    | 122/200 [03:30<02:15,  1.74s/it]
  iters:  62%|██████▏   | 123/200 [03:32<02:13,  1.73s/it]
  iters:  62%|██████▏   | 124/200 [03:34<02:11,  1.73s/it]
  iters:  62%|██████▎   | 125/200 [03:36<02:09,  1.73s/it]
  iters:  63%|██████▎   | 126/200 [03:37<02:07,  1.73s/it]
  iters:  64%|██████▎   | 127/200 [03:39<02:06,  1.73s/it]
  iters:  64%|██████▍   | 128/200 [03:41<02:04,  1.74s/it]
  iters:  64%|██████▍   | 129/200 [03:43<02:03,  1.73s/it]
  iters:  65%|██████▌   | 130/200 [03:44<02:01,  1.73s/it]
  iters:  66%|██████▌   | 131/200 [03:46<01:59,  1.73s/it]
  iters:  66%|██████▌   | 132/200 [03:48<01:57,  1.72s/it]
  iters:  66%|██████▋   | 133/200 [03:49<01:55,  1.72s/it]
  iters:  67%|██████▋   | 134/200 [03:51<01:53,  1.72s/it]
  iters:  68%|██████▊   | 135/200 [03:53<01:51,  1.72s/it]
  iters:  68%|██████▊   | 136/200 [03:55<01:50,  1.72s/it]
  iters:  68%|██████▊   | 137/200 [03:56<01:48,  1.72s/it]
  iters:  69%|██████▉   | 138/200 [03:58<01:46,  1.72s/it]
  iters:  70%|██████▉   | 139/200 [04:00<01:44,  1.72s/it]
  iters:  70%|███████   | 140/200 [04:01<01:43,  1.72s/it]
  iters:  70%|███████   | 141/200 [04:03<01:41,  1.72s/it]
  iters:  71%|███████   | 142/200 [04:05<01:39,  1.72s/it]
  iters:  72%|███████▏  | 143/200 [04:07<01:38,  1.73s/it]
  iters:  72%|███████▏  | 144/200 [04:08<01:36,  1.72s/it]
  iters:  72%|███████▎  | 145/200 [04:10<01:34,  1.72s/it]
  iters:  73%|███████▎  | 146/200 [04:12<01:33,  1.72s/it]
  iters:  74%|███████▎  | 147/200 [04:14<01:31,  1.72s/it]
  iters:  74%|███████▍  | 148/200 [04:15<01:29,  1.72s/it]
  iters:  74%|███████▍  | 149/200 [04:17<01:27,  1.72s/it]
  iters:  75%|███████▌  | 150/200 [04:19<01:26,  1.72s/it]
  iters:  76%|███████▌  | 151/200 [04:20<01:24,  1.72s/it]
  iters:  76%|███████▌  | 152/200 [04:22<01:22,  1.72s/it]
  iters:  76%|███████▋  | 153/200 [04:24<01:20,  1.72s/it]
  iters:  77%|███████▋  | 154/200 [04:26<01:19,  1.72s/it]
  iters:  78%|███████▊  | 155/200 [04:27<01:17,  1.72s/it]
  iters:  78%|███████▊  | 156/200 [04:29<01:15,  1.72s/it]
  iters:  78%|███████▊  | 157/200 [04:31<01:13,  1.72s/it]
  iters:  79%|███████▉  | 158/200 [04:32<01:12,  1.72s/it]
  iters:  80%|███████▉  | 159/200 [04:34<01:10,  1.72s/it]
  iters:  80%|████████  | 160/200 [04:36<01:08,  1.72s/it]
  iters:  80%|████████  | 161/200 [04:38<01:07,  1.72s/it]
  iters:  81%|████████  | 162/200 [04:39<01:05,  1.72s/it]
  iters:  82%|████████▏ | 163/200 [04:41<01:03,  1.73s/it]
  iters:  82%|████████▏ | 164/200 [04:43<01:02,  1.73s/it]
  iters:  82%|████████▎ | 165/200 [04:45<01:00,  1.73s/it]
  iters:  83%|████████▎ | 166/200 [04:46<00:58,  1.73s/it]
  iters:  84%|████████▎ | 167/200 [04:48<00:56,  1.72s/it]
  iters:  84%|████████▍ | 168/200 [04:50<00:55,  1.72s/it]
  iters:  84%|████████▍ | 169/200 [04:51<00:53,  1.72s/it]
  iters:  85%|████████▌ | 170/200 [04:53<00:51,  1.72s/it]
  iters:  86%|████████▌ | 171/200 [04:55<00:49,  1.72s/it]
  iters:  86%|████████▌ | 172/200 [04:57<00:48,  1.72s/it]
  iters:  86%|████████▋ | 173/200 [04:58<00:46,  1.72s/it]
  iters:  87%|████████▋ | 174/200 [05:00<00:44,  1.72s/it]
  iters:  88%|████████▊ | 175/200 [05:02<00:43,  1.72s/it]
  iters:  88%|████████▊ | 176/200 [05:03<00:41,  1.72s/it]
  iters:  88%|████████▊ | 177/200 [05:05<00:39,  1.73s/it]
  iters:  89%|████████▉ | 178/200 [05:07<00:37,  1.72s/it]
  iters:  90%|████████▉ | 179/200 [05:09<00:36,  1.72s/it]
  iters:  90%|█████████ | 180/200 [05:10<00:34,  1.72s/it]
  iters:  90%|█████████ | 181/200 [05:12<00:32,  1.72s/it]
  iters:  91%|█████████ | 182/200 [05:14<00:31,  1.72s/it]
  iters:  92%|█████████▏| 183/200 [05:16<00:29,  1.72s/it]
  iters:  92%|█████████▏| 184/200 [05:17<00:27,  1.72s/it]
  iters:  92%|█████████▎| 185/200 [05:19<00:25,  1.72s/it]
  iters:  93%|█████████▎| 186/200 [05:21<00:24,  1.72s/it]
  iters:  94%|█████████▎| 187/200 [05:22<00:22,  1.72s/it]
  iters:  94%|█████████▍| 188/200 [05:24<00:20,  1.72s/it]
  iters:  94%|█████████▍| 189/200 [05:26<00:18,  1.72s/it]
  iters:  95%|█████████▌| 190/200 [05:28<00:17,  1.72s/it]
  iters:  96%|█████████▌| 191/200 [05:29<00:15,  1.72s/it]
  iters:  96%|█████████▌| 192/200 [05:31<00:13,  1.73s/it]
  iters:  96%|█████████▋| 193/200 [05:33<00:12,  1.72s/it]
  iters:  97%|█████████▋| 194/200 [05:35<00:10,  1.72s/it]
  iters:  98%|█████████▊| 195/200 [05:36<00:08,  1.72s/it]
  iters:  98%|█████████▊| 196/200 [05:38<00:06,  1.72s/it]
  iters:  98%|█████████▊| 197/200 [05:40<00:05,  1.72s/it]
  iters:  99%|█████████▉| 198/200 [05:41<00:03,  1.72s/it]
  iters: 100%|█████████▉| 199/200 [05:43<00:01,  1.72s/it]
  iters: 100%|██████████| 200/200 [05:45<00:00,  1.72s/it]

  [timing] data: 2.4s (1%) | forward: 84.4s (24%) | backward: 258.5s (75%) | total: 345.3s

Training:  50%|█████     | 2/4 [18:52<12:35, 377.54s/it, acc=0.9996, det=0.0069, edge=0.0004]

  Epoch   2/4 | edge=0.0004 | det=0.0069 | test_loss=0.0007 | acc=0.9996 | recall=0.8405 | best=0.8471   | train=345.5s test=31.7s

Training:  75%|███████▌  | 3/4 [18:52<06:17, 377.39s/it, acc=0.9996, det=0.0069, edge=0.0004]
  iters:   0%|          | 0/200 [00:00<?, ?it/s]
  iters:   0%|          | 1/200 [00:02<06:41,  2.02s/it]
  iters:   1%|          | 2/200 [00:03<06:06,  1.85s/it]
  iters:   2%|▏         | 3/200 [00:05<05:51,  1.79s/it]
  iters:   2%|▏         | 4/200 [00:07<05:44,  1.76s/it]
  iters:   2%|▎         | 5/200 [00:08<05:40,  1.74s/it]
  iters:   3%|▎         | 6/200 [00:10<05:37,  1.74s/it]
  iters:   4%|▎         | 7/200 [00:12<05:34,  1.73s/it]
  iters:   4%|▍         | 8/200 [00:14<05:31,  1.73s/it]
  iters:   4%|▍         | 9/200 [00:15<05:29,  1.72s/it]
  iters:   5%|▌         | 10/200 [00:17<05:27,  1.72s/it]
  iters:   6%|▌         | 11/200 [00:19<05:24,  1.72s/it]
  iters:   6%|▌         | 12/200 [00:20<05:23,  1.72s/it]
  iters:   6%|▋         | 13/200 [00:22<05:22,  1.72s/it]
  iters:   7%|▋         | 14/200 [00:24<05:19,  1.72s/it]
  iters:   8%|▊         | 15/200 [00:26<05:17,  1.72s/it]
  iters:   8%|▊         | 16/200 [00:28<05:29,  1.79s/it]
  iters:   8%|▊         | 17/200 [00:29<05:23,  1.77s/it]
  iters:   9%|▉         | 18/200 [00:31<05:19,  1.75s/it]
  iters:  10%|▉         | 19/200 [00:33<05:15,  1.74s/it]
  iters:  10%|█         | 20/200 [00:34<05:12,  1.74s/it]
  iters:  10%|█         | 21/200 [00:36<05:10,  1.73s/it]
  iters:  11%|█         | 22/200 [00:38<05:07,  1.73s/it]
  iters:  12%|█▏        | 23/200 [00:40<05:04,  1.72s/it]
  iters:  12%|█▏        | 24/200 [00:41<05:03,  1.72s/it]
  iters:  12%|█▎        | 25/200 [00:43<05:01,  1.72s/it]
  iters:  13%|█▎        | 26/200 [00:45<04:59,  1.72s/it]
  iters:  14%|█▎        | 27/200 [00:46<04:58,  1.73s/it]
  iters:  14%|█▍        | 28/200 [00:48<04:56,  1.72s/it]
  iters:  14%|█▍        | 29/200 [00:50<04:54,  1.72s/it]
  iters:  15%|█▌        | 30/200 [00:52<04:52,  1.72s/it]
  iters:  16%|█▌        | 31/200 [00:53<04:51,  1.72s/it]
  iters:  16%|█▌        | 32/200 [00:55<04:49,  1.73s/it]
  iters:  16%|█▋        | 33/200 [00:57<04:48,  1.73s/it]
  iters:  17%|█▋        | 34/200 [00:59<04:46,  1.73s/it]
  iters:  18%|█▊        | 35/200 [01:00<04:45,  1.73s/it]
  iters:  18%|█▊        | 36/200 [01:02<04:43,  1.73s/it]
  iters:  18%|█▊        | 37/200 [01:04<04:42,  1.73s/it]
  iters:  19%|█▉        | 38/200 [01:05<04:40,  1.73s/it]
  iters:  20%|█▉        | 39/200 [01:07<04:38,  1.73s/it]
  iters:  20%|██        | 40/200 [01:09<04:36,  1.73s/it]
  iters:  20%|██        | 41/200 [01:11<04:34,  1.73s/it]
  iters:  21%|██        | 42/200 [01:12<04:32,  1.73s/it]
  iters:  22%|██▏       | 43/200 [01:14<04:31,  1.73s/it]
  iters:  22%|██▏       | 44/200 [01:16<04:29,  1.73s/it]
  iters:  22%|██▎       | 45/200 [01:18<04:28,  1.73s/it]
  iters:  23%|██▎       | 46/200 [01:19<04:26,  1.73s/it]
  iters:  24%|██▎       | 47/200 [01:21<04:24,  1.73s/it]
  iters:  24%|██▍       | 48/200 [01:23<04:23,  1.73s/it]
  iters:  24%|██▍       | 49/200 [01:24<04:19,  1.72s/it]
  iters:  25%|██▌       | 50/200 [01:26<04:17,  1.72s/it]
  iters:  26%|██▌       | 51/200 [01:28<04:16,  1.72s/it]
  iters:  26%|██▌       | 52/200 [01:30<04:14,  1.72s/it]
  iters:  26%|██▋       | 53/200 [01:31<04:13,  1.72s/it]
  iters:  27%|██▋       | 54/200 [01:33<04:11,  1.72s/it]
  iters:  28%|██▊       | 55/200 [01:35<04:10,  1.72s/it]
  iters:  28%|██▊       | 56/200 [01:37<04:08,  1.72s/it]
  iters:  28%|██▊       | 57/200 [01:38<04:06,  1.72s/it]
  iters:  29%|██▉       | 58/200 [01:40<04:04,  1.72s/it]
  iters:  30%|██▉       | 59/200 [01:42<04:02,  1.72s/it]
  iters:  30%|███       | 60/200 [01:43<04:00,  1.72s/it]
  iters:  30%|███       | 61/200 [01:45<03:59,  1.72s/it]
  iters:  31%|███       | 62/200 [01:47<03:57,  1.72s/it]
  iters:  32%|███▏      | 63/200 [01:49<03:55,  1.72s/it]
  iters:  32%|███▏      | 64/200 [01:50<03:53,  1.72s/it]
  iters:  32%|███▎      | 65/200 [01:52<03:53,  1.73s/it]
  iters:  33%|███▎      | 66/200 [01:54<03:51,  1.73s/it]
  iters:  34%|███▎      | 67/200 [01:55<03:49,  1.73s/it]
  iters:  34%|███▍      | 68/200 [01:57<03:47,  1.73s/it]
  iters:  34%|███▍      | 69/200 [01:59<03:45,  1.72s/it]
  iters:  35%|███▌      | 70/200 [02:01<03:43,  1.72s/it]
  iters:  36%|███▌      | 71/200 [02:02<03:41,  1.71s/it]
  iters:  36%|███▌      | 72/200 [02:04<03:39,  1.72s/it]
  iters:  36%|███▋      | 73/200 [02:06<03:38,  1.72s/it]
  iters:  37%|███▋      | 74/200 [02:07<03:36,  1.72s/it]
  iters:  38%|███▊      | 75/200 [02:09<03:34,  1.72s/it]
  iters:  38%|███▊      | 76/200 [02:11<03:33,  1.72s/it]
  iters:  38%|███▊      | 77/200 [02:13<03:31,  1.72s/it]
  iters:  39%|███▉      | 78/200 [02:14<03:29,  1.71s/it]
  iters:  40%|███▉      | 79/200 [02:16<03:27,  1.71s/it]
  iters:  40%|████      | 80/200 [02:18<03:25,  1.71s/it]
  iters:  40%|████      | 81/200 [02:19<03:24,  1.72s/it]
  iters:  41%|████      | 82/200 [02:21<03:22,  1.72s/it]
  iters:  42%|████▏     | 83/200 [02:23<03:21,  1.72s/it]
  iters:  42%|████▏     | 84/200 [02:25<03:19,  1.72s/it]
  iters:  42%|████▎     | 85/200 [02:26<03:17,  1.72s/it]
  iters:  43%|████▎     | 86/200 [02:28<03:16,  1.72s/it]
  iters:  44%|████▎     | 87/200 [02:30<03:14,  1.72s/it]
  iters:  44%|████▍     | 88/200 [02:32<03:12,  1.72s/it]
  iters:  44%|████▍     | 89/200 [02:33<03:11,  1.72s/it]
  iters:  45%|████▌     | 90/200 [02:35<03:09,  1.72s/it]
  iters:  46%|████▌     | 91/200 [02:37<03:07,  1.72s/it]
  iters:  46%|████▌     | 92/200 [02:38<03:06,  1.72s/it]
  iters:  46%|████▋     | 93/200 [02:40<03:04,  1.73s/it]
  iters:  47%|████▋     | 94/200 [02:42<03:02,  1.72s/it]
  iters:  48%|████▊     | 95/200 [02:44<03:01,  1.73s/it]
  iters:  48%|████▊     | 96/200 [02:45<02:58,  1.71s/it]
  iters:  48%|████▊     | 97/200 [02:47<02:56,  1.72s/it]
  iters:  49%|████▉     | 98/200 [02:49<02:55,  1.72s/it]
  iters:  50%|████▉     | 99/200 [02:50<02:52,  1.71s/it]
  iters:  50%|█████     | 100/200 [02:52<02:51,  1.71s/it]
  iters:  50%|█████     | 101/200 [02:54<02:49,  1.72s/it]
  iters:  51%|█████     | 102/200 [02:56<02:46,  1.70s/it]
  iters:  52%|█████▏    | 103/200 [02:57<02:45,  1.71s/it]
  iters:  52%|█████▏    | 104/200 [02:59<02:44,  1.72s/it]
  iters:  52%|█████▎    | 105/200 [03:01<02:42,  1.71s/it]
  iters:  53%|█████▎    | 106/200 [03:02<02:41,  1.71s/it]
  iters:  54%|█████▎    | 107/200 [03:04<02:39,  1.72s/it]
  iters:  54%|█████▍    | 108/200 [03:06<02:45,  1.80s/it]
  iters:  55%|█████▍    | 109/200 [03:08<02:41,  1.78s/it]
  iters:  55%|█████▌    | 110/200 [03:10<02:38,  1.76s/it]
  iters:  56%|█████▌    | 111/200 [03:11<02:35,  1.75s/it]
  iters:  56%|█████▌    | 112/200 [03:13<02:33,  1.74s/it]
  iters:  56%|█████▋    | 113/200 [03:15<02:31,  1.74s/it]
  iters:  57%|█████▋    | 114/200 [03:16<02:29,  1.74s/it]
  iters:  57%|█████▊    | 115/200 [03:18<02:27,  1.73s/it]
  iters:  58%|█████▊    | 116/200 [03:20<02:25,  1.73s/it]
  iters:  58%|█████▊    | 117/200 [03:22<02:23,  1.73s/it]
  iters:  59%|█████▉    | 118/200 [03:23<02:21,  1.73s/it]
  iters:  60%|█████▉    | 119/200 [03:25<02:19,  1.73s/it]
  iters:  60%|██████    | 120/200 [03:27<02:18,  1.73s/it]
  iters:  60%|██████    | 121/200 [03:29<02:16,  1.72s/it]
  iters:  61%|██████    | 122/200 [03:30<02:14,  1.72s/it]
  iters:  62%|██████▏   | 123/200 [03:32<02:12,  1.72s/it]
  iters:  62%|██████▏   | 124/200 [03:34<02:10,  1.72s/it]
  iters:  62%|██████▎   | 125/200 [03:35<02:09,  1.72s/it]
  iters:  63%|██████▎   | 126/200 [03:37<02:07,  1.72s/it]
  iters:  64%|██████▎   | 127/200 [03:39<02:06,  1.73s/it]
  iters:  64%|██████▍   | 128/200 [03:41<02:04,  1.72s/it]
  iters:  64%|██████▍   | 129/200 [03:42<02:02,  1.72s/it]
  iters:  65%|██████▌   | 130/200 [03:44<02:00,  1.72s/it]
  iters:  66%|██████▌   | 131/200 [03:46<01:58,  1.72s/it]
  iters:  66%|██████▌   | 132/200 [03:48<01:57,  1.72s/it]
  iters:  66%|██████▋   | 133/200 [03:49<01:55,  1.72s/it]
  iters:  67%|██████▋   | 134/200 [03:51<01:53,  1.72s/it]
  iters:  68%|██████▊   | 135/200 [03:53<01:51,  1.72s/it]
  iters:  68%|██████▊   | 136/200 [03:54<01:50,  1.72s/it]
  iters:  68%|██████▊   | 137/200 [03:56<01:48,  1.72s/it]
  iters:  69%|██████▉   | 138/200 [03:58<01:46,  1.72s/it]
  iters:  70%|██████▉   | 139/200 [04:00<01:45,  1.72s/it]
  iters:  70%|███████   | 140/200 [04:01<01:43,  1.72s/it]
  iters:  70%|███████   | 141/200 [04:03<01:41,  1.72s/it]
  iters:  71%|███████   | 142/200 [04:05<01:39,  1.72s/it]
  iters:  72%|███████▏  | 143/200 [04:06<01:38,  1.73s/it]
  iters:  72%|███████▏  | 144/200 [04:08<01:36,  1.72s/it]
  iters:  72%|███████▎  | 145/200 [04:10<01:35,  1.73s/it]
  iters:  73%|███████▎  | 146/200 [04:12<01:33,  1.72s/it]
  iters:  74%|███████▎  | 147/200 [04:13<01:31,  1.73s/it]
  iters:  74%|███████▍  | 148/200 [04:15<01:29,  1.72s/it]
  iters:  74%|███████▍  | 149/200 [04:17<01:27,  1.72s/it]
  iters:  75%|███████▌  | 150/200 [04:19<01:25,  1.72s/it]
  iters:  76%|███████▌  | 151/200 [04:20<01:24,  1.72s/it]
  iters:  76%|███████▌  | 152/200 [04:22<01:22,  1.72s/it]
  iters:  76%|███████▋  | 153/200 [04:24<01:21,  1.73s/it]
  iters:  77%|███████▋  | 154/200 [04:25<01:19,  1.72s/it]
  iters:  78%|███████▊  | 155/200 [04:27<01:17,  1.73s/it]
  iters:  78%|███████▊  | 156/200 [04:29<01:15,  1.72s/it]
  iters:  78%|███████▊  | 157/200 [04:31<01:14,  1.72s/it]
  iters:  79%|███████▉  | 158/200 [04:32<01:12,  1.72s/it]
  iters:  80%|███████▉  | 159/200 [04:34<01:10,  1.72s/it]
  iters:  80%|████████  | 160/200 [04:36<01:08,  1.72s/it]
  iters:  80%|████████  | 161/200 [04:37<01:07,  1.72s/it]
  iters:  81%|████████  | 162/200 [04:39<01:05,  1.72s/it]
  iters:  82%|████████▏ | 163/200 [04:41<01:03,  1.72s/it]
  iters:  82%|████████▏ | 164/200 [04:43<01:02,  1.72s/it]
  iters:  82%|████████▎ | 165/200 [04:44<01:00,  1.72s/it]
  iters:  83%|████████▎ | 166/200 [04:46<00:58,  1.72s/it]
  iters:  84%|████████▎ | 167/200 [04:48<00:56,  1.72s/it]
  iters:  84%|████████▍ | 168/200 [04:50<00:55,  1.72s/it]
  iters:  84%|████████▍ | 169/200 [04:51<00:53,  1.72s/it]
  iters:  85%|████████▌ | 170/200 [04:53<00:51,  1.72s/it]
  iters:  86%|████████▌ | 171/200 [04:55<00:49,  1.72s/it]
  iters:  86%|████████▌ | 172/200 [04:56<00:48,  1.72s/it]
  iters:  86%|████████▋ | 173/200 [04:58<00:46,  1.72s/it]
  iters:  87%|████████▋ | 174/200 [05:00<00:44,  1.72s/it]
  iters:  88%|████████▊ | 175/200 [05:02<00:43,  1.72s/it]
  iters:  88%|████████▊ | 176/200 [05:03<00:41,  1.72s/it]
  iters:  88%|████████▊ | 177/200 [05:05<00:39,  1.72s/it]
  iters:  89%|████████▉ | 178/200 [05:07<00:37,  1.72s/it]
  iters:  90%|████████▉ | 179/200 [05:08<00:36,  1.72s/it]
  iters:  90%|█████████ | 180/200 [05:10<00:34,  1.72s/it]
  iters:  90%|█████████ | 181/200 [05:12<00:32,  1.72s/it]
  iters:  91%|█████████ | 182/200 [05:14<00:31,  1.73s/it]
  iters:  92%|█████████▏| 183/200 [05:15<00:29,  1.73s/it]
  iters:  92%|█████████▏| 184/200 [05:17<00:27,  1.72s/it]
  iters:  92%|█████████▎| 185/200 [05:19<00:25,  1.72s/it]
  iters:  93%|█████████▎| 186/200 [05:21<00:24,  1.72s/it]
  iters:  94%|█████████▎| 187/200 [05:22<00:22,  1.72s/it]
  iters:  94%|█████████▍| 188/200 [05:24<00:20,  1.72s/it]
  iters:  94%|█████████▍| 189/200 [05:26<00:18,  1.72s/it]
  iters:  95%|█████████▌| 190/200 [05:27<00:17,  1.72s/it]
  iters:  96%|█████████▌| 191/200 [05:29<00:15,  1.72s/it]
  iters:  96%|█████████▌| 192/200 [05:31<00:13,  1.72s/it]
  iters:  96%|█████████▋| 193/200 [05:33<00:12,  1.72s/it]
  iters:  97%|█████████▋| 194/200 [05:34<00:10,  1.72s/it]
  iters:  98%|█████████▊| 195/200 [05:36<00:08,  1.72s/it]
  iters:  98%|█████████▊| 196/200 [05:38<00:06,  1.72s/it]
  iters:  98%|█████████▊| 197/200 [05:39<00:05,  1.72s/it]
  iters:  99%|█████████▉| 198/200 [05:41<00:03,  1.72s/it]
  iters: 100%|█████████▉| 199/200 [05:43<00:01,  1.72s/it]
  iters: 100%|██████████| 200/200 [05:45<00:00,  1.72s/it]

  [timing] data: 2.4s (1%) | forward: 84.4s (24%) | backward: 258.3s (75%) | total: 345.1s

Training:  75%|███████▌  | 3/4 [25:09<06:17, 377.39s/it, acc=0.9996, det=0.0065, edge=0.0004]

  Epoch   3/4 | edge=0.0004 | det=0.0065 | test_loss=0.0006 | acc=0.9996 | recall=0.8424 | best=0.8471   | train=345.3s test=31.7s

Training: 100%|██████████| 4/4 [25:09<00:00, 377.38s/it, acc=0.9996, det=0.0065, edge=0.0004]

Best score (acc*recall): 0.8471, saved to /kaggle/working/cellmot-baseline-artifacts/repo/weights/hp_search_tier1/split_0/edge_predictor_best.pth

[tier2_006] score=0.8471  (1516s)
0.019136512 GB allocated
0.182452224 GB reserved
Fold 0: 8 train, 2 test
Loading train (8 datasets)...

train: 100%|██████████| 8/8 [00:04<00:00,  1.87it/s]

  train done: 787 windows total
Loading test (2 datasets)...

test: 100%|██████████| 2/2 [00:00<00:00,  2.48it/s]

  test done: 164 windows total
max_nodes=17
Using device: cuda | visible CUDA GPUs: 2
  Full checkpoint loaded from /kaggle/input/datasets/thibautgoldsborough/cellmot-baseline-artifacts/cellmot-baseline-artifacts/weights/unet_transformer/split_0/edge_predictor_best.pth: 0 missing, 0 unexpected
Single-GPU training (--single-gpu set). For 2 GPUs set the Kaggle accelerator to 'GPU T4 x2'.
Model parameters: 2,076,706
Starting training for 4 epochs (batch_size=2)...

Training:   0%|          | 0/4 [00:00<?, ?it/s]

Detection loss: weight=4, neg_weight=0.01

  iters:   0%|          | 0/200 [00:00<?, ?it/s]
  iters:   0%|          | 1/200 [00:01<05:01,  1.52s/it]
  iters:   1%|          | 2/200 [00:02<04:20,  1.32s/it]
  iters:   2%|▏         | 3/200 [00:03<04:06,  1.25s/it]
  iters:   2%|▏         | 4/200 [00:05<04:00,  1.22s/it]
  iters:   2%|▎         | 5/200 [00:06<03:56,  1.21s/it]
  iters:   3%|▎         | 6/200 [00:07<03:52,  1.20s/it]
  iters:   4%|▎         | 7/200 [00:08<03:50,  1.20s/it]
  iters:   4%|▍         | 8/200 [00:09<03:48,  1.19s/it]
  iters:   4%|▍         | 9/200 [00:11<03:48,  1.20s/it]
  iters:   5%|▌         | 10/200 [00:12<03:47,  1.20s/it]
  iters:   6%|▌         | 11/200 [00:13<03:46,  1.20s/it]
  iters:   6%|▌         | 12/200 [00:14<03:45,  1.20s/it]
  iters:   6%|▋         | 13/200 [00:15<03:44,  1.20s/it]
  iters:   7%|▋         | 14/200 [00:17<03:43,  1.20s/it]
  iters:   8%|▊         | 15/200 [00:18<03:42,  1.20s/it]
  iters:   8%|▊         | 16/200 [00:19<03:41,  1.20s/it]
  iters:   8%|▊         | 17/200 [00:20<03:40,  1.21s/it]
  iters:   9%|▉         | 18/200 [00:21<03:39,  1.21s/it]
  iters:  10%|▉         | 19/200 [00:23<03:38,  1.21s/it]
  iters:  10%|█         | 20/200 [00:24<03:37,  1.21s/it]
  iters:  10%|█         | 21/200 [00:25<03:36,  1.21s/it]
  iters:  11%|█         | 22/200 [00:26<03:36,  1.21s/it]
  iters:  12%|█▏        | 23/200 [00:27<03:34,  1.21s/it]
  iters:  12%|█▏        | 24/200 [00:29<03:33,  1.21s/it]
  iters:  12%|█▎        | 25/200 [00:30<03:32,  1.21s/it]
  iters:  13%|█▎        | 26/200 [00:31<03:31,  1.22s/it]
  iters:  14%|█▎        | 27/200 [00:32<03:29,  1.21s/it]
  iters:  14%|█▍        | 28/200 [00:33<03:28,  1.21s/it]
  iters:  14%|█▍        | 29/200 [00:35<03:26,  1.21s/it]
  iters:  15%|█▌        | 30/200 [00:36<03:25,  1.21s/it]
  iters:  16%|█▌        | 31/200 [00:37<03:24,  1.21s/it]
  iters:  16%|█▌        | 32/200 [00:38<03:23,  1.21s/it]
  iters:  16%|█▋        | 33/200 [00:40<03:21,  1.21s/it]
  iters:  17%|█▋        | 34/200 [00:41<03:20,  1.21s/it]
  iters:  18%|█▊        | 35/200 [00:42<03:18,  1.21s/it]
  iters:  18%|█▊        | 36/200 [00:43<03:17,  1.20s/it]
  iters:  18%|█▊        | 37/200 [00:44<03:16,  1.20s/it]
  iters:  19%|█▉        | 38/200 [00:46<03:14,  1.20s/it]
  iters:  20%|█▉        | 39/200 [00:47<03:13,  1.20s/it]
  iters:  20%|██        | 40/200 [00:48<03:12,  1.20s/it]
  iters:  20%|██        | 41/200 [00:49<03:10,  1.20s/it]
  iters:  21%|██        | 42/200 [00:50<03:10,  1.20s/it]
  iters:  22%|██▏       | 43/200 [00:52<03:08,  1.20s/it]
  iters:  22%|██▏       | 44/200 [00:53<03:07,  1.20s/it]
  iters:  22%|██▎       | 45/200 [00:54<03:05,  1.20s/it]
  iters:  23%|██▎       | 46/200 [00:55<03:03,  1.19s/it]
  iters:  24%|██▎       | 47/200 [00:56<03:02,  1.19s/it]
  iters:  24%|██▍       | 48/200 [00:57<03:01,  1.20s/it]
  iters:  24%|██▍       | 49/200 [00:59<03:00,  1.20s/it]
  iters:  25%|██▌       | 50/200 [01:00<02:58,  1.19s/it]
  iters:  26%|██▌       | 51/200 [01:01<02:57,  1.19s/it]
  iters:  26%|██▌       | 52/200 [01:02<02:56,  1.19s/it]
  iters:  26%|██▋       | 53/200 [01:03<02:54,  1.19s/it]
  iters:  27%|██▋       | 54/200 [01:05<02:53,  1.19s/it]
  iters:  28%|██▊       | 55/200 [01:06<02:50,  1.17s/it]
  iters:  28%|██▊       | 56/200 [01:07<02:49,  1.18s/it]
  iters:  28%|██▊       | 57/200 [01:08<02:48,  1.18s/it]
  iters:  29%|██▉       | 58/200 [01:09<02:47,  1.18s/it]
  iters:  30%|██▉       | 59/200 [01:10<02:46,  1.18s/it]
  iters:  30%|███       | 60/200 [01:12<02:45,  1.18s/it]
  iters:  30%|███       | 61/200 [01:13<02:44,  1.18s/it]
  iters:  31%|███       | 62/200 [01:14<02:43,  1.18s/it]
  iters:  32%|███▏      | 63/200 [01:15<02:42,  1.18s/it]
  iters:  32%|███▏      | 64/200 [01:16<02:41,  1.19s/it]
  iters:  32%|███▎      | 65/200 [01:18<02:39,  1.18s/it]
  iters:  33%|███▎      | 66/200 [01:19<02:38,  1.18s/it]
  iters:  34%|███▎      | 67/200 [01:20<02:37,  1.18s/it]
  iters:  34%|███▍      | 68/200 [01:21<02:36,  1.18s/it]
  iters:  34%|███▍      | 69/200 [01:22<02:34,  1.18s/it]
  iters:  35%|███▌      | 70/200 [01:24<02:33,  1.18s/it]
  iters:  36%|███▌      | 71/200 [01:25<02:32,  1.18s/it]
  iters:  36%|███▌      | 72/200 [01:26<02:31,  1.19s/it]
  iters:  36%|███▋      | 73/200 [01:27<02:30,  1.19s/it]
  iters:  37%|███▋      | 74/200 [01:28<02:29,  1.19s/it]
  iters:  38%|███▊      | 75/200 [01:29<02:28,  1.19s/it]
  iters:  38%|███▊      | 76/200 [01:31<02:27,  1.19s/it]
  iters:  38%|███▊      | 77/200 [01:32<02:25,  1.19s/it]
  iters:  39%|███▉      | 78/200 [01:33<02:25,  1.19s/it]
  iters:  40%|███▉      | 79/200 [01:34<02:23,  1.19s/it]
  iters:  40%|████      | 80/200 [01:35<02:22,  1.19s/it]
  iters:  40%|████      | 81/200 [01:37<02:21,  1.19s/it]
  iters:  41%|████      | 82/200 [01:38<02:20,  1.19s/it]
  iters:  42%|████▏     | 83/200 [01:39<02:19,  1.19s/it]
  iters:  42%|████▏     | 84/200 [01:40<02:18,  1.19s/it]
  iters:  42%|████▎     | 85/200 [01:41<02:17,  1.19s/it]
  iters:  43%|████▎     | 86/200 [01:43<02:15,  1.19s/it]
  iters:  44%|████▎     | 87/200 [01:44<02:14,  1.19s/it]
  iters:  44%|████▍     | 88/200 [01:45<02:13,  1.19s/it]
  iters:  44%|████▍     | 89/200 [01:46<02:12,  1.19s/it]
  iters:  45%|████▌     | 90/200 [01:47<02:11,  1.19s/it]
  iters:  46%|████▌     | 91/200 [01:49<02:10,  1.19s/it]
  iters:  46%|████▌     | 92/200 [01:50<02:08,  1.19s/it]
  iters:  46%|████▋     | 93/200 [01:51<02:08,  1.20s/it]
  iters:  47%|████▋     | 94/200 [01:52<02:07,  1.20s/it]
  iters:  48%|████▊     | 95/200 [01:53<02:06,  1.20s/it]
  iters:  48%|████▊     | 96/200 [01:55<02:04,  1.20s/it]
  iters:  48%|████▊     | 97/200 [01:56<02:03,  1.20s/it]
  iters:  49%|████▉     | 98/200 [01:57<02:02,  1.20s/it]
  iters:  50%|████▉     | 99/200 [01:58<02:01,  1.20s/it]
  iters:  50%|█████     | 100/200 [01:59<02:00,  1.20s/it]
  iters:  50%|█████     | 101/200 [02:01<01:58,  1.20s/it]
  iters:  51%|█████     | 102/200 [02:02<01:57,  1.20s/it]
  iters:  52%|█████▏    | 103/200 [02:03<01:56,  1.20s/it]
  iters:  52%|█████▏    | 104/200 [02:04<01:55,  1.20s/it]
  iters:  52%|█████▎    | 105/200 [02:05<01:54,  1.20s/it]
  iters:  53%|█████▎    | 106/200 [02:07<01:52,  1.20s/it]
  iters:  54%|█████▎    | 107/200 [02:08<01:51,  1.20s/it]
  iters:  54%|█████▍    | 108/200 [02:09<01:50,  1.20s/it]
  iters:  55%|█████▍    | 109/200 [02:10<01:49,  1.20s/it]
  iters:  55%|█████▌    | 110/200 [02:11<01:48,  1.20s/it]
  iters:  56%|█████▌    | 111/200 [02:13<01:46,  1.20s/it]
  iters:  56%|█████▌    | 112/200 [02:14<01:44,  1.19s/it]
  iters:  56%|█████▋    | 113/200 [02:15<01:43,  1.19s/it]
  iters:  57%|█████▋    | 114/200 [02:16<01:42,  1.19s/it]
  iters:  57%|█████▊    | 115/200 [02:17<01:41,  1.20s/it]
  iters:  58%|█████▊    | 116/200 [02:19<01:40,  1.20s/it]
  iters:  58%|█████▊    | 117/200 [02:20<01:39,  1.19s/it]
  iters:  59%|█████▉    | 118/200 [02:21<01:37,  1.19s/it]
  iters:  60%|█████▉    | 119/200 [02:22<01:36,  1.20s/it]
  iters:  60%|██████    | 120/200 [02:23<01:35,  1.20s/it]
  iters:  60%|██████    | 121/200 [02:24<01:34,  1.20s/it]
  iters:  61%|██████    | 122/200 [02:26<01:33,  1.20s/it]
  iters:  62%|██████▏   | 123/200 [02:27<01:32,  1.20s/it]
  iters:  62%|██████▏   | 124/200 [02:28<01:30,  1.19s/it]
  iters:  62%|██████▎   | 125/200 [02:29<01:29,  1.19s/it]
  iters:  63%|██████▎   | 126/200 [02:30<01:28,  1.20s/it]
  iters:  64%|██████▎   | 127/200 [02:32<01:27,  1.19s/it]
  iters:  64%|██████▍   | 128/200 [02:33<01:25,  1.19s/it]
  iters:  64%|██████▍   | 129/200 [02:34<01:24,  1.19s/it]
  iters:  65%|██████▌   | 130/200 [02:35<01:23,  1.19s/it]
  iters:  66%|██████▌   | 131/200 [02:36<01:22,  1.19s/it]
  iters:  66%|██████▌   | 132/200 [02:38<01:20,  1.19s/it]
  iters:  66%|██████▋   | 133/200 [02:39<01:19,  1.19s/it]
  iters:  67%|██████▋   | 134/200 [02:40<01:18,  1.19s/it]
  iters:  68%|██████▊   | 135/200 [02:41<01:17,  1.19s/it]
  iters:  68%|██████▊   | 136/200 [02:42<01:16,  1.19s/it]
  iters:  68%|██████▊   | 137/200 [02:44<01:14,  1.19s/it]
  iters:  69%|██████▉   | 138/200 [02:45<01:13,  1.19s/it]
  iters:  70%|██████▉   | 139/200 [02:46<01:12,  1.19s/it]
  iters:  70%|███████   | 140/200 [02:47<01:11,  1.19s/it]
  iters:  70%|███████   | 141/200 [02:48<01:10,  1.19s/it]
  iters:  71%|███████   | 142/200 [02:49<01:08,  1.19s/it]
  iters:  72%|███████▏  | 143/200 [02:51<01:07,  1.19s/it]
  iters:  72%|███████▏  | 144/200 [02:52<01:06,  1.19s/it]
  iters:  72%|███████▎  | 145/200 [02:53<01:05,  1.19s/it]
  iters:  73%|███████▎  | 146/200 [02:54<01:04,  1.19s/it]
  iters:  74%|███████▎  | 147/200 [02:55<01:03,  1.19s/it]
  iters:  74%|███████▍  | 148/200 [02:57<01:01,  1.19s/it]
  iters:  74%|███████▍  | 149/200 [02:58<01:00,  1.19s/it]
  iters:  75%|███████▌  | 150/200 [02:59<00:59,  1.19s/it]
  iters:  76%|███████▌  | 151/200 [03:00<00:58,  1.19s/it]
  iters:  76%|███████▌  | 152/200 [03:01<00:57,  1.19s/it]
  iters:  76%|███████▋  | 153/200 [03:03<00:55,  1.19s/it]
  iters:  77%|███████▋  | 154/200 [03:04<00:54,  1.19s/it]
  iters:  78%|███████▊  | 155/200 [03:05<00:53,  1.19s/it]
  iters:  78%|███████▊  | 156/200 [03:06<00:52,  1.19s/it]
  iters:  78%|███████▊  | 157/200 [03:07<00:51,  1.19s/it]
  iters:  79%|███████▉  | 158/200 [03:09<00:50,  1.19s/it]
  iters:  80%|███████▉  | 159/200 [03:10<00:48,  1.19s/it]
  iters:  80%|████████  | 160/200 [03:11<00:47,  1.19s/it]
  iters:  80%|████████  | 161/200 [03:12<00:46,  1.19s/it]
  iters:  81%|████████  | 162/200 [03:13<00:45,  1.19s/it]
  iters:  82%|████████▏ | 163/200 [03:14<00:43,  1.19s/it]
  iters:  82%|████████▏ | 164/200 [03:16<00:42,  1.19s/it]
  iters:  82%|████████▎ | 165/200 [03:17<00:41,  1.19s/it]
  iters:  83%|████████▎ | 166/200 [03:18<00:40,  1.19s/it]
  iters:  84%|████████▎ | 167/200 [03:19<00:39,  1.19s/it]
  iters:  84%|████████▍ | 168/200 [03:20<00:38,  1.19s/it]
  iters:  84%|████████▍ | 169/200 [03:22<00:36,  1.19s/it]
  iters:  85%|████████▌ | 170/200 [03:23<00:35,  1.19s/it]
  iters:  86%|████████▌ | 171/200 [03:24<00:34,  1.19s/it]
  iters:  86%|████████▌ | 172/200 [03:25<00:33,  1.19s/it]
  iters:  86%|████████▋ | 173/200 [03:26<00:32,  1.19s/it]
  iters:  87%|████████▋ | 174/200 [03:28<00:30,  1.19s/it]
  iters:  88%|████████▊ | 175/200 [03:29<00:29,  1.19s/it]
  iters:  88%|████████▊ | 176/200 [03:30<00:28,  1.19s/it]
  iters:  88%|████████▊ | 177/200 [03:31<00:27,  1.19s/it]
  iters:  89%|████████▉ | 178/200 [03:32<00:26,  1.19s/it]
  iters:  90%|████████▉ | 179/200 [03:33<00:24,  1.19s/it]
  iters:  90%|█████████ | 180/200 [03:35<00:23,  1.19s/it]
  iters:  90%|█████████ | 181/200 [03:36<00:22,  1.19s/it]
  iters:  91%|█████████ | 182/200 [03:37<00:21,  1.19s/it]
  iters:  92%|█████████▏| 183/200 [03:38<00:20,  1.19s/it]
  iters:  92%|█████████▏| 184/200 [03:39<00:19,  1.19s/it]
  iters:  92%|█████████▎| 185/200 [03:41<00:17,  1.20s/it]
  iters:  93%|█████████▎| 186/200 [03:42<00:16,  1.19s/it]
  iters:  94%|█████████▎| 187/200 [03:43<00:15,  1.19s/it]
  iters:  94%|█████████▍| 188/200 [03:44<00:14,  1.19s/it]
  iters:  94%|█████████▍| 189/200 [03:45<00:13,  1.19s/it]
  iters:  95%|█████████▌| 190/200 [03:47<00:11,  1.19s/it]
  iters:  96%|█████████▌| 191/200 [03:48<00:10,  1.19s/it]
  iters:  96%|█████████▌| 192/200 [03:49<00:09,  1.19s/it]
  iters:  96%|█████████▋| 193/200 [03:50<00:08,  1.19s/it]
  iters:  97%|█████████▋| 194/200 [03:51<00:07,  1.19s/it]
  iters:  98%|█████████▊| 195/200 [03:53<00:05,  1.19s/it]
  iters:  98%|█████████▊| 196/200 [03:54<00:04,  1.20s/it]
  iters:  98%|█████████▊| 197/200 [03:55<00:03,  1.20s/it]
  iters:  99%|█████████▉| 198/200 [03:56<00:02,  1.18s/it]
  iters: 100%|█████████▉| 199/200 [03:57<00:01,  1.19s/it]
  iters: 100%|██████████| 200/200 [03:59<00:00,  1.19s/it]

  [timing] data: 2.2s (1%) | forward: 57.5s (24%) | backward: 179.3s (75%) | total: 239.0s

Training:   0%|          | 0/4 [04:21<?, ?it/s, acc=0.9995, det=0.0087, edge=0.0004]

  Epoch   0/4 | edge=0.0004 | det=0.0087 | test_loss=0.0006 | acc=0.9995 | recall=0.8297 | best=0.8293 * | train=239.3s test=22.6s

Training:  25%|██▌       | 1/4 [04:21<13:05, 261.86s/it, acc=0.9995, det=0.0087, edge=0.0004]
  iters:   0%|          | 0/200 [00:00<?, ?it/s]
  iters:   0%|          | 1/200 [00:01<04:22,  1.32s/it]
  iters:   1%|          | 2/200 [00:02<04:07,  1.25s/it]
  iters:   2%|▏         | 3/200 [00:03<04:01,  1.22s/it]
  iters:   2%|▏         | 4/200 [00:04<03:57,  1.21s/it]
  iters:   2%|▎         | 5/200 [00:06<03:55,  1.21s/it]
  iters:   3%|▎         | 6/200 [00:07<03:53,  1.20s/it]
  iters:   4%|▎         | 7/200 [00:08<03:50,  1.19s/it]
  iters:   4%|▍         | 8/200 [00:09<03:49,  1.19s/it]
  iters:   4%|▍         | 9/200 [00:10<03:47,  1.19s/it]
  iters:   5%|▌         | 10/200 [00:12<03:46,  1.19s/it]
  iters:   6%|▌         | 11/200 [00:13<03:45,  1.20s/it]
  iters:   6%|▌         | 12/200 [00:14<03:44,  1.19s/it]
  iters:   6%|▋         | 13/200 [00:15<03:42,  1.19s/it]
  iters:   7%|▋         | 14/200 [00:16<03:41,  1.19s/it]
  iters:   8%|▊         | 15/200 [00:18<03:40,  1.19s/it]
  iters:   8%|▊         | 16/200 [00:19<03:39,  1.19s/it]
  iters:   8%|▊         | 17/200 [00:20<03:37,  1.19s/it]
  iters:   9%|▉         | 18/200 [00:21<03:36,  1.19s/it]
  iters:  10%|▉         | 19/200 [00:22<03:35,  1.19s/it]
  iters:  10%|█         | 20/200 [00:23<03:34,  1.19s/it]
  iters:  10%|█         | 21/200 [00:25<03:33,  1.19s/it]
  iters:  11%|█         | 22/200 [00:26<03:32,  1.19s/it]
  iters:  12%|█▏        | 23/200 [00:27<03:31,  1.19s/it]
  iters:  12%|█▏        | 24/200 [00:28<03:29,  1.19s/it]
  iters:  12%|█▎        | 25/200 [00:29<03:28,  1.19s/it]
  iters:  13%|█▎        | 26/200 [00:31<03:27,  1.19s/it]
  iters:  14%|█▎        | 27/200 [00:32<03:26,  1.19s/it]
  iters:  14%|█▍        | 28/200 [00:33<03:25,  1.19s/it]
  iters:  14%|█▍        | 29/200 [00:34<03:23,  1.19s/it]
  iters:  15%|█▌        | 30/200 [00:35<03:22,  1.19s/it]
  iters:  16%|█▌        | 31/200 [00:37<03:21,  1.19s/it]
  iters:  16%|█▌        | 32/200 [00:38<03:19,  1.19s/it]
  iters:  16%|█▋        | 33/200 [00:39<03:18,  1.19s/it]
  iters:  17%|█▋        | 34/200 [00:40<03:17,  1.19s/it]
  iters:  18%|█▊        | 35/200 [00:41<03:16,  1.19s/it]
  iters:  18%|█▊        | 36/200 [00:43<03:15,  1.19s/it]
  iters:  18%|█▊        | 37/200 [00:44<03:13,  1.19s/it]
  iters:  19%|█▉        | 38/200 [00:45<03:12,  1.19s/it]
  iters:  20%|█▉        | 39/200 [00:46<03:11,  1.19s/it]
  iters:  20%|██        | 40/200 [00:47<03:10,  1.19s/it]
  iters:  20%|██        | 41/200 [00:48<03:09,  1.19s/it]
  iters:  21%|██        | 42/200 [00:50<03:08,  1.19s/it]
  iters:  22%|██▏       | 43/200 [00:51<03:18,  1.27s/it]
  iters:  22%|██▏       | 44/200 [00:52<03:13,  1.24s/it]
  iters:  22%|██▎       | 45/200 [00:54<03:10,  1.23s/it]
  iters:  23%|██▎       | 46/200 [00:55<03:07,  1.22s/it]
  iters:  24%|██▎       | 47/200 [00:56<03:05,  1.21s/it]
  iters:  24%|██▍       | 48/200 [00:57<03:03,  1.20s/it]
  iters:  24%|██▍       | 49/200 [00:58<03:01,  1.20s/it]
  iters:  25%|██▌       | 50/200 [00:59<02:59,  1.20s/it]
  iters:  26%|██▌       | 51/200 [01:01<02:58,  1.20s/it]
  iters:  26%|██▌       | 52/200 [01:02<02:57,  1.20s/it]
  iters:  26%|██▋       | 53/200 [01:03<02:56,  1.20s/it]
  iters:  27%|██▋       | 54/200 [01:04<02:54,  1.20s/it]
  iters:  28%|██▊       | 55/200 [01:05<02:53,  1.20s/it]
  iters:  28%|██▊       | 56/200 [01:07<02:52,  1.20s/it]
  iters:  28%|██▊       | 57/200 [01:08<02:50,  1.19s/it]
  iters:  29%|██▉       | 58/200 [01:09<02:49,  1.19s/it]
  iters:  30%|██▉       | 59/200 [01:10<02:48,  1.19s/it]
  iters:  30%|███       | 60/200 [01:11<02:46,  1.19s/it]
  iters:  30%|███       | 61/200 [01:13<02:45,  1.19s/it]
  iters:  31%|███       | 62/200 [01:14<02:44,  1.19s/it]
  iters:  32%|███▏      | 63/200 [01:15<02:43,  1.19s/it]
  iters:  32%|███▏      | 64/200 [01:16<02:42,  1.19s/it]
  iters:  32%|███▎      | 65/200 [01:17<02:38,  1.18s/it]
  iters:  33%|███▎      | 66/200 [01:19<02:38,  1.18s/it]
  iters:  34%|███▎      | 67/200 [01:20<02:37,  1.18s/it]
  iters:  34%|███▍      | 68/200 [01:21<02:36,  1.19s/it]
  iters:  34%|███▍      | 69/200 [01:22<02:35,  1.19s/it]
  iters:  35%|███▌      | 70/200 [01:23<02:32,  1.17s/it]
  iters:  36%|███▌      | 71/200 [01:24<02:32,  1.18s/it]
  iters:  36%|███▌      | 72/200 [01:26<02:31,  1.18s/it]
  iters:  36%|███▋      | 73/200 [01:27<02:30,  1.19s/it]
  iters:  37%|███▋      | 74/200 [01:28<02:29,  1.19s/it]
  iters:  38%|███▊      | 75/200 [01:29<02:28,  1.19s/it]
  iters:  38%|███▊      | 76/200 [01:30<02:27,  1.19s/it]
  iters:  38%|███▊      | 77/200 [01:32<02:26,  1.19s/it]
  iters:  39%|███▉      | 78/200 [01:33<02:25,  1.19s/it]
  iters:  40%|███▉      | 79/200 [01:34<02:24,  1.20s/it]
  iters:  40%|████      | 80/200 [01:35<02:23,  1.20s/it]
  iters:  40%|████      | 81/200 [01:36<02:22,  1.20s/it]
  iters:  41%|████      | 82/200 [01:38<02:21,  1.20s/it]
  iters:  42%|████▏     | 83/200 [01:39<02:19,  1.20s/it]
  iters:  42%|████▏     | 84/200 [01:40<02:18,  1.20s/it]
  iters:  42%|████▎     | 85/200 [01:41<02:17,  1.19s/it]
  iters:  43%|████▎     | 86/200 [01:42<02:16,  1.20s/it]
  iters:  44%|████▎     | 87/200 [01:44<02:15,  1.20s/it]
  iters:  44%|████▍     | 88/200 [01:45<02:13,  1.20s/it]
  iters:  44%|████▍     | 89/200 [01:46<02:12,  1.20s/it]
  iters:  45%|████▌     | 90/200 [01:47<02:11,  1.19s/it]
  iters:  46%|████▌     | 91/200 [01:48<02:10,  1.19s/it]
  iters:  46%|████▌     | 92/200 [01:50<02:08,  1.19s/it]
  iters:  46%|████▋     | 93/200 [01:51<02:07,  1.19s/it]
  iters:  47%|████▋     | 94/200 [01:52<02:06,  1.20s/it]
  iters:  48%|████▊     | 95/200 [01:53<02:05,  1.20s/it]
  iters:  48%|████▊     | 96/200 [01:54<02:04,  1.20s/it]
  iters:  48%|████▊     | 97/200 [01:55<02:03,  1.20s/it]
  iters:  49%|████▉     | 98/200 [01:57<02:01,  1.20s/it]
  iters:  50%|████▉     | 99/200 [01:58<02:00,  1.20s/it]
  iters:  50%|█████     | 100/200 [01:59<01:59,  1.20s/it]
  iters:  50%|█████     | 101/200 [02:00<01:58,  1.20s/it]
  iters:  51%|█████     | 102/200 [02:01<01:57,  1.20s/it]
  iters:  52%|█████▏    | 103/200 [02:03<01:56,  1.20s/it]
  iters:  52%|█████▏    | 104/200 [02:04<01:54,  1.20s/it]
  iters:  52%|█████▎    | 105/200 [02:05<01:53,  1.20s/it]
  iters:  53%|█████▎    | 106/200 [02:06<01:52,  1.20s/it]
  iters:  54%|█████▎    | 107/200 [02:07<01:51,  1.20s/it]
  iters:  54%|█████▍    | 108/200 [02:09<01:50,  1.20s/it]
  iters:  55%|█████▍    | 109/200 [02:10<01:48,  1.20s/it]
  iters:  55%|█████▌    | 110/200 [02:11<01:47,  1.19s/it]
  iters:  56%|█████▌    | 111/200 [02:12<01:46,  1.19s/it]
  iters:  56%|█████▌    | 112/200 [02:13<01:45,  1.20s/it]
  iters:  56%|█████▋    | 113/200 [02:15<01:44,  1.20s/it]
  iters:  57%|█████▋    | 114/200 [02:16<01:42,  1.20s/it]
  iters:  57%|█████▊    | 115/200 [02:17<01:41,  1.20s/it]
  iters:  58%|█████▊    | 116/200 [02:18<01:40,  1.20s/it]
  iters:  58%|█████▊    | 117/200 [02:19<01:39,  1.20s/it]
  iters:  59%|█████▉    | 118/200 [02:21<01:37,  1.19s/it]
  iters:  60%|█████▉    | 119/200 [02:22<01:36,  1.19s/it]
  iters:  60%|██████    | 120/200 [02:23<01:35,  1.19s/it]
  iters:  60%|██████    | 121/200 [02:24<01:34,  1.19s/it]
  iters:  61%|██████    | 122/200 [02:25<01:32,  1.19s/it]
  iters:  62%|██████▏   | 123/200 [02:27<01:31,  1.19s/it]
  iters:  62%|██████▏   | 124/200 [02:28<01:30,  1.19s/it]
  iters:  62%|██████▎   | 125/200 [02:29<01:29,  1.19s/it]
  iters:  63%|██████▎   | 126/200 [02:30<01:28,  1.19s/it]
  iters:  64%|██████▎   | 127/200 [02:31<01:26,  1.19s/it]
  iters:  64%|██████▍   | 128/200 [02:33<01:25,  1.19s/it]
  iters:  64%|██████▍   | 129/200 [02:34<01:24,  1.19s/it]
  iters:  65%|██████▌   | 130/200 [02:35<01:23,  1.19s/it]
  iters:  66%|██████▌   | 131/200 [02:36<01:22,  1.19s/it]
  iters:  66%|██████▌   | 132/200 [02:37<01:21,  1.19s/it]
  iters:  66%|██████▋   | 133/200 [02:38<01:19,  1.19s/it]
  iters:  67%|██████▋   | 134/200 [02:40<01:18,  1.19s/it]
  iters:  68%|██████▊   | 135/200 [02:41<01:17,  1.19s/it]
  iters:  68%|██████▊   | 136/200 [02:42<01:16,  1.19s/it]
  iters:  68%|██████▊   | 137/200 [02:43<01:15,  1.19s/it]
  iters:  69%|██████▉   | 138/200 [02:44<01:14,  1.20s/it]
  iters:  70%|██████▉   | 139/200 [02:46<01:12,  1.19s/it]
  iters:  70%|███████   | 140/200 [02:47<01:11,  1.19s/it]
  iters:  70%|███████   | 141/200 [02:48<01:10,  1.19s/it]
  iters:  71%|███████   | 142/200 [02:49<01:09,  1.19s/it]
  iters:  72%|███████▏  | 143/200 [02:50<01:07,  1.19s/it]
  iters:  72%|███████▏  | 144/200 [02:52<01:06,  1.19s/it]
  iters:  72%|███████▎  | 145/200 [02:53<01:05,  1.19s/it]
  iters:  73%|███████▎  | 146/200 [02:54<01:04,  1.19s/it]
  iters:  74%|███████▎  | 147/200 [02:55<01:03,  1.19s/it]
  iters:  74%|███████▍  | 148/200 [02:56<01:01,  1.19s/it]
  iters:  74%|███████▍  | 149/200 [02:58<01:00,  1.19s/it]
  iters:  75%|███████▌  | 150/200 [02:59<00:59,  1.19s/it]
  iters:  76%|███████▌  | 151/200 [03:00<00:58,  1.19s/it]
  iters:  76%|███████▌  | 152/200 [03:01<00:57,  1.19s/it]
  iters:  76%|███████▋  | 153/200 [03:02<00:55,  1.19s/it]
  iters:  77%|███████▋  | 154/200 [03:03<00:54,  1.19s/it]
  iters:  78%|███████▊  | 155/200 [03:05<00:53,  1.19s/it]
  iters:  78%|███████▊  | 156/200 [03:06<00:52,  1.19s/it]
  iters:  78%|███████▊  | 157/200 [03:07<00:51,  1.19s/it]
  iters:  79%|███████▉  | 158/200 [03:08<00:50,  1.19s/it]
  iters:  80%|███████▉  | 159/200 [03:09<00:48,  1.19s/it]
  iters:  80%|████████  | 160/200 [03:11<00:47,  1.19s/it]
  iters:  80%|████████  | 161/200 [03:12<00:46,  1.19s/it]
  iters:  81%|████████  | 162/200 [03:13<00:45,  1.19s/it]
  iters:  82%|████████▏ | 163/200 [03:14<00:44,  1.19s/it]
  iters:  82%|████████▏ | 164/200 [03:15<00:43,  1.19s/it]
  iters:  82%|████████▎ | 165/200 [03:17<00:41,  1.19s/it]
  iters:  83%|████████▎ | 166/200 [03:18<00:40,  1.20s/it]
  iters:  84%|████████▎ | 167/200 [03:19<00:39,  1.19s/it]
  iters:  84%|████████▍ | 168/200 [03:20<00:38,  1.19s/it]
  iters:  84%|████████▍ | 169/200 [03:21<00:37,  1.19s/it]
  iters:  85%|████████▌ | 170/200 [03:23<00:35,  1.19s/it]
  iters:  86%|████████▌ | 171/200 [03:24<00:34,  1.19s/it]
  iters:  86%|████████▌ | 172/200 [03:25<00:33,  1.20s/it]
  iters:  86%|████████▋ | 173/200 [03:26<00:32,  1.20s/it]
  iters:  87%|████████▋ | 174/200 [03:27<00:31,  1.20s/it]
  iters:  88%|████████▊ | 175/200 [03:29<00:30,  1.20s/it]
  iters:  88%|████████▊ | 176/200 [03:30<00:28,  1.20s/it]
  iters:  88%|████████▊ | 177/200 [03:31<00:27,  1.20s/it]
  iters:  89%|████████▉ | 178/200 [03:32<00:26,  1.19s/it]
  iters:  90%|████████▉ | 179/200 [03:33<00:25,  1.20s/it]
  iters:  90%|█████████ | 180/200 [03:35<00:23,  1.19s/it]
  iters:  90%|█████████ | 181/200 [03:36<00:22,  1.19s/it]
  iters:  91%|█████████ | 182/200 [03:37<00:21,  1.19s/it]
  iters:  92%|█████████▏| 183/200 [03:38<00:20,  1.19s/it]
  iters:  92%|█████████▏| 184/200 [03:39<00:19,  1.19s/it]
  iters:  92%|█████████▎| 185/200 [03:41<00:17,  1.19s/it]
  iters:  93%|█████████▎| 186/200 [03:42<00:16,  1.19s/it]
  iters:  94%|█████████▎| 187/200 [03:43<00:15,  1.19s/it]
  iters:  94%|█████████▍| 188/200 [03:44<00:14,  1.20s/it]
  iters:  94%|█████████▍| 189/200 [03:45<00:13,  1.20s/it]
  iters:  95%|█████████▌| 190/200 [03:46<00:11,  1.20s/it]
  iters:  96%|█████████▌| 191/200 [03:48<00:10,  1.20s/it]
  iters:  96%|█████████▌| 192/200 [03:49<00:09,  1.20s/it]
  iters:  96%|█████████▋| 193/200 [03:50<00:08,  1.20s/it]
  iters:  97%|█████████▋| 194/200 [03:51<00:07,  1.20s/it]
  iters:  98%|█████████▊| 195/200 [03:52<00:05,  1.20s/it]
  iters:  98%|█████████▊| 196/200 [03:54<00:04,  1.19s/it]
  iters:  98%|█████████▊| 197/200 [03:55<00:03,  1.19s/it]
  iters:  99%|█████████▉| 198/200 [03:56<00:02,  1.19s/it]
  iters: 100%|█████████▉| 199/200 [03:57<00:01,  1.20s/it]
  iters: 100%|██████████| 200/200 [03:58<00:00,  1.19s/it]

  [timing] data: 2.1s (1%) | forward: 57.6s (24%) | backward: 179.2s (75%) | total: 238.9s

Training:  25%|██▌       | 1/4 [08:43<13:05, 261.86s/it, acc=0.9996, det=0.0077, edge=0.0004]

  Epoch   1/4 | edge=0.0004 | det=0.0077 | test_loss=0.0005 | acc=0.9996 | recall=0.8085 | best=0.8293   | train=239.1s test=22.3s

Training:  50%|█████     | 2/4 [08:43<08:43, 261.62s/it, acc=0.9996, det=0.0077, edge=0.0004]
  iters:   0%|          | 0/200 [00:00<?, ?it/s]
  iters:   0%|          | 1/200 [00:01<04:40,  1.41s/it]
  iters:   1%|          | 2/200 [00:02<04:15,  1.29s/it]
  iters:   2%|▏         | 3/200 [00:03<04:04,  1.24s/it]
  iters:   2%|▏         | 4/200 [00:04<03:59,  1.22s/it]
  iters:   2%|▎         | 5/200 [00:06<03:53,  1.20s/it]
  iters:   3%|▎         | 6/200 [00:07<03:52,  1.20s/it]
  iters:   4%|▎         | 7/200 [00:08<03:50,  1.20s/it]
  iters:   4%|▍         | 8/200 [00:09<03:49,  1.19s/it]
  iters:   4%|▍         | 9/200 [00:10<03:48,  1.19s/it]
  iters:   5%|▌         | 10/200 [00:12<03:46,  1.19s/it]
  iters:   6%|▌         | 11/200 [00:13<03:45,  1.19s/it]
  iters:   6%|▌         | 12/200 [00:14<03:41,  1.18s/it]
  iters:   6%|▋         | 13/200 [00:15<03:41,  1.18s/it]
  iters:   7%|▋         | 14/200 [00:16<03:41,  1.19s/it]
  iters:   8%|▊         | 15/200 [00:18<03:40,  1.19s/it]
  iters:   8%|▊         | 16/200 [00:19<03:39,  1.19s/it]
  iters:   8%|▊         | 17/200 [00:20<03:38,  1.19s/it]
  iters:   9%|▉         | 18/200 [00:21<03:37,  1.19s/it]
  iters:  10%|▉         | 19/200 [00:22<03:35,  1.19s/it]
  iters:  10%|█         | 20/200 [00:24<03:34,  1.19s/it]
  iters:  10%|█         | 21/200 [00:25<03:34,  1.20s/it]
  iters:  11%|█         | 22/200 [00:26<03:32,  1.20s/it]
  iters:  12%|█▏        | 23/200 [00:27<03:32,  1.20s/it]
  iters:  12%|█▏        | 24/200 [00:28<03:30,  1.20s/it]
  iters:  12%|█▎        | 25/200 [00:30<03:29,  1.20s/it]
  iters:  13%|█▎        | 26/200 [00:31<03:27,  1.19s/it]
  iters:  14%|█▎        | 27/200 [00:32<03:26,  1.20s/it]
  iters:  14%|█▍        | 28/200 [00:33<03:25,  1.19s/it]
  iters:  14%|█▍        | 29/200 [00:34<03:24,  1.19s/it]
  iters:  15%|█▌        | 30/200 [00:35<03:22,  1.19s/it]
  iters:  16%|█▌        | 31/200 [00:37<03:21,  1.19s/it]
  iters:  16%|█▌        | 32/200 [00:38<03:20,  1.19s/it]
  iters:  16%|█▋        | 33/200 [00:39<03:19,  1.19s/it]
  iters:  17%|█▋        | 34/200 [00:40<03:17,  1.19s/it]
  iters:  18%|█▊        | 35/200 [00:41<03:16,  1.19s/it]
  iters:  18%|█▊        | 36/200 [00:43<03:15,  1.19s/it]
  iters:  18%|█▊        | 37/200 [00:44<03:14,  1.19s/it]
  iters:  19%|█▉        | 38/200 [00:45<03:13,  1.19s/it]
  iters:  20%|█▉        | 39/200 [00:46<03:11,  1.19s/it]
  iters:  20%|██        | 40/200 [00:47<03:10,  1.19s/it]
  iters:  20%|██        | 41/200 [00:49<03:09,  1.19s/it]
  iters:  21%|██        | 42/200 [00:50<03:08,  1.19s/it]
  iters:  22%|██▏       | 43/200 [00:51<03:07,  1.19s/it]
  iters:  22%|██▏       | 44/200 [00:52<03:06,  1.19s/it]
  iters:  22%|██▎       | 45/200 [00:53<03:04,  1.19s/it]
  iters:  23%|██▎       | 46/200 [00:55<03:03,  1.19s/it]
  iters:  24%|██▎       | 47/200 [00:56<03:01,  1.19s/it]
  iters:  24%|██▍       | 48/200 [00:57<03:00,  1.19s/it]
  iters:  24%|██▍       | 49/200 [00:58<02:59,  1.19s/it]
  iters:  25%|██▌       | 50/200 [00:59<02:58,  1.19s/it]
  iters:  26%|██▌       | 51/200 [01:00<02:57,  1.19s/it]
  iters:  26%|██▌       | 52/200 [01:02<02:56,  1.19s/it]
  iters:  26%|██▋       | 53/200 [01:03<02:55,  1.19s/it]
  iters:  27%|██▋       | 54/200 [01:04<02:53,  1.19s/it]
  iters:  28%|██▊       | 55/200 [01:05<02:52,  1.19s/it]
  iters:  28%|██▊       | 56/200 [01:06<02:51,  1.19s/it]
  iters:  28%|██▊       | 57/200 [01:08<02:50,  1.19s/it]
  iters:  29%|██▉       | 58/200 [01:09<02:48,  1.19s/it]
  iters:  30%|██▉       | 59/200 [01:10<02:47,  1.19s/it]
  iters:  30%|███       | 60/200 [01:11<02:47,  1.19s/it]
  iters:  30%|███       | 61/200 [01:12<02:45,  1.19s/it]
  iters:  31%|███       | 62/200 [01:14<02:44,  1.19s/it]
  iters:  32%|███▏      | 63/200 [01:15<02:43,  1.19s/it]
  iters:  32%|███▏      | 64/200 [01:16<02:42,  1.19s/it]
  iters:  32%|███▎      | 65/200 [01:17<02:41,  1.20s/it]
  iters:  33%|███▎      | 66/200 [01:18<02:40,  1.20s/it]
  iters:  34%|███▎      | 67/200 [01:20<02:38,  1.19s/it]
  iters:  34%|███▍      | 68/200 [01:21<02:37,  1.19s/it]
  iters:  34%|███▍      | 69/200 [01:22<02:36,  1.19s/it]
  iters:  35%|███▌      | 70/200 [01:23<02:39,  1.23s/it]
  iters:  36%|███▌      | 71/200 [01:24<02:36,  1.21s/it]
  iters:  36%|███▌      | 72/200 [01:26<02:34,  1.21s/it]
  iters:  36%|███▋      | 73/200 [01:27<02:32,  1.20s/it]
  iters:  37%|███▋      | 74/200 [01:28<02:31,  1.20s/it]
  iters:  38%|███▊      | 75/200 [01:29<02:29,  1.20s/it]
  iters:  38%|███▊      | 76/200 [01:30<02:28,  1.20s/it]
  iters:  38%|███▊      | 77/200 [01:32<02:26,  1.19s/it]
  iters:  39%|███▉      | 78/200 [01:33<02:25,  1.19s/it]
  iters:  40%|███▉      | 79/200 [01:34<02:24,  1.19s/it]
  iters:  40%|████      | 80/200 [01:35<02:23,  1.19s/it]
  iters:  40%|████      | 81/200 [01:36<02:22,  1.19s/it]
  iters:  41%|████      | 82/200 [01:38<02:20,  1.19s/it]
  iters:  42%|████▏     | 83/200 [01:39<02:19,  1.19s/it]
  iters:  42%|████▏     | 84/200 [01:40<02:18,  1.19s/it]
  iters:  42%|████▎     | 85/200 [01:41<02:17,  1.19s/it]
  iters:  43%|████▎     | 86/200 [01:42<02:15,  1.19s/it]
  iters:  44%|████▎     | 87/200 [01:44<02:14,  1.19s/it]
  iters:  44%|████▍     | 88/200 [01:45<02:13,  1.19s/it]
  iters:  44%|████▍     | 89/200 [01:46<02:12,  1.19s/it]
  iters:  45%|████▌     | 90/200 [01:47<02:11,  1.20s/it]
  iters:  46%|████▌     | 91/200 [01:48<02:10,  1.20s/it]
  iters:  46%|████▌     | 92/200 [01:50<02:09,  1.19s/it]
  iters:  46%|████▋     | 93/200 [01:51<02:07,  1.19s/it]
  iters:  47%|████▋     | 94/200 [01:52<02:06,  1.20s/it]
  iters:  48%|████▊     | 95/200 [01:53<02:05,  1.20s/it]
  iters:  48%|████▊     | 96/200 [01:54<02:04,  1.20s/it]
  iters:  48%|████▊     | 97/200 [01:55<02:03,  1.20s/it]
  iters:  49%|████▉     | 98/200 [01:57<02:01,  1.20s/it]
  iters:  50%|████▉     | 99/200 [01:58<02:00,  1.19s/it]
  iters:  50%|█████     | 100/200 [01:59<01:59,  1.19s/it]
  iters:  50%|█████     | 101/200 [02:00<01:58,  1.19s/it]
  iters:  51%|█████     | 102/200 [02:01<01:56,  1.19s/it]
  iters:  52%|█████▏    | 103/200 [02:03<01:55,  1.19s/it]
  iters:  52%|█████▏    | 104/200 [02:04<01:54,  1.19s/it]
  iters:  52%|█████▎    | 105/200 [02:05<01:53,  1.19s/it]
  iters:  53%|█████▎    | 106/200 [02:06<01:52,  1.19s/it]
  iters:  54%|█████▎    | 107/200 [02:07<01:51,  1.20s/it]
  iters:  54%|█████▍    | 108/200 [02:09<01:49,  1.19s/it]
  iters:  55%|█████▍    | 109/200 [02:10<01:48,  1.19s/it]
  iters:  55%|█████▌    | 110/200 [02:11<01:47,  1.19s/it]
  iters:  56%|█████▌    | 111/200 [02:12<01:46,  1.19s/it]
  iters:  56%|█████▌    | 112/200 [02:13<01:44,  1.19s/it]
  iters:  56%|█████▋    | 113/200 [02:15<01:43,  1.19s/it]
  iters:  57%|█████▋    | 114/200 [02:16<01:43,  1.20s/it]
  iters:  57%|█████▊    | 115/200 [02:17<01:41,  1.20s/it]
  iters:  58%|█████▊    | 116/200 [02:18<01:40,  1.20s/it]
  iters:  58%|█████▊    | 117/200 [02:19<01:39,  1.20s/it]
  iters:  59%|█████▉    | 118/200 [02:21<01:38,  1.20s/it]
  iters:  60%|█████▉    | 119/200 [02:22<01:36,  1.20s/it]
  iters:  60%|██████    | 120/200 [02:23<01:35,  1.20s/it]
  iters:  60%|██████    | 121/200 [02:24<01:34,  1.20s/it]
  iters:  61%|██████    | 122/200 [02:25<01:33,  1.20s/it]
  iters:  62%|██████▏   | 123/200 [02:27<01:32,  1.20s/it]
  iters:  62%|██████▏   | 124/200 [02:28<01:31,  1.20s/it]
  iters:  62%|██████▎   | 125/200 [02:29<01:29,  1.20s/it]
  iters:  63%|██████▎   | 126/200 [02:30<01:28,  1.20s/it]
  iters:  64%|██████▎   | 127/200 [02:31<01:27,  1.20s/it]
  iters:  64%|██████▍   | 128/200 [02:33<01:26,  1.20s/it]
  iters:  64%|██████▍   | 129/200 [02:34<01:23,  1.18s/it]
  iters:  65%|██████▌   | 130/200 [02:35<01:23,  1.19s/it]
  iters:  66%|██████▌   | 131/200 [02:36<01:22,  1.19s/it]
  iters:  66%|██████▌   | 132/200 [02:37<01:21,  1.19s/it]
  iters:  66%|██████▋   | 133/200 [02:38<01:19,  1.19s/it]
  iters:  67%|██████▋   | 134/200 [02:40<01:18,  1.19s/it]
  iters:  68%|██████▊   | 135/200 [02:41<01:17,  1.19s/it]
  iters:  68%|██████▊   | 136/200 [02:42<01:16,  1.19s/it]
  iters:  68%|██████▊   | 137/200 [02:43<01:15,  1.19s/it]
  iters:  69%|██████▉   | 138/200 [02:44<01:13,  1.19s/it]
  iters:  70%|██████▉   | 139/200 [02:46<01:12,  1.19s/it]
  iters:  70%|███████   | 140/200 [02:47<01:11,  1.19s/it]
  iters:  70%|███████   | 141/200 [02:48<01:10,  1.19s/it]
  iters:  71%|███████   | 142/200 [02:49<01:09,  1.20s/it]
  iters:  72%|███████▏  | 143/200 [02:50<01:08,  1.20s/it]
  iters:  72%|███████▏  | 144/200 [02:52<01:07,  1.20s/it]
  iters:  72%|███████▎  | 145/200 [02:53<01:05,  1.20s/it]
  iters:  73%|███████▎  | 146/200 [02:54<01:04,  1.20s/it]
  iters:  74%|███████▎  | 147/200 [02:55<01:03,  1.20s/it]
  iters:  74%|███████▍  | 148/200 [02:56<01:02,  1.20s/it]
  iters:  74%|███████▍  | 149/200 [02:58<01:00,  1.20s/it]
  iters:  75%|███████▌  | 150/200 [02:59<00:59,  1.20s/it]
  iters:  76%|███████▌  | 151/200 [03:00<00:58,  1.20s/it]
  iters:  76%|███████▌  | 152/200 [03:01<00:57,  1.20s/it]
  iters:  76%|███████▋  | 153/200 [03:02<00:56,  1.19s/it]
  iters:  77%|███████▋  | 154/200 [03:04<00:54,  1.19s/it]
  iters:  78%|███████▊  | 155/200 [03:05<00:53,  1.19s/it]
  iters:  78%|███████▊  | 156/200 [03:06<00:52,  1.19s/it]
  iters:  78%|███████▊  | 157/200 [03:07<00:51,  1.20s/it]
  iters:  79%|███████▉  | 158/200 [03:08<00:50,  1.20s/it]
  iters:  80%|███████▉  | 159/200 [03:10<00:49,  1.20s/it]
  iters:  80%|████████  | 160/200 [03:11<00:47,  1.20s/it]
  iters:  80%|████████  | 161/200 [03:12<00:46,  1.20s/it]
  iters:  81%|████████  | 162/200 [03:13<00:45,  1.20s/it]
  iters:  82%|████████▏ | 163/200 [03:14<00:44,  1.20s/it]
  iters:  82%|████████▏ | 164/200 [03:16<00:43,  1.19s/it]
  iters:  82%|████████▎ | 165/200 [03:17<00:41,  1.19s/it]
  iters:  83%|████████▎ | 166/200 [03:18<00:40,  1.19s/it]
  iters:  84%|████████▎ | 167/200 [03:19<00:39,  1.19s/it]
  iters:  84%|████████▍ | 168/200 [03:20<00:38,  1.20s/it]
  iters:  84%|████████▍ | 169/200 [03:21<00:36,  1.18s/it]
  iters:  85%|████████▌ | 170/200 [03:23<00:35,  1.19s/it]
  iters:  86%|████████▌ | 171/200 [03:24<00:34,  1.19s/it]
  iters:  86%|████████▌ | 172/200 [03:25<00:33,  1.19s/it]
  iters:  86%|████████▋ | 173/200 [03:26<00:32,  1.19s/it]
  iters:  87%|████████▋ | 174/200 [03:27<00:31,  1.19s/it]
  iters:  88%|████████▊ | 175/200 [03:29<00:29,  1.19s/it]
  iters:  88%|████████▊ | 176/200 [03:30<00:28,  1.19s/it]
  iters:  88%|████████▊ | 177/200 [03:31<00:27,  1.19s/it]
  iters:  89%|████████▉ | 178/200 [03:32<00:26,  1.19s/it]
  iters:  90%|████████▉ | 179/200 [03:33<00:25,  1.19s/it]
  iters:  90%|█████████ | 180/200 [03:35<00:23,  1.20s/it]
  iters:  90%|█████████ | 181/200 [03:36<00:22,  1.20s/it]
  iters:  91%|█████████ | 182/200 [03:37<00:21,  1.20s/it]
  iters:  92%|█████████▏| 183/200 [03:38<00:20,  1.20s/it]
  iters:  92%|█████████▏| 184/200 [03:39<00:19,  1.20s/it]
  iters:  92%|█████████▎| 185/200 [03:41<00:17,  1.20s/it]
  iters:  93%|█████████▎| 186/200 [03:42<00:16,  1.19s/it]
  iters:  94%|█████████▎| 187/200 [03:43<00:15,  1.19s/it]
  iters:  94%|█████████▍| 188/200 [03:44<00:14,  1.19s/it]
  iters:  94%|█████████▍| 189/200 [03:45<00:13,  1.19s/it]
  iters:  95%|█████████▌| 190/200 [03:47<00:11,  1.19s/it]
  iters:  96%|█████████▌| 191/200 [03:48<00:10,  1.19s/it]
  iters:  96%|█████████▌| 192/200 [03:49<00:09,  1.19s/it]
  iters:  96%|█████████▋| 193/200 [03:50<00:08,  1.19s/it]
  iters:  97%|█████████▋| 194/200 [03:51<00:07,  1.19s/it]
  iters:  98%|█████████▊| 195/200 [03:53<00:05,  1.19s/it]
  iters:  98%|█████████▊| 196/200 [03:54<00:04,  1.19s/it]
  iters:  98%|█████████▊| 197/200 [03:55<00:03,  1.20s/it]
  iters:  99%|█████████▉| 198/200 [03:56<00:02,  1.19s/it]
  iters: 100%|█████████▉| 199/200 [03:57<00:01,  1.20s/it]
  iters: 100%|██████████| 200/200 [03:59<00:00,  1.20s/it]

  [timing] data: 2.2s (1%) | forward: 57.6s (24%) | backward: 179.2s (75%) | total: 239.0s

Training:  50%|█████     | 2/4 [13:04<08:43, 261.62s/it, acc=0.9995, det=0.0070, edge=0.0006]

  Epoch   2/4 | edge=0.0006 | det=0.0070 | test_loss=0.0005 | acc=0.9995 | recall=0.8466 | best=0.8463 * | train=239.2s test=22.4s

Training:  75%|███████▌  | 3/4 [13:04<04:21, 261.59s/it, acc=0.9995, det=0.0070, edge=0.0006]
  iters:   0%|          | 0/200 [00:00<?, ?it/s]
  iters:   0%|          | 1/200 [00:01<04:33,  1.38s/it]
  iters:   1%|          | 2/200 [00:02<04:10,  1.26s/it]
  iters:   2%|▏         | 3/200 [00:03<04:02,  1.23s/it]
  iters:   2%|▏         | 4/200 [00:04<03:58,  1.22s/it]
  iters:   2%|▎         | 5/200 [00:06<03:56,  1.21s/it]
  iters:   3%|▎         | 6/200 [00:07<03:53,  1.20s/it]
  iters:   4%|▎         | 7/200 [00:08<03:51,  1.20s/it]
  iters:   4%|▍         | 8/200 [00:09<03:49,  1.20s/it]
  iters:   4%|▍         | 9/200 [00:10<03:48,  1.20s/it]
  iters:   5%|▌         | 10/200 [00:12<03:46,  1.19s/it]
  iters:   6%|▌         | 11/200 [00:13<03:45,  1.19s/it]
  iters:   6%|▌         | 12/200 [00:14<03:44,  1.19s/it]
  iters:   6%|▋         | 13/200 [00:15<03:43,  1.19s/it]
  iters:   7%|▋         | 14/200 [00:16<03:42,  1.19s/it]
  iters:   8%|▊         | 15/200 [00:18<03:40,  1.19s/it]
  iters:   8%|▊         | 16/200 [00:19<03:39,  1.19s/it]
  iters:   8%|▊         | 17/200 [00:20<03:37,  1.19s/it]
  iters:   9%|▉         | 18/200 [00:21<03:34,  1.18s/it]
  iters:  10%|▉         | 19/200 [00:22<03:33,  1.18s/it]
  iters:  10%|█         | 20/200 [00:23<03:33,  1.18s/it]
  iters:  10%|█         | 21/200 [00:25<03:32,  1.19s/it]
  iters:  11%|█         | 22/200 [00:26<03:31,  1.19s/it]
  iters:  12%|█▏        | 23/200 [00:27<03:30,  1.19s/it]
  iters:  12%|█▏        | 24/200 [00:28<03:29,  1.19s/it]
  iters:  12%|█▎        | 25/200 [00:29<03:27,  1.19s/it]
  iters:  13%|█▎        | 26/200 [00:31<03:26,  1.19s/it]
  iters:  14%|█▎        | 27/200 [00:32<03:25,  1.19s/it]
  iters:  14%|█▍        | 28/200 [00:33<03:24,  1.19s/it]
  iters:  14%|█▍        | 29/200 [00:34<03:23,  1.19s/it]
  iters:  15%|█▌        | 30/200 [00:35<03:21,  1.19s/it]
  iters:  16%|█▌        | 31/200 [00:37<03:21,  1.19s/it]
  iters:  16%|█▌        | 32/200 [00:38<03:19,  1.19s/it]
  iters:  16%|█▋        | 33/200 [00:39<03:19,  1.19s/it]
  iters:  17%|█▋        | 34/200 [00:40<03:18,  1.19s/it]
  iters:  18%|█▊        | 35/200 [00:41<03:14,  1.18s/it]
  iters:  18%|█▊        | 36/200 [00:42<03:13,  1.18s/it]
  iters:  18%|█▊        | 37/200 [00:44<03:13,  1.19s/it]
  iters:  19%|█▉        | 38/200 [00:45<03:12,  1.19s/it]
  iters:  20%|█▉        | 39/200 [00:46<03:11,  1.19s/it]
  iters:  20%|██        | 40/200 [00:47<03:10,  1.19s/it]
  iters:  20%|██        | 41/200 [00:48<03:08,  1.19s/it]
  iters:  21%|██        | 42/200 [00:50<03:07,  1.19s/it]
  iters:  22%|██▏       | 43/200 [00:51<03:06,  1.19s/it]
  iters:  22%|██▏       | 44/200 [00:52<03:05,  1.19s/it]
  iters:  22%|██▎       | 45/200 [00:53<03:04,  1.19s/it]
  iters:  23%|██▎       | 46/200 [00:54<03:03,  1.19s/it]
  iters:  24%|██▎       | 47/200 [00:56<03:02,  1.20s/it]
  iters:  24%|██▍       | 48/200 [00:57<03:01,  1.19s/it]
  iters:  24%|██▍       | 49/200 [00:58<03:00,  1.19s/it]
  iters:  25%|██▌       | 50/200 [00:59<02:58,  1.19s/it]
  iters:  26%|██▌       | 51/200 [01:00<02:57,  1.19s/it]
  iters:  26%|██▌       | 52/200 [01:02<02:56,  1.19s/it]
  iters:  26%|██▋       | 53/200 [01:03<02:55,  1.19s/it]
  iters:  27%|██▋       | 54/200 [01:04<02:54,  1.19s/it]
  iters:  28%|██▊       | 55/200 [01:05<02:53,  1.19s/it]
  iters:  28%|██▊       | 56/200 [01:06<02:52,  1.19s/it]
  iters:  28%|██▊       | 57/200 [01:08<02:50,  1.19s/it]
  iters:  29%|██▉       | 58/200 [01:09<02:49,  1.19s/it]
  iters:  30%|██▉       | 59/200 [01:10<02:48,  1.19s/it]
  iters:  30%|███       | 60/200 [01:11<02:47,  1.19s/it]
  iters:  30%|███       | 61/200 [01:12<02:45,  1.19s/it]
  iters:  31%|███       | 62/200 [01:13<02:44,  1.19s/it]
  iters:  32%|███▏      | 63/200 [01:15<02:43,  1.20s/it]
  iters:  32%|███▏      | 64/200 [01:16<02:42,  1.20s/it]
  iters:  32%|███▎      | 65/200 [01:17<02:41,  1.20s/it]
  iters:  33%|███▎      | 66/200 [01:18<02:40,  1.20s/it]
  iters:  34%|███▎      | 67/200 [01:19<02:38,  1.20s/it]
  iters:  34%|███▍      | 68/200 [01:21<02:37,  1.19s/it]
  iters:  34%|███▍      | 69/200 [01:22<02:36,  1.19s/it]
  iters:  35%|███▌      | 70/200 [01:23<02:35,  1.19s/it]
  iters:  36%|███▌      | 71/200 [01:24<02:32,  1.18s/it]
  iters:  36%|███▌      | 72/200 [01:25<02:31,  1.18s/it]
  iters:  36%|███▋      | 73/200 [01:27<02:30,  1.19s/it]
  iters:  37%|███▋      | 74/200 [01:28<02:29,  1.19s/it]
  iters:  38%|███▊      | 75/200 [01:29<02:28,  1.19s/it]
  iters:  38%|███▊      | 76/200 [01:30<02:27,  1.19s/it]
  iters:  38%|███▊      | 77/200 [01:31<02:26,  1.19s/it]
  iters:  39%|███▉      | 78/200 [01:33<02:25,  1.19s/it]
  iters:  40%|███▉      | 79/200 [01:34<02:24,  1.19s/it]
  iters:  40%|████      | 80/200 [01:35<02:23,  1.19s/it]
  iters:  40%|████      | 81/200 [01:36<02:21,  1.19s/it]
  iters:  41%|████      | 82/200 [01:37<02:20,  1.19s/it]
  iters:  42%|████▏     | 83/200 [01:38<02:19,  1.19s/it]
  iters:  42%|████▏     | 84/200 [01:40<02:18,  1.19s/it]
  iters:  42%|████▎     | 85/200 [01:41<02:17,  1.19s/it]
  iters:  43%|████▎     | 86/200 [01:42<02:16,  1.19s/it]
  iters:  44%|████▎     | 87/200 [01:43<02:14,  1.19s/it]
  iters:  44%|████▍     | 88/200 [01:44<02:13,  1.19s/it]
  iters:  44%|████▍     | 89/200 [01:46<02:12,  1.19s/it]
  iters:  45%|████▌     | 90/200 [01:47<02:11,  1.19s/it]
  iters:  46%|████▌     | 91/200 [01:48<02:10,  1.19s/it]
  iters:  46%|████▌     | 92/200 [01:49<02:09,  1.19s/it]
  iters:  46%|████▋     | 93/200 [01:50<02:07,  1.20s/it]
  iters:  47%|████▋     | 94/200 [01:52<02:06,  1.20s/it]
  iters:  48%|████▊     | 95/200 [01:53<02:05,  1.20s/it]
  iters:  48%|████▊     | 96/200 [01:54<02:04,  1.19s/it]
  iters:  48%|████▊     | 97/200 [01:55<02:02,  1.19s/it]
  iters:  49%|████▉     | 98/200 [01:56<02:01,  1.19s/it]
  iters:  50%|████▉     | 99/200 [01:58<02:00,  1.19s/it]
  iters:  50%|█████     | 100/200 [01:59<01:59,  1.19s/it]
  iters:  50%|█████     | 101/200 [02:00<01:58,  1.19s/it]
  iters:  51%|█████     | 102/200 [02:01<01:57,  1.19s/it]
  iters:  52%|█████▏    | 103/200 [02:02<01:55,  1.19s/it]
  iters:  52%|█████▏    | 104/200 [02:04<01:54,  1.19s/it]
  iters:  52%|█████▎    | 105/200 [02:05<01:53,  1.19s/it]
  iters:  53%|█████▎    | 106/200 [02:06<01:52,  1.19s/it]
  iters:  54%|█████▎    | 107/200 [02:07<01:51,  1.20s/it]
  iters:  54%|█████▍    | 108/200 [02:08<01:50,  1.20s/it]
  iters:  55%|█████▍    | 109/200 [02:10<01:48,  1.20s/it]
  iters:  55%|█████▌    | 110/200 [02:11<01:47,  1.19s/it]
  iters:  56%|█████▌    | 111/200 [02:12<01:46,  1.19s/it]
  iters:  56%|█████▌    | 112/200 [02:13<01:45,  1.20s/it]
  iters:  56%|█████▋    | 113/200 [02:14<01:43,  1.20s/it]
  iters:  57%|█████▋    | 114/200 [02:16<01:43,  1.20s/it]
  iters:  57%|█████▊    | 115/200 [02:17<01:41,  1.20s/it]
  iters:  58%|█████▊    | 116/200 [02:18<01:40,  1.20s/it]
  iters:  58%|█████▊    | 117/200 [02:19<01:39,  1.20s/it]
  iters:  59%|█████▉    | 118/200 [02:20<01:38,  1.20s/it]
  iters:  60%|█████▉    | 119/200 [02:22<01:37,  1.20s/it]
  iters:  60%|██████    | 120/200 [02:23<01:35,  1.20s/it]
  iters:  60%|██████    | 121/200 [02:24<01:34,  1.20s/it]
  iters:  61%|██████    | 122/200 [02:25<01:33,  1.20s/it]
  iters:  62%|██████▏   | 123/200 [02:26<01:32,  1.20s/it]
  iters:  62%|██████▏   | 124/200 [02:27<01:30,  1.20s/it]
  iters:  62%|██████▎   | 125/200 [02:29<01:29,  1.20s/it]
  iters:  63%|██████▎   | 126/200 [02:30<01:28,  1.20s/it]
  iters:  64%|██████▎   | 127/200 [02:31<01:27,  1.20s/it]
  iters:  64%|██████▍   | 128/200 [02:32<01:25,  1.19s/it]
  iters:  64%|██████▍   | 129/200 [02:33<01:24,  1.20s/it]
  iters:  65%|██████▌   | 130/200 [02:35<01:23,  1.19s/it]
  iters:  66%|██████▌   | 131/200 [02:36<01:22,  1.20s/it]
  iters:  66%|██████▌   | 132/200 [02:37<01:21,  1.19s/it]
  iters:  66%|██████▋   | 133/200 [02:38<01:20,  1.19s/it]
  iters:  67%|██████▋   | 134/200 [02:39<01:18,  1.19s/it]
  iters:  68%|██████▊   | 135/200 [02:41<01:17,  1.19s/it]
  iters:  68%|██████▊   | 136/200 [02:42<01:16,  1.19s/it]
  iters:  68%|██████▊   | 137/200 [02:43<01:15,  1.20s/it]
  iters:  69%|██████▉   | 138/200 [02:44<01:14,  1.20s/it]
  iters:  70%|██████▉   | 139/200 [02:45<01:12,  1.19s/it]
  iters:  70%|███████   | 140/200 [02:47<01:11,  1.19s/it]
  iters:  70%|███████   | 141/200 [02:48<01:10,  1.19s/it]
  iters:  71%|███████   | 142/200 [02:49<01:09,  1.19s/it]
  iters:  72%|███████▏  | 143/200 [02:50<01:08,  1.19s/it]
  iters:  72%|███████▏  | 144/200 [02:51<01:06,  1.19s/it]
  iters:  72%|███████▎  | 145/200 [02:53<01:05,  1.19s/it]
  iters:  73%|███████▎  | 146/200 [02:54<01:05,  1.22s/it]
  iters:  74%|███████▎  | 147/200 [02:55<01:04,  1.21s/it]
  iters:  74%|███████▍  | 148/200 [02:56<01:02,  1.21s/it]
  iters:  74%|███████▍  | 149/200 [02:57<01:01,  1.20s/it]
  iters:  75%|███████▌  | 150/200 [02:59<00:59,  1.20s/it]
  iters:  76%|███████▌  | 151/200 [03:00<00:58,  1.20s/it]
  iters:  76%|███████▌  | 152/200 [03:01<00:57,  1.19s/it]
  iters:  76%|███████▋  | 153/200 [03:02<00:56,  1.19s/it]
  iters:  77%|███████▋  | 154/200 [03:03<00:54,  1.19s/it]
  iters:  78%|███████▊  | 155/200 [03:05<00:53,  1.19s/it]
  iters:  78%|███████▊  | 156/200 [03:06<00:52,  1.19s/it]
  iters:  78%|███████▊  | 157/200 [03:07<00:51,  1.19s/it]
  iters:  79%|███████▉  | 158/200 [03:08<00:49,  1.19s/it]
  iters:  80%|███████▉  | 159/200 [03:09<00:48,  1.19s/it]
  iters:  80%|████████  | 160/200 [03:11<00:47,  1.19s/it]
  iters:  80%|████████  | 161/200 [03:12<00:46,  1.19s/it]
  iters:  81%|████████  | 162/200 [03:13<00:45,  1.19s/it]
  iters:  82%|████████▏ | 163/200 [03:14<00:44,  1.19s/it]
  iters:  82%|████████▏ | 164/200 [03:15<00:42,  1.19s/it]
  iters:  82%|████████▎ | 165/200 [03:16<00:41,  1.19s/it]
  iters:  83%|████████▎ | 166/200 [03:18<00:40,  1.19s/it]
  iters:  84%|████████▎ | 167/200 [03:19<00:39,  1.19s/it]
  iters:  84%|████████▍ | 168/200 [03:20<00:38,  1.19s/it]
  iters:  84%|████████▍ | 169/200 [03:21<00:36,  1.19s/it]
  iters:  85%|████████▌ | 170/200 [03:22<00:35,  1.19s/it]
  iters:  86%|████████▌ | 171/200 [03:24<00:34,  1.19s/it]
  iters:  86%|████████▌ | 172/200 [03:25<00:33,  1.19s/it]
  iters:  86%|████████▋ | 173/200 [03:26<00:32,  1.19s/it]
  iters:  87%|████████▋ | 174/200 [03:27<00:30,  1.19s/it]
  iters:  88%|████████▊ | 175/200 [03:28<00:29,  1.19s/it]
  iters:  88%|████████▊ | 176/200 [03:30<00:28,  1.19s/it]
  iters:  88%|████████▊ | 177/200 [03:31<00:27,  1.19s/it]
  iters:  89%|████████▉ | 178/200 [03:32<00:26,  1.19s/it]
  iters:  90%|████████▉ | 179/200 [03:33<00:24,  1.19s/it]
  iters:  90%|█████████ | 180/200 [03:34<00:23,  1.19s/it]
  iters:  90%|█████████ | 181/200 [03:36<00:22,  1.19s/it]
  iters:  91%|█████████ | 182/200 [03:37<00:21,  1.19s/it]
  iters:  92%|█████████▏| 183/200 [03:38<00:20,  1.19s/it]
  iters:  92%|█████████▏| 184/200 [03:39<00:19,  1.19s/it]
  iters:  92%|█████████▎| 185/200 [03:40<00:17,  1.19s/it]
  iters:  93%|█████████▎| 186/200 [03:41<00:16,  1.19s/it]
  iters:  94%|█████████▎| 187/200 [03:43<00:15,  1.19s/it]
  iters:  94%|█████████▍| 188/200 [03:44<00:14,  1.19s/it]
  iters:  94%|█████████▍| 189/200 [03:45<00:13,  1.19s/it]
  iters:  95%|█████████▌| 190/200 [03:46<00:11,  1.19s/it]
  iters:  96%|█████████▌| 191/200 [03:47<00:10,  1.19s/it]
  iters:  96%|█████████▌| 192/200 [03:49<00:09,  1.19s/it]
  iters:  96%|█████████▋| 193/200 [03:50<00:08,  1.19s/it]
  iters:  97%|█████████▋| 194/200 [03:51<00:07,  1.19s/it]
  iters:  98%|█████████▊| 195/200 [03:52<00:05,  1.19s/it]
  iters:  98%|█████████▊| 196/200 [03:53<00:04,  1.19s/it]
  iters:  98%|█████████▊| 197/200 [03:55<00:03,  1.19s/it]
  iters:  99%|█████████▉| 198/200 [03:56<00:02,  1.19s/it]
  iters: 100%|█████████▉| 199/200 [03:57<00:01,  1.19s/it]
  iters: 100%|██████████| 200/200 [03:58<00:00,  1.19s/it]

  [timing] data: 2.2s (1%) | forward: 57.5s (24%) | backward: 179.0s (75%) | total: 238.6s

Training:  75%|███████▌  | 3/4 [17:25<04:21, 261.59s/it, acc=0.9996, det=0.0064, edge=0.0003]

  Epoch   3/4 | edge=0.0003 | det=0.0064 | test_loss=0.0006 | acc=0.9996 | recall=0.8346 | best=0.8463   | train=238.8s test=22.3s

Training: 100%|██████████| 4/4 [17:25<00:00, 261.49s/it, acc=0.9996, det=0.0064, edge=0.0003]

Best score (acc*recall): 0.8463, saved to /kaggle/working/cellmot-baseline-artifacts/repo/weights/hp_search_tier1/split_0/edge_predictor_best.pth

[tier2_007] score=0.8463  (1052s)
0.019136512 GB allocated
0.245366784 GB reserved

In [20]:
import pandas as pd

df = pd.read_json("hp_search_results_part3.jsonl", lines=True)
df = df.sort_values("best_score", ascending=False)
print(df.head(10))

    trial_id  elapsed_s  fold  n_epochs  max_iters  seed  data_parallel  \
1  tier2_001     1586.8     0         4        200     0          False
4  tier2_004     1086.9     0         4        200     0          False
3  tier2_003     1068.8     0         4        200     0          False
5  tier2_005     1552.9     0         4        200     0          False
6  tier2_006     1516.3     0         4        200     0          False
7  tier2_007     1051.7     0         4        200     0          False
0  tier2_000     1056.2     0         4        200     0          False
2  tier2_002     1521.1     0         4        200     0          False

   batch_size           method       lr  ...  det_threshold  pool_kernel_um  \
1           2  hp_search_tier1  0.00005  ...            0.8        2.499346
4           2  hp_search_tier1  0.00005  ...            0.8        2.499346
3           2  hp_search_tier1  0.00005  ...            0.8        7.498037
5           2  hp_search_tier1  0.00005  ...            0.8        7.498037
6           2  hp_search_tier1  0.00005  ...            0.8       17.495419
7           2  hp_search_tier1  0.00005  ...            0.8       17.495419
0           2  hp_search_tier1  0.00005  ...            0.8       24.993456
2           2  hp_search_tier1  0.00005  ...            0.8       24.993456

   window_size  best_score  final_edge_loss  final_det_loss  final_test_acc  \
1            3    0.917246         0.000622        0.006965        0.998920
4            2    0.913841         0.000632        0.006457        0.998762
3            2    0.905206         0.000461        0.006708        0.999116
5            3    0.893606         0.000460        0.006465        0.999387
6            3    0.847070         0.000384        0.006546        0.999604
7            2    0.846250         0.000338        0.006413        0.999622
0            2    0.806619         0.000328        0.006442        0.999444
2            3    0.792121         0.000576        0.007181        0.999525

   final_test_recall  best_test_acc  best_test_recall
1           0.845204       0.998821          0.918329
4           0.867138       0.998521          0.915194
3           0.906007       0.999116          0.906007
5           0.864672       0.999434          0.894112
6           0.842355       0.999400          0.847578
7           0.834629       0.999536          0.846643
0           0.807067       0.999444          0.807067
2           0.792498       0.999525          0.792498

[8 rows x 22 columns]

In [21]:
# sanity-check marginal effect of each param independently
for param in ["lr", "det_loss_weight", "det_neg_weight", "det_threshold"]:
    print(df.groupby(param)["best_score"].agg(["mean", "std", "count"]))

             mean       std  count
lr
0.00005  0.865245  0.049197      8
                     mean       std  count
det_loss_weight
4                0.865245  0.049197      8
                    mean       std  count
det_neg_weight
0.01            0.865245  0.049197      8
                   mean       std  count
det_threshold
0.8            0.865245  0.049197      8

In [22]:
import subprocess
target = ARTIFACTS_WORK / "repo/scripts/train_unet_transformer.py"

result = subprocess.run(["grep", "-n", "max_match_distance\|def train_epoch\|def evaluate\|def train(", str(target)],
                         capture_output=True, text=True)
print(result.stdout)

627:    max_match_distance: float = 5.0,
647:    max_match_distance : maximum physical distance for detection→GT matching.
713:                if min_d[idx] > max_match_distance:
782:def train_epoch(
921:def evaluate(
1005:def train(

<>:4: SyntaxWarning: invalid escape sequence '\|'
<>:4: SyntaxWarning: invalid escape sequence '\|'
/tmp/ipykernel_22/1791499151.py:4: SyntaxWarning: invalid escape sequence '\|'
  result = subprocess.run(["grep", "-n", "max_match_distance\|def train_epoch\|def evaluate\|def train(", str(target)],